// Esercizi della versione 1.5 (4 in più, per arrivare a 69): due sull'ansia e due sulla paura della morte.
// Idee da Seneca (Lettere a Lucilio, con il commento di Reale) e da Epitteto (Discorsi). Testi originali: nessuna citazione.
// Stesso formato di esercizi.js.

export const ESERCIZI_4 = [
  {
    id: 'speranza-e-timore',
    titolo: 'La speranza e il timore',
    disciplina: 'desiderio',
    famiglia: 'pensiero',
    stati: ['ansia', 'paura', 'notte'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'speranza e timore legati come da una stessa catena (lettera 5, che cita Ecatone)' },
    perche: `Chi aspetta con ansia un esito spera e teme insieme: sono due facce della stessa attesa. Seneca osserva che il timore cala quando si scioglie la speranza attaccata all'esito. Il punto è staccare la propria pace dall'esito, e continuare a volere le cose.`,
    studio: 'paura-desiderio',
    voci: {
      epitteto: { apertura: `Speri e temi insieme: è una sola attesa. Guarda che cosa hai attaccato all'esito.`, chiusura: `Fai ciò che dipende da te. L'esito aspetta senza la tua pace in pegno.` },
      seneca: { apertura: `Vieni, guardiamo la tua attesa: speranza e timore sono come due prigionieri legati alla stessa catena.`, chiusura: `Hai sciolto un nodo. Puoi ancora sperare, ma con la mano libera.` },
      marco: { apertura: `Che cosa aspetto, e che cosa temo di non ottenere? È la stessa attesa, vista da due lati.`, chiusura: `Ho fatto la mia parte. L'esito è affare di altri.` },
    },
    passi: [
      { tipo: 'testo', testo: `Pensa a qualcosa che aspetti con ansia: una risposta, un esito, una decisione degli altri. Chi aspetta così spera e teme allo stesso tempo. Guardiamo tutte e due le cose.` },
      { tipo: 'scrivi', chiave: 'spero', testo: `Che cosa speri che accada? Scrivilo con onestà, senza vergognarti.`, segnaposto: 'Spero che…' },
      { tipo: 'scrivi', chiave: 'temo', testo: `E che cosa temi che accada, se la tua speranza non si realizza?`, segnaposto: 'Temo che…' },
      { tipo: 'testo', testo: `Vedi quanto sono legate? Seneca le paragona a due prigionieri incatenati insieme: dove c'è l'una, presto arriva l'altra. Non serve smettere di volere: serve staccare la tua pace dall'esito.` },
      { tipo: 'scegli', chiave: 'dipende', testo: `L'esito dipende soltanto da te?`, opzioni: [{ testo: 'Sì, in gran parte', vai: 'agisci' }, { testo: 'No, dipende anche da altri o dal caso', vai: 'resta' }] },
      { id: 'agisci', tipo: 'testo', testo: `Allora sposta l'energia sull'azione: che cosa puoi fare oggi perché l'esito sia più probabile? Fai quel passo, poi lascia lavorare il tempo.`, poi: 'fine' },
      { id: 'resta', tipo: 'testo', testo: `Allora fai la parte tua e lascia l'esito a chi lo decide. Puoi ripeterti: «Ho fatto ciò che dipendeva da me». L'attesa resta, ma non serve pagarla con la pace.` },
    ],
  },

  {
    id: 'seguire-o-essere-trascinati',
    titolo: 'Seguire o essere trascinati',
    disciplina: 'desiderio',
    famiglia: 'meditazioni',
    stati: ['ansia', 'rabbia', 'sconforto'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'il destino guida chi lo segue e trascina chi si oppone (lettera 107, con i versi di Cleante)' },
    perche: `Alcune cose non si possono cambiare. Su quelle resta una scelta: opporsi lamentandosi, oppure accettarle e cercare che cosa fare dentro di esse. Seneca ricorda un verso di Cleante: il destino guida chi lo segue e trascina chi si oppone. La strada è la stessa, cambia il modo di percorrerla. Accettare non significa approvare.`,
    studio: 'accettare-cio-che-accade',
    voci: {
      epitteto: { apertura: `Ciò che è già accaduto non chiede il tuo permesso. Scegli come stargli davanti.`, chiusura: `La strada è la stessa. Tu scegli se camminarla o farti trascinare.` },
      seneca: { apertura: `Fermiamoci un momento su ciò che non puoi cambiare: di lì passa quasi tutta la pace che cerchi.`, chiusura: `Non hai approvato niente: hai smesso di lottare contro ciò che è già qui. Ora hai più forze.` },
      marco: { apertura: `Ciò che è avvenuto doveva avvenire. Ora chiedo a me stesso come starci dentro.`, chiusura: `Ho seguito, non sono stato trascinato. Torno a ciò che posso fare.` },
    },
    passi: [
      { tipo: 'testo', testo: `Pensa a qualcosa che ti è capitato, o ti sta capitando, e che non puoi cambiare, almeno per ora. Non deve essere la cosa più grave: basta una a cui senti di opporti.` },
      { tipo: 'scrivi', chiave: 'resisto', testo: `Come ti stai opponendo? Che cosa ti ripeti, o ti lamenti, dentro di te?`, segnaposto: 'Non è giusto che…' },
      { tipo: 'testo', testo: `Seneca cita un verso di Cleante: il destino guida chi lo segue e trascina chi recalcitra. La strada è la stessa. Cambia il modo di percorrerla: con la testa alta e i piedi tuoi, oppure trascinato.` },
      { tipo: 'scegli', chiave: 'segui', testo: `Se lo seguissi senza lottare, che cosa cambierebbe di più?`, opzioni: [{ testo: 'Agirei con più calma', vai: 'calma' }, { testo: 'Il dolore resterebbe, ma senza la lotta', vai: 'dolore' }] },
      { id: 'calma', tipo: 'testo', testo: `Bene: la calma è già un modo di agire. Chi non spreca le forze a litigare con ciò che è accaduto le ha per ciò che viene dopo.`, poi: 'passo' },
      { id: 'dolore', tipo: 'testo', testo: `Bene: alcune cose fanno male comunque. Ma il dolore senza la lotta pesa meno. Puoi riconoscerlo e lasciarlo essere, senza aggiungerci un secondo peso.` },
      { id: 'passo', tipo: 'scrivi', chiave: 'passo', testo: `Che cosa puoi fare, dentro questa situazione, con calma? Un gesto che dipende da te.`, segnaposto: 'Posso…' },
      { tipo: 'testo', testo: `Accettare significa una cosa diversa dall'approvare e dall'arrendersi. È smettere di litigare con ciò che è già accaduto, per usare le forze su ciò che viene dopo.` },
    ],
  },

  {
    id: 'lo-spauracchio',
    titolo: 'Lo spauracchio',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['paura', 'ansia', 'notte'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Discorsi', nota: 'Socrate chiamava spauracchi le paure della morte: ciò che spaventa è l\'opinione, non la cosa' },
    perche: `Un bambino ha paura di una maschera finché non scopre che è una maschera. Epitteto ricorda che Socrate chiamava «spauracchi» le paure della morte: la cosa in sé non è il male, lo è l'opinione che ne abbiamo. Guardare la paura per com'è, con calma, non la cancella, ma ne mostra i contorni.`,
    studio: 'il-ricordo-della-fine',
    voci: {
      epitteto: { apertura: `Che cosa ti spaventa davvero? Guardalo in faccia: dietro la maschera c'è un'opinione.`, chiusura: `Ciò che hai guardato in faccia fa meno paura. Torna a ciò che dipende da te.` },
      seneca: { apertura: `Parliamo con calma di ciò che ti fa paura. Nessuno ti chiede di non provarla: solo di guardarla.`, chiusura: `Hai guardato la tua paura senza scappare. Già questo la rende più piccola.` },
      marco: { apertura: `Prendo la paura e la esamino come una cosa che sta sul tavolo: che cos'è, esattamente?`, chiusura: `La paura c'è ancora, ma la conosco. Posso tornare alla mia giornata.` },
    },
    passi: [
      { tipo: 'testo', testo: `Questo esercizio parla di paure grandi, come la fine o la perdita. Vai con calma e fermati quando vuoi. Puoi avere paura quanto vuoi: l'esercizio ti chiede solo di guardarla in faccia.` },
      { tipo: 'respiro', testo: `Qualche respiro lento, prima di cominciare.`, dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'paura', testo: `Che cosa ti spaventa, esattamente? Scrivilo con parole concrete: che cosa, quando, come.`, segnaposto: 'Mi spaventa…' },
      { tipo: 'testo', testo: `Epitteto racconta che Socrate chiamava spauracchi queste paure: le maschere con cui si spaventano i bambini. Dietro la maschera c'è una persona. Dietro il tuo spauracchio c'è un'opinione: che quella cosa sia un male terribile.` },
      { tipo: 'scegli', chiave: 'cosa', testo: `Che cosa ti spaventa di più?`, opzioni: [{ testo: 'Il momento stesso', vai: 'momento' }, { testo: 'Ciò che viene prima o dopo: dolore, perdita, lasciare chi amo', vai: 'attorno' }] },
      { id: 'momento', tipo: 'testo', testo: `Del momento in sé nessuno ha esperienza: è un pensiero, non un ricordo. Gli antichi, stoici ed epicurei, ne facevano un argomento di calma. Per te può bastare notare che stai temendo qualcosa che nessuno ha ancora vissuto.`, poi: 'gesto' },
      { id: 'attorno', tipo: 'testo', testo: `Allora la paura riguarda cose distinte: il dolore, la perdita, il lasciare. Sono cose vere, e si possono guardare una per una. Molte si alleviano con l'aiuto di altri, con le cure, con parole dette in tempo.` },
      { id: 'gesto', tipo: 'scrivi', chiave: 'gesto', testo: `C'è un piccolo gesto che puoi fare oggi per stare meglio con questa paura? Parlarne con qualcuno, scrivere una cosa che non hai detto, curare ciò che dipende da te.`, segnaposto: 'Posso…' },
      { tipo: 'testo', testo: `Se la paura è molto forte o ti accompagna da tempo, parlane con un medico o con una persona di fiducia: gli esercizi aiutano, ma non sostituiscono l'ascolto di un professionista.` },
    ],
  },

  {
    id: 'la-commedia-ben-recitata',
    titolo: 'La commedia ben recitata',
    disciplina: 'azione',
    famiglia: 'meditazioni',
    stati: ['paura', 'non-so', 'sconforto'],
    minuti: 10,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'la vita è come una commedia: conta come è recitata, non quanto è lunga (lettera 77)' },
    perche: `Chi teme la fine misura spesso la vita dalla lunghezza. Seneca propone un altro criterio: come in una commedia, ciò che conta è quanto bene viene recitata. La domanda cambia, da «quanto mi resta?» a «come sto recitando la parte di oggi?». Non toglie la paura, ma dà qualcosa da fare.`,
    studio: 'il-ricordo-della-fine',
    voci: {
      epitteto: { apertura: `Non decidi quanto durerà la commedia. Decidi come recitarla, oggi.`, chiusura: `Hai guardato la tua parte. Ora torna a recitarla bene.` },
      seneca: { apertura: `Siediti con me, e parliamo della vita come di una commedia: lunga o breve, conta come si recita.`, chiusura: `Hai guardato ciò che è stato recitato bene e ciò che vuoi ancora recitare. È un lavoro d'amore.` },
      marco: { apertura: `Guardo la mia vita dall'esterno, come una scena. Non quanto dura: come la vivo.`, chiusura: `Ho ricordato chi voglio essere. Torno alla scena di oggi.` },
    },
    passi: [
      { tipo: 'testo', testo: `Questo esercizio dura circa dieci minuti e parla della fine della vita, con delicatezza. Se ti sembra troppo, fermati: puoi riprenderlo in un altro momento.` },
      { tipo: 'respiro', testo: `Qualche respiro lento, per arrivare qui con calma.`, dentro: 4, fuori: 6, cicli: 4 },
      { tipo: 'testo', testo: `Seneca paragona la vita a una commedia: a contare è la qualità della recitazione, e la lunghezza c'entra poco. Una parte lunga può essere recitata male, una breve può essere recitata bene.` },
      { tipo: 'scrivi', chiave: 'bene', testo: `Quale parte della tua vita, finora, è stata recitata bene? Una scena, un periodo, un gesto.`, segnaposto: 'Ho recitato bene…' },
      { tipo: 'pausa', secondi: 45, testo: `Resta con quella scena. Guardala per com'è: non per ciò che è mancato, ma per ciò che c'è stato.` },
      { tipo: 'scrivi', chiave: 'ancora', testo: `Che cosa vorresti ancora recitare bene, nella parte che ti resta? Una relazione, un lavoro, un modo di essere.`, segnaposto: 'Vorrei ancora…' },
      { tipo: 'testo', testo: `Seneca aggiunge che si impara a vivere finché si vive, e finché si vive si impara anche a lasciarla andare. Puoi temere, e intanto continuare a recitare: la parte non va lasciata a metà per la paura.` },
      { tipo: 'scrivi', chiave: 'gesto', testo: `Che gesto puoi fare oggi, coerente con la parte che vuoi recitare?`, segnaposto: 'Oggi posso…' },
      { tipo: 'respiro', testo: `Torna al presente con qualche respiro: ora, qui, la scena è questa.`, dentro: 4, fuori: 6, cicli: 3 },
    ],
  },
];
