// Esercizi della Fase 3 (20 in più, per arrivare a 60). Testi originali, senza citazioni dai libri: ogni esercizio indica la fonte.
// Stesso formato di esercizi.js.

export const ESERCIZI_3 = [
  {
    id: 'il-consenso-sospeso',
    titolo: 'Il consenso sospeso',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['ansia', 'paura', 'notte'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: "l'esame delle impressioni prima di darvi il proprio assenso" },
    perche: `Un pensiero che ci spaventa arriva con una forza che sembra una prova. Gli stoici chiamavano «assenso» il sì che gli diamo. Sospenderlo, anche solo per un minuto, ci lascia il tempo di controllare se il pensiero è vero prima di viverlo come se lo fosse.`,
    studio: 'impressioni-giudizio',
    voci: {
      epitteto: { apertura: "Un pensiero ti pesa? Puoi non dargli ancora il tuo sì. Prima dagli un'occhiata.", chiusura: "Un pensiero senza il tuo consenso è solo un pensiero." },
      seneca: { apertura: `Fermiamoci un momento, tu e io. Prima di credere a ciò che ti dice la paura, chiediamole con calma su che cosa si basa.`, chiusura: `Hai dato al pensiero il tempo di mostrarsi per quello che è. Già questo alleggerisce.` },
      marco: { apertura: `Il pensiero è arrivato. Io non sono obbligato a dirgli di sì.`, chiusura: `Ho guardato il pensiero senza farlo mio. Resta la calma di chi decide.` },
    },
    passi: [
      { tipo: 'respiro', testo: `Prima di tutto rallenta: qualche respiro lungo, seguendo il cerchio.`, dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'pensiero', testo: `Scrivi il pensiero che ti turba, con le parole che usa nella tua testa.`, segnaposto: 'Il pensiero dice che…' },
      { tipo: 'testo', testo: `Ora immagina di essere davanti a un ospite che ti porta una notizia. Non devi né cacciarlo né credergli subito. Puoi dirgli: «Ti ascolto, ma controllo».` },
      { tipo: 'scegli', chiave: 'prova', testo: `Hai una prova concreta che questo pensiero sia vero, adesso?`, opzioni: [{ testo: 'Sì, ne ho una', vai: 'prova' }, { testo: 'No, è una sensazione', vai: 'sensazione' }] },
      { id: 'prova', tipo: 'testo', testo: `Bene: allora c'è qualcosa di reale da guardare. Chiediti che cosa puoi fare, e in quale ordine. Il resto lo lasci alla prossima cosa concreta.`, poi: 'fine' },
      { id: 'sensazione', tipo: 'testo', testo: `Una sensazione può essere molto forte senza essere vera. Ripeti tra te: «È un'impressione, e per ora la sospendo». Poi torna a ciò che stai facendo.` },
    ],
  },
  {
    id: 'un-nome-alla-passione',
    titolo: 'Un nome alla passione',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['sconforto', 'rabbia', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Crisippo', opera: 'Frammenti sulle passioni', nota: 'le passioni come giudizi, raccolte da von Arnim' },
    perche: `Per gli stoici ogni passione contiene un giudizio: «mi hanno tolto ciò che mi spetta», «senza questo non sto bene». Dare un nome preciso a ciò che si sente aiuta a trovare il giudizio nascosto e a esaminarlo. Un'emozione con un nome è meno confusa.`,
    studio: 'mappa-delle-passioni',
    voci: {
      epitteto: { apertura: "Che cosa senti, esattamente? Dagli un nome. Poi cerca il giudizio che c'è sotto.", chiusura: "Sotto ogni passione c'è un giudizio. Trovalo e potrai discuterlo." },
      seneca: { apertura: `Quando stai male, spesso non sai nemmeno che cosa hai. Proviamo a dare un nome a ciò che si muove dentro di te.`, chiusura: `Un dolore con un nome fa meno paura. Adesso lo conosci un po' meglio.` },
      marco: { apertura: `Che cosa sta succedendo in me? Lo nomino, e lo guardo.`, chiusura: `L'ho chiamato per nome. Ora è più piccolo.` },
    },
    passi: [
      { tipo: 'testo', testo: `Gli stoici hanno lasciato una mappa di venticinque passioni, divise in quattro famiglie: desiderio, paura, piacere, dolore. Ne trovi l'elenco nello Studio.` },
      { tipo: 'scegli', chiave: 'famiglia', testo: `Che cosa somiglia di più a ciò che senti ora?`, opzioni: [{ testo: 'Voglio qualcosa che non ho', vai: 'unico' }, { testo: 'Temo qualcosa che potrebbe accadere', vai: 'unico' }, { testo: 'Soffro per qualcosa che è già accaduto', vai: 'unico' }] },
      { id: 'unico', tipo: 'scrivi', chiave: 'nome', testo: `Scegli il nome più preciso che ti viene: per esempio rancore, vergogna, invidia, sconforto, angoscia, gelosia. Scrivilo.`, segnaposto: 'Quello che provo è…' },
      { tipo: 'scrivi', chiave: 'giudizio', testo: `Ora completa la frase: «Dietro a questa emozione c'è il giudizio che…». Non serve che sia giusto: serve che sia onesto.`, segnaposto: 'Dietro c\'è il giudizio che…' },
      { tipo: 'testo', testo: `Rileggi ciò che hai scritto. Quel giudizio è certo, o è solo una tua interpretazione? Per oggi basta averlo trovato: puoi tornarci con calma.` },
    ],
  },
  {
    id: 'ogni-cosa-ha-due-manici',
    titolo: 'Ogni cosa ha due manici',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['rabbia', 'sconforto', 'colpa'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'ogni cosa si può prendere da due parti, una sopportabile e una no' },
    perche: `Epitteto dice che ogni cosa ha due manici: una parte per cui si sopporta e una per cui pesa. Il fatto è lo stesso, ma dipende da dove lo afferriamo. Cercare l'altro manico non cancella il problema: ci permette di portarlo.`,
    studio: 'impressioni-giudizio',
    voci: {
      epitteto: { apertura: "Stai afferrando la cosa dal lato che pesa. Prova a cercare l'altro manico.", chiusura: "Il fatto è uno. Puoi scegliere da che parte prenderlo." },
      seneca: { apertura: `Ciò che ti pesa ha anche un lato più mite. Cerchiamolo insieme, senza fingere che il problema non esista.`, chiusura: `Non hai cambiato le cose. Hai cambiato la presa, e ora si porta meglio.` },
      marco: { apertura: `Come sto prendendo questa cosa? Provo l'altro manico.`, chiusura: `La stessa cosa, da un'altra parte, pesa di meno.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'peso', testo: `Che cosa ti pesa in questo momento? Scrivilo in una riga.`, segnaposto: 'Mi pesa…' },
      { tipo: 'scrivi', chiave: 'manico1', testo: `Come lo stai prendendo adesso? Scrivi la storia che ti racconti su questa cosa.`, segnaposto: 'La sto prendendo come…' },
      { tipo: 'testo', testo: `Ora cerca l'altro manico. Puoi chiederti: che cosa c'è di utile? Che cosa sto imparando? Chi mi è vicino? Che cosa potrebbe dirmi un amico?` },
      { tipo: 'scrivi', chiave: 'manico2', testo: `Scrivi un modo diverso, e anche parziale, di prendere la stessa cosa.`, segnaposto: 'Potrei prenderla come…' },
      { tipo: 'pausa', secondi: 20, testo: `Resta un momento con questa seconda presa. Sentila senza forzarla.` },
    ],
  },
  {
    id: 'la-parte-che-recito',
    titolo: 'La parte che recito',
    disciplina: 'azione',
    famiglia: 'pensiero',
    stati: ['sopraffatto', 'colpa'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: "l'attore che recita la parte che gli è stata assegnata" },
    perche: `Epitteto paragona la vita a una commedia: la parte non l'hai scelta tu, ma il modo di recitarla sì. Concentrarti su come recitare bene la parte di oggi (genitore, collega, figlio, amico) ti toglie dal confronto con tutte le parti che non hai.`,
    studio: 'il-manuale-di-epitteto',
    voci: {
      epitteto: { apertura: "Oggi hai una parte da recitare. Non l'hai scelta tu, ma puoi recitarla bene.", chiusura: "Scegliere la parte non spetta a te. Recitarla con cura, sì." },
      seneca: { apertura: `Nessuno può fare tutto. Guardiamo quale parte ti spetta, e facciamo quella con cura.`, chiusura: `Fare bene la propria parte basta a una giornata.` },
      marco: { apertura: `Qual è il mio posto oggi? Lo occupo con serietà.`, chiusura: `La parte è piccola, ma è mia. La recito.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'parti', testo: `Quali parti ti tocca recitare oggi? Per esempio: figlia, collega, amico, vicino, genitore. Scrivine due o tre.`, segnaposto: 'Oggi sono…' },
      { tipo: 'testo', testo: `Ogni parte ha i suoi doveri e le sue misure. Non serve essere perfetti: serve fare ciò che a quella parte compete, con onestà.` },
      { tipo: 'scrivi', chiave: 'una', testo: `Scegli la parte più importante di oggi. Che cosa farebbe, in concreto, una persona che la recita bene?`, segnaposto: 'Farebbe…' },
      { tipo: 'testo', testo: `Ora lascia andare tutto ciò che non rientra nella parte di oggi. Non è tuo da risolvere adesso, e lo si vedrà quando sarà il momento.` },
    ],
  },
  {
    id: 'come-il-promontorio',
    titolo: 'Come il promontorio',
    disciplina: 'desiderio',
    famiglia: 'meditazioni',
    stati: ['ansia', 'sopraffatto', 'paura'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: "l'immagine del promontorio contro cui si infrangono le onde (IV, 49)" },
    perche: `Marco Aurelio si ricorda di essere come uno scoglio che resta fermo mentre le onde si infrangono. Le onde sono le circostanze, che arrivano e passano. Immaginarsi saldi, senza irrigidirsi, aiuta a stare in mezzo a ciò che agita.`,
    studio: 'paura-desiderio',
    voci: {
      epitteto: { apertura: "Le onde arrivano. Tu sei lo scoglio: puoi restare dove sei.", chiusura: "Le onde passano. Chi resta saldo, resta." },
      seneca: { apertura: `Immagina un promontorio sul mare, con le onde che si rompono ai suoi piedi. Prova a sentirti così: fermo, e tranquillo.`, chiusura: `Le onde torneranno, e tu con loro. Ma adesso hai imparato a restare.` },
      marco: { apertura: `Sono lo scoglio, e il mare mi batte intorno. Resto fermo.`, chiusura: `Ho lasciato passare le onde. Sono ancora qui.` },
    },
    passi: [
      { tipo: 'respiro', testo: `Rallenta il respiro. Senti i piedi o la schiena, dove il corpo poggia.`, dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'testo', testo: `Immagina un grande scoglio sul mare. Le onde si alzano, si rompono, ricadono. Lo scoglio non le combatte: le lascia venire e restare dove sono.` },
      { tipo: 'testo', testo: `Ciò che ti agita oggi è come il mare: viene a ondate. Ogni onda ha un principio e una fine. Tu sei lo scoglio: solido, e non duro.` },
      { tipo: 'pausa', secondi: 40, testo: `Resta in silenzio, sentendoti saldo come lo scoglio. Se un pensiero arriva, è un'onda: lascialo passare.` },
    ],
  },
  {
    id: 'come-se-fosse-l-ultimo',
    titolo: 'Come se fosse l’ultimo',
    disciplina: 'azione',
    famiglia: 'meditazioni',
    stati: ['ansia', 'sopraffatto', 'non-so'],
    minuti: 1,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'vivere ogni giorno come se fosse l’ultimo (VII, 69)' },
    perche: `Marco Aurelio scrive che la perfezione del carattere sta nel passare ogni giorno come se fosse l'ultimo, senza agitazione né indifferenza. Non si tratta di paura: è un modo di dare a ogni ora il suo peso, e di lasciare andare ciò che non conta.`,
    studio: 'il-tempo-la-morte',
    voci: {
      epitteto: { apertura: "Se oggi fosse l'ultimo giorno, che cosa faresti con più cura? Prova a farlo.", chiusura: "Il giorno è breve. Usalo per ciò che merita." },
      seneca: { apertura: `Il tempo è la tua vera ricchezza. Spendilo bene: come sceglieresti oggi, se fosse l'ultimo?`, chiusura: `Un giorno vissuto con attenzione vale più di molti giorni distratti.` },
      marco: { apertura: `Oggi potrebbe essere l'ultimo. Lo vivo con calma e con cura.`, chiusura: `Un giorno alla volta, senza fretta e senza dispersione.` },
    },
    passi: [
      { tipo: 'testo', testo: `Immagina, senza paura, che questo sia l'ultimo giorno in cui puoi agire come vuoi. Non serve crederci: è un modo di guardare.` },
      { tipo: 'scrivi', chiave: 'importa', testo: `Che cosa ti sembra importante, adesso? Una sola cosa.`, segnaposto: 'La cosa importante è…' },
      { tipo: 'scrivi', chiave: 'lascio', testo: `E che cosa, di ciò che ti agita, puoi lasciare andare?`, segnaposto: 'Lascio andare…' },
    ],
  },
  {
    id: 'la-lista-dei-doveri',
    titolo: 'La lista dei doveri',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['sopraffatto'],
    minuti: 10,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'i doveri misurati sui propri ruoli e sulle relazioni' },
    perche: `Quando tutto sembra urgente, la confusione nasce dal mettere sullo stesso piano cose diverse. Epitteto misura i doveri sui ruoli che abbiamo: se so di essere genitore, collega, amico, vedo che cosa mi compete e che cosa posso lasciare da parte.`,
    studio: 'dicotomia-in-pratica',
    voci: {
      epitteto: { apertura: "Troppe cose tutte insieme? Ordinale per ruolo. Poi fai ciò che spetta al tuo ruolo.", chiusura: "Non tutto è tuo da fare. Ciò che è tuo, fallo con calma." },
      seneca: { apertura: `Quando il carico è troppo, aiuta scrivere. Mettiamo su carta ciò che ti pesa e vediamo a chi spetta.`, chiusura: `Una lista chiara pesa meno di mille pensieri in testa.` },
      marco: { apertura: `Troppe cose. Le scrivo, le ordino, scelgo la prima.`, chiusura: `Una cosa alla volta. Ora so qual è la prima.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'tutto', testo: `Scrivi tutto ciò che ti pesa, senza ordine. Non serve che sia ben scritto.`, segnaposto: 'Devo…' },
      { tipo: 'scrivi', chiave: 'ruoli', testo: `Ora scrivi i ruoli che hai in questo momento: per esempio lavoratore, genitore, figlia, amico, socio.`, segnaposto: 'Sono…' },
      { tipo: 'colonne', chiave: 'compito', testo: `Metti ogni cosa nella colonna giusta. Se una cosa non corrisponde a nessun ruolo, forse tocca ad altri.`, sinistra: 'Tocca a me', destra: 'Non tocca a me' },
      { tipo: 'scrivi', chiave: 'prima', testo: `Tra quelle che toccano a te, scegli una cosa da fare per prima. Scrivila.`, segnaposto: 'Comincio da…' },
      { tipo: 'pausa', secondi: 60, testo: `Chiudi gli occhi per un minuto. Lascia che le cose che non toccano a te restino fuori dalla porta.` },
      { tipo: 'testo', testo: `Torna alla prima cosa, e falla senza pensare alle altre. Il resto verrà, uno alla volta.` },
    ],
  },
  {
    id: 'la-sentinella',
    titolo: 'La sentinella',
    disciplina: 'presenza',
    famiglia: 'attenzione',
    stati: ['ansia', 'notte'],
    minuti: 3,
    fonte: { autore: 'Hadot', opera: 'Esercizi spirituali e filosofia antica', nota: "l'attenzione a sé (prosoché) come atteggiamento di sentinella" },
    perche: `Hadot descrive l'attenzione a sé come una vigilanza continua sui propri pensieri. Non si tratta di respingerli: si tratta di stare alla porta come una sentinella che vede chi arriva e lo lascia passare. Basta osservare, senza seguire ogni pensiero.`,
    studio: 'esercizi-spirituali',
    voci: {
      epitteto: { apertura: "Mettiti alla porta della mente. Osserva chi entra, senza seguire nessuno.", chiusura: "Chi osserva i pensieri ne è trascinato meno." },
      seneca: { apertura: `Siediti alla porta dei tuoi pensieri come un amico accorto: saluta chi arriva, e lascialo andare.`, chiusura: `Oggi hai guardato i pensieri passare, senza inseguirli.` },
      marco: { apertura: `Sto alla porta e guardo. I pensieri vanno e vengono.`, chiusura: `La sentinella ha fatto il suo turno. Può riposare.` },
    },
    passi: [
      { tipo: 'testo', testo: `Siediti comodo. Immagina di essere una sentinella alla porta di una città. Ogni pensiero è un viandante che arriva. Tu non chiudi la porta: li guardi passare.` },
      { tipo: 'pausa', secondi: 45, testo: `Osserva i pensieri come viandanti. A ognuno puoi dare un nome breve: «lavoro», «paura», «domani». Poi lo lasci andare.` },
      { tipo: 'testo', testo: `Se ti accorgi di aver seguito un pensiero e di essere lontano, va bene: è l'esercizio. Torna alla porta con gentilezza.` },
      { tipo: 'pausa', secondi: 45, testo: `Ancora un minuto alla porta. Non cerchi niente: guardi.` },
    ],
  },
  {
    id: 'sospendi-il-desiderio',
    titolo: 'Sospendi il desiderio',
    disciplina: 'desiderio',
    famiglia: 'pensiero',
    stati: ['ansia', 'sconforto'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'sospendere il desiderio, per ora' },
    perche: `Epitteto consiglia di sospendere, per ora, ogni desiderio, e di usare solo l'impulso ad agire, con leggerezza e con riserva. Quando desideriamo qualcosa che non dipende da noi, ci mettiamo in mano ad altri. Sospendere dà pace.`,
    studio: 'paura-desiderio',
    voci: {
      epitteto: { apertura: "Stai desiderando qualcosa che non dipende da te. Puoi metterlo in pausa. Per ora.", chiusura: "Ciò che non dipende da te, per ora lo lasci. Il resto è tuo." },
      seneca: { apertura: `Il desiderio fa tremare chi lo porta. Vediamo se ciò che vuoi è in tuo potere.`, chiusura: `Sospendere non è rinunciare. È scegliere quando e come desiderare.` },
      marco: { apertura: `Che cosa voglio con tanta ansia? Lo metto da parte per un momento.`, chiusura: `Il desiderio è rimasto lì, ma non mi guida.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'desidero', testo: `Che cosa desideri, o temi di non ottenere, in questo momento? Scrivilo.`, segnaposto: 'Desidero…' },
      { tipo: 'scegli', chiave: 'controllo', testo: `Ottenerlo dipende solo da te?`, opzioni: [{ testo: 'Sì, dipende da me', vai: 'si' }, { testo: 'No, dipende da altri o dalle circostanze', vai: 'no' }] },
      { id: 'si', tipo: 'testo', testo: `Allora il desiderio può diventare un piano: che cosa fai, quando, come? Non serve che sia grande: serve un primo passo.`, poi: 'fine' },
      { id: 'no', tipo: 'testo', testo: `Allora, per ora, sospendi il desiderio. Non lo cancelli: lo metti da parte, e smetti di viverci dentro. Concentrati su ciò che in questa situazione dipende da te.` },
      { tipo: 'scrivi', chiave: 'mio', testo: `Che cosa, in questa situazione, dipende davvero da te?`, segnaposto: 'Dipende da me…' },
    ],
  },
  {
    id: 'l-invidia-in-tre-mosse',
    titolo: 'L’invidia in tre mosse',
    disciplina: 'desiderio',
    famiglia: 'pensiero',
    stati: ['sconforto', 'colpa'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: "perché un altro è onorato e io no: il prezzo di ciò che si ottiene" },
    perche: `Epitteto osserva che ciò che gli altri ottengono ha un prezzo: tempo, servilismo, rinunce. Se rifiuti di pagare quel prezzo, hai poco da rimpiangere: ciò che l'altro ha ottenuto costava troppo. L'invidia si scioglie guardando il costo.`,
    studio: 'mappa-delle-passioni',
    voci: {
      epitteto: { apertura: "Invidi qualcuno? Guarda il prezzo che ha pagato. Lo pagheresti tu?", chiusura: "Ognuno riceve ciò che paga. Anche tu." },
      seneca: { apertura: `L'invidia ci fa guardare il bene altrui e dimenticare il nostro. Proviamo a rimettere le cose a posto.`, chiusura: `Ciò che hai è tuo. Ciò che ha lui è suo, e ha avuto un costo.` },
      marco: { apertura: `Che cosa ha lui che io non ho? E a quale prezzo?`, chiusura: `Ho guardato l'altro senza guardare il mio prezzo. Ora riguardo me.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'invidio', testo: `Che cosa invidi, e a chi? Scrivilo con sincerità: nessuno lo leggerà.`, segnaposto: 'Invidio… il fatto che…' },
      { tipo: 'scrivi', chiave: 'prezzo', testo: `Che cosa ha dovuto fare, o rinunciare, quella persona per ottenerlo? Prova a immaginarlo con equità.`, segnaposto: 'Ha dovuto…' },
      { tipo: 'scegli', chiave: 'pagare', testo: `Tu saresti disposto a pagare quel prezzo?`, opzioni: [{ testo: 'Sì', vai: 'si' }, { testo: 'No', vai: 'no' }] },
      { id: 'si', tipo: 'testo', testo: `Allora l'invidia ti indica una direzione: forse è ciò che desideri davvero. Che cosa puoi fare oggi, di piccolo, per muoverti verso quel bene?`, poi: 'fine' },
      { id: 'no', tipo: 'testo', testo: `Allora non è privazione: è una scelta. Quel bene lo hai lasciato al suo prezzo: nessuno te l'ha tolto. Lo puoi guardare con serenità, senza rancore.` },
    ],
  },
  {
    id: 'il-confronto-che-pesa',
    titolo: 'Il confronto che pesa',
    disciplina: 'desiderio',
    famiglia: 'pensiero',
    stati: ['sconforto'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'vantarsi o sentirsi inferiori per ciò che è altrui è un errore' },
    perche: `Il confronto con gli altri riguarda quasi sempre ciò che non dipende da noi: aspetto, successo, fortuna. Epitteto ricorda che il nostro valore sta nel modo in cui usiamo ciò che è nostro, non nei beni degli altri.`,
    studio: 'cio-che-dipende-da-noi',
    voci: {
      epitteto: { apertura: "Ti stai confrontando? Chiediti su che cosa. Il tuo valore sta in ciò che dipende da te.", chiusura: "Il confronto più giusto è con te di ieri." },
      seneca: { apertura: `Guardare gli altri ci fa sentire poveri. Torniamo a ciò che possiedi davvero.`, chiusura: `Non hai bisogno di essere il primo. Hai bisogno di essere onesto.` },
      marco: { apertura: `Mi paragono. Su che cosa? E che cosa conta davvero?`, chiusura: `Mi misuro su ciò che posso scegliere. Il resto è altrui.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'confronto', testo: `Con chi ti stai confrontando, e su che cosa? Scrivilo.`, segnaposto: 'Mi confronto con… su…' },
      { tipo: 'colonne', chiave: 'proprio', testo: `Ciò su cui ti confronti dipende da te o no? Metti le cose nella colonna giusta.`, sinistra: 'Dipende da me', destra: 'Non dipende da me' },
      { tipo: 'testo', testo: `Sulle cose della seconda colonna il confronto è ingiusto: dipendono dalla fortuna, dalle circostanze, dalle scelte altrui. Non puoi né vincerle né perderle per merito.` },
      { tipo: 'scrivi', chiave: 'ieri', testo: `Sulle cose della prima colonna, confrontati con te di ieri. In che cosa sei migliorato, anche di poco?`, segnaposto: 'Rispetto a ieri…' },
    ],
  },
  {
    id: 'un-favore-in-silenzio',
    titolo: 'Un favore in silenzio',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['colpa', 'sconforto', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: 'Sui benefici', nota: 'il bene fatto senza aspettarsi nulla' },
    perche: `Seneca dice che il bene fatto senza aspettarsi di essere ripagato è quello che più ci libera. Fare un piccolo favore a qualcuno, senza dirlo, sposta l'attenzione da sé agli altri e ci ricorda che possiamo essere utili. Spesso il sollievo viene dall'azione.`,
    studio: 'amicizia-e-comunita',
    voci: {
      epitteto: { apertura: "Puoi fare qualcosa di utile per qualcuno. Provaci, senza dirlo a nessuno.", chiusura: "Il bene fatto in silenzio resta tuo, e costa poco." },
      seneca: { apertura: `Fare bene a qualcuno è uno dei modi più antichi per stare meglio. Pensa a chi puoi aiutare oggi, in piccolo.`, chiusura: `Un favore senza pubblico fa bene a chi lo riceve e a chi lo fa.` },
      marco: { apertura: `Nato per collaborare: che cosa posso fare per qualcuno, oggi?`, chiusura: `Ho fatto la mia parte, piccola. Basta così.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'chi', testo: `A chi potresti fare un piccolo favore oggi? Può essere chiunque: un vicino, un collega, un familiare.`, segnaposto: 'A…' },
      { tipo: 'scrivi', chiave: 'che-cosa', testo: `Che cosa potresti fare? Scegli qualcosa di piccolo e possibile: un messaggio, un aiuto, un gesto.`, segnaposto: 'Potrei…' },
      { tipo: 'testo', testo: `Il favore vale se è senza contropartita. Non serve che l'altro lo sappia o ti ringrazi. Per oggi, basta che lo faccia.` },
      { tipo: 'testo', testo: `Se puoi, fallo entro oggi. Poi lascia andare: non cercare il ritorno.` },
    ],
  },
  {
    id: 'parla-poco',
    titolo: 'Parla poco',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['rabbia', 'sopraffatto'],
    minuti: 1,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'parlare poco, e solo di ciò che serve' },
    perche: `Epitteto invita a tacere per lo più, o a dire poche cose e necessarie. Quando siamo agitati, le parole in più peggiorano le cose. Un minuto di silenzio scelto dà tempo al giudizio di tornare, e a ciò che dirai di essere più giusto.`,
    studio: 'l-ira-secondo-seneca',
    voci: {
      epitteto: { apertura: "Chi sa, tace volentieri. Per un minuto, dì poco e solo ciò che serve.", chiusura: "Di un silenzio ci si pente di rado." },
      seneca: { apertura: `Quando l'animo è in tumulto, il silenzio è un buon amico. Concediti un minuto senza parole.`, chiusura: `Ora, se serve, potrai parlare con più chiarezza.` },
      marco: { apertura: `Un minuto senza parole. Per lasciare posto ai pensieri giusti.`, chiusura: `Il silenzio mi ha restituito la voce giusta.` },
    },
    passi: [
      { tipo: 'testo', testo: `Per un minuto taci, con tutti, e metti da parte anche il telefono. Nemmeno dentro di te, se puoi: lascia che il rumore si posi.` },
      { tipo: 'pausa', secondi: 60, testo: `Solo silenzio. Respira, e senti il corpo.` },
      { tipo: 'scegli', chiave: 'serve', testo: `Adesso, che cosa serve davvero dire, se serve?`, opzioni: [{ testo: 'Una cosa breve e chiara', vai: 'breve' }, { testo: 'Niente, per ora', vai: 'niente' }] },
      { id: 'breve', tipo: 'testo', testo: `Bene: dì quella cosa sola, senza aggiungere. Meno parole, più peso.`, poi: 'fine' },
      { id: 'niente', tipo: 'testo', testo: `Va benissimo. Non ogni cosa chiede una risposta subito. Domani vedrai più chiaro.` },
    ],
  },
  {
    id: 'il-lavoro-che-hai-tra-le-mani',
    titolo: 'Il lavoro che hai tra le mani',
    disciplina: 'azione',
    famiglia: 'attenzione',
    stati: ['sopraffatto', 'ansia'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'fare con serietà ciò che si ha davanti, una cosa alla volta' },
    perche: `Marco Aurelio si esorta a fare con cura ciò che ha in mano, senza distrarsi con tutto il resto. La sensazione di essere sommersi nasce dal guardare tutto insieme. Restringere lo sguardo alla cosa di adesso rende il carico sopportabile.`,
    studio: 'stoicismo-e-lavoro',
    voci: {
      epitteto: { apertura: "Una cosa alla volta. Quella che hai in mano ora.", chiusura: "Il lavoro di oggi è quello che stai facendo." },
      seneca: { apertura: `Chi vuole fare tutto insieme non fa nulla bene. Torniamo a ciò che hai davanti.`, chiusura: `Un gesto ben fatto vale più di dieci abbozzati.` },
      marco: { apertura: `Che cosa ho in mano? Lo faccio con cura, e con serietà.`, chiusura: `Ho un compito, e lo compio.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'mani', testo: `Che cosa stai facendo, o dovresti fare, adesso? Una cosa sola.`, segnaposto: 'Adesso devo…' },
      { tipo: 'testo', testo: `Lascia fuori tutto il resto. Le altre cose esistono, ma non sono nelle tue mani in questo momento.` },
      { tipo: 'scrivi', chiave: 'primo', testo: `Qual è il primo gesto, piccolo e concreto, per cominciare?`, segnaposto: 'Comincio con…' },
      { tipo: 'pausa', secondi: 30, testo: `Prima di cominciare, respira una volta a fondo. Poi fai il primo gesto, con tutta la tua attenzione.` },
    ],
  },
  {
    id: 'l-elenco-di-cio-che-rimandi',
    titolo: 'L’elenco di ciò che rimandi',
    disciplina: 'azione',
    famiglia: 'pensiero',
    stati: ['colpa', 'sopraffatto'],
    minuti: 10,
    fonte: { autore: 'Seneca', opera: 'Sulla brevità della vita', nota: 'il tempo sprecato nel rimandare' },
    perche: `Seneca scrive che la vita non è breve: ne perdiamo molta. Rimandare è uno dei modi di perderla. Guardare l'elenco di ciò che rimandiamo ci fa vedere che spesso la fatica sta nell'attesa, non nel fare.`,
    studio: 'il-tempo-secondo-seneca',
    voci: {
      epitteto: { apertura: "Stai rimandando? Guarda l'elenco. Poi scegli una cosa, e falla ora se ti va.", chiusura: "Ciò che si rimanda pesa spesso più di ciò che si fa." },
      seneca: { apertura: `Il tempo che rimandiamo è tempo che perdiamo. Guardiamo insieme che cosa hai lasciato in attesa.`, chiusura: `Hai riconquistato un pezzo di tempo. Ne hai molto più di quanto pensavi.` },
      marco: { apertura: `Che cosa rimando? Lo guardo, senza scuse.`, chiusura: `Un passo oggi vale più di un piano domani.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'rimando', testo: `Scrivi le cose che rimandi da più di una settimana. Non giudicarti: elenca.`, segnaposto: 'Rimando…' },
      { tipo: 'colonne', chiave: 'sistemo', testo: `Metti ogni cosa nella colonna giusta: quelle che puoi fare e quelle che puoi togliere.`, sinistra: 'La faccio', destra: 'La tolgo' },
      { tipo: 'scrivi', chiave: 'una', testo: `Tra quelle che farai, scegli la più piccola. Scrivi quando la farai.`, segnaposto: 'La farò…' },
      { tipo: 'testo', testo: `Ora immagina la fine della giornata, con quella cosa fatta. Che cosa senti? Il sollievo è il premio di chi smette di rimandare.` },
      { tipo: 'pausa', secondi: 45, testo: `Un minuto per lasciare andare le cose che hai deciso di togliere. Non ti appartengono più.` },
      { tipo: 'testo', testo: `Fai la cosa piccola ora, se puoi. Se no, fissa il momento e mantieni la parola data a te stesso.` },
    ],
  },
  {
    id: 'la-sera-in-un-minuto',
    titolo: 'La sera in un minuto',
    disciplina: 'giudizio',
    famiglia: 'meditazioni',
    stati: ['colpa', 'notte'],
    minuti: 1,
    fonte: { autore: 'Seneca', opera: "Sull'ira", nota: "l'esame della sera in forma breve (III, 36)" },
    perche: `Seneca esaminava la giornata ogni sera, senza nascondersi nulla. Anche una versione di un minuto, con tre domande, tiene vivo il gesto: riconoscere ciò che è andato bene, correggere ciò che si può, e poi riposare senza portarsi dietro la giornata.`,
    studio: 'un-giorno-stoico',
    voci: {
      epitteto: { apertura: "Un minuto, tre domande. Poi puoi dormire.", chiusura: "Il giorno è chiuso. Ciò che resta lo riprendi domani." },
      seneca: { apertura: `Prima di dormire, ripercorriamo la giornata, con benevolenza e senza sconti. Bastano tre domande.`, chiusura: `Hai guardato la giornata. Ora puoi riposare, con la coscienza in ordine.` },
      marco: { apertura: `Sera. Rivedo il giorno in tre domande.`, chiusura: `Il giorno è passato. Lo lascio andare.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'bene', testo: `Che cosa ho fatto bene oggi? Anche una cosa piccola.`, segnaposto: 'Ho fatto bene…' },
      { tipo: 'scrivi', chiave: 'correggere', testo: `Dove ho sbagliato, o potevo fare meglio? Senza giudicarti.`, segnaposto: 'Potevo…' },
      { tipo: 'scrivi', chiave: 'domani', testo: `Che cosa farò diversamente domani? Una cosa sola.`, segnaposto: 'Domani…' },
    ],
  },
  {
    id: 'chi-l-ha-portato-prima-di-me',
    titolo: 'Chi l’ha portato prima di me',
    disciplina: 'desiderio',
    famiglia: 'meditazioni',
    stati: ['sconforto', 'paura'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'guardare le vite di chi ci ha preceduto' },
    perche: `Marco Aurelio richiama spesso le vite di chi è vissuto prima di lui: hanno avuto lutti, guerre, malattie, e sono andati avanti. Serve a ricordare, senza sminuire il dolore, che altri lo hanno già sopportato e che si può.`,
    studio: 'il-dolore-e-la-perdita',
    voci: {
      epitteto: { apertura: "Non sei il primo a soffrire così. Altri hanno portato lo stesso peso, e ce l'hanno fatta.", chiusura: "Ciò che altri hanno sopportato, puoi sopportarlo anche tu." },
      seneca: { apertura: `Pensa a chi, prima di te, ha attraversato un dolore come il tuo. Non sei solo.`, chiusura: `Ti unisci a una lunga fila di persone che hanno tenuto duro.` },
      marco: { apertura: `Quanti hanno vissuto questo, prima di me? E hanno continuato.`, chiusura: `Non sono il primo. Non sarò l'ultimo. Posso farcela.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'peso', testo: `Qual è la difficoltà che stai attraversando? Scrivila in una riga.`, segnaposto: 'Sto attraversando…' },
      { tipo: 'testo', testo: `Ora pensa a una persona, vicina o lontana, viva o no, che ha attraversato qualcosa di simile. Può essere qualcuno che conosci, una figura storica, un personaggio letto.` },
      { tipo: 'scrivi', chiave: 'chi', testo: `Chi hai in mente? Che cosa ha fatto per andare avanti?`, segnaposto: 'Ha…' },
      { tipo: 'pausa', secondi: 30, testo: `Resta un momento con questa persona accanto. Lei ce l'ha fatta, e questo è anche un piccolo pezzo della tua forza.` },
    ],
  },
  {
    id: 'un-appunto-per-domani',
    titolo: 'Un appunto per domani',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['notte', 'ansia'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo", nota: 'la mente ha bisogno di riposo' },
    perche: `Di notte i pensieri sembrano più grandi, e la mente cerca di risolvere tutto subito. Scrivere ciò che ti preoccupa e affidarlo al domani gli dà un posto sicuro. Seneca ricorda che la mente ha bisogno di riposo come di attività.`,
    studio: 'la-paura-del-futuro',
    voci: {
      epitteto: { apertura: "Di notte le cose sembrano più grandi. Scrivi, e lascia la decisione al mattino.", chiusura: "Il pensiero resta scritto. Tu puoi dormire." },
      seneca: { apertura: `L'animo, come il corpo, ha bisogno di riposo. Mettiamo per iscritto ciò che ti agita e lo lasciamo al mattino.`, chiusura: `Il domani ti aspetta, con un appunto e con una mente più fresca.` },
      marco: { apertura: `Ciò che mi agita lo scrivo. Poi lo lascio al giorno.`, chiusura: `L'ho scritto. Posso lasciar andare.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'pensieri', testo: `Scrivi tutto ciò che ti gira in testa, come viene. Non serve che abbia senso.`, segnaposto: 'Mi preoccupa…' },
      { tipo: 'scrivi', chiave: 'domani', testo: `Che cosa potresti fare domani, in concreto, per una di queste cose? Una sola.`, segnaposto: 'Domani…' },
      { tipo: 'testo', testo: `Ora hai messo le cose in un posto sicuro. Ripeti tra te: «È scritto, e domani me ne occupo. Adesso è tempo di riposare».` },
      { tipo: 'respiro', testo: `Rallenta il respiro. Ogni volta che espiri, lascia andare un pensiero.`, dentro: 4, fuori: 7, cicli: 4 },
    ],
  },
  {
    id: 'la-scelta-di-oggi',
    titolo: 'La scelta di oggi',
    disciplina: 'azione',
    famiglia: 'pensiero',
    stati: ['sopraffatto', 'non-so', 'sconforto'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Discorsi', nota: 'la facoltà di scelta (prohaíresis) come ciò che ci appartiene' },
    perche: `Per Epitteto ciò che davvero ci appartiene è la facoltà di scegliere: come rispondere, che cosa fare, in che direzione andare. Quando ci sentiamo in balia degli eventi, ricordare una sola scelta che spetta a noi restituisce un senso di forza.`,
    studio: 'cio-che-dipende-da-noi',
    voci: {
      epitteto: { apertura: "Gli eventi non li scegli. Come rispondere sì. Qual è la tua scelta?", chiusura: "La scelta è l'unica cosa che nessuno può toglierti." },
      seneca: { apertura: `Ti senti in balia delle cose? Tra tutto ciò che non decidi, c'è sempre qualcosa che scegli. Cerchiamolo.`, chiusura: `Hai scelto. È già un modo di essere libero.` },
      marco: { apertura: `Qual è la mia scelta, oggi? Una sola, per cominciare.`, chiusura: `Ho scelto, e la scelta è mia.` },
    },
    passi: [
      { tipo: 'testo', testo: `Ci sono giorni in cui tutto sembra deciso da altri. Ma tra ciò che accade e ciò che facciamo c'è sempre uno spazio: la scelta.` },
      { tipo: 'scrivi', chiave: 'scelta', testo: `Qual è una scelta che spetta a te, oggi? Non deve essere grande: un modo di rispondere, un atteggiamento, un gesto.`, segnaposto: 'Oggi scelgo di…' },
      { tipo: 'testo', testo: `Ripeti la frase a voce bassa. Questa scelta è tua: nessuno può renderla impossibile, e nessuno può farla al posto tuo.` },
      { tipo: 'pausa', secondi: 20, testo: `Un momento di silenzio, con la tua scelta.` },
    ],
  },
  {
    id: 'il-rimedio-dell-abitudine',
    titolo: 'Il rimedio dell’abitudine',
    disciplina: 'desiderio',
    famiglia: 'azione',
    stati: ['paura', 'ansia'],
    minuti: 10,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'esercitarsi alla mancanza con giorni di vita semplice (lettera 18)' },
    perche: `Seneca consigliava di scegliere ogni tanto qualche giorno di vita più semplice, per accorgersi che si può stare senza molte cose che si temono di perdere. La paura di perdere qualcosa nasce dall'abitudine: provare a farne a meno, per poco, la ridimensiona.`,
    studio: 'virtu-temperanza',
    voci: {
      epitteto: { apertura: "Hai paura di perdere qualcosa? Prova a farne a meno, per scelta tua, per un poco.", chiusura: "Chi ha provato a fare senza teme meno di perdere." },
      seneca: { apertura: `Ogni tanto conviene esercitarsi alla mancanza, con serenità. Scegliamo insieme una piccola rinuncia.`, chiusura: `Hai visto che si può. La paura, adesso, ha meno presa.` },
      marco: { apertura: `Di che cosa ho paura di restare senza? Provo a farne a meno, per poco.`, chiusura: `Ho fatto a meno, e sono rimasto in piedi.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'temo', testo: `Di che cosa temi di dover fare a meno? Può essere una comodità, un'abitudine, una sicurezza.`, segnaposto: 'Temo di perdere…' },
      { tipo: 'testo', testo: `Gli stoici non chiedevano di rinunciare per sempre, né di punirsi. Chiedevano di provare, per poco e di proposito, a stare senza, per scoprire quanto si è liberi.` },
      { tipo: 'scrivi', chiave: 'prova', testo: `Scegli una piccola prova, sicura e breve, legata a ciò che temi. Per esempio: un giorno senza telefono per un'ora, un pasto semplice, una passeggiata a piedi.`, segnaposto: 'Proverò a…' },
      { tipo: 'scrivi', chiave: 'quando', testo: `Quando la farai? Fissa il momento.`, segnaposto: 'La farò…' },
      { tipo: 'pausa', secondi: 60, testo: `Immagina di farla. Che cosa provi? Che cosa scopri, dopo?` },
      { tipo: 'testo', testo: `Dopo la prova, chiediti: «È questo che temevo?». Spesso la risposta è no, e la paura si scioglie un poco.` },
    ],
  },
  {
    id: 'il-primo-respiro-del-mattino',
    titolo: 'Il primo respiro del mattino',
    disciplina: 'presenza',
    famiglia: 'attenzione',
    stati: ['ansia', 'non-so'],
    minuti: 1,
    fonte: { autore: 'Hadot', opera: 'Esercizi spirituali e filosofia antica', nota: 'l’attenzione al presente e il rito del risveglio' },
    perche: `Il primo pensiero della giornata spesso corre in avanti, tra cose da fare e cose da temere. Fermarsi a un respiro, prima di alzarsi, permette di cominciare dal presente e non dall'ansia. È il modo più breve per esercitare l'attenzione.`,
    studio: 'un-giorno-stoico',
    voci: {
      epitteto: { apertura: "Prima di alzarti, un respiro. Poi scegli come cominciare.", chiusura: "La giornata è tua da guidare. Buon inizio." },
      seneca: { apertura: `Il mattino è un piccolo inizio. Concediti un respiro prima di correre.`, chiusura: `Buona giornata. Hai cominciato con calma.` },
      marco: { apertura: `Mi sveglio. Un respiro, e sono qui.`, chiusura: `Il giorno comincia. Io con lui.` },
    },
    passi: [
      { tipo: 'respiro', testo: `Prima di alzarti, respira lentamente, sentendo il corpo nel letto.`, dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'testo', testo: `Ricorda una sola cosa che oggi dipende da te: come vuoi trattare le persone che incontrerai.` },
      { tipo: 'testo', testo: `Poi alzati, con calma. Il primo gesto lo fai con attenzione.` },
    ],
  },
  {
    id: 'la-conversazione-in-corso',
    titolo: 'La conversazione in corso',
    disciplina: 'azione',
    famiglia: 'attenzione',
    stati: ['rabbia', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'ascoltare con attenzione e capire ciò che l’altro intende' },
    perche: `Nelle conversazioni difficili rispondiamo a ciò che temiamo che l'altro voglia dire, non a ciò che dice. Marco Aurelio insiste sull'ascoltare con attenzione, entrando nel pensiero dell'altro. Un momento di ascolto vero può evitare una lite.`,
    studio: 'stoicismo-e-relazioni',
    voci: {
      epitteto: { apertura: "Prima di rispondere, prova a capire che cosa vuole dire l'altro. Poi rispondi.", chiusura: "Chi ascolta bene risponde meglio." },
      seneca: { apertura: `Nelle discussioni si parla troppo e si ascolta poco. Proviamo a fare il contrario.`, chiusura: `Hai ascoltato con pazienza. Il resto viene più facile.` },
      marco: { apertura: `Che cosa intende, davvero? Provo a entrare nel suo pensiero.`, chiusura: `Ho ascoltato prima di rispondere.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'ha-detto', testo: `Che cosa ti ha detto o scritto l'altra persona? Riporta le sue parole, senza interpretare.`, segnaposto: 'Ha detto…' },
      { tipo: 'scrivi', chiave: 'intende', testo: `Che cosa potrebbe voler dire, se la guardi con benevolenza? Cerca una lettura più generosa.`, segnaposto: 'Forse intende…' },
      { tipo: 'testo', testo: `Non serve che la lettura generosa sia quella giusta. Serve a raffreddare la reazione e a rispondere da un luogo più calmo.` },
      { tipo: 'scrivi', chiave: 'risposta', testo: `Che cosa risponderesti, se volessi restare giusto e chiaro? Scrivi una frase.`, segnaposto: 'Risponderei…' },
    ],
  },
  {
    id: 'un-limite-gentile',
    titolo: 'Un limite gentile',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['sopraffatto', 'rabbia'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'salvaguardare ciò che è proprio, senza durezza' },
    perche: `Quando accettiamo tutto, ci carichiamo cose che non ci competono e finiamo per covare rancore. Dire di no con gentilezza, e senza offendere, fa parte della giustizia verso se stessi. Epitteto ricorda di custodire ciò che dipende da noi.`,
    studio: 'virtu-giustizia',
    voci: {
      epitteto: { apertura: "Puoi dire di no senza offendere. Custodisci con garbo ciò che è tuo.", chiusura: "Un limite chiaro è un atto di giustizia." },
      seneca: { apertura: `Dire sì a tutti significa dire no a se stessi. Cerchiamo un modo gentile di fissare un confine.`, chiusura: `Il tuo tempo è tuo. Ora lo sai anche dire.` },
      marco: { apertura: `Fin dove arriva ciò che devo? Dove comincia il mio limite?`, chiusura: `Ho fissato un limite, con garbo.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'troppo', testo: `Che cosa ti stanno chiedendo, o ti sei preso, che è troppo per te adesso?`, segnaposto: 'È troppo…' },
      { tipo: 'scrivi', chiave: 'limite', testo: `Qual è il limite giusto? Che cosa puoi fare, e che cosa no?`, segnaposto: 'Posso… ma…' },
      { tipo: 'scrivi', chiave: 'frase', testo: `Scrivi la frase che potresti dire: chiara, gentile, senza troppe scuse.`, segnaposto: 'Vorrei dirti che…' },
      { tipo: 'testo', testo: `Rileggila. Ha un tono rispettoso verso l'altro e verso di te? Se sì, quando puoi dirla? Fissa il momento.` },
    ],
  },
  {
    id: 'la-ricompensa-nascosta',
    titolo: 'La ricompensa nascosta',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['sconforto', 'colpa'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'ciò che ostacola può diventare esercizio di virtù' },
    perche: `Marco Aurelio nota che ciò che ci ostacola diventa esercizio: una perdita insegna pazienza, un torto insegna equità, un fallimento insegna umiltà. Cercare che cosa si può imparare non consola subito, ma dà un senso a ciò che pesa.`,
    studio: 'il-dolore-e-la-perdita',
    voci: {
      epitteto: { apertura: "Ciò che ti pesa è anche un allenamento. Che cosa ti sta insegnando?", chiusura: "Ogni ostacolo è un maestro, se hai voglia di ascoltarlo." },
      seneca: { apertura: `Nessuna difficoltà è del tutto inutile. Cerchiamo che cosa sta insegnandoti questa.`, chiusura: `Hai trovato un frutto, anche piccolo, in ciò che ti pesa.` },
      marco: { apertura: `Che cosa mi insegna questo ostacolo? Lo chiedo a lui.`, chiusura: `L'ostacolo è diventato il sentiero.` },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'ostacolo', testo: `Qual è l'ostacolo o la difficoltà che ti pesa? Scrivilo con semplicità.`, segnaposto: 'La difficoltà è…' },
      { tipo: 'scegli', chiave: 'virtu', testo: `Quale virtù ti chiede di esercitare?`, opzioni: [{ testo: 'Pazienza o coraggio', vai: 'unico' }, { testo: 'Giustizia o benevolenza', vai: 'unico' }, { testo: 'Misura o saggezza', vai: 'unico' }] },
      { id: 'unico', tipo: 'scrivi', chiave: 'impara', testo: `Che cosa puoi imparare da questa situazione, o che cosa ti sta insegnando? Anche solo una piccola cosa.`, segnaposto: 'Mi sta insegnando…' },
      { tipo: 'testo', testo: `Non è detto che ora ti consoli. Ma dà una direzione: da ostacolo, la difficoltà diventa esercizio.` },
    ],
  },
  {
    id: 'le-due-mani',
    titolo: 'Le due mani',
    disciplina: 'azione',
    famiglia: 'meditazioni',
    stati: ['colpa', 'sconforto', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'nati per collaborare, come le mani, i piedi, le palpebre (II, 1)' },
    perche: `Marco Aurelio ricorda che siamo nati per collaborare, come le due mani o i due occhi. Quando ci sentiamo soli o inutili, ricordare che facciamo parte di un insieme e che possiamo servire a qualcuno cambia lo sguardo su di noi.`,
    studio: 'amicizia-e-comunita',
    voci: {
      epitteto: { apertura: "Sei in compagnia: fai parte di una comunità. Pensa a chi ti sta vicino.", chiusura: "Sei una parte utile di un insieme più grande." },
      seneca: { apertura: `Nessuno vive per sé soltanto. Pensiamo alle persone che contano per te, e a quelle per cui conti.`, chiusura: `La vita è meno pesante quando la si sente condivisa.` },
      marco: { apertura: `Sono parte di un insieme, come una mano di un corpo.`, chiusura: `Non sono solo. Ho un posto, e un compito.` },
    },
    passi: [
      { tipo: 'testo', testo: `Guarda le tue mani. Sono due, e lavorano insieme: nessuna è più importante dell'altra. Gli stoici dicevano che gli esseri umani sono fatti così: per aiutarsi.` },
      { tipo: 'scrivi', chiave: 'persone', testo: `Chi ti sta accanto, anche in piccolo? Scrivi due o tre persone che contano per te.`, segnaposto: 'Contano per me…' },
      { tipo: 'scrivi', chiave: 'per-chi', testo: `Per chi puoi essere utile, oggi o questa settimana? Anche in modo semplice.`, segnaposto: 'Posso essere utile a…' },
      { tipo: 'pausa', secondi: 30, testo: `Un momento di silenzio, con queste persone nel cuore.` },
    ],
  },
];
