// Gli esercizi guidati. I testi sono originali (nessuna citazione dai libri); ogni esercizio indica la fonte.
// Formato dei passi: vedi tests/contenuti.test.js e app/js/logica/sessione.js.

export const ESERCIZI = [
  {
    id: 'fermati-impressione',
    titolo: 'Fermati, impressione',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['ansia', 'paura', 'sopraffatto'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: "l'esame delle impressioni e ciò che dipende da noi" },
    perche: 'Quando qualcosa ci spaventa, di solito reagiamo al pensiero che ne abbiamo e non alla cosa. Fermarsi a riconoscere che è un pensiero, e non ancora un fatto, dà lo spazio per esaminarlo prima di crederci.',
    studio: 'impressioni-giudizio',
    voci: {
      epitteto: {
        apertura: "Fermati. Quello che senti è un'impressione. Prima di crederle, esaminala.",
        chiusura: 'Ciò che ti turba è quasi sempre il giudizio sulla cosa, più della cosa stessa.',
      },
      seneca: {
        apertura: 'Siediti un momento con me. Spesso soffriamo più per ciò che immaginiamo che per ciò che accade: guardiamo da vicino ciò che ti preoccupa.',
        chiusura: 'Torna a ciò che c\'è, ora. Il resto può aspettare.',
      },
      marco: {
        apertura: 'Un attimo. Rientra in te. Descrivi ciò che è, senza aggiungere altro.',
        chiusura: 'Sei più grande del pensiero che ti attraversa.',
      },
    },
    passi: [
      { tipo: 'respiro', testo: 'Fermati. Fai qualche respiro lento, seguendo il cerchio.', dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'sembra', testo: 'Completa la frase «Mi sembra che…» con ciò che ti turba, nel modo più semplice possibile.', segnaposto: 'Mi sembra che…' },
      { tipo: 'testo', testo: "Quello che hai scritto è un'impressione: il modo in cui la situazione ti appare adesso. Non è ancora un fatto. Prima di crederle, puoi esaminarla." },
      {
        tipo: 'scegli',
        chiave: 'dipende',
        testo: 'Ciò che hai scritto riguarda qualcosa che dipende da te?',
        opzioni: [{ testo: 'Sì, dipende da me', vai: 'si' }, { testo: 'No, non dipende da me', vai: 'no' }],
      },
      { id: 'si', tipo: 'testo', testo: 'Allora c\'è qualcosa che puoi fare. Pensa al gesto più piccolo che puoi compiere oggi: non serve risolvere tutto, serve cominciare.', poi: 'fine' },
      { id: 'no', tipo: 'testo', testo: 'Allora non puoi decidere come andrà. Puoi decidere come stare in ciò che accade: lascia andare il controllo, senza lasciare andare l\'impegno.' },
    ],
  },
  {
    id: 'descrivi-senza-aggiungere',
    titolo: 'Descrivi senza aggiungere',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['rabbia', 'sconforto', 'colpa'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'descrivere la cosa nuda, senza le aggiunte del giudizio' },
    perche: "Le cose ci feriscono spesso per ciò che ci aggiungiamo sopra: un'intenzione, un'offesa, una condanna. Descrivere solo ciò che c'è, come farebbe un testimone, toglie la parte di peso che viene dal giudizio.",
    studio: 'impressioni-giudizio',
    voci: {
      epitteto: {
        apertura: 'Descrivi la cosa com\'è, come un testimone. Poi togli tutto ciò che ci hai aggiunto tu.',
        chiusura: 'La cosa è più piccola di quanto la fa il tuo giudizio. Guardala per quella che è.',
      },
      seneca: {
        apertura: 'Facciamo ciò che faresti con un amico: raccontiamo i fatti uno alla volta, senza colorarli.',
        chiusura: 'Ora sai quali parole erano tue. Puoi decidere se tenerle.',
      },
      marco: {
        apertura: 'Metti la cosa a nudo. Che cos\'è davvero, da che cosa è fatta, per quanto tempo durerà?',
        chiusura: 'Ciò che resta, una volta tolto il giudizio, è quasi sempre sopportabile.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Pensa a ciò che ti sta pesando adesso. Per qualche minuto lo guarderai come farebbe un testimone: solo ciò che si potrebbe vedere o registrare.' },
      { tipo: 'scrivi', chiave: 'fatti', testo: 'Scrivi soltanto i fatti: chi ha detto o fatto che cosa, e quando. Niente intenzioni, niente aggettivi.', segnaposto: 'È successo che…' },
      { tipo: 'scrivi', chiave: 'aggiunte', testo: 'Ora scrivi ciò che ci hai aggiunto tu: che cosa pensi che significhi, che intenzione c\'era, quanto è grave, che cosa ne seguirà.', segnaposto: 'Ci ho aggiunto che…' },
      { tipo: 'testo', testo: 'I fatti sono una cosa, le aggiunte un\'altra. Le aggiunte sono giudizi, e i giudizi si possono esaminare: a volte sono giusti, spesso sono solo abitudini di pensiero.' },
      {
        tipo: 'scegli',
        chiave: 'dopo',
        testo: 'Rileggi soltanto i fatti. Come ti senti, adesso, rispetto a prima?',
        opzioni: [{ testo: 'Più leggero', vai: 'leggero' }, { testo: 'Uguale', vai: 'ancora' }, { testo: 'Peggio', vai: 'ancora' }],
      },
      { id: 'leggero', tipo: 'testo', testo: 'Quella parte di peso veniva dal giudizio, non dai fatti. Quando il pensiero ritorna, ricorda la differenza.', poi: 'fine' },
      { id: 'ancora', tipo: 'testo', testo: 'Può succedere: alcuni fatti pesano davvero. Allora chiediti una cosa sola: tra i fatti, c\'è qualcosa che dipende da te? Se sì, comincia da lì. Se no, riconosci che è pesante e non aggiungere altro peso.' },
    ],
  },
  {
    id: 'fatto-e-giudizio',
    titolo: 'Il fatto e il giudizio',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['rabbia', 'colpa', 'sconforto'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'ciò che turba non sono le cose, ma i giudizi sulle cose' },
    perche: 'Distinguere ciò che è accaduto da ciò che ne abbiamo concluso è il gesto più semplice e più potente dello stoicismo: i fatti restano, ma molte conclusioni si scoprono discutibili.',
    studio: 'impressioni-giudizio',
    voci: {
      epitteto: {
        apertura: 'Due colonne. Nella prima i fatti, nella seconda i tuoi giudizi. Non mescolarle.',
        chiusura: 'Non sono le cose a turbarti, ma ciò che ne pensi. E ciò che pensi lo puoi cambiare.',
      },
      seneca: {
        apertura: 'Mettiamo un po\' d\'ordine, come si fa con le carte di un processo: da una parte i fatti, dall\'altra le nostre conclusioni.',
        chiusura: 'Non tutto ciò che concludiamo merita fiducia. Puoi rimandare il verdetto.',
      },
      marco: {
        apertura: 'Separa ciò che è accaduto da ciò che pensi che significhi. Sono due cose diverse.',
        chiusura: 'Il giudizio è tuo: puoi tenerlo, correggerlo o lasciarlo andare.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Pensa a ciò che ti turba. Ora dividi ciò che riguarda quella situazione in due elenchi: ciò che è accaduto e ciò che ne hai concluso.' },
      { tipo: 'colonne', chiave: 'fatto-giudizio', testo: 'Scrivi le cose e mettile nella colonna giusta. Se ne sbagli una, toccala per spostarla.', sinistra: 'Ciò che è accaduto', destra: 'Ciò che ne ho concluso' },
      {
        tipo: 'scegli',
        chiave: 'prova',
        testo: 'Guarda la colonna delle conclusioni. Ce n\'è qualcuna che non potresti dimostrare a un giudice?',
        opzioni: [{ testo: 'Sì, qualcuna', vai: 'opinione' }, { testo: 'No, reggono tutte', vai: 'regge' }],
      },
      { id: 'opinione', tipo: 'testo', testo: 'Quella conclusione è un\'opinione, non un fatto. Prova a riscriverla come una possibilità, con la parola «forse»: il peso di solito cala.', poi: 'fine' },
      { id: 'regge', tipo: 'testo', testo: 'Allora il tuo giudizio regge. Ma resta una domanda: che cosa vuoi farne? Anche un giudizio giusto non ti obbliga a restare nella rabbia o nella colpa.' },
    ],
  },
  {
    id: 'come-la-prima-volta',
    titolo: 'Guarda come per la prima volta',
    disciplina: 'presenza',
    famiglia: 'attenzione',
    stati: ['sconforto', 'sopraffatto', 'non-so'],
    minuti: 1,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'lo «spettatore nuovo»' },
    perche: 'L\'abitudine ci fa vedere solo ciò che ci preoccupa. Guardare come se fosse la prima volta riapre lo sguardo: le cose non cambiano, ma il mondo torna più grande del pensiero che ci occupa.',
    studio: 'esercizi-spirituali',
    voci: {
      epitteto: {
        apertura: 'Ora puoi soltanto guardare, come se fosse la prima volta.',
        chiusura: 'Il mondo è ancora là, ed è più grande del tuo pensiero. Guardalo.',
      },
      seneca: {
        apertura: 'Ti confido un\'abitudine mia: guardo il mondo come se vi arrivassi in questo momento. Proviamo insieme.',
        chiusura: 'Lo stupore non si era perso: era coperto dall\'abitudine.',
      },
      marco: {
        apertura: 'Guarda questo luogo come farebbe un ospite appena arrivato.',
        chiusura: 'Tutto è più ampio del pensiero che ti occupa.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Alza lo sguardo. Per un minuto guarda ciò che hai attorno come se lo vedessi per la prima volta, come un viaggiatore appena arrivato.' },
      { tipo: 'pausa', secondi: 30, testo: 'Cerca cinque cose che di solito non noti: una forma, un colore, un gioco di luce, un dettaglio, un suono.' },
      { tipo: 'scrivi', chiave: 'novita', testo: 'Scrivi una cosa che hai notato, come se fosse nuova.', segnaposto: 'Ho notato…' },
      { tipo: 'testo', testo: 'Le cose non sono cambiate: è cambiato lo sguardo. Quello abituale ci mostra solo ciò che ci preoccupa; quello nuovo lascia entrare il resto del mondo.' },
      { tipo: 'testo', testo: 'Porta questo sguardo con te ancora un momento. Se un pensiero difficile ritorna, guardalo allo stesso modo: come se lo incontrassi per la prima volta.' },
    ],
  },
  {
    id: 'cio-che-dipende-da-me',
    titolo: 'Ciò che dipende da me',
    disciplina: 'desiderio',
    famiglia: 'pensiero',
    stati: ['ansia', 'paura', 'sopraffatto', 'sconforto', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: "la distinzione tra ciò che dipende da noi e ciò che non dipende da noi" },
    perche: `Gran parte dell'inquietudine nasce dal voler controllare ciò che non dipende da noi. Separare le due cose libera energia: si sa dove agire e dove soltanto sopportare o accettare.`,
    studio: 'cio-che-dipende-da-noi',
    voci: {
      epitteto: {
        apertura: `Due elenchi: ciò che dipende da te e ciò che non dipende da te. È la regola da cui viene tutto il resto.`,
        chiusura: `Metti la tua forza dove può servire. Il resto non è tuo da portare.`,
      },
      seneca: {
        apertura: `Fermiamoci a contare ciò che è davvero nelle tue mani. Sarà meno di quanto temi, e più di quanto pensi.`,
        chiusura: `Lasciare andare ciò che è di altri è risparmiare le forze, più che arrendersi.`,
      },
      marco: {
        apertura: `Che cosa è tuo, in tutto questo? I tuoi giudizi, le tue scelte. Il resto appartiene al corso delle cose.`,
        chiusura: `Custodisci ciò che è tuo. Il resto lo affronterai quando verrà.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Pensa a ciò che ti preoccupa adesso. Lo divideremo in due elenchi: ciò che dipende da te e ciò che non dipende da te.` },
      { tipo: 'colonne', chiave: 'controllo', testo: `Scrivi le tue preoccupazioni e mettile nella colonna giusta. Dipende da te ciò che scegli, pensi e fai; non dipende da te ciò che decidono gli altri, l'esito delle cose e il passato.`, sinistra: 'Dipende da me', destra: 'Non dipende da me' },
      { tipo: 'testo', testo: `Guarda la colonna di destra. Quelle cose sfuggono al tuo comando, e preoccuparti le lascia com'erano. Puoi solo decidere come stare davanti a loro.` },
      {
        tipo: 'scegli',
        chiave: 'energia',
        testo: `Nella colonna di sinistra, c'è qualcosa che puoi fare oggi?`,
        opzioni: [{ testo: 'Sì, qualcosa', vai: 'agisci' }, { testo: 'Non oggi', vai: 'riposa' }],
      },
      { id: 'agisci', tipo: 'testo', testo: `Scegli una sola cosa di quella colonna e decidi quando la farai. Non tutte: una. Il resto, per ora, può aspettare.`, poi: 'fine' },
      { id: 'riposa', tipo: 'testo', testo: `Allora oggi c'è ben poco da fare. Hai già fatto la parte più difficile: capire dove è inutile agire. Puoi riposare senza sensi di colpa.` },
    ],
  },
  {
    id: 'prepararsi-al-peggio',
    titolo: 'Prepararsi al peggio',
    disciplina: 'desiderio',
    famiglia: 'meditazioni',
    stati: ['paura', 'ansia'],
    minuti: 10,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'la premeditazione dei mali, insieme a Epitteto, Manuale' },
    perche: `Immaginare con calma ciò che si teme toglie alla paura il potere della sorpresa: si vede che cosa si potrebbe fare, e si torna al presente più preparati e meno spaventati.`,
    studio: 'paura-desiderio',
    voci: {
      epitteto: {
        apertura: `Guarda in faccia ciò che temi, con calma. Poi decidi che cosa farai.`,
        chiusura: `Ciò che hai guardato in faccia fa meno paura. Ora torna a ciò che devi fare.`,
      },
      seneca: {
        apertura: `Vieni, guardiamo insieme ciò che temi: serve a essere preparati, non a soffrire in anticipo.`,
        chiusura: `Hai guardato il peggio e sei ancora qui. Ora il presente ti sembrerà più leggero.`,
      },
      marco: {
        apertura: `Immagina con calma ciò che potrebbe accadere. Poi ricorda che cosa puoi fare, e chi vuoi essere.`,
        chiusura: `Sei pronto, per quanto si può essere. Torna a ciò che stai facendo.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Questo esercizio dura circa dieci minuti. Siediti comodo. Non serve credere che ciò che temi accadrà: serve soltanto guardarlo con calma.` },
      { tipo: 'respiro', testo: `Qualche respiro lento, per arrivare qui.`, dentro: 4, fuori: 6, cicli: 4 },
      { tipo: 'scrivi', chiave: 'timore', testo: `Scrivi ciò che temi, nel modo più concreto possibile: che cosa, esattamente, potrebbe accadere?`, segnaposto: 'Temo che…' },
      { tipo: 'testo', testo: `Ora immaginalo davvero, per un momento, senza scappare: com'è? Che cosa vedresti, che cosa sentiresti? Resta lì, con il respiro tranquillo.` },
      { tipo: 'pausa', secondi: 60, testo: `Resta con questa immagine per un minuto. Se la paura sale, ricordati di respirare e continua.` },
      { tipo: 'testo', testo: `Adesso guardala con occhi pratici. Se accadesse davvero: che cosa sarebbe nelle tue mani? A chi potresti chiedere aiuto? Che cosa faresti il primo giorno?` },
      { tipo: 'scrivi', chiave: 'risposta', testo: `Scrivi in due o tre righe che cosa faresti.`, segnaposto: 'Farei…' },
      { tipo: 'testo', testo: `Ricorda: non è detto che accada. Ma se accadesse, non saresti impreparato: hai già una strada. Il futuro non è nelle tue mani; il modo in cui lo affronti sì.` },
      { tipo: 'respiro', testo: `Torna al presente con qualche respiro: ora, qui, è tutto ciò che devi affrontare.`, dentro: 4, fuori: 6, cicli: 3 },
    ],
  },
  {
    id: 'il-peggio-misurato',
    titolo: 'Il peggio, misurato',
    disciplina: 'desiderio',
    famiglia: 'pensiero',
    stati: ['ansia', 'paura'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'si soffre più con l\'immaginazione che nella realtà' },
    perche: `L'ansia gonfia le possibilità. Misurare il peggio con tre domande concrete lo riporta alla sua vera grandezza, e spesso mostra che è meno probabile e più sopportabile di come lo immaginiamo.`,
    studio: 'paura-desiderio',
    voci: {
      epitteto: {
        apertura: `Tre domande sul tuo timore. Rispondi con onestà, non con paura.`,
        chiusura: `Hai misurato la paura. Ora sai quanto pesa davvero.`,
      },
      seneca: {
        apertura: `Soffriamo spesso più nell'immaginazione che nella realtà. Misuriamo insieme ciò che temi.`,
        chiusura: `Non lasciare che la paura arrivi prima di ciò che temi.`,
      },
      marco: {
        apertura: `Guarda ciò che temi come lo guarderebbe un giudice: con prove e con misura.`,
        chiusura: `Ciò che è davvero, è quasi sempre più piccolo di ciò che immaginiamo.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Pensa a ciò che temi. Lo misureremo con tre domande, una alla volta.` },
      { tipo: 'scegli', chiave: 'probabile', testo: `È probabile? Se guardi i fatti, e non la paura, quante possibilità ci sono che accada?`, opzioni: [{ testo: 'Poche' }, { testo: 'Non lo so' }, { testo: 'Molte' }] },
      { tipo: 'scegli', chiave: 'sopportabile', testo: `Se accadesse, potresti sopportarlo? Non che sarebbe piacevole: solo se potresti attraversarlo.`, opzioni: [{ testo: 'Sì, con fatica' }, { testo: 'Non lo so' }, { testo: 'Sarebbe troppo' }] },
      { tipo: 'scegli', chiave: 'gia', testo: `Hai già affrontato, in passato, qualcosa di difficile e ne sei uscito?`, opzioni: [{ testo: 'Sì' }, { testo: 'Non mi pare' }] },
      { tipo: 'testo', testo: `Ecco il quadro. Spesso ciò che temiamo è meno probabile di come lo sentiamo e più sopportabile di come lo immaginiamo. E anche quando non lo è, le cose difficili si attraversano un passo alla volta.` },
      { tipo: 'scrivi', chiave: 'passo', testo: `Se dovessi fare un solo passo oggi, per prepararti o per stare meglio, quale sarebbe?`, segnaposto: 'Il primo passo è…' },
    ],
  },
  {
    id: 'la-brocca-che-si-rompe',
    titolo: 'La brocca che si può rompere',
    disciplina: 'desiderio',
    famiglia: 'meditazioni',
    stati: ['paura', 'sconforto'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'la fragilità delle cose che amiamo, e la brocca che può rompersi' },
    perche: `Ricordare che le cose e le persone care sono fragili e di passaggio non serve a rattristarci: serve a volere loro bene con più presenza e con meno paura di perderle.`,
    studio: 'il-tempo-la-morte',
    voci: {
      epitteto: {
        apertura: `Ricorda ciò che è fragile. Ciò che ami può rompersi: amalo comunque, e con più attenzione.`,
        chiusura: `Stringi meno, guarda di più. Ciò che ami è un dono, non un possesso.`,
      },
      seneca: {
        apertura: `Con calma e con dolcezza: pensiamo a quanto le cose sono preziose proprio perché non sono eterne.`,
        chiusura: `Ciò che dura poco merita più attenzione e meno paura.`,
      },
      marco: {
        apertura: `Tutto passa. Guarda ciò che ami con la gratitudine di chi sa che è un momento.`,
        chiusura: `Vivi con ciò che hai ora. È già molto.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Questo esercizio è delicato: fallo quando ti senti pronto. Se a un certo punto ti sembra troppo, puoi fermarti. Non è una gara.` },
      { tipo: 'testo', testo: `Pensa a una cosa o a una persona a cui tieni. Gli stoici ricordavano a se stessi che ciò che amiamo è fragile e non è nostro per sempre, come una bella brocca che potrebbe rompersi.` },
      { tipo: 'respiro', testo: `Un respiro lento, mentre la tieni nel pensiero.`, dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'grazie', testo: `Scrivi che cosa ti dà, questa cosa o questa persona: che cosa ti ha regalato finora.`, segnaposto: 'Sono grato per…' },
      { tipo: 'testo', testo: `La fragilità non toglie valore: lo dà. Ciò che potrebbe finire merita la tua attenzione di oggi. Puoi volergli bene con le mani aperte: senza stringere, senza pretendere che duri.` },
      { tipo: 'scegli', chiave: 'gesto', testo: `C'è un piccolo gesto che puoi fare oggi per questa cosa o questa persona?`, opzioni: [{ testo: 'Sì', vai: 'gesto' }, { testo: 'Non oggi', vai: 'fine' }] },
      { id: 'gesto', tipo: 'testo', testo: `Allora fallo: una parola, una telefonata, un momento di attenzione. L'affetto vive di gesti piccoli e presenti.`, poi: 'fine' },
    ],
  },
  {
    id: 'il-primo-gesto-piccolo',
    titolo: 'Il primo gesto piccolo',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['sopraffatto', 'ansia', 'non-so'],
    minuti: 1,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'fare con cura ciò che si ha tra le mani, ora' },
    perche: `Quando le cose da fare sono troppe, la mente si blocca. Scegliere una sola cosa e il suo primo gesto, così piccolo da compierlo in due minuti, restituisce il movimento.`,
    studio: 'tre-discipline',
    voci: {
      epitteto: {
        apertura: `Una cosa sola. Il primo gesto. Poi il resto.`,
        chiusura: `Comincia. Il resto si sistema lungo la strada.`,
      },
      seneca: {
        apertura: `Non devi risolvere tutto oggi. Scegliamo una cosa e il suo primo gesto.`,
        chiusura: `Un gesto piccolo, fatto davvero, vale più di cento propositi.`,
      },
      marco: {
        apertura: `Fai ciò che hai tra le mani, ora, con cura. Il resto verrà dopo.`,
        chiusura: `Ora fai questo, e soltanto questo, con tutta l'attenzione che hai.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Quando le cose da fare sono troppe, ogni inizio sembra impossibile. Scegliamone una sola.` },
      { tipo: 'scrivi', chiave: 'cosa', testo: `Tra tutte, quale sarebbe più utile o più leggera da togliere di mezzo? Scrivila.`, segnaposto: 'La cosa è…' },
      { tipo: 'scrivi', chiave: 'gesto', testo: `Qual è il primo gesto, così piccolo da poterlo fare in due minuti? Aprire un file, scrivere una riga, fare una telefonata.`, segnaposto: 'Il primo gesto è…' },
      { tipo: 'testo', testo: `Non pensare al resto. Ora, per due minuti, fai soltanto quel gesto con tutta la tua attenzione.` },
    ],
  },
  {
    id: 'chi-voglio-essere-qui',
    titolo: 'Chi voglio essere qui',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['colpa', 'rabbia'],
    minuti: 3,
    fonte: { autore: 'Epitteto', opera: 'Manuale', nota: 'i ruoli che ricopriamo e i doveri che ne vengono' },
    perche: `Nei momenti difficili è facile lasciarsi guidare dall'emozione. Chiedersi in quale ruolo ci troviamo, e che cosa farebbe una persona buona in quel ruolo, dà un punto fermo per agire bene.`,
    studio: 'tre-discipline',
    voci: {
      epitteto: {
        apertura: `In questo momento sei figlio, collega, amico, cittadino. Che cosa chiede da te ogni ruolo?`,
        chiusura: `Fai ciò che chiede il tuo ruolo. Il resto non è affar tuo.`,
      },
      seneca: {
        apertura: `Prima di agire, chiediti chi vuoi essere in questa situazione, non solo che cosa provi.`,
        chiusura: `Le emozioni passano. Ciò che fai resta parte di te.`,
      },
      marco: {
        apertura: `Sii ciò che sei chiamato a essere in questo momento: con giustizia, con cura, senza clamore.`,
        chiusura: `Fai bene la tua parte. Non serve altro.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Pensa alla situazione che ti pesa. In essa tu hai un ruolo, o più di uno: figlio, genitore, collega, amico, cittadino.` },
      { tipo: 'scrivi', chiave: 'ruolo', testo: `In quale ruolo ti trovi, adesso?`, segnaposto: 'Qui sono…' },
      { tipo: 'scrivi', chiave: 'persona-buona', testo: `Che cosa farebbe una persona buona e giusta, in quel ruolo? Non ciò che vorresti fare in questo momento: ciò che sarebbe giusto.`, segnaposto: 'Farebbe…' },
      { tipo: 'scegli', chiave: 'pronto', testo: `Riesci a farlo?`, opzioni: [{ testo: 'Sì', vai: 'si' }, { testo: 'Non ancora', vai: 'non' }] },
      { id: 'si', tipo: 'testo', testo: `Bene. Fallo con calma, senza aspettare che la rabbia o la colpa passino del tutto.`, poi: 'fine' },
      { id: 'non', tipo: 'testo', testo: `Allora fai un passo più piccolo: qual è la parte più semplice di ciò che è giusto fare? Comincia da quella.` },
    ],
  },
  {
    id: 'se-nulla-lo-impedisce',
    titolo: 'Se nulla lo impedisce',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['ansia', 'sopraffatto'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: 'Sulla tranquillità dell\'animo', nota: 'la clausola di riserva: agire con impegno senza legare la serenità all\'esito' },
    perche: `Quando pretendiamo che un progetto vada esattamente come vogliamo, ogni ostacolo diventa una minaccia. Agire con una riserva, «lo farò, se nulla lo impedisce», permette di impegnarsi davvero senza legare la propria serenità all'esito.`,
    studio: 'cio-che-dipende-da-noi',
    voci: {
      epitteto: {
        apertura: `Fai il tuo progetto con impegno. Poi aggiungi: se nulla lo impedisce.`,
        chiusura: `Hai fatto la tua parte. L'esito non è tuo.`,
      },
      seneca: {
        apertura: `Il saggio si mette all'opera con tutte le forze e con una riserva: se nulla lo impedisce. Proviamo anche noi.`,
        chiusura: `Chi agisce così non si spezza quando le cose cambiano.`,
      },
      marco: {
        apertura: `Agisci con cura, e tieni conto che qualcosa potrebbe intralciarti.`,
        chiusura: `L'impegno è tuo. Il risultato appartiene al corso delle cose.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Pensa a qualcosa che vuoi fare e che ti preoccupa, perché potrebbe non andare come speri.` },
      { tipo: 'scrivi', chiave: 'progetto', testo: `Scrivi che cosa vuoi fare, in una frase.`, segnaposto: 'Voglio…' },
      { tipo: 'testo', testo: `Ora aggiungi la riserva degli stoici: «lo farò, se nulla lo impedisce». Non è una scusa per impegnarti meno: è il modo di impegnarti del tutto senza attaccare la tua serenità al risultato.` },
      { tipo: 'scrivi', chiave: 'ostacoli', testo: `Che cosa potrebbe intralciarti? Scrivi una o due cose.`, segnaposto: 'Potrebbe intralciarmi…' },
      { tipo: 'scegli', chiave: 'accetti', testo: `Se accadesse, sapresti di aver comunque fatto il tuo meglio?`, opzioni: [{ testo: 'Sì', vai: 'si' }, { testo: 'Non ancora', vai: 'non' }] },
      { id: 'si', tipo: 'testo', testo: `Allora sei pronto: agisci con tutta la forza che hai. Il resto non dipende da te.`, poi: 'fine' },
      { id: 'non', tipo: 'testo', testo: `Allora chiediti che cosa ti manca per poter dire di aver fatto il tuo meglio: un aiuto, più tempo, un'informazione? Prima di agire, procura quello.` },
    ],
  },
  {
    id: 'l-ostacolo-come-materia',
    titolo: 'L\'ostacolo come materia',
    disciplina: 'azione',
    famiglia: 'meditazioni',
    stati: ['sconforto', 'sopraffatto'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'ogni impedimento può diventare materia per la propria azione' },
    perche: `Ciò che si oppone a noi può diventare occasione: dove non possiamo cambiare la situazione, possiamo esercitare una qualità. L'ostacolo diventa il materiale su cui lavorare.`,
    studio: 'tre-discipline',
    voci: {
      epitteto: {
        apertura: `Ciò che ti ostacola è materiale. Che cosa puoi costruire con esso?`,
        chiusura: `L'ostacolo non ferma chi sa usarlo.`,
      },
      seneca: {
        apertura: `Nessuna difficoltà è inutile: ognuna esercita qualcosa in noi. Vediamo che cosa.`,
        chiusura: `Ciò che ti pesa può renderti più saldo, se lo attraversi con misura.`,
      },
      marco: {
        apertura: `Ciò che ti sbarra il passo può diventare il passo. Guardalo così.`,
        chiusura: `Che cosa può esercitare in te, questo ostacolo? Fallo diventare un compito.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Pensa a ciò che ti ostacola in questo momento: una situazione, una persona, una difficoltà.` },
      { tipo: 'scrivi', chiave: 'ostacolo', testo: `Scrivilo in una frase.`, segnaposto: "L'ostacolo è…" },
      { tipo: 'testo', testo: `Un ostacolo non si può sempre eliminare. Ma si può sempre chiedere: che cosa mi permette di esercitare? Pazienza, coraggio, misura, generosità?` },
      { tipo: 'scegli', chiave: 'qualita', testo: `Quale di queste qualità ti serve di più, adesso?`, opzioni: [{ testo: 'Pazienza' }, { testo: 'Coraggio' }, { testo: 'Misura' }] },
      { tipo: 'scrivi', chiave: 'come', testo: `Che cosa significherebbe, in concreto, esercitare questa qualità davanti a questo ostacolo?`, segnaposto: 'Userei questa qualità così…' },
      { tipo: 'testo', testo: `Ora l'ostacolo ha un compito: non è più soltanto un peso, è il materiale del tuo lavoro di oggi.` },
    ],
  },
  {
    id: 'qui-e-ora-cinque-sensi',
    titolo: 'Qui e ora, con i cinque sensi',
    disciplina: 'presenza',
    famiglia: 'attenzione',
    stati: ['ansia', 'notte', 'non-so'],
    minuti: 1,
    sostegno: true,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: "vivere nel momento presente" },
    perche: `L'ansia vive nel futuro e nel passato. I sensi sono sempre nel presente: notare ciò che si vede, si tocca e si sente riporta l'attenzione qui, dove le cose sono ancora affrontabili. Usare i sensi è una tecnica di oggi, coerente con l'invito di Marco Aurelio a vivere nel momento presente.`,
    studio: 'esercizi-spirituali',
    voci: {
      epitteto: {
        apertura: `Torna ai sensi. Che cosa vedi, che cosa tocchi, adesso?`,
        chiusura: `Sei qui. È l'unico luogo in cui puoi fare qualcosa.`,
      },
      seneca: {
        apertura: `Esci dai pensieri con dolcezza: ascoltiamo che cosa c'è intorno a te.`,
        chiusura: `Il presente è quasi sempre più sopportabile dei pensieri che lo precedono.`,
      },
      marco: {
        apertura: `Lascia il pensiero e torna a ciò che c'è: la luce, i suoni, il tuo respiro.`,
        chiusura: `Questo momento è tutto ciò che possiedi. Basta.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Ferma lo sguardo. Per un minuto porta l'attenzione ai sensi. Non serve pensare: serve notare.` },
      { tipo: 'testo', testo: `Guarda intorno e nomina, dentro di te, cinque cose che vedi.` },
      { tipo: 'testo', testo: `Ora quattro cose che tocchi o senti a contatto con il corpo: la sedia, i vestiti, i piedi sul pavimento.` },
      { tipo: 'testo', testo: `Tre cose che senti con le orecchie. Anche i suoni più lontani.` },
      { tipo: 'respiro', testo: `Due odori, se ce ne sono, e un sapore in bocca. Poi un respiro lento.`, dentro: 4, fuori: 6, cicli: 2 },
      { tipo: 'testo', testo: `Ora che sei più calmo, fai una domanda sola: di ciò che ti turba, che cosa dipende da te? Tieni quella cosa. Il resto, per ora, lascialo stare.` },
    ],
  },
  {
    id: 'respiro-e-attenzione',
    titolo: 'Respiro e attenzione',
    disciplina: 'presenza',
    famiglia: 'attenzione',
    stati: ['ansia', 'notte'],
    minuti: 3,
    sostegno: true,
    fonte: { autore: 'Epitteto', opera: 'Discorsi', nota: "l'attenzione a sé (prosoché); il respiro è un sostegno di oggi" },
    perche: `Gli stoici chiamavano prosoché la vigilanza su di sé. Seguire il respiro non è un loro esercizio: lo usiamo come sostegno di oggi, perché è il modo più semplice di portare l'attenzione qui. Ogni volta che la mente scappa e la riportiamo indietro, rafforziamo la capacità di tornare al presente.`,
    studio: 'esercizi-spirituali',
    voci: {
      epitteto: {
        apertura: `Un respiro dopo l'altro. Se la mente scappa, riportala, senza rimproveri.`,
        chiusura: `Ogni ritorno è un piccolo allenamento. Hai già fatto bene.`,
      },
      seneca: {
        apertura: `Facciamo insieme qualche respiro, senza fretta: adesso c'è ben poco da risolvere.`,
        chiusura: `Quando la mente ritorna, non ha sbagliato: sta imparando.`,
      },
      marco: {
        apertura: `Torna al respiro, come si torna a casa. Ti accoglie così come sei.`,
        chiusura: `Ti sei fermato. Già questo è un modo di rimettere ordine.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Siediti o stenditi in modo comodo. Per tre minuti seguirai il respiro, senza cambiarlo.` },
      { tipo: 'respiro', testo: `Segui il cerchio: dentro, fuori. Se la mente scappa, riportala al respiro, senza rimproverarti.`, dentro: 4, fuori: 6, cicli: 6 },
      { tipo: 'testo', testo: `Ogni volta che ti accorgi di essere altrove e torni, stai facendo proprio l'esercizio: quello è il muscolo dell'attenzione.` },
      { tipo: 'respiro', testo: `Ancora qualche respiro, con lo stesso ritmo.`, dentro: 4, fuori: 6, cicli: 4 },
      { tipo: 'testo', testo: `Quando sei pronto, guarda ciò che hai attorno e torna a ciò che stavi facendo, con un po' più di spazio dentro.` },
      { tipo: 'testo', testo: `Ora che sei più calmo, fai una domanda sola: di ciò che ti turba, che cosa dipende da te? Tieni quella cosa. Il resto, per ora, lascialo stare.` },
    ],
  },
  {
    id: 'aspetta-prima-di-rispondere',
    titolo: 'Aspetta prima di rispondere',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['rabbia'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: 'Sull\'ira', nota: 'il ritardo come primo rimedio contro la collera' },
    perche: `Nel pieno della rabbia si dice e si fa ciò che poi si rimpiange. Il rimedio più antico è aspettare: il tempo tra ciò che accade e ciò che rispondiamo è il luogo in cui si sceglie.`,
    studio: 'tre-discipline',
    voci: {
      epitteto: {
        apertura: `Fermati prima di rispondere. La tua risposta è tua: sceglila.`,
        chiusura: `Chi risponde con calma conserva tutto. Chi risponde con rabbia, spesso perde qualcosa.`,
      },
      seneca: {
        apertura: `Il miglior rimedio all'ira è il ritardo. Prendiamoci un momento prima di parlare.`,
        chiusura: `Ciò che decidi da calmo è sempre più tuo di ciò che decidi da arrabbiato.`,
      },
      marco: {
        apertura: `Non lasciare che l'ira decida per te. Aspetta, e poi rispondi con misura.`,
        chiusura: `Rispondere con calma è già una risposta.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Se sei arrabbiato, non rispondere ancora. Per ora fermati.` },
      { tipo: 'pausa', secondi: 30, testo: `Trenta secondi di silenzio. Senti il corpo: le spalle, la mascella, il respiro. Osserva senza cercare di cambiare nulla.` },
      { tipo: 'scrivi', chiave: 'voglio', testo: `Che cosa vuoi ottenere, davvero, con la tua risposta? Che l'altro capisca, che le cose migliorino, che cosa?`, segnaposto: 'Vorrei ottenere…' },
      { tipo: 'scegli', chiave: 'risposta', testo: `La risposta che stai pensando ti porta verso ciò che vuoi ottenere?`, opzioni: [{ testo: 'Sì', vai: 'si' }, { testo: 'No', vai: 'no' }] },
      { id: 'si', tipo: 'testo', testo: `Allora puoi rispondere: con calma, con parole misurate.`, poi: 'fine' },
      { id: 'no', tipo: 'testo', testo: `Allora aspetta ancora: non è il momento. Cambia stanza, bevi un bicchiere d'acqua, cammina un po'. Se puoi, rispondi domani: la rabbia di oggi non ha il diritto di parlare per te.` },
    ],
  },
  {
    id: 'esame-della-sera',
    titolo: 'Esame della sera',
    disciplina: 'giudizio',
    famiglia: 'meditazioni',
    stati: ['colpa', 'notte'],
    minuti: 10,
    fonte: { autore: 'Seneca', opera: 'Sull\'ira', nota: "l'esame di coscienza della sera, secondo la pratica di Sestio e di Seneca" },
    perche: `L'esame della sera, come lo praticava Seneca, non è una condanna ma un colloquio con se stessi: si guarda la giornata con onestà, si riconosce ciò che è andato bene, si corregge ciò che si può, e si dorme senza portarsi dietro il processo.`,
    studio: 'esercizi-spirituali',
    voci: {
      epitteto: {
        apertura: `Passa in rassegna la giornata. Che cosa hai fatto bene? Che cosa correggi? Poi basta.`,
        chiusura: `Domani è un'altra occasione. Riposa.`,
      },
      seneca: {
        apertura: `Quando la luce si spegne, mi faccio il processo con calma e senza nascondermi niente. Facciamolo insieme.`,
        chiusura: `Nessun errore ti spaventi: guardalo, perdonati e correggiti.`,
      },
      marco: {
        apertura: `Chiudi la giornata come si chiude un quaderno: rileggi, annota, metti da parte.`,
        chiusura: `Hai fatto ciò che potevi. Domani ricomincerai.`,
      },
    },
    passi: [
      { tipo: 'testo', testo: `Questo esercizio è per la sera. Non è un processo: è un colloquio onesto con te stesso, come lo faceva Seneca. Siediti in silenzio e ripensa alla giornata, dall'inizio.` },
      { tipo: 'respiro', testo: `Qualche respiro lento, per lasciare la giornata alle spalle un momento.`, dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'bene', testo: `Che cosa hai fatto bene oggi? Anche le cose piccole.`, segnaposto: 'Ho fatto bene…' },
      { tipo: 'scrivi', chiave: 'sbagliato', testo: `Dove hai sbagliato o non sei stato come volevi? Scrivilo con semplicità, senza aggettivi cattivi su di te.`, segnaposto: 'Ho sbagliato…' },
      { tipo: 'scrivi', chiave: 'diverso', testo: `Che cosa farai diversamente, se si ripresenta? Una cosa sola.`, segnaposto: 'La prossima volta…' },
      { tipo: 'testo', testo: `Ora chiudi il conto. Ciò che hai riconosciuto lo hai già in parte corretto. Seneca si concedeva il perdono per gli errori di ogni giorno e si impegnava a fare meglio: non serve punirsi per rimettere le cose a posto.` },
      { tipo: 'pausa', secondi: 30, testo: `Un momento di silenzio prima di dormire. Lascia andare la giornata.` },
    ],
  },
  {
    id: 'prepara-la-giornata',
    titolo: 'Prepara la giornata',
    disciplina: 'giudizio',
    famiglia: 'meditazioni',
    stati: ['ansia', 'sopraffatto', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'la preparazione del mattino (II, 1)' },
    perche: `Marco Aurelio comincia la giornata dicendosi in anticipo che incontrerà persone difficili. Lo fa per essere pronto, e per ricordarsi che chi sbaglia lo fa spesso per ignoranza. Ciò che si è già previsto agita meno.`,
    studio: 'il-tempo-la-morte',
    voci: {
      epitteto: {
        apertura: 'Prima di uscire, prepara la parte che devi recitare. Che cosa ti aspetta oggi?',
        chiusura: 'Sei pronto. Ciò che arriverà lo vedrai per quello che è.',
      },
      seneca: {
        apertura: 'Facciamo il conto della giornata prima che cominci, con calma. Che cosa potrebbe metterti alla prova?',
        chiusura: 'Sapere prima ciò che può accadere toglie metà del suo peso.',
      },
      marco: {
        apertura: 'Prima ancora di cominciare, dì a te stesso che cosa incontrerai e come vorrai essere.',
        chiusura: 'Adesso puoi andare. Sei già preparato.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Prendi un minuto prima di cominciare la giornata (o la prossima parte della giornata). Non serve organizzare tutto: serve prepararsi.' },
      { tipo: 'scrivi', chiave: 'incontri', testo: 'Che cosa, o chi, potrebbe metterti alla prova oggi? Una persona difficile, un imprevisto, una cosa che temi.', segnaposto: 'Oggi potrei incontrare…' },
      { tipo: 'testo', testo: 'Ora ricordati una cosa: chi si comporta male, di solito lo fa perché non vede meglio. Questo non scusa nessuno, ma ti aiuta a prenderla meno sul personale.' },
      { tipo: 'scrivi', chiave: 'come', testo: 'Come vuoi essere tu, in quel momento? Scegli una qualità: pazienza, chiarezza, gentilezza, calma.', segnaposto: 'Voglio essere…' },
      { tipo: 'pausa', secondi: 20, testo: 'Immagina la scena, e immagina te stesso che rispondi con quella qualità.' },
    ],
  },
  {
    id: 'un-compito-per-oggi',
    titolo: 'Un compito per oggi',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['sconforto', 'sopraffatto'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'il lavoro proprio dell\'uomo, al risveglio (V, 1)' },
    perche: `Marco Aurelio racconta a se stesso la fatica di alzarsi la mattina. La sua risposta è ricordare che ognuno ha un compito suo, e che è quello a dare senso alla giornata. Quando ci si sente senza forze, un compito piccolo e chiaro vale più di un buon proposito grande.`,
    studio: 'tre-discipline',
    voci: {
      epitteto: {
        apertura: 'Non hai forze? Allora non chiederti tutto. Chiediti una cosa sola: qual è il tuo compito adesso?',
        chiusura: 'Un compito fatto bene vale più di cento propositi.',
      },
      seneca: {
        apertura: 'Ci sono giorni pesanti, e va bene. Cerchiamo insieme un piccolo gesto da compiere.',
        chiusura: 'Fare una cosa piccola è già rimettersi in cammino.',
      },
      marco: {
        apertura: 'Ti pesa alzarti? Ricordati a che cosa servi, e comincia da lì.',
        chiusura: 'Hai scelto il tuo compito. Il resto verrà a poco a poco.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Quando ci si sente senza forze, tutto sembra troppo grande. Gli stoici rispondevano con una domanda semplice: qual è il mio compito?' },
      { tipo: 'scrivi', chiave: 'compito', testo: 'Che cosa devi, o vuoi, fare oggi che davvero conta? Scegline una sola, anche piccola.', segnaposto: 'Oggi il mio compito è…' },
      { tipo: 'scrivi', chiave: 'primo', testo: 'Qual è il primo gesto, così piccolo che potresti farlo in due minuti?', segnaposto: 'Comincio da…' },
      { tipo: 'testo', testo: 'Ricordati che non devi averne voglia per cominciare. La voglia, di solito, arriva dopo il primo gesto.' },
      { tipo: 'pausa', secondi: 15, testo: 'Respira, e pensa a te stesso mentre fai quel primo gesto.' },
    ],
  },
  {
    id: 'il-rifugio-dentro',
    titolo: 'Il rifugio dentro',
    disciplina: 'presenza',
    famiglia: 'meditazioni',
    stati: ['ansia', 'sopraffatto', 'rabbia', 'notte'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'il ritirarsi in se stessi (IV, 3)' },
    perche: `Marco Aurelio scrive che molti cercano un rifugio in campagna o al mare, ma è sempre possibile ritirarsi in se stessi. Nel proprio animo ci si può ritirare con più tranquillità che altrove, a patto di avere a portata di mano poche idee semplici. È un luogo che ti accompagna ovunque.`,
    studio: 'come-usare',
    voci: {
      epitteto: {
        apertura: 'Il rifugio non è un posto. Sei tu, quando ti ricordi ciò che conta.',
        chiusura: 'Puoi tornare qui in ogni momento. Nessuno può portartelo via.',
      },
      seneca: {
        apertura: 'Ritiriamoci un momento, tu ed io, dentro di te. Lì c\'è più quiete di quanto pensi.',
        chiusura: 'Questo rifugio è tuo. Rinnovalo ogni volta che ne hai bisogno.',
      },
      marco: {
        apertura: 'Rientra in te. È il luogo più tranquillo che esista, e sempre a disposizione.',
        chiusura: 'Ti sei concesso un rifugio. Torna quando vuoi.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Molti cercano un rifugio lontano: una casa al mare, un fine settimana. Marco Aurelio ricorda che c\'è un rifugio più vicino: dentro di te. Ora ci entri.' },
      { tipo: 'respiro', testo: 'Chiudi gli occhi, se vuoi. Sei in un luogo interiore dove nessuno può disturbarti.', dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'massima', testo: 'Che cosa ti basta ricordare, adesso, per stare più tranquillo? Una frase breve e semplice, per esempio «Posso solo fare la mia parte».', segnaposto: 'Mi ricordo che…' },
      { tipo: 'testo', testo: 'Questa frase è la tua massima: breve, semplice, a portata di mano. Gli stoici ne tenevano poche, per poterle ripetere anche nei momenti difficili.' },
      { tipo: 'pausa', secondi: 30, testo: 'Resta un momento in questo rifugio, con la tua frase.' },
      { tipo: 'testo', testo: 'Ora esci con calma. Il rifugio resta dov\'è: puoi tornarci ogni volta.' },
    ],
  },
  {
    id: 'chi-sbaglia-non-sa',
    titolo: 'Chi sbaglia non sa',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['rabbia'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'chi sbaglia per ignoranza del bene; siamo nati per collaborare (II, 1)' },
    perche: `Per gli stoici chi si comporta male lo fa perché ignora il vero bene, e non perché sia un mostro. Non è una scusa: è un modo di guardare che toglie forza alla rabbia. Marco Aurelio aggiunge che siamo nati per collaborare, come le mani o i piedi, e che agire gli uni contro gli altri va contro la nostra natura.`,
    studio: 'tre-discipline',
    voci: {
      epitteto: {
        apertura: 'Ti ha offeso? Chiediti: chi mi offende? Uno che vede male. Pensa a questo, e guarda cosa resta della rabbia.',
        chiusura: 'La rabbia dice di te più di quanto dica di lui. Ora scegli tu come rispondere.',
      },
      seneca: {
        apertura: 'Prima di rispondere fermiamoci un momento. Chi ti ha ferito forse ha frainteso, oppure ha visto peggio di te.',
        chiusura: 'Non serve perdonare subito. Basta non agire finché la rabbia è alta.',
      },
      marco: {
        apertura: 'Ricorda: siamo fatti per collaborare. Chi sbaglia va contro la sua natura, prima ancora che contro di te.',
        chiusura: 'Non hai dovuto giustificarlo. Hai solo guardato ciò che c\'era.',
      },
    },
    passi: [
      { tipo: 'respiro', testo: 'Prima di tutto, qualche respiro lento. La rabbia ragiona male.', dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'fatto', testo: 'Che cosa ha fatto, o detto, questa persona? Scrivi soltanto i fatti.', segnaposto: 'Ha fatto o detto…' },
      { tipo: 'testo', testo: 'Gli stoici ripetevano che chi si comporta male lo fa perché non vede il bene. Non lo giustifica: lo spiega. Chi agisce così non sa fare di meglio, in questo momento.' },
      { tipo: 'scrivi', chiave: 'perche', testo: 'Che cosa potrebbe sfuggire, o restare ignoto, a questa persona? Che paura o che bisogno c\'è dietro?', segnaposto: 'Forse non vede che…' },
      { tipo: 'testo', testo: 'Adesso puoi scegliere. La rabbia non è obbligatoria: puoi rispondere con chiarezza, con fermezza, oppure lasciar correre. Ma la scelta è tua, non di chi ti ha fatto arrabbiare.' },
    ],
  },
  {
    id: 'lodi-e-biasimi',
    titolo: 'Lodi e biasimi',
    disciplina: 'desiderio',
    famiglia: 'meditazioni',
    stati: ['colpa', 'ansia', 'sconforto'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'la fama e la memoria degli altri (IX, 30)' },
    perche: `Quanto ci pesa il giudizio degli altri? Marco Aurelio invita a pensare a quanti non ci conoscono, a quanti ci hanno già dimenticato e a chi oggi ci loda e domani ci criticherà. La fama e la memoria sono instabili, e quindi un terreno fragile su cui costruire il proprio valore.`,
    studio: 'paura-desiderio',
    voci: {
      epitteto: {
        apertura: 'Il giudizio degli altri non dipende da te. Vediamo quanto peso gli stai dando.',
        chiusura: 'Curati di ciò che dipende da te. Il resto lascialo agli altri.',
      },
      seneca: {
        apertura: 'Ci preoccupiamo più di ciò che pensano di noi che di ciò che siamo. Guardiamo la cosa con distanza.',
        chiusura: 'Ciò che sei tu lo decidi con le tue azioni. Le opinioni cambiano ogni giorno.',
      },
      marco: {
        apertura: 'Chi ti loda oggi domani ti critica. Chi ti critica oggi domani ti dimentica. Guarda questo.',
        chiusura: 'Il tuo valore non abita nella bocca degli altri.',
      },
    },
    passi: [
      { tipo: 'scrivi', chiave: 'pensiero', testo: 'Che cosa temi che gli altri pensino di te, in questo momento? Scrivilo con le parole più semplici.', segnaposto: 'Temo che pensino che…' },
      { tipo: 'testo', testo: 'Ora allarga lo sguardo. Pensa a quante persone, in questo momento, nemmeno sanno che esisti. E a quante, tra pochi anni, ricorderanno questo episodio.' },
      { tipo: 'testo', testo: 'Marco Aurelio scrive che chi ti loda oggi presto potrebbe criticarti, e che chi ti critica presto ti dimenticherà. Lodi e biasimi vanno e vengono: sono un terreno instabile.' },
      { tipo: 'scegli', chiave: 'agire', testo: 'C\'è qualcosa, in ciò che hai scritto, su cui puoi agire tu?', opzioni: [{ testo: 'Sì, posso fare qualcosa', vai: 'si' }, { testo: 'No, dipende dagli altri', vai: 'no' }] },
      { id: 'si', tipo: 'scrivi', chiave: 'gesto', testo: 'Che cosa puoi fare, concretamente? Una parola chiarificatrice, una scusa, un gesto.', segnaposto: 'Posso…', poi: 'fine' },
      { id: 'no', tipo: 'testo', testo: 'Allora questo peso non è tuo. Puoi restare sereno e continuare a fare bene ciò che fai: è l\'unica cosa che ti spetta.' },
    ],
  },
  {
    id: 'un-testimone-esemplare',
    titolo: 'Un testimone esemplare',
    disciplina: 'azione',
    famiglia: 'azione',
    stati: ['colpa', 'rabbia', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'scegliere una persona di valore e agire come se ci guardasse (lettera 11)' },
    perche: `Seneca consiglia di scegliere una persona che stimiamo e di vivere come se ci guardasse. Lo riprende da Epicuro, e aggiunge che molti errori si evitano se c'è un testimone. La persona scelta fa da «custode»: non ci giudica, ci ricorda chi vogliamo essere. Se la persona scelta è troppo rigida, Seneca suggerisce di sceglierne una più mite.`,
    studio: 'tre-discipline',
    voci: {
      epitteto: {
        apertura: 'Scegli chi vorresti diventare. Poi agisci come se ti guardasse.',
        chiusura: 'Ogni azione è un voto per la persona che stai diventando.',
      },
      seneca: {
        apertura: 'Ti do un consiglio che serve anche a me: scegli una persona che stimi e agisci come se ti vedesse.',
        chiusura: 'Non serve essere perfetti, serve avere un esempio davanti agli occhi.',
      },
      marco: {
        apertura: 'Chi vorresti avere accanto, in questo momento? Pensa a come agirebbe.',
        chiusura: 'Puoi richiamarla ogni volta che dubiti.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Seneca consiglia di scegliere una persona che stimi, viva o del passato, e di agire come se ci vedesse. Non per paura di essere giudicati: per ricordarci chi vogliamo essere.' },
      { tipo: 'scrivi', chiave: 'modello', testo: 'Quale persona sceglieresti? Qualcuno che ammiri per il carattere: un familiare, un maestro, un personaggio storico. Se ti sembra troppo severa, scegline una più mite.', segnaposto: 'Scelgo…' },
      { tipo: 'scrivi', chiave: 'qualita', testo: 'Che cosa ammiri di questa persona? Una qualità, un modo di reagire.', segnaposto: 'Ammiro il suo modo di…' },
      { tipo: 'scrivi', chiave: 'farebbe', testo: 'Nella situazione che stai vivendo, che cosa farebbe, o direbbe, questa persona?', segnaposto: 'Farebbe…' },
      { tipo: 'testo', testo: 'Ora sai come agire. Non devi eseguirlo alla perfezione: devi solo avvicinarti. Ogni volta che dubiti, ripensa a questa persona.' },
    ],
  },
  {
    id: 'un-momento-alla-volta',
    titolo: 'Un momento alla volta',
    disciplina: 'presenza',
    famiglia: 'attenzione',
    stati: ['sopraffatto', 'sconforto', 'ansia', 'notte'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'le difficoltà sopportabili se guardate nel presente (VIII, 36)' },
    perche: `Il dolore e la fatica sembrano insopportabili quando li guardiamo tutti insieme, nel passato e nel futuro. Ma il presente, il momento che stiamo vivendo adesso, è sempre piccolo, sempre affrontabile. Per gli stoici, portare l'attenzione qui toglie forza alle passioni che vengono da ciò che è stato o da ciò che sarà.`,
    studio: 'il-tempo-la-morte',
    voci: {
      epitteto: {
        apertura: 'Non affrontare tutto insieme. Affronta solo questo momento, poi il successivo.',
        chiusura: 'Un momento alla volta: così si attraversa qualunque giornata.',
      },
      seneca: {
        apertura: 'Soffriamo più con l\'immaginazione che con la realtà. Restiamo un momento in ciò che c\'è, adesso.',
        chiusura: 'Il momento che stai vivendo è sempre sopportabile. Quello che temi ancora non esiste.',
      },
      marco: {
        apertura: 'Il passato non ti appartiene più, il futuro ancora no. Ti resta questo momento, e basta.',
        chiusura: 'Il presente è piccolo, e proprio per questo puoi reggerlo.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Quando siamo sopraffatti, ci pesa tutto insieme: ciò che è stato, ciò che sarà, ciò che dobbiamo fare. Ma nessuno vive tutto insieme. Si vive un momento alla volta.' },
      { tipo: 'respiro', testo: 'Un respiro, poi un altro. Solo questo momento.', dentro: 4, fuori: 6, cicli: 3 },
      { tipo: 'scrivi', chiave: 'adesso', testo: 'Adesso, in questo preciso momento: c\'è qualcosa che ti manca, o che non riesci a sopportare? Scrivi com\'è davvero, senza pensare a dopo.', segnaposto: 'In questo momento…' },
      { tipo: 'testo', testo: 'Spesso la risposta è: no, adesso sto bene abbastanza. Ciò che pesa è ciò che immaginiamo. Il momento presente è sempre piccolo, e per questo affrontabile.' },
      { tipo: 'testo', testo: 'Fai una cosa sola, la più vicina. Poi la successiva. Ogni momento ha il suo compito.' },
    ],
  },
  {
    id: 'cio-che-ho-ricevuto',
    titolo: 'Ciò che ho ricevuto',
    disciplina: 'giudizio',
    famiglia: 'pensiero',
    stati: ['sconforto', 'colpa', 'notte', 'non-so'],
    minuti: 3,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'il libro I: che cosa ho imparato da ciascuno' },
    perche: `Marco Aurelio apre i suoi appunti ringraziando, una persona alla volta, per ciò che ha imparato da ciascuna: dal nonno il buon carattere, da altri la pazienza, la semplicità, la giustizia. Ricordare ciò che abbiamo ricevuto sposta l'attenzione da ciò che manca a ciò che c'è, e ci ricorda che non siamo soli.`,
    studio: 'tre-maestri',
    voci: {
      epitteto: {
        apertura: 'Ciò che hai perso è tornato a chi te l\'aveva dato. Guarda invece ciò che ti resta.',
        chiusura: 'Ciò che hai ricevuto è tuo, da usare ora.',
      },
      seneca: {
        apertura: 'Facciamo un conto diverso: guardiamo ciò che hai ricevuto e mai contato, invece di ciò che ti manca.',
        chiusura: 'Ricordare chi ci ha dato qualcosa è già una forma di ricchezza.',
      },
      marco: {
        apertura: 'Riprendi il mio modo di fare: «Da questa persona, questo». Uno alla volta.',
        chiusura: 'Non sei partito da zero. Porti con te chi ti ha dato qualcosa.',
      },
    },
    passi: [
      { tipo: 'testo', testo: 'Marco Aurelio comincia il suo diario con un elenco: «Da mio nonno, il buon carattere. Da mia madre, la semplicità…». Ringrazia ciascuno per ciò che gli ha lasciato. Facciamo lo stesso.' },
      { tipo: 'scrivi', chiave: 'prima', testo: 'Pensa a una persona che ti ha dato qualcosa, anche piccolo. Che cosa hai imparato da lei?', segnaposto: 'Da… ho imparato…' },
      { tipo: 'scrivi', chiave: 'seconda', testo: 'Un\'altra persona. Che cosa ti ha lasciato?', segnaposto: 'Da… ho ricevuto…' },
      { tipo: 'scrivi', chiave: 'terza', testo: 'Ancora una. Può essere un maestro, un amico, un autore, uno sconosciuto.', segnaposto: 'Da… ho ricevuto…' },
      { tipo: 'pausa', secondi: 20, testo: 'Lascia che ognuna di queste persone ti stia accanto, per un momento.' },
      { tipo: 'testo', testo: 'Ciò che hai ricevuto è ancora con te. Puoi usarlo oggi, e passarlo a qualcun altro.' },
    ],
  },
];
