// Pagine informative, contatti e messaggi di posta già pronti. Nel testo **così** è grassetto e *così* è corsivo.

export const VERSIONE = '1.6 · settembre 2026';

export const CONTATTI = {
  sito: 'https://www.formebrevi.it',
  app: 'https://stoicismo.formebrevi.it',
  dialogo: 'https://dialogo.formebrevi.it',
  kalmly: 'https://kalmly.app',
  paypal: 'https://www.paypal.me/formebrevi',
  iscrizione: 'https://www.formebrevi.it/iscriviti.html',
  corsi: 'https://www.formebrevi.it/corsi.html',
  risorse: 'https://www.formebrevi.it/risorse.html',
  email: 'formebrevi@gmail.com',
};

export const mailto = (oggetto, corpo = '') =>
  'mailto:' + CONTATTI.email + '?subject=' + encodeURIComponent(oggetto) + (corpo ? '&body=' + encodeURIComponent(corpo) : '');

export const MAIL = {
  problema: mailto('Stoicismo quotidiano: segnalazione di un problema', 'Che cosa è successo?\n\nChe telefono e che browser usi?\n'),
  suggerimento: mailto('Stoicismo quotidiano: suggerimento', 'Il mio suggerimento (un esercizio, un pensiero, una pagina):\n'),
  scrivi: mailto('Messaggio da Stoicismo quotidiano'),
};

export const PAGINE_INFO = [
  {
    id: 'come-funziona',
    gruppo: 'app',
    titolo: 'Come funziona',
    sotto: 'La guida completa: esercizi, meditazioni, voci, studio e privacy.',
    blocchi: [
      { t: 'h', x: 'In breve' },
      { t: 'p', x: `Stoicismo quotidiano è la app gratuita di Formebrevi APS. Ti offre esercizi guidati per i momenti difficili, meditazioni brevi e pagine per capire lo stoicismo. Funziona anche senza connessione e non ti chiede di registrarti.` },
      { t: 'h', x: 'Le cinque zone' },
      { t: 'lista', x: [
        `**Ora:** il pulsante «Ho bisogno di un momento» ti porta, in pochi tocchi, a un esercizio adatto.`,
        `**Esercizi:** il catalogo di tutti gli esercizi e le meditazioni a tempo, con ricerca e filtri.`,
        `**Quaderno:** un posto privato per scrivere: la mattina, la sera, una lettera a te stesso o ciò che vuoi.`,
        `**Studio:** le pagine che spiegano lo stoicismo e da dove vengono gli esercizi.`,
        `**Info:** questa guida, le fonti, i crediti e come sostenere Formebrevi.`,
      ] },
      { t: 'h', x: 'Ho bisogno di un momento' },
      { t: 'passi', x: [
        { titolo: 'Che cosa senti?', testo: `Scegli il sentimento che descrive meglio il momento: ansia, paura, rabbia, sconforto, sopraffatto, colpa, notte agitata, oppure «non lo so».` },
        { titolo: 'Dove ti sei perso?', testo: `Nel giudizio (ciò che pensi), nel desiderio o nella paura (ciò che vuoi o temi), oppure nell'azione (ciò che devi fare). Se non lo sai, due domande ti aiutano a capirlo.` },
        { titolo: 'Quanto tempo hai?', testo: `Uno, tre o dieci minuti.` },
        { titolo: 'Scegli un esercizio.', testo: `La app te ne propone tre adatti. Puoi sceglierne uno, oppure toccare «Sorprendimi».` },
        { titolo: 'Fai l\'esercizio.', testo: `Un passo per schermata. Alla fine trovi un pensiero da portare con te.` },
      ] },
      { t: 'h', x: 'Come funziona un esercizio' },
      { t: 'p', x: `Ogni esercizio è una sequenza di passi. Puoi andare avanti con «Avanti» e tornare indietro con «Indietro». I passi sono di sei tipi:` },
      { t: 'lista', x: [
        `**Testo:** leggi e vai avanti.`,
        `**Respiro:** un cerchio che si allarga e si restringe a ritmo lento. Ti basta seguirlo.`,
        `**Pausa:** qualche secondo di silenzio, con un suono dolce alla fine.`,
        `**Scrivi:** un piccolo campo dove scrivere una frase. Ciò che scrivi resta sul telefono e, alla fine, puoi salvarlo nel quaderno.`,
        `**Scegli:** due o tre risposte. Ognuna può portare a un passo diverso.`,
        `**Colonne:** due elenchi, per esempio «dipende da me» e «non dipende da me». Aggiungi le cose e toccale per spostarle.`,
      ] },
      { t: 'p', x: `Respiri, pause e scrittura non sono riempitivi: sono le parti che lavorano. Sotto ogni passo trovi un riquadro «Perché questo passo?», e sotto ogni richiesta di scrittura un esempio e un aiuto per quando ci si blocca.` },
      { t: 'azione', x: 'Perché respiri, pause e scrittura', az: 'info', id: 'perche-respiri-pause-scrittura', stile: 'chiaro' },
      { t: 'h', x: 'Chi ti accompagna: le tre voci' },
      { t: 'p', x: `Gli stessi esercizi hanno tre toni: **Epitteto** (secco e diretto), **Seneca** (caldo, come una lettera) e **Marco Aurelio** (interiore, come un quaderno). La voce cambia le frasi di apertura e di chiusura e i pensieri, non i passi. Puoi cambiarla quando vuoi, e la app ricorda la tua scelta.` },
      { t: 'h', x: 'Un pensiero' },
      { t: 'p', x: `Nella zona Ora, «Un pensiero» ti mostra una breve frase, scritta con parole nostre, che riprende un'idea di Epitteto, Seneca o Marco Aurelio, nella voce che hai scelto.` },
      { t: 'h', x: 'Le meditazioni a tempo' },
      { t: 'p', x: `Nella zona Esercizi trovi meditazioni da cinque a dieci minuti. Un testo compare a intervalli, con una campana dolce all'inizio e alla fine. Lo schermo resta acceso, se il telefono lo permette. Puoi fermarti in qualsiasi momento. Nella «Vista dall'alto» compare anche un disegno che sale dalla stanza fino allo spazio e poi torna giù.` },
      { t: 'h', x: 'Il quaderno' },
      { t: 'p', x: `Il quaderno ha quattro modelli: **Mattina** (prepararsi alla giornata), **Sera** (esaminare la giornata in tre domande), **Lettera** (scrivere a te stesso come a un amico) e **Pagina libera**. Nei primi tre puoi cambiare la domanda con un'altra. Le pagine si salvano da sole, le puoi rileggere, modificare, eliminare e copiare. Alla fine di un esercizio puoi anche salvare ciò che hai scritto.` },
      { t: 'p', x: `Il quaderno resta soltanto su questo telefono. Se cancelli i dati del browser o disinstalli la app, le pagine si perdono: usa «Copia tutto» per conservarne una copia.` },
      { t: 'h', x: 'Il suono' },
      { t: 'p', x: `I suoni (la campana, il segnale della pausa) sono generati dalla app e usano l'audio del telefono. Se il volume è spento, gli esercizi funzionano lo stesso.` },
      { t: 'h', x: 'Privacy' },
      { t: 'p', x: `La app è senza account, senza pubblicità e senza raccolta di dati: nessun dato lascia il telefono. Sul telefono restano soltanto la voce che hai scelto, l'informazione di aver letto la nota di apertura e, se lo usi, le pagine del quaderno. Ciò che scrivi negli esercizi si salva solo se scegli «Salva nel quaderno».` },
      { t: 'h', x: 'Installarla sul telefono' },
      { t: 'lista', x: [
        `**Android (Chrome):** tocca i tre puntini in alto a destra, poi «Installa app» o «Aggiungi a schermata Home».`,
        `**iPhone (Safari):** tocca il tasto Condividi, poi «Aggiungi alla schermata Home».`,
        `Dopo l'installazione trovi l'icona con le altre app e si apre a schermo intero.`,
      ] },
      { t: 'h', x: 'Senza connessione' },
      { t: 'p', x: `Apri Stoicismo quotidiano una volta con la connessione: da quel momento tutto viene salvato sul telefono e la app si apre anche senza rete. Quando torna la connessione, si aggiorna da sola.` },
      { t: 'h', x: 'Domande frequenti' },
      { t: 'lista', x: [
        `**Devo praticare ogni giorno?** No. La app non conta i giorni: la apri quando ti serve.`,
        `**Devo credere allo stoicismo?** No. Gli esercizi si provano: se aiutano, li ripeti.`,
        `**Ho scritto qualcosa in un esercizio: dove va?** Resta sul telefono. Se a fine esercizio scegli «Salva nel quaderno», la trovi nel quaderno. Altrimenti sparisce quando esci.`,
        `**Posso cambiare voce a metà?** Sì, dalla zona Ora. Vale per gli esercizi successivi.`,
        `**È gratuita?** Sì. Se ti è utile, puoi sostenere Formebrevi dalla pagina «Sostieni Formebrevi».`,
      ] },
      { t: 'azione', x: 'Serve aiuto? Vai a «Supporto»', az: 'info', id: 'supporto' },
    ],
  },
  {
    id: 'perche-respiri-pause-scrittura',
    gruppo: 'app',
    titolo: 'Perché respiri, pause e scrittura',
    sotto: 'Le tre cose che tornano in ogni esercizio, e a che cosa servono.',
    blocchi: [
      { t: 'p', x: `In quasi ogni esercizio trovi tre tipi di passo che sembrano semplici: un respiro lento, una pausa di silenzio, un momento di scrittura. Non sono riempitivi: sono la parte che lavora. Qui spieghiamo perché ci sono, dicendo anche che cosa sappiamo e che cosa no.` },
      { t: 'h', x: 'Il respiro lento' },
      { t: 'p', x: `Quando siamo agitati il respiro diventa corto e alto, e il corpo si prepara ad agire: cuore veloce, muscoli tesi. Rallentare, con un'uscita più lunga dell'entrata, manda al corpo il segnale opposto. Il cerchio della app segue questo ritmo: di solito quattro secondi dentro e sei fuori, e sette fuori negli esercizi per la notte.` },
      { t: 'p', x: `Diversi studi sulla respirazione lenta hanno trovato una riduzione di ansia e di tensione, spesso modesta, e la qualità delle prove varia. Il respiro non cura niente da solo. Ha uno scopo più semplice: abbassa il volume quanto basta per poter pensare. Nell'antichità non era un esercizio stoico, a parte l'attenzione che richiede: per questo lo consideriamo un sostegno di oggi.` },
      { t: 'h', x: 'La pausa' },
      { t: 'p', x: `La pausa è la parte più antica. Gli stoici parlavano di uno spazio: tra ciò che appare e il sì che gli diamo, come dice Epitteto, e tra la collera e l'azione, come dice Seneca quando consiglia di rimandare la risposta. Se reagisci subito, risponde l'abitudine. Se aspetti anche solo trenta secondi, puoi rispondere tu.` },
      { t: 'p', x: `Nella app le pause hanno un conto alla rovescia, da quindici secondi a un minuto. Servono a restare con ciò che senti senza scappare: la paura, l'irritazione e la fretta salgono, arrivano a un punto e poi calano. Puoi sempre passare avanti se non ti serve.` },
      { t: 'h', x: 'La scrittura' },
      { t: 'p', x: `Scrivere mette il pensiero fuori dalla testa, dove si può guardare. Ha tre effetti pratici:` },
      { t: 'lista', x: [
        `**Precisione:** una frase vaga diventa una frase chiara. Ciò che resta confuso in testa, sulla pagina si vede.`,
        `**Distanza:** un pensiero scritto è un pensiero, e non la realtà. Si può rileggere, discutere, correggere.`,
        `**Decisione:** un piano scritto, con un orario, si realizza più facilmente di un buon proposito.`,
      ] },
      { t: 'p', x: `Gli antichi la usavano così. Marco Aurelio scrisse appunti a se stesso, Seneca lettere a un amico, e Hadot parla della scrittura come di un vero esercizio spirituale. Oggi gli studi sulla scrittura riflessiva, soprattutto dopo esperienze difficili, indicano benefici in molti casi ma non in tutti. Per questo la app ti chiede pochi minuti e poche righe, non pagine intere.` },
      { t: 'p', x: `Ciò che scrivi resta sul tuo telefono. Alla fine puoi salvarlo nel quaderno, oppure lasciarlo cadere.` },
      { t: 'h', x: 'Se un passo non fa per te' },
      { t: 'p', x: `Ogni passo si può saltare con «Avanti». Nessun esercizio è un test. Chi è molto agitato può fare solo il respiro, chi ha la testa piena può fare solo la scrittura. Sotto ogni passo trovi un riquadro «Perché questo passo?», e sotto ogni richiesta di scrittura un esempio e un aiuto per quando ci si blocca.` },
      { t: 'nota', x: `Questi esercizi sono una riflessione, non una cura. Se il malessere è forte o dura da tempo, parlane con il tuo medico o con un professionista.` },
      { t: 'azione', x: 'Vai a «Come funziona»', az: 'info', id: 'come-funziona', stile: 'chiaro' },
      { t: 'azione', x: 'Gli esercizi spirituali', az: 'studio', id: 'esercizi-spirituali', stile: 'chiaro' },
      { t: 'azione', x: 'La filosofia come cura dell\'anima', az: 'studio', id: 'la-cura-dell-anima', stile: 'chiaro' },
    ],
  },
  {
    id: 'che-cose',
    gruppo: 'app',
    titolo: "Che cos'è Stoicismo quotidiano",
    sotto: 'Una guida di riflessione ispirata allo stoicismo.',
    blocchi: [
      { t: 'p', x: `Stoicismo quotidiano è una **guida di riflessione ispirata allo stoicismo**. Propone pratiche di pensiero e di attenzione, prese dai testi degli stoici antichi. Non sostituisce il parere del medico né un percorso di cura o di sostegno psicologico: se il malessere è forte o dura da tempo, parlane con il tuo medico o con un professionista.` },
      { t: 'h', x: 'Su che cosa si basa' },
      { t: 'lista', x: [
        `Gli scritti di **Epitteto**, **Seneca** e **Marco Aurelio**.`,
        `I frammenti degli **stoici antichi**, raccolti dagli studiosi.`,
      ] },
      { t: 'h', x: 'Come sono scritti i testi' },
      { t: 'p', x: `I testi della app sono stati scritti per questa app. Riprendono le idee degli autori antichi con parole nostre, senza citazioni copiate dalle traduzioni. Ogni esercizio indica la sua fonte, cioè l'autore e l'opera da cui viene l'idea. Trovi l'elenco nella pagina Fonti.` },
      { t: 'h', x: 'Chi la realizza' },
      { t: 'p', x: `Stoicismo quotidiano è un progetto di Formebrevi APS, associazione di promozione sociale di Caltanissetta. La app è gratuita e senza pubblicità.` },
    ],
  },
  {
    id: 'fonti',
    gruppo: 'app',
    titolo: 'Fonti e bibliografia',
    sotto: 'I libri da cui vengono le idee, con le edizioni.',
    blocchi: [
      { t: 'p', x: `Ecco i libri su cui si basa la app. Sono anche un punto di partenza per chi vuole leggere gli stoici.` },
      { t: 'lista', x: [
        `**Epitteto,** *Tutte le opere*, testo greco a fronte, a cura di Giovanni Reale. Contiene il *Manuale* e i *Discorsi*.`,
        `**Marco Aurelio,** *Ricordi* (noto anche come *A se stesso*), nuova traduzione di Franco Scalenghe, con note e commento.`,
        `**Seneca,** *Tutte le opere*, cura e traduzione di Mario Scaffidi Abbate (Newton Compton). Comprende le *Lettere a Lucilio* e i dialoghi (*Sull'ira*, *Sulla brevità della vita*, *Sulla tranquillità dell'animo*, *Sulla provvidenza*).`,
        `**Giovanni Reale,** *La filosofia di Seneca come terapia dei mali dell'anima*.`,
        `**Pierre Hadot,** *Esercizi spirituali e filosofia antica*, a cura di Arnold I. Davidson, traduzione di Anna Maria Marietti (Einaudi, Piccola Biblioteca Einaudi).`,
        `**Andrea E. Cavanna e altri,** *The Western origins of mindfulness therapy in ancient Rome*, Neurological Sciences, 2023.`,
        `**Georgina King,** *Modern Stoicism and mental health: a randomised controlled trial*, tesi di dottorato, Royal Holloway, University of London, 2025.`,
        `**Hans von Arnim,** *Stoici antichi. Tutti i frammenti*, a cura di Roberto Radice.`,
        `**Max Pohlenz,** *La Stoa. Storia di un movimento spirituale*, a cura di Giovanni Reale.`,
        `**Epitteto,** *Le diatribe e i frammenti*.`,
        `**Epitteto,** *Il manuale di Epitteto (Enchiridion)*, traduzione di Giacomo Leopardi (Liber Liber).`,
      ] },
      { t: 'nota', x: `Le pagine di Studio spiegano come leggerli e da dove cominciare.` },
      { t: 'azione', x: 'Come leggere gli stoici', az: 'studio', id: 'come-leggere' },
    ],
  },
  {
    id: 'sostieni',
    gruppo: 'formebrevi',
    titolo: 'Sostieni Formebrevi',
    sotto: 'La app è gratuita: se ti è utile, aiutaci a continuare.',
    blocchi: [
      { t: 'p', x: `La app è gratuita, senza pubblicità e senza account. È realizzata dai volontari di Formebrevi APS. Se ti è stata utile, puoi aiutare l'associazione a continuare.` },
      { t: 'h', x: 'Dona con PayPal' },
      { t: 'p', x: 'Una donazione libera, di qualsiasi importo.' },
      { t: 'link', x: 'Dona con PayPal', href: 'paypal', stile: 'primario' },
      { t: 'h', x: 'Associati a Formebrevi' },
      { t: 'p', x: `Diventare socio costa 10 € l'anno. Compili la domanda di ammissione, la esamina il Consiglio Direttivo e poi versi la quota. I soci partecipano gratuitamente alle sessioni di dialogo filosofico online.` },
      { t: 'link', x: 'Compila la domanda di ammissione', href: 'iscrizione', stile: 'chiaro' },
      { t: 'h', x: 'Fai conoscere Stoicismo quotidiano' },
      { t: 'p', x: `Il modo più semplice di aiutarci: parlane a una persona che potrebbe averne bisogno.` },
      { t: 'azione', x: 'Condividi Stoicismo quotidiano', az: 'condividi', stile: 'chiaro' },
      { t: 'h', x: 'A che cosa serve il tuo contributo' },
      { t: 'p', x: `Il contributo aiuta l'associazione a mantenere gratuiti le app e i materiali, come Stoicismo quotidiano, Dialogo, Kalmly e i kit didattici. Grazie.` },
    ],
  },
  {
    id: 'supporto',
    gruppo: 'formebrevi',
    titolo: 'Supporto',
    sotto: 'Segnala un problema, suggerisci un esercizio, scrivici.',
    blocchi: [
      { t: 'h', x: 'Serve aiuto con la app?' },
      { t: 'p', x: `Scrivici: siamo un'associazione di volontari e rispondiamo di solito entro 3–5 giorni lavorativi.` },
      { t: 'link', x: 'Segnala un problema', href: 'mail:problema', stile: 'primario' },
      { t: 'link', x: 'Suggerisci un esercizio o un pensiero', href: 'mail:suggerimento', stile: 'chiaro' },
      { t: 'link', x: 'Scrivi a Formebrevi', href: 'mail:scrivi', stile: 'chiaro' },
      { t: 'h', x: 'Prima di scrivere' },
      { t: 'lista', x: [
        `Guarda la pagina «Come funziona»: forse la risposta c'è già.`,
        `Se qualcosa si vede male, aggiorna la pagina con il tasto di ricarica del browser.`,
        `Dicci che telefono e che browser usi: ci aiuta a capire il problema.`,
      ] },
      { t: 'azione', x: 'Vai a «Come funziona»', az: 'info', id: 'come-funziona', stile: 'chiaro' },
    ],
  },
  {
    id: 'crediti',
    gruppo: 'formebrevi',
    titolo: 'Crediti e privacy',
    sotto: 'Autori, licenza, privacy e versione.',
    blocchi: [
      { t: 'h', x: 'Autori' },
      { t: 'p', x: 'La app è realizzata da Formebrevi APS.' },
      { t: 'h', x: 'Contenuti e licenza' },
      { t: 'p', x: `I contenuti sono distribuiti con licenza Creative Commons BY-NC-SA 4.0: puoi usarli e condividerli per scopi non commerciali, citando la fonte. Le idee sono degli autori antichi e degli studiosi indicati nella pagina Fonti; i testi sono stati scritti per questa app.` },
      { t: 'h', x: 'Privacy' },
      { t: 'p', x: `La app è senza account, senza pubblicità e senza raccolta di dati: nessun dato lascia il telefono. Sul telefono restano soltanto la voce scelta, la nota di apertura già letta e, se lo usi, il quaderno.` },
      { t: 'h', x: 'Altre app di Formebrevi' },
      { t: 'link', x: 'Dialogo, per condurre un dialogo filosofico', href: 'dialogo', stile: 'chiaro' },
      { t: 'link', x: "Kalmly, l'app per l'ADHD", href: 'kalmly', stile: 'chiaro' },
      { t: 'h', x: 'Versione' },
      { t: 'p', x: `Stoicismo quotidiano, versione ${VERSIONE}.` },
    ],
  },
];
