// Pagine informative, contatti e messaggi di posta già pronti. Nel testo **così** è grassetto e *così* è corsivo.

export const VERSIONE = '2.0 · settembre 2026';

export const CONTATTI = {
  sito: 'https://www.formebrevi.it',
  app: 'https://stoicismo.formebrevi.it',
  dialogo: 'https://dialogo.formebrevi.it',
  kalmly: 'https://kalmly.app',
  paypal: 'https://www.paypal.me/formebrevi',
  iscrizione: 'https://www.formebrevi.it/iscriviti.html',
  corsi: 'https://www.formebrevi.it/corsi.html',
  risorse: 'https://www.formebrevi.it/risorse.html',
  email: 'formebrevi@gmail.com',
};

export const mailto = (oggetto, corpo = '') =>
  'mailto:' + CONTATTI.email + '?subject=' + encodeURIComponent(oggetto) + (corpo ? '&body=' + encodeURIComponent(corpo) : '');

export const MAIL = {
  problema: mailto('Stoicismo quotidiano: segnalazione di un problema', 'Che cosa è successo?\n\nChe telefono e che browser usi?\n'),
  suggerimento: mailto('Stoicismo quotidiano: suggerimento', 'Il mio suggerimento (una lezione, una pagina, una correzione):\n'),
  scrivi: mailto('Messaggio da Stoicismo quotidiano'),
};

export const PAGINE_INFO = [
  {
    id: 'come-funziona',
    gruppo: 'app',
    titolo: 'Come funziona',
    sotto: 'La guida completa: corso, quaderno, biblioteca e privacy.',
    blocchi: [
      { t: 'h', x: 'In breve' },
      { t: 'p', x: `Stoicismo quotidiano è la app gratuita di Formebrevi APS. È un corso per imparare a essere stoici, con i riferimenti ai testi di Epitteto, Seneca e Marco Aurelio. Funziona anche senza connessione e non ti chiede di registrarti.` },
      { t: 'h', x: 'Le quattro zone' },
      { t: 'lista', x: [
        `**Corso:** otto moduli di lezioni, dalle fondamenta alla vita stoica di ogni giorno.`,
        `**Quaderno:** un posto privato per scrivere: la mattina, la sera, una lettera a te stesso, le domande delle lezioni o ciò che vuoi.`,
        `**Biblioteca:** le pagine per approfondire: le idee, le passioni e le virtù, gli autori, la storia della scuola, il glossario.`,
        `**Info:** questa guida, le fonti, i crediti e come sostenere Formebrevi.`,
      ] },
      { t: 'h', x: 'Il corso' },
      { t: 'p', x: `Il corso segue l'ordine in cui Epitteto insegnava: prima le fondamenta e le impressioni, poi il desiderio e la paura, poi l'azione con gli altri, poi il giudizio; infine il tempo, il nostro posto nella natura e le pratiche di ogni giorno. La prima schermata ti propone sempre la lezione da cui continuare, ma nessuna lezione è bloccata: puoi aprire quella che vuoi.` },
      { t: 'p', x: `Ogni lezione ha le stesse parti:` },
      { t: 'lista', x: [
        `**L'idea,** spiegata in parole semplici, con esempi della vita di tutti i giorni.`,
        `**Cosa dicono i testi:** i passi precisi in cui trovi l'idea, con che cosa c'è in ciascuno. Ogni passo è stato controllato sui libri; le parole della lezione sono nostre.`,
        `**Da ricordare:** una frase sola, da portare con te.`,
        `**Nella vita di tutti i giorni:** come gli stoici mettevano in pratica l'idea, raccontato a partire dai loro testi.`,
        `**Una domanda per il Quaderno** e **Per approfondire:** le pagine della Biblioteca collegate.`,
      ] },
      { t: 'p', x: `Quando hai finito una lezione puoi segnarla con «Ho finito questa lezione». Il segno resta sul telefono e si può togliere. Non ci sono punteggi né giorni di fila da mantenere: puoi andare al tuo ritmo.` },
      { t: 'h', x: 'Il quaderno' },
      { t: 'p', x: `Il quaderno ha quattro modelli: **Mattina** (prepararsi alla giornata), **Sera** (esaminare la giornata in tre domande), **Lettera** (scrivere a te stesso come a un amico) e **Pagina libera**. Nei primi tre puoi cambiare la domanda con un'altra. Le pagine si salvano da sole, le puoi rileggere, modificare, eliminare e copiare. Da ogni lezione puoi aprire una pagina con la sua domanda.` },
      { t: 'p', x: `Scrivere per sé è una pratica degli stoici: Epitteto chiedeva ai suoi allievi di scrivere ogni giorno i pensieri su cui esercitarsi, Seneca alternava lettura e scrittura, Marco Aurelio ci ha lasciato il suo quaderno.` },
      { t: 'p', x: `Il quaderno resta soltanto su questo telefono. Se cancelli i dati del browser o disinstalli la app, le pagine si perdono: usa «Copia tutto» per conservarne una copia.` },
      { t: 'h', x: 'Privacy' },
      { t: 'p', x: `La app è senza account, senza pubblicità e senza raccolta di dati: nessun dato lascia il telefono. Sul telefono restano soltanto l'informazione di aver letto la nota di apertura, le lezioni che hai segnato come fatte e, se lo usi, le pagine del quaderno.` },
      { t: 'h', x: 'Installarla sul telefono' },
      { t: 'lista', x: [
        `**Android (Chrome):** tocca i tre puntini in alto a destra, poi «Installa app» o «Aggiungi a schermata Home».`,
        `**iPhone (Safari):** tocca il tasto Condividi, poi «Aggiungi alla schermata Home».`,
        `Dopo l'installazione trovi l'icona con le altre app e si apre a schermo intero.`,
      ] },
      { t: 'h', x: 'Senza connessione' },
      { t: 'p', x: `Apri Stoicismo quotidiano una volta con la connessione: da quel momento tutto viene salvato sul telefono e la app si apre anche senza rete. Quando torna la connessione, si aggiorna da sola.` },
      { t: 'h', x: 'Domande frequenti' },
      { t: 'lista', x: [
        `**Devo fare una lezione al giorno?** No. La app non conta i giorni: vai al tuo ritmo, anche una lezione alla settimana.`,
        `**Devo credere allo stoicismo?** No. Le lezioni spiegano che cosa pensavano gli stoici e dove leggerlo: sta a te vedere che cosa ti è utile.`,
        `**Le parole delle lezioni sono degli autori antichi?** No: le idee sono loro, le parole sono nostre. Nella sezione «Cosa dicono i testi» trovi dove leggere i passi originali.`,
        `**È gratuita?** Sì. Se ti è utile, puoi sostenere Formebrevi dalla pagina «Sostieni Formebrevi».`,
      ] },
      { t: 'azione', x: 'Serve aiuto? Vai a «Supporto»', az: 'info', id: 'supporto' },
    ],
  },
  {
    id: 'che-cose',
    gruppo: 'app',
    titolo: "Che cos'è Stoicismo quotidiano",
    sotto: 'Una guida di riflessione ispirata allo stoicismo.',
    blocchi: [
      { t: 'p', x: `Stoicismo quotidiano è una **guida di riflessione ispirata allo stoicismo**. Spiega le idee e le pratiche degli stoici antichi, con i riferimenti ai loro testi. Non sostituisce il parere del medico né un percorso di cura o di sostegno psicologico: se il malessere è forte o dura da tempo, parlane con il tuo medico o con un professionista.` },
      { t: 'h', x: 'Su che cosa si basa' },
      { t: 'lista', x: [
        `Gli scritti di **Epitteto**, **Seneca** e **Marco Aurelio**.`,
        `I frammenti degli **stoici antichi**, raccolti dagli studiosi.`,
      ] },
      { t: 'h', x: 'Come sono scritti i testi' },
      { t: 'p', x: `I testi della app sono stati scritti per questa app. Riprendono le idee degli autori antichi con parole nostre, senza citazioni copiate dalle traduzioni. Ogni lezione indica i passi precisi da cui vengono le idee, controllati sui libri. Trovi l'elenco dei libri nella pagina Fonti.` },
      { t: 'h', x: 'Chi la realizza' },
      { t: 'p', x: `Stoicismo quotidiano è un progetto di Formebrevi APS, associazione di promozione sociale di Caltanissetta. La app è gratuita e senza pubblicità.` },
    ],
  },
  {
    id: 'fonti',
    gruppo: 'app',
    titolo: 'Fonti e bibliografia',
    sotto: 'I libri da cui vengono le idee, con le edizioni.',
    blocchi: [
      { t: 'p', x: `Ecco i libri su cui si basa la app. Sono anche un punto di partenza per chi vuole leggere gli stoici.` },
      { t: 'lista', x: [
        `**Epitteto,** *Tutte le opere*, testo greco a fronte, a cura di Giovanni Reale. Contiene il *Manuale* e i *Discorsi*.`,
        `**Marco Aurelio,** *Ricordi* (noto anche come *A se stesso*), nuova traduzione di Franco Scalenghe, con note e commento.`,
        `**Seneca,** *Tutte le opere*, cura e traduzione di Mario Scaffidi Abbate (Newton Compton). Comprende le *Lettere a Lucilio* e i dialoghi (*Sull'ira*, *Sulla brevità della vita*, *Sulla tranquillità dell'animo*, *Sulla provvidenza*).`,
        `**Giovanni Reale,** *La filosofia di Seneca come terapia dei mali dell'anima*.`,
        `**Pierre Hadot,** *Esercizi spirituali e filosofia antica*, a cura di Arnold I. Davidson, traduzione di Anna Maria Marietti (Einaudi, Piccola Biblioteca Einaudi).`,
        `**Andrea E. Cavanna e altri,** *The Western origins of mindfulness therapy in ancient Rome*, Neurological Sciences, 2023.`,
        `**Georgina King,** *Modern Stoicism and mental health: a randomised controlled trial*, tesi di dottorato, Royal Holloway, University of London, 2025.`,
        `**Hans von Arnim,** *Stoici antichi. Tutti i frammenti*, a cura di Roberto Radice.`,
        `**Max Pohlenz,** *La Stoa. Storia di un movimento spirituale*, a cura di Giovanni Reale.`,
        `**Epitteto,** *Le diatribe e i frammenti*.`,
        `**Epitteto,** *Il manuale di Epitteto (Enchiridion)*, traduzione di Giacomo Leopardi (Liber Liber).`,
      ] },
      { t: 'p', x: `Nelle lezioni del corso i passi sono indicati con la numerazione tradizionale: il capitolo per il *Manuale*, libro e capitolo per i *Discorsi* di Epitteto (che alcune edizioni italiane chiamano *Diatribe*) e per *A se stesso* di Marco Aurelio, il numero della lettera per le *Lettere a Lucilio*. Così li ritrovi in qualunque edizione.` },
      { t: 'nota', x: `Le pagine della Biblioteca spiegano come leggerli e da dove cominciare.` },
      { t: 'azione', x: 'Come leggere gli stoici', az: 'studio', id: 'come-leggere' },
    ],
  },
  {
    id: 'sostieni',
    gruppo: 'formebrevi',
    titolo: 'Sostieni Formebrevi',
    sotto: 'La app è gratuita: se ti è utile, aiutaci a continuare.',
    blocchi: [
      { t: 'p', x: `La app è gratuita, senza pubblicità e senza account. È realizzata dai volontari di Formebrevi APS. Se ti è stata utile, puoi aiutare l'associazione a continuare.` },
      { t: 'h', x: 'Dona con PayPal' },
      { t: 'p', x: 'Una donazione libera, di qualsiasi importo.' },
      { t: 'link', x: 'Dona con PayPal', href: 'paypal', stile: 'primario' },
      { t: 'h', x: 'Associati a Formebrevi' },
      { t: 'p', x: `Diventare socio costa 10 € l'anno. Compili la domanda di ammissione, la esamina il Consiglio Direttivo e poi versi la quota. I soci partecipano gratuitamente alle sessioni di dialogo filosofico online.` },
      { t: 'link', x: 'Compila la domanda di ammissione', href: 'iscrizione', stile: 'chiaro' },
      { t: 'h', x: 'Fai conoscere Stoicismo quotidiano' },
      { t: 'p', x: `Il modo più semplice di aiutarci: parlane a una persona che potrebbe averne bisogno.` },
      { t: 'azione', x: 'Condividi Stoicismo quotidiano', az: 'condividi', stile: 'chiaro' },
      { t: 'h', x: 'A che cosa serve il tuo contributo' },
      { t: 'p', x: `Il contributo aiuta l'associazione a mantenere gratuiti le app e i materiali, come Stoicismo quotidiano, Dialogo, Kalmly e i kit didattici. Grazie.` },
    ],
  },
  {
    id: 'supporto',
    gruppo: 'formebrevi',
    titolo: 'Supporto',
    sotto: 'Segnala un problema, suggerisci una correzione, scrivici.',
    blocchi: [
      { t: 'h', x: 'Serve aiuto con la app?' },
      { t: 'p', x: `Scrivici: siamo un'associazione di volontari e rispondiamo di solito entro 3–5 giorni lavorativi.` },
      { t: 'link', x: 'Segnala un problema', href: 'mail:problema', stile: 'primario' },
      { t: 'link', x: 'Suggerisci una correzione o un\'idea', href: 'mail:suggerimento', stile: 'chiaro' },
      { t: 'link', x: 'Scrivi a Formebrevi', href: 'mail:scrivi', stile: 'chiaro' },
      { t: 'h', x: 'Prima di scrivere' },
      { t: 'lista', x: [
        `Guarda la pagina «Come funziona»: forse la risposta c'è già.`,
        `Se qualcosa si vede male, aggiorna la pagina con il tasto di ricarica del browser.`,
        `Dicci che telefono e che browser usi: ci aiuta a capire il problema.`,
      ] },
      { t: 'azione', x: 'Vai a «Come funziona»', az: 'info', id: 'come-funziona', stile: 'chiaro' },
    ],
  },
  {
    id: 'crediti',
    gruppo: 'formebrevi',
    titolo: 'Crediti e privacy',
    sotto: 'Autori, licenza, privacy e versione.',
    blocchi: [
      { t: 'h', x: 'Autori' },
      { t: 'p', x: 'La app è realizzata da Formebrevi APS.' },
      { t: 'h', x: 'Contenuti e licenza' },
      { t: 'p', x: `I contenuti sono distribuiti con licenza Creative Commons BY-NC-SA 4.0: puoi usarli e condividerli per scopi non commerciali, citando la fonte. Le idee sono degli autori antichi e degli studiosi indicati nella pagina Fonti; i testi sono stati scritti per questa app.` },
      { t: 'h', x: 'Privacy' },
      { t: 'p', x: `La app è senza account, senza pubblicità e senza raccolta di dati: nessun dato lascia il telefono. Sul telefono restano soltanto la nota di apertura già letta, le lezioni segnate come fatte e, se lo usi, il quaderno.` },
      { t: 'h', x: 'Altre app di Formebrevi' },
      { t: 'link', x: 'Dialogo, per condurre un dialogo filosofico', href: 'dialogo', stile: 'chiaro' },
      { t: 'link', x: "Kalmly, l'app per l'ADHD", href: 'kalmly', stile: 'chiaro' },
      { t: 'h', x: 'Versione' },
      { t: 'p', x: `Stoicismo quotidiano, versione ${VERSIONE}.` },
    ],
  },
];
