// Meditazioni della Fase 3 (4 in più, per arrivare a 12). Stesso formato di meditazioni.js: la somma dei secondi dei segmenti deve dare i minuti dichiarati.

export const MEDITAZIONI_3 = [
  {
    id: 'guardare-il-peggio',
    titolo: 'Guardare il peggio con calma',
    sotto: 'Sette minuti per guardare in faccia una paura, come faceva Seneca, e ritrovarla più piccola.',
    minuti: 7,
    fonte: { autore: 'Seneca', opera: 'Lettere a Lucilio', nota: 'la premeditazione dei mali' },
    cosaFare: [
      `Scegli una preoccupazione precisa, non la più grande: una che ti ronza in testa oggi.`,
      `Siediti comodo e segui le frasi, una alla volta, con calma.`,
      `Se la paura sale troppo, apri gli occhi e guarda intorno: puoi fermarti quando vuoi.`,
    ],
    perche: `Gli stoici praticavano la **premeditazione dei mali**: immaginare in anticipo, con calma, ciò che si teme. Il male immaginato con metodo perde parte della sua forza, e chi lo ha già guardato in faccia ha più risorse per affrontarlo. Non è pessimismo: è prepararsi.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: `Siediti comodo, con la schiena appoggiata. Respira, e senti il peso del corpo sulla sedia.` },
      { secondi: 45, testo: `Scegli una preoccupazione. Non la più grande: una precisa, che oggi ti ronza in testa. Dille un nome breve, per esempio «il colloquio» o «la visita».` },
      { secondi: 60, testo: `Ora immagina, con calma, che cosa potrebbe andare storto. Non serve drammatizzare: guarda la scena come si guarda una fotografia, con i dettagli semplici.` },
      { secondi: 60, testo: `Chiediti: se accadesse, che cosa farei? Prova a vedere i primi due o tre gesti, concreti e possibili. Chi ha un piano ha già una parte della forza che serve.` },
      { secondi: 60, testo: `Guarda che cosa resterebbe intatto anche nel caso peggiore: le persone che ti vogliono bene, le tue capacità, la tua libertà di scegliere come rispondere.` },
      { secondi: 60, testo: `Ora dai una misura al male immaginato. Su una scala da uno a dieci, quanto sarebbe grave, davvero? Spesso è meno di quanto la paura lo faceva sembrare.` },
      { secondi: 50, testo: `Lascia andare la scena. Ricorda che il futuro non è scritto: quasi sempre accade qualcosa di più semplice, e di più diverso, di ciò che abbiamo immaginato.` },
      { secondi: 40, testo: `Riporta l'attenzione al presente. Senti i piedi a terra, il respiro, i suoni intorno. Adesso non c'è nessun male: c'è solo questo momento.` },
      { secondi: 20, testo: `Quando sei pronto, riapri gli occhi. Hai guardato la paura, e sei ancora qui.` },
    ],
  },
  {
    id: 'la-natura-ci-accoglie',
    titolo: 'La natura ci accoglie',
    sotto: 'Cinque minuti per sentirsi parte di qualcosa di più grande, come suggerivano gli stoici.',
    minuti: 5,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'l’ordine della natura e il nostro posto in essa' },
    cosaFare: [
      `Se puoi, siediti vicino a una finestra o all'aperto. Anche solo guardare il cielo aiuta.`,
      `Segui le frasi, e lascia che siano le immagini a guidarti.`,
      `Non serve credere a niente: basta guardare con attenzione.`,
    ],
    perche: `Per gli stoici l'essere umano è una parte della natura, non un ospite estraneo. Guardarsi come una parte dell'ordine del mondo dà una calma diversa: ciò che ci preoccupa è piccolo, e noi siamo tenuti dentro qualcosa di più grande. Marco Aurelio lo ricorda spesso.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: `Siediti e guarda fuori: il cielo, un albero, un muro con la luce sopra. Se non puoi, chiudi gli occhi e immagina un posto che ami.` },
      { secondi: 50, testo: `Nota le cose che stanno accadendo senza di te: il vento, la luce che cambia, gli uccelli, le foglie. Tutto procede, con un ordine che non hai deciso tu.` },
      { secondi: 50, testo: `Ricorda che anche tu sei parte di questo ordine. Il tuo respiro fa parte dell'aria, il tuo corpo è fatto della stessa materia della terra e dell'acqua.` },
      { secondi: 50, testo: `Pensa a quanto è lontana la stella più vicina, e a quanto spazio c'è tra te e lei. Ciò che ti preoccupa oggi ha, in quello spazio, una dimensione minuscola.` },
      { secondi: 50, testo: `Nella natura ogni cosa fa la sua parte: l'albero cresce, il fiume scorre, il sole sorge. Nessuno chiede loro di essere altro. Che cosa vorrebbe dire, per te, fare la tua parte, semplicemente?` },
      { secondi: 50, testo: `Concediti di appartenere. Non devi guadagnarti il tuo posto nel mondo: ce l'hai già, come ogni altro essere vivente.` },
      { secondi: 25, testo: `Riapri lo sguardo e guardati intorno una volta ancora. Porta con te questa calma, più larga di prima.` },
    ],
  },
  {
    id: 'un-compito-alla-volta',
    titolo: 'Un compito alla volta',
    sotto: 'Cinque minuti per riportare ordine quando tutto sembra da fare insieme.',
    minuti: 5,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'fare con attenzione ciò che si ha in mano' },
    cosaFare: [
      `Tieni a portata di mano carta e penna, se ti serve. Non sono obbligatorie.`,
      `Segui le frasi e lascia che l'ordine venga da sé, senza forzare.`,
      `Alla fine avrai una cosa sola da fare: solo quella.`,
    ],
    perche: `Il senso di sommersione nasce dal guardare tutto insieme. Marco Aurelio si ricorda di fare con attenzione ciò che ha in mano e di lasciare il resto a dopo. Un compito alla volta è più facile da fare, e più facile da fare bene.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: `Siediti e lascia le mani libere. Respira una volta a fondo. Non devi fare nulla, adesso, tranne ascoltare.` },
      { secondi: 45, testo: `Lascia venire in mente tutto ciò che hai da fare, senza ordine. Nota come si accavalla: è la mente che li guarda tutti insieme, per questo pesano tanto.` },
      { secondi: 60, testo: `Ora scegli. Tra tutte le cose, quale è davvero necessaria oggi? Quale è la più urgente, e quale la più importante? Non sono sempre la stessa.` },
      { secondi: 60, testo: `Tieni in mente solo quella. Guarda i suoi primi tre gesti, in ordine: che cosa faresti per cominciare, poi, poi ancora. Non c'è altro.` },
      { secondi: 50, testo: `Le altre cose restano lì, e aspettano. Esistono ancora, ma per ora possono aspettare. Quando sarà il loro turno, tornerai a guardarle una alla volta.` },
      { secondi: 40, testo: `Ricordati: essere occupato non è lo stesso che essere agitato. Puoi fare molto con calma, se lo fai un passo alla volta.` },
      { secondi: 20, testo: `Riapri gli occhi e comincia dal primo gesto. Con tutta l'attenzione che hai.` },
    ],
  },
  {
    id: 'la-calma-della-sera',
    titolo: 'La calma della sera',
    sotto: 'Dieci minuti per chiudere la giornata e prepararsi al sonno, senza portarsi dietro i pensieri.',
    minuti: 10,
    fonte: { autore: 'Seneca', opera: "Sull'ira e Lettere a Lucilio", nota: "l'esame della sera e il congedo dalla giornata" },
    cosaFare: [
      `Falla sdraiato o seduto comodo, con la luce bassa. Puoi anche addormentarti alla fine: va bene.`,
      `Lascia che le frasi ti accompagnino. Non serve rispondere.`,
      `Se ti accorgi di seguire un pensiero, torna con gentilezza alla voce.`,
    ],
    perche: `La sera è il momento in cui la giornata si chiude e la mente tende a ripassare tutto. Seneca ripassava la giornata con benevolenza, e poi si congedava da essa. Congedarsi vuol dire riconoscere ciò che è stato, perdonare ciò che si può, e lasciare al riposo il suo posto.`,
    segmenti: [
      { secondi: 30, suono: 'campana', testo: `Sdraiati o siediti comodo. Il giorno è finito: non c'è più nulla da fare, per stasera. Lascia che il corpo si appoggi.` },
      { secondi: 60, testo: `Respira lentamente. Ad ogni espiro senti il corpo farsi più pesante, e più fermo. Non c'è fretta: hai tutta la notte.` },
      { secondi: 70, testo: `Ripercorri la giornata, a grandi passi, dal mattino a ora. Non giudicare: guarda come si guardano le pagine di un libro, una dopo l'altra.` },
      { secondi: 70, testo: `Che cosa è andato bene, oggi? Anche una cosa piccola: un gesto gentile, una cosa finita, un momento di calma. Riconoscilo, con gratitudine.` },
      { secondi: 70, testo: `Dove hai sbagliato, o potevi fare meglio? Guardalo senza durezza, come faresti con un amico. Che cosa puoi imparare, per domani?` },
      { secondi: 70, testo: `A chi devi qualcosa, una parola o un pensiero? Se c'è una persona, lascia che il suo volto ti passi davanti. Domani, se serve, troverai le parole.` },
      { secondi: 70, testo: `Ora congeda la giornata. Dille: «Hai fatto il tuo corso. Ti lascio andare». Ciò che era da fare è fatto, e ciò che resta si vedrà domani.` },
      { secondi: 60, testo: `Metti da parte le preoccupazioni. Ti aspetteranno al mattino, ma per ora possono restare fuori, come le scarpe fuori dalla porta.` },
      { secondi: 50, testo: `Senti il respiro, il letto o la sedia, il silenzio della stanza. Per stanotte sei al sicuro, e puoi riposare.` },
      { secondi: 50, testo: `Buonanotte. Riposa bene, senza sforzo: il sonno arriva da solo, quando lo si lascia venire.` },
    ],
  },
];
