// Meditazioni a tempo: una sequenza di segmenti, ciascuno con un testo e una durata in secondi.
// Con «suono: 'campana'» una campana dolce suona all'inizio del segmento. Una campana suona anche alla fine.

import { MEDITAZIONI_3 } from './meditazioni3.js';

const MEDITAZIONI_BASE = [
  {
    id: 'attenzione-presente',
    titolo: "L'attenzione a se stessi",
    sotto: 'Cinque minuti per restare svegli su ciò che pensi e su ciò che fai, come facevano gli stoici.',
    minuti: 5,
    fonte: { autore: 'Epitteto e Marco Aurelio', opera: 'Discorsi (IV, 12) e A se stesso (VII, 54)', nota: "l'attenzione a sé, in greco prosoché" },
    cosaFare: [
      `Siediti comodo, con gli occhi chiusi o lo sguardo basso.`,
      `Non devi svuotare la mente né smettere di pensare. Devi restare sveglio su ciò che pensi.`,
      `Segui le frasi che compaiono: ognuna ti propone una piccola domanda da farti, in silenzio.`,
    ],
    perche: `Per gli stoici l'esercizio di base era l'**attenzione a se stessi**: vigilare a ogni istante su ciò che si pensa e su ciò che si fa, ricordando che cosa dipende da noi e che cosa no. Epitteto le dedica un intero discorso. Marco Aurelio la riassume in tre gesti: esaminare l'impressione presente, accettare ciò che accade, comportarsi con giustizia con le persone che si hanno davanti. La meditazione ti fa fare proprio questi tre gesti.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: 'Siediti comodo. Ora non c\'è nulla da risolvere. Gli stoici non chiedevano di svuotare la mente, ma di restare svegli su ciò che passa nella mente.' },
      { secondi: 40, testo: 'Nota che cosa c\'è adesso nella tua testa: un pensiero, un\'inquietudine, un\'immagine. Dagli un nome semplice, per esempio «sto pensando a domani».' },
      { secondi: 60, testo: 'Ricordati che è un\'impressione, non un fatto. Prima di crederle, esaminala: è vera? È utile? Lo stoico non scaccia i pensieri, li guarda con metodo.' },
      { secondi: 60, testo: 'Ora chiediti: questo dipende da me? Se dipende da te, tienilo per dopo, quando agirai. Se non dipende da te, lascia che sia com\'è.' },
      { secondi: 50, testo: 'Accetta ciò che sta accadendo in questo momento, senza pretendere che sia diverso. Non devi amarlo: basta smettere di litigare con il fatto che è così.' },
      { secondi: 50, testo: 'Pensa alle persone che hai vicino oggi. Qual è la cosa giusta, piccola e concreta, che puoi fare per una di loro nella prossima ora?' },
      { secondi: 15, testo: 'Se in questi minuti la mente ti è scappata, va bene: accorgersene e tornare è già l\'esercizio. Porta con te questo sguardo e riapri gli occhi.' },
    ],
  },
  {
    id: 'esame-della-sera-guidato',
    titolo: 'Esame della sera',
    sotto: 'Dieci minuti per chiudere la giornata, alla maniera di Seneca.',
    minuti: 10,
    fonte: { autore: 'Seneca', opera: "Sull'ira", nota: "l'esame di coscienza della sera" },
    cosaFare: [
      `Siediti in silenzio e ripercorri la giornata, dall'inizio alla fine, come guardando un film.`,
      `Rispondi con onestà a tre domande: che cosa ho fatto bene, dove ho sbagliato, che cosa farò diversamente.`,
      `Chiudi con il perdono verso te stesso e con la gratitudine. Il fine è correggersi, non punirsi.`,
    ],
    perche: `Seneca racconta che ogni sera esaminava la propria giornata, e lo faceva senza severità: riconoscere gli errori per correggerli e poi riposare. Per gli stoici è uno dei modi più semplici di allenare il giudizio su se stessi.`,
    segmenti: [
      { secondi: 30, suono: 'campana', testo: 'Questa meditazione è per la sera. Siediti in silenzio. Per Seneca la giornata si chiude con un colloquio onesto con se stessi.' },
      { secondi: 60, testo: 'Qualche respiro lento, per lasciare la giornata alle spalle.' },
      { secondi: 90, testo: 'Ripensa alla giornata dall\'inizio, come guardando un film: il risveglio, gli incontri, le cose fatte. Guarda, senza giudicare.' },
      { secondi: 90, testo: 'Che cosa hai fatto bene, oggi? Anche le cose piccole. Prenditi il tempo di riconoscerle.' },
      { secondi: 120, testo: 'Dove hai sbagliato, o sei stato diverso da come volevi? Guardalo con onestà e con dolcezza, come faresti con un amico.' },
      { secondi: 90, testo: 'Che cosa farai diversamente, se si ripresenta? Scegli una cosa sola, semplice.' },
      { secondi: 60, testo: 'Concediti il perdono per ciò che è stato. Seneca lo faceva ogni sera: riconoscere, correggere, riposare.' },
      { secondi: 60, testo: 'Ringrazia per ciò che la giornata ti ha dato, anche se poco. Poi lascia andare tutto.' },
    ],
  },
  {
    id: 'vista-dall-alto-guidata',
    titolo: "Vista dall'alto",
    sotto: 'Cinque minuti per guardare la tua vita da lontano e ritrovare la misura.',
    minuti: 5,
    animazione: 'vista-dall-alto',
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: "lo sguardo dall'alto" },
    cosaFare: [
      `Siediti comodo e chiudi gli occhi.`,
      `Immagina di salire piano piano: dalla tua stanza alla casa, alla città, alla Terra, fino a guardare anche i secoli.`,
      `Da lassù guarda il tuo problema: è ancora tuo, ma ha la sua misura. Poi scendi con calma.`,
    ],
    perche: `Marco Aurelio scrive che è utile guardare le vicende umane dall'alto: da lontano le preoccupazioni ritrovano la loro misura. Gli stoici lo praticavano quando un problema sembrava troppo grande.`,
    segmenti: [
      { secondi: 20, livello: [0, 0], suono: 'campana', testo: 'Siediti comodo e respira. Oggi guarderai la tua vita dall\'alto.' },
      { secondi: 30, livello: [0, 0], testo: 'Sei nella tua stanza. Senti il corpo, il respiro, ciò che ti preoccupa.' },
      { secondi: 40, livello: [0, 1], testo: 'Sali un poco. Vedi la casa dall\'alto, il tetto, la strada, le persone che ci vivono.' },
      { secondi: 50, livello: [1, 2], testo: 'Sali ancora: il quartiere, la città con le sue luci, le strade, i movimenti. Ogni luce è una vita.' },
      { secondi: 50, livello: [2, 3], testo: 'Ancora più su: le colline, il mare, il paese intero. Tante persone che lavorano, sperano, si preoccupano, come te.' },
      { secondi: 50, livello: [3, 4], testo: 'Ora la Terra, tutta intera, piccola e silenziosa nello spazio. Da quassù, dov\'è il tuo problema?' },
      { secondi: 30, livello: [4, 5], testo: 'Guarda anche il tempo: i secoli passati e quelli futuri. Quanto peserà, tra cent\'anni, ciò che oggi ti agita?' },
      { secondi: 30, livello: [5, 0], testo: 'Comincia a scendere, lentamente: la Terra, il paese, la città, la tua casa, la tua stanza. Torna con calma.' },
    ],
  },
  {
    id: 'la-mattina',
    titolo: 'La mattina',
    sotto: 'Cinque minuti per preparare la giornata, come faceva Marco Aurelio.',
    minuti: 5,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'la preparazione del mattino (II, 1) e il lavoro proprio dell\'uomo (V, 1)' },
    cosaFare: [
      `Siediti prima di cominciare la giornata, con gli occhi chiusi o lo sguardo basso.`,
      `Segui le frasi: ti guidano a prevedere ciò che incontrerai, a scegliere un compito e a decidere come vuoi essere.`,
      `Non devi organizzare tutto. Devi solo prepararti.`,
    ],
    perche: `Marco Aurelio comincia la giornata dicendosi in anticipo che incontrerà persone difficili, e ricordandosi che chi sbaglia lo fa spesso per ignoranza. Quando si alza a fatica, si chiede a che cosa serve e qual è il suo compito. È un modo di entrare nella giornata senza farsi sorprendere.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: 'Siediti, all\'inizio della giornata. Marco Aurelio cominciava così: si preparava prima ancora di uscire.' },
      { secondi: 45, testo: 'Pensa a che cosa ti aspetta oggi: incontri, compiti, imprevisti. Guardali uno alla volta, senza agitarti.' },
      { secondi: 55, testo: 'Tra queste persone, ce n\'è una difficile? Ricorda che chi si comporta male di solito ignora il bene. Non lo scusa, ma ti aiuta a restare in piedi.' },
      { secondi: 45, testo: 'Ricordati che siamo fatti per collaborare, come le mani o i piedi. Agire gli uni contro gli altri va contro la nostra natura.' },
      { secondi: 55, testo: 'Se stamattina ti pesa alzarti, chiediti: qual è il mio compito di oggi? Scegline uno solo, il più importante.' },
      { secondi: 45, testo: 'Immagina di svolgerlo con calma e con la qualità che vuoi: pazienza, chiarezza, gentilezza.' },
      { secondi: 30, testo: 'Sei pronto. Ciò che accadrà lo affronterai un momento alla volta. Quando vuoi, apri gli occhi e comincia.' },
    ],
  },
  {
    id: 'il-rifugio-interiore',
    titolo: 'Il rifugio interiore',
    sotto: 'Cinque minuti per ritirarti in te stesso e rinnovarti.',
    minuti: 5,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'il ritirarsi in se stessi (IV, 3)' },
    cosaFare: [
      `Siediti comodo e chiudi gli occhi.`,
      `Immagina un luogo semplice e silenzioso dentro di te, e scegli una massima breve da tenere con te.`,
      `Se affiora un pensiero che ti turba, guardalo da lì: è un'impressione, non ancora un fatto.`,
    ],
    perche: `Marco Aurelio scrive che molti cercano un rifugio in campagna o al mare, ma è sempre possibile ritirarsi in se stessi, e che in nessun luogo ci si ritira con più tranquillità che nel proprio animo. Consiglia di concedersi questo rifugio continuamente e di tenere a portata di mano poche idee brevi ed elementari, capaci di scacciare il malcontento.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: 'Siediti comodo. Per questi minuti non c\'è nulla da fare.' },
      { secondi: 40, testo: 'Marco Aurelio scrive che si può sempre ritirarsi in se stessi, e che non esiste rifugio più tranquillo del proprio animo.' },
      { secondi: 50, testo: 'Immagina un luogo dentro di te, semplice e silenzioso. Può essere una stanza, un giardino, una riva. Nessuno entra senza il tuo permesso.' },
      { secondi: 55, testo: 'In questo luogo, ricorda una massima breve che ti aiuti a stare in piedi. Per esempio: «Posso solo fare la mia parte» oppure «Questo passerà».' },
      { secondi: 55, testo: 'Se affiora qualcosa che ti turba, guardalo da qui: è un\'impressione, non ancora un fatto. Chiediti se dipende da te.' },
      { secondi: 50, testo: 'Concediti di riposare. Marco Aurelio consiglia di rinnovarsi in questo rifugio, per tornare poi agli impegni con meno peso.' },
      { secondi: 25, testo: 'Quando sei pronto, esci con calma. Il rifugio resta dov\'è: puoi tornarci ogni volta.' },
    ],
  },
  {
    id: 'il-tempo-che-hai',
    titolo: 'Il tempo che hai',
    sotto: 'Cinque minuti per chiederti a che cosa dedichi il tuo tempo.',
    minuti: 5,
    fonte: { autore: 'Seneca', opera: 'Sulla brevità della vita', nota: 'la vita è abbastanza lunga se sappiamo usarla' },
    cosaFare: [
      `Siediti in silenzio e pensa alle tue ore, senza giudicarti.`,
      `Scegli una cosa che merita davvero il tuo tempo oggi, e una che puoi ridurre.`,
      `Non serve angosciarsi: serve un po' di attenzione.`,
    ],
    perche: `Seneca sostiene che la vita non è breve per natura: la rendiamo breve noi, disperdendone gran parte in cose che non contano. Il tempo è l'unica cosa che ci è davvero affidata e, una volta passato, non torna. La sua conclusione non è l'angoscia ma una scelta: dedicare il tempo a ciò che vale.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: 'Siediti. Seneca scrive che la vita non è breve: la rendiamo breve noi, perdendone tanta parte.' },
      { secondi: 45, testo: 'Pensa a ieri: quanto tempo hai dedicato a ciò che conta per te? E quanto a cose che non ricordi già più?' },
      { secondi: 55, testo: 'Il tempo è l\'unica cosa che ci è davvero affidata. Il denaro, la fama, gli oggetti passano da una mano all\'altra. Il tempo, una volta passato, non torna.' },
      { secondi: 50, testo: 'Non serve farne una fonte di angoscia. Serve un\'attenzione: oggi, a che cosa vale la pena dedicare le tue ore?' },
      { secondi: 55, testo: 'Scegli una cosa che merita il tuo tempo oggi. Può essere piccola: una persona, un compito, un riposo.' },
      { secondi: 40, testo: 'Poi scegli una cosa che puoi togliere, o ridurre, perché ti prende tempo senza darti nulla.' },
      { secondi: 30, testo: 'Torna al presente. Questo momento è l\'unico che hai in mano. Usalo bene.' },
    ],
  },
  {
    id: 'una-giornata-intera',
    titolo: 'Una giornata intera',
    sotto: 'Cinque minuti per vivere la giornata senza agitarti, senza intorpidirti, senza recitare.',
    minuti: 5,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'la completezza del carattere: la giornata vissuta con tutto il suo peso (VII, 69)' },
    cosaFare: [
      `Siediti comodo e chiudi gli occhi.`,
      `Segui le frasi: ti chiedono di guardare la giornata senza agitazione, senza torpore e senza recitare una parte.`,
      `Alla fine scegli una cosa da fare con tutta la tua attenzione.`,
    ],
    perche: `Marco Aurelio descrive il carattere completo come quello di chi vive l'intera giornata con il suo peso pieno, senza batticuore, senza intorpidirsi e senza recitare una parte. Non è una sfida: è un invito a smettere di rimandare la vita a un domani migliore e a stare dentro ciò che si fa oggi.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: 'Siediti. Marco Aurelio descriveva il carattere completo come quello di chi vive l\'intera giornata senza agitarsi e senza intorpidirsi.' },
      { secondi: 45, testo: 'Pensa a questa giornata, dall\'inizio alla sera. Che cosa vuoi che ci sia? Non tutto: soltanto ciò che conta.' },
      { secondi: 55, testo: 'Senza agitarti. Che cosa ti fa correre più del necessario? Guardalo, e prova a rallentare di un passo.' },
      { secondi: 50, testo: 'Senza intorpidirti. Che cosa stai lasciando andare, per stanchezza o per abitudine, e ti importa davvero?' },
      { secondi: 55, testo: 'Senza recitare. In quale momento della giornata reciti una parte? Immagina di essere, lì, semplicemente te stesso.' },
      { secondi: 40, testo: 'Scegli una cosa da fare oggi con tutta la tua attenzione. Anche piccola: una telefonata, un pasto, una passeggiata.' },
      { secondi: 30, testo: 'Ora torna a questo momento. La giornata è un momento dopo l\'altro. Apri gli occhi quando vuoi.' },
    ],
  },
  {
    id: 'la-citta-comune',
    titolo: 'La città comune',
    sotto: 'Cinque minuti per ricordarti che fai parte di qualcosa di più grande.',
    minuti: 5,
    fonte: { autore: 'Marco Aurelio', opera: 'A se stesso', nota: 'la ragione comune e il cosmo come città (IV, 4); siamo nati per collaborare (II, 1)' },
    cosaFare: [
      `Siediti comodo e chiudi gli occhi.`,
      `Pensa alle persone che vivono, in questo momento, giornate simili alla tua, e poi a chi ti sta vicino.`,
      `Alla fine scegli un piccolo gesto da fare per qualcuno.`,
    ],
    perche: `Marco Aurelio ragiona così: se la ragione è comune a tutti gli esseri umani, siamo tutti cittadini di una stessa città, il cosmo. Aggiunge che siamo nati per collaborare, come le mani, i piedi, le palpebre. Nel dolore ci si sente soli: ricordare di far parte di una comunità è per gli stoici un rimedio concreto.`,
    segmenti: [
      { secondi: 25, suono: 'campana', testo: 'Siediti comodo. Marco Aurelio scrive che siamo tutti cittadini di una stessa città: il mondo, con la sua ragione comune.' },
      { secondi: 40, testo: 'Pensa alle persone che, in questo momento, stanno vivendo una giornata come la tua: lavorano, aspettano, si preoccupano, sperano.' },
      { secondi: 55, testo: 'Ora pensa a chi ti sta vicino: familiari, amici, colleghi, vicini. Ognuno ha qualcosa da portare, come te.' },
      { secondi: 55, testo: 'Siamo nati per collaborare, come le mani, i piedi, le palpebre. Nessuna parte funziona da sola.' },
      { secondi: 50, testo: 'Se oggi ti senti solo, ricorda che fai parte di questa città anche adesso. Il tuo posto c\'è, e ti aspetta.' },
      { secondi: 45, testo: 'Pensa a un gesto piccolo che puoi fare per qualcuno oggi, anche senza dirlo: una parola, un aiuto, un ascolto.' },
      { secondi: 30, testo: 'Torna a te. Porta con te la certezza di far parte di qualcosa. Quando vuoi, apri gli occhi.' },
    ],
  },
];

export const MEDITAZIONI = [...MEDITAZIONI_BASE, ...MEDITAZIONI_3];
