// Pensieri da portare con te della Fase 3 (100 in più, per arrivare a 300). Formulazioni originali, senza citazioni dai libri.

const E = { autore: 'Epitteto', opera: 'Manuale' };
const ED = { autore: 'Epitteto', opera: 'Discorsi' };
const SL = { autore: 'Seneca', opera: 'Lettere a Lucilio' };
const SI = { autore: 'Seneca', opera: "Sull'ira" };
const SB = { autore: 'Seneca', opera: 'Sulla brevità della vita' };
const ST = { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" };
const SBEN = { autore: 'Seneca', opera: 'Sui benefici' };
const M = { autore: 'Marco Aurelio', opera: 'A se stesso' };

export const PENSIERI_3 = [
  { id: 'e68', voce: 'epitteto', testo: 'Prima di reagire, chiediti: questa cosa dipende da me? Se la risposta è no, risparmia le forze.', fonte: E },
  { id: 'e69', voce: 'epitteto', testo: 'Chi vuole essere libero non desidera ciò che dipende da altri. Comincia a contare le cose che sono tue.', fonte: E },
  { id: 'e70', voce: 'epitteto', testo: 'Le parole degli altri sono suono finché non le fai tue. Tu decidi se lasciarle entrare.', fonte: E },
  { id: 'e71', voce: 'epitteto', testo: 'Non aspettarti un premio per ogni cosa giusta. Farla è già il premio.', fonte: E },
  { id: 'e72', voce: 'epitteto', testo: 'Quando qualcosa ti disturba, dagli il nome che ha: un fatto o un giudizio? Poi decidi.', fonte: E },
  { id: 'e73', voce: 'epitteto', testo: 'Tutti vorrebbero cambiare il mondo. Pochi cominciano dal proprio modo di guardarlo.', fonte: ED },
  { id: 'e74', voce: 'epitteto', testo: 'Ogni giorno hai una parte da recitare: recitala senza invidiare le parti degli altri.', fonte: E },
  { id: 'e75', voce: 'epitteto', testo: 'Se ti offende un insulto, guarda chi lo dice e quanto vale il suo giudizio. Poi decidi se pesarlo.', fonte: E },
  { id: 'e76', voce: 'epitteto', testo: 'La calma non si trova nelle cose: si costruisce nel modo in cui le accogli.', fonte: E },
  { id: 'e77', voce: 'epitteto', testo: 'Prima di dire che qualcosa è terribile, misura che cosa è davvero accaduto.', fonte: E },
  { id: 'e78', voce: 'epitteto', testo: 'Non è la malattia a togliere libertà, ma il giudizio che ne dai. Il corpo può soffrire e la mente restare libera.', fonte: ED },
  { id: 'e79', voce: 'epitteto', testo: 'Quando ti senti trattato ingiustamente, ricorda che chi sbaglia crede di fare bene.', fonte: E },
  { id: 'e80', voce: 'epitteto', testo: 'Ciò che fai oggi forma chi sarai domani. Scegli con cura anche le cose piccole.', fonte: ED },
  { id: 'e81', voce: 'epitteto', testo: 'Nessuno è padrone di te, se non ti fai padroneggiare da ciò che desideri.', fonte: E },
  { id: 'e82', voce: 'epitteto', testo: 'Non dire di aver perso qualcosa. Di\' che l\'hai restituita, e ringrazia per il tempo che l\'hai avuta.', fonte: E },
  { id: 'e83', voce: 'epitteto', testo: 'Chi si esercita ogni giorno vede il cambiamento. Chi aspetta di sentirsi pronto, aspetta a lungo.', fonte: ED },
  { id: 'e84', voce: 'epitteto', testo: 'Parla poco, e solo di ciò che serve. Le parole in più pesano sul tuo cuore.', fonte: E },
  { id: 'e85', voce: 'epitteto', testo: 'Il lavoro di un filosofo è curare i giudizi sbagliati. Comincia dai tuoi.', fonte: ED },
  { id: 'e86', voce: 'epitteto', testo: 'Sii paziente con te stesso: si impara a vivere come si impara un mestiere, un giorno dopo l\'altro.', fonte: ED },
  { id: 'e87', voce: 'epitteto', testo: 'Ogni difficoltà è un allenatore che ti prepara: chiediti a che cosa serve.', fonte: ED },
  { id: 'e88', voce: 'epitteto', testo: 'Sapere che cosa è tuo e che cosa è altrui è la metà della serenità.', fonte: E },
  { id: 'e89', voce: 'epitteto', testo: 'Non giudicare una persona dal suo lavoro o dalla sua fortuna: giudicala da come usa la sua scelta.', fonte: E },
  { id: 'e90', voce: 'epitteto', testo: 'Quando ti chiedi che cosa devi fare, guarda il tuo ruolo: figlio, amico, cittadino. La risposta è lì.', fonte: E },
  { id: 'e91', voce: 'epitteto', testo: 'Non avere fretta di avere ragione: la verità resta vera anche se la dici piano.', fonte: E },
  { id: 'e92', voce: 'epitteto', testo: 'Chi teme di perdere ciò che ha, lo possiede male. Godilo con mano leggera.', fonte: E },
  { id: 'e93', voce: 'epitteto', testo: 'Ogni sera chiediti che cosa è dipeso da te, oggi, e come lo hai usato.', fonte: ED },
  { id: 'e94', voce: 'epitteto', testo: 'Il coraggio comincia dal dire a se stessi la verità. Il resto viene più facile.', fonte: ED },
  { id: 'e95', voce: 'epitteto', testo: 'Non serve avere tutte le risposte. Serve fare bene la prossima cosa.', fonte: E },
  { id: 'e96', voce: 'epitteto', testo: 'Chi si lamenta di tutto è schiavo di tutto. Scegli un lamento in meno, oggi.', fonte: E },
  { id: 'e97', voce: 'epitteto', testo: 'Una buona giornata è fatta di molte piccole scelte giuste. Falle una alla volta.', fonte: ED },
  { id: 'e98', voce: 'epitteto', testo: 'Quando ti senti fragile, ricordati che nessuno decide per te che cosa pensare.', fonte: E },
  { id: 'e99', voce: 'epitteto', testo: 'Sii grato per l\'occasione di esercitarti: senza ostacoli, la pazienza resterebbe una parola.', fonte: ED },
  { id: 'e100', voce: 'epitteto', testo: 'Vivere bene è un mestiere, e si impara facendolo. Comincia oggi con una cosa piccola.', fonte: ED },
  { id: 'e101', voce: 'epitteto', testo: 'Ciò che pensi di una cosa è tuo. Cambiarlo è il primo lavoro, e nessuno può farlo al posto tuo.', fonte: E },

  { id: 's68', voce: 'seneca', testo: 'Ti preoccupi per molte cose che non accadranno mai. Quanto tempo hai già sprecato in questo modo?', fonte: SL },
  { id: 's69', voce: 'seneca', testo: 'Il tempo che hai è più che sufficiente, se lo usi con cura. Ne perdiamo tanto distraendoci.', fonte: SB },
  { id: 's70', voce: 'seneca', testo: 'Ogni giorno è una piccola vita: cominciala con attenzione, chiudila con gratitudine.', fonte: SL },
  { id: 's71', voce: 'seneca', testo: 'Non si è poveri per avere poco, ma per desiderare troppo. Riduci il desiderio e sarai ricco.', fonte: SL },
  { id: 's72', voce: 'seneca', testo: 'L\'ira è un ospite che si accomoda subito e poi non vuole andarsene. Non dargli la sedia.', fonte: SI },
  { id: 's73', voce: 'seneca', testo: 'Se qualcuno ti irrita, aspetta un giorno prima di rispondere. Il giorno dopo la questione avrà un\'altra misura.', fonte: SI },
  { id: 's74', voce: 'seneca', testo: 'Scegli un amico che ti renda migliore, e sii tu quello che rende migliori gli altri.', fonte: SL },
  { id: 's75', voce: 'seneca', testo: 'Ciò che ci fa soffrire è spesso l\'attesa del male, più del male stesso. Impara a non anticiparlo.', fonte: SL },
  { id: 's76', voce: 'seneca', testo: 'Leggere poco e bene vale più che leggere molto in fretta. Torna sui pensieri che ti toccano.', fonte: SL },
  { id: 's77', voce: 'seneca', testo: 'Nessun vento è favorevole per chi non sa dove andare. Decidi che cosa vuoi diventare.', fonte: SL },
  { id: 's78', voce: 'seneca', testo: 'Il piacere di un giorno tranquillo vale più di molti giorni di successo agitato.', fonte: ST },
  { id: 's79', voce: 'seneca', testo: 'Ogni tanto lascia la folla e stai con te. Chi si frequenta poco, si conosce poco.', fonte: ST },
  { id: 's80', voce: 'seneca', testo: 'Ricorda quanto è breve la vita, non per spaventarti, ma per usarla con più cura.', fonte: SB },
  { id: 's81', voce: 'seneca', testo: 'Non serve viaggiare lontano per cambiare: porti te stesso ovunque. Comincia da qui.', fonte: SL },
  { id: 's82', voce: 'seneca', testo: 'Chi ha imparato a stare con poco non teme la sorte: ha già fatto pace con la perdita.', fonte: SL },
  { id: 's83', voce: 'seneca', testo: 'Quando sei stanco, riposa. Un animo teso si spezza, uno riposato si ripiega e si rialza.', fonte: ST },
  { id: 's84', voce: 'seneca', testo: 'Fai del bene senza contare quante volte. Il conto lo tiene solo chi si aspetta un ritorno.', fonte: SBEN },
  { id: 's85', voce: 'seneca', testo: 'Ringrazia chi ti ha aiutato, e non dimenticarlo. La gratitudine è la memoria del cuore.', fonte: SBEN },
  { id: 's86', voce: 'seneca', testo: 'Ciò che pesa oggi domani sarà più leggero. Tieni duro finché passa.', fonte: SL },
  { id: 's87', voce: 'seneca', testo: 'La fortuna può togliere molto, ma non ciò che hai dentro: le tue scelte e il tuo carattere.', fonte: SL },
  { id: 's88', voce: 'seneca', testo: 'Non aspettare di essere sereno per essere gentile. La gentilezza aiuta a diventarlo.', fonte: SI },
  { id: 's89', voce: 'seneca', testo: 'Prima di giudicare qualcuno, ricorda quante volte hai sbagliato tu.', fonte: SI },
  { id: 's90', voce: 'seneca', testo: 'Ogni sera, rivedi la giornata come faresti con un amico: senza sconti e senza durezza.', fonte: SI },
  { id: 's91', voce: 'seneca', testo: 'Chi si prepara al peggio spesso lo trova più mite di come l\'aveva temuto.', fonte: SL },
  { id: 's92', voce: 'seneca', testo: 'Non serve avere tutto per essere sereni. Serve saper usare bene ciò che si ha.', fonte: SL },
  { id: 's93', voce: 'seneca', testo: 'Il tempo dato agli altri con generosità è ben speso. Quello regalato alla distrazione è perso.', fonte: SB },
  { id: 's94', voce: 'seneca', testo: 'Cerca chi ti dice la verità con affetto. Vale più di cento che ti dicono ciò che vuoi sentire.', fonte: SL },
  { id: 's95', voce: 'seneca', testo: 'Una cosa alla volta, e con tutta l\'anima: è il modo più breve di finire ciò che conta.', fonte: ST },
  { id: 's96', voce: 'seneca', testo: 'Impara a stare da solo senza sentirti solo: è una delle compagnie migliori.', fonte: ST },
  { id: 's97', voce: 'seneca', testo: 'Quando hai fatto del tuo meglio, lascia andare l\'esito. Il resto non è tuo.', fonte: SL },
  { id: 's98', voce: 'seneca', testo: 'È sempre in tempo chi comincia, e chi si corregge non è mai in anticipo.', fonte: SL },
  { id: 's99', voce: 'seneca', testo: 'Un giorno ben vissuto è un piccolo capolavoro. Non ne servono di grandi.', fonte: SL },
  { id: 's100', voce: 'seneca', testo: 'Chi ti ha ferito ti ha dato un\'occasione: quella di rispondere da persona saggia.', fonte: SI },

  { id: 'm68', voce: 'marco', testo: 'Mi alzo e mi ricordo: oggi incontrerò persone difficili, e potrò rispondere con calma.', fonte: M },
  { id: 'm69', voce: 'marco', testo: 'Ciò che ostacola la strada diventa la strada. Guardo l\'ostacolo come una materia da lavorare.', fonte: M },
  { id: 'm70', voce: 'marco', testo: 'Ogni cosa che vedo è passeggera. Mi attacco poco, e la scaccio senza paura.', fonte: M },
  { id: 'm71', voce: 'marco', testo: 'Guardo dall\'alto le mie preoccupazioni: da lassù sono piccole, e con loro le mie paure.', fonte: M },
  { id: 'm72', voce: 'marco', testo: 'Faccio ciò che devo fare adesso. Del resto si vedrà.', fonte: M },
  { id: 'm73', voce: 'marco', testo: 'Chi mi ha ferito era spinto da un giudizio sbagliato. Posso capirlo, e non somigliargli.', fonte: M },
  { id: 'm74', voce: 'marco', testo: 'Il mio rifugio è dentro di me. Posso ritirarmici quando voglio, senza chiedere il permesso.', fonte: M },
  { id: 'm75', voce: 'marco', testo: 'Il meglio che posso fare è essere giusto, oggi, con chi mi sta vicino.', fonte: M },
  { id: 'm76', voce: 'marco', testo: 'Guardo il mondo come un unico corpo: ciò che aiuta uno aiuta tutti.', fonte: M },
  { id: 'm77', voce: 'marco', testo: 'Non cerco di essere perfetto. Cerco di essere migliore di ieri, in una cosa piccola.', fonte: M },
  { id: 'm78', voce: 'marco', testo: 'Quando mi sento perso, torno alle domande semplici: che cosa è vero, che cosa è utile, che cosa devo fare?', fonte: M },
  { id: 'm79', voce: 'marco', testo: 'Ricordo chi mi ha insegnato qualcosa, e ne sono grato. La gratitudine è una forza silenziosa.', fonte: M },
  { id: 'm80', voce: 'marco', testo: 'Ho ricevuto tanto, senza averlo meritato. Ora è il mio turno di dare.', fonte: M },
  { id: 'm81', voce: 'marco', testo: 'Nessuno può impedirmi di fare la cosa giusta. Al massimo può renderla più difficile.', fonte: M },
  { id: 'm82', voce: 'marco', testo: 'Il tempo scorre come un fiume. Io posso stare sulla riva e guardarlo, senza esserne trascinato.', fonte: M },
  { id: 'm83', voce: 'marco', testo: 'Il pensiero di ieri non decide il mio oggi. Ricomincio.', fonte: M },
  { id: 'm84', voce: 'marco', testo: 'Vivo una cosa alla volta, con tutta l\'attenzione. Il resto è rumore.', fonte: M },
  { id: 'm85', voce: 'marco', testo: 'Chi mi critica mi dà un\'occasione per correggermi, se ha ragione, e per restare in pace se ha torto.', fonte: M },
  { id: 'm86', voce: 'marco', testo: 'Il lavoro che faccio ora è tutto ciò che serve. Lo faccio con serietà e senza fretta.', fonte: M },
  { id: 'm87', voce: 'marco', testo: 'Ricordo che sono un cittadino del mondo: le mie azioni contano per tutti.', fonte: M },
  { id: 'm88', voce: 'marco', testo: 'Quanto poco basta per stare bene: un respiro, un pensiero giusto, un gesto onesto.', fonte: M },
  { id: 'm89', voce: 'marco', testo: 'Se una cosa è dentro le mie forze, la faccio. Se è fuori, l\'accetto e vado avanti.', fonte: M },
  { id: 'm90', voce: 'marco', testo: 'Passerà. Anche questo passerà, e io sarò ancora qui, un po\' più saggio.', fonte: M },
  { id: 'm91', voce: 'marco', testo: 'Guardo le persone difficili come una parte del mio allenamento. Loro mi insegnano la pazienza.', fonte: M },
  { id: 'm92', voce: 'marco', testo: 'Quando il corpo è stanco, ascolto. Quando la mente è agitata, aspetto. Poi decido.', fonte: M },
  { id: 'm93', voce: 'marco', testo: 'Sono piccolo davanti al cielo, e questo mi consola: il peso che porto è piccolo anch\'esso.', fonte: M },
  { id: 'm94', voce: 'marco', testo: 'Faccio del mio meglio ogni giorno, e lascio che il resto sia com\'è.', fonte: M },
  { id: 'm95', voce: 'marco', testo: 'Tra ciò che accade e ciò che rispondo c\'è uno spazio. In quello spazio sono io.', fonte: M },
  { id: 'm96', voce: 'marco', testo: 'Il coraggio di oggi è tornare a fare ciò che ho lasciato indietro.', fonte: M },
  { id: 'm97', voce: 'marco', testo: 'Non lascio che le opinioni degli altri decidano il mio valore. Lo decido io, agendo bene.', fonte: M },
  { id: 'm98', voce: 'marco', testo: 'La mia vita è breve e preziosa. La spendo per ciò che ha valore.', fonte: M },
  { id: 'm99', voce: 'marco', testo: 'Rifletto su come sono stato con gli altri oggi. Domani provo a fare meglio.', fonte: M },
  { id: 'm100', voce: 'marco', testo: 'Ho un compito, e la calma per compierlo. Comincio.', fonte: M },
];
