// Pensieri da portare con te: formulazioni originali di idee stoiche, una per voce. Nessuna citazione dai libri.

import { PENSIERI_3 } from './pensieri3.js';

const PENSIERI_BASE = [
  { id: 'e01', voce: 'epitteto', testo: "Alcune cose dipendono da te, altre no. Comincia sempre da qui: qual è quale?", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e02', voce: 'epitteto', testo: "Non ti turbano le cose, ma i giudizi che ne dai. Cambia il giudizio, e la cosa peserà meno.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e03', voce: 'epitteto', testo: "Non pretendere che le cose vadano come vuoi. Vuoi che vadano come vanno, e starai sereno.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e04', voce: 'epitteto', testo: "Un'impressione non è un fatto. Prima di crederle, chiedile: sei vera?", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e05', voce: 'epitteto', testo: "Nessuno può ferirti senza il tuo consenso: ciò che ti ferisce è il giudizio che dai all'offesa.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e06', voce: 'epitteto', testo: "Il corpo, la reputazione, i beni: non sono davvero tuoi. Tuo è soltanto il modo in cui li usi.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e07', voce: 'epitteto', testo: "Ciò che perdi non è distrutto: è tornato a chi te l'aveva prestato. Ringrazia per il tempo che l'hai avuto.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e08', voce: 'epitteto', testo: "La vita è un banchetto: prendi con garbo ciò che ti passa davanti, e lascia passare ciò che non è ancora arrivato.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e09', voce: 'epitteto', testo: "Sei un attore in una parte scelta da altri, breve o lunga: recitala bene. Scegliere la parte non spetta a te.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e10', voce: 'epitteto', testo: "Prima di ogni impresa chiediti che cosa comporta. Chi sa a che cosa va incontro, non si lascia sorprendere.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e11', voce: 'epitteto', testo: "Il desiderio ti rende schiavo di ciò che desideri. Desidera poco, e sarai libero.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e12', voce: 'epitteto', testo: "Non sono le persone a offenderti, ma la tua idea di ciò che avrebbero dovuto fare.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e13', voce: 'epitteto', testo: "Fai ciò che è giusto senza contare gli applausi. Il valore sta nell'azione, non nel riconoscimento.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e14', voce: 'epitteto', testo: "Esercitati nelle piccole cose: una parola detta con calma, un desiderio lasciato andare. Si comincia da lì.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e15', voce: 'epitteto', testo: "Il filosofo non parla molto di ciò che sa. Lo mostra con ciò che fa.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e16', voce: 'epitteto', testo: "Se ti criticano, rispondi con calma: chi conoscesse il resto di te avrebbe ben altro da dire. E vai avanti.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e17', voce: 'epitteto', testo: "È libero solo chi è padrone di sé. Comincia dai desideri.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e18', voce: 'epitteto', testo: "Ciò che chiami sfortuna è quasi sempre una prova: chiediti che cosa ti chiede di imparare.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e19', voce: 'epitteto', testo: "Un ostacolo ti misura: mostra che cosa sei disposto a fare.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e20', voce: 'epitteto', testo: "Non lodare ciò che appartiene agli altri come se fosse anche tuo: la ricchezza, la bellezza, il talento sono doni loro.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e21', voce: 'epitteto', testo: "Quando ti manca qualcosa, chiediti a che prezzo l'avresti ottenuta: ogni cosa ha il suo prezzo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e22', voce: 'epitteto', testo: "Se vuoi migliorare, accetta di sembrare inesperto agli occhi degli altri.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e23', voce: 'epitteto', testo: "Non chiedere agli altri di essere diversi. Chiedi a te stesso di rispondere bene a come sono.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e24', voce: 'epitteto', testo: "Il tuo compito è tenere in ordine il giudizio. Il resto lo farà la vita.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e25', voce: 'epitteto', testo: "La calma non è l'assenza di eventi: è il modo in cui ti tieni in mezzo a essi.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e26', voce: 'epitteto', testo: "Chi ha imparato a lasciare andare ha ben poco da temere.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e27', voce: 'epitteto', testo: "La morte e l'esilio non sono terribili in sé: lo è l'opinione che ne abbiamo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e28', voce: 'epitteto', testo: "Prima di rispondere a un'offesa, guarda che cosa ti sta chiedendo: la tua calma o la tua rabbia?", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e29', voce: 'epitteto', testo: "Se ami una tazza, ricordati che è una tazza: quando si romperà, la tua serenità resterà intera.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e30', voce: 'epitteto', testo: "Il tempo che passi a lamentarti è tempo tolto a ciò che potresti fare.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e31', voce: 'epitteto', testo: "Un principio semplice, tenuto a portata di mano, vale più di cento discorsi: distingui ciò che dipende da te.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e32', voce: 'epitteto', testo: "Fai attenzione a ciò che ti occupa: ogni pensiero sprecato per ciò che è degli altri è una forza in meno per ciò che è tuo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e33', voce: 'epitteto', testo: "Non giudicare in fretta. Chi vede solo un pezzo, giudica soltanto un pezzo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e34', voce: 'epitteto', testo: "Le difficoltà rivelano chi sei: non tremare, sono un allenamento.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e35', voce: 'epitteto', testo: "Sei responsabile della tua parte, non del risultato. Fai bene la prima.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e36', voce: 'epitteto', testo: "Se devi scegliere tra la comodità e il dovere, ricordati che cosa vorrai aver scelto a fine giornata.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e37', voce: 'epitteto', testo: "Cerca dentro ciò che ti serve: la pace dipende da te, e il luogo conta poco.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e38', voce: 'epitteto', testo: "Chi accetta di poter perdere ciò che non è suo, smette di temere gli altri.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e39', voce: 'epitteto', testo: "Comincia oggi. Il progresso non è un colpo di fortuna: è la somma di piccoli giorni.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e40', voce: 'epitteto', testo: "Ogni sera chiediti: che cosa ho fatto, che cosa ho tralasciato? Poi dormi.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e41', voce: 'epitteto', testo: "Prima di dire «è terribile», chiediti: lo è davvero, o mi sembra soltanto? La parola pesa più del fatto.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e42', voce: 'epitteto', testo: "Chiama le cose con il loro nome, senza aggiungerne altri: un ritardo è un ritardo, non un disastro.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e43', voce: 'epitteto', testo: "Quando fai qualcosa, ricorda che cosa vuoi davvero. Se vai al bagno pubblico per lavarti, la confusione è già prevista.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e44', voce: 'epitteto', testo: "Quando un piacere ti chiama, aspetta un momento e confrontalo con come ti sentirai dopo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e45', voce: 'epitteto', testo: "Chi ti tratta male fa ciò che gli sembra giusto in quel momento. Se sbaglia, a perdere è lui.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e46', voce: 'epitteto', testo: "Aspettati il bene e il male da te, e non dagli altri: è lì che puoi davvero agire.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e47', voce: 'epitteto', testo: "Meglio poco con serenità che molto con inquietudine: la calma si paga in cose, e ne vale la pena.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e48', voce: 'epitteto', testo: "Chi cambia strada rischia di essere deriso. Lascia che ridano, e continua a camminare.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e49', voce: 'epitteto', testo: "Quando qualcosa di doloroso capita a un altro, sai dire «è la vita». Prova a dirlo anche quando capita a te.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e50', voce: 'epitteto', testo: "Scegli il carattere che vuoi avere e mantienilo, sia quando sei solo sia quando sei tra la gente.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e51', voce: 'epitteto', testo: "Se fai ciò che è giusto, puoi essere visto senza timore. Se è ingiusto, meglio lasciarlo, anche di nascosto.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e52', voce: 'epitteto', testo: "Non spiegare agli altri come si mangia: mangia con misura, e il resto si vedrà.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e53', voce: 'epitteto', testo: "Fino a quando rimanderai a pretendere il meglio da te? Il momento di cominciare è questo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e54', voce: 'epitteto', testo: "Chi vuole vincere non aspetta il giorno della gara per prepararsi: ogni giorno è già allenamento.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e55', voce: 'epitteto', testo: "Custodisci la tua attenzione come una porta: decidi tu che cosa entra e che cosa resta fuori.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e56', voce: 'epitteto', testo: "Ciò che dipende da te è poco, ma è tutto ciò che conta: giudizio, desiderio, azione.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e57', voce: 'epitteto', testo: "Il modo di stare in una situazione difficile dice più di te della situazione stessa.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e58', voce: 'epitteto', testo: "Non chiederti perché proprio a te. Chiediti che cosa puoi farne, ora.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e59', voce: 'epitteto', testo: "Le parole degli altri sono suoni: il loro significato lo scegli tu.", fonte: { autore: 'Epitteto', opera: "sulla scia del Manuale" } },
  { id: 'e60', voce: 'epitteto', testo: "Ogni cosa ha due manici: prendila da quello con cui puoi portarla.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e61', voce: 'epitteto', testo: "Un fratello ti ha offeso? Prendilo dal manico giusto: è pur sempre tuo fratello.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e62', voce: 'epitteto', testo: "Non è la ricchezza a fare un uomo, né la povertà a disfarlo: è ciò che ne fa.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e63', voce: 'epitteto', testo: "Il vero coraggio è sapere che cosa non dipende da te e tenere la calma proprio lì.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e64', voce: 'epitteto', testo: "Non cercare di cambiare il mondo prima di aver messo ordine in ciò che pensi.", fonte: { autore: 'Epitteto', opera: "Discorsi" } },
  { id: 'e65', voce: 'epitteto', testo: "Dì a te stesso ogni mattina: oggi farò bene la mia parte, chiunque mi stia intorno.", fonte: { autore: 'Epitteto', opera: "sulla scia del Manuale" } },
  { id: 'e66', voce: 'epitteto', testo: "Quando ti senti perso, ricorda che ti bastano due domande: che cosa dipende da me? e che cosa faccio adesso?", fonte: { autore: 'Epitteto', opera: "sulla scia del Manuale" } },
  { id: 's01', voce: 'seneca', testo: "Non abbiamo poco tempo: ne perdiamo molto. La vita è lunga, se sai come usarla.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's02', voce: 'seneca', testo: "Soffriamo più con l'immaginazione che nella realtà. Guarda ciò che c'è, prima di temere ciò che potrebbe esserci.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's03', voce: 'seneca', testo: "Ogni giorno è una piccola vita: cominciala bene e chiudila in pace.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's04', voce: 'seneca', testo: "Chi è dappertutto è altrove. Scegli un posto dove stare, e stai lì con tutto te stesso.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's05', voce: 'seneca', testo: "La vera povertà è il desiderio che non si ferma. Chi si accontenta è già ricco.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's06', voce: 'seneca', testo: "Il vento giova solo a chi ha scelto la meta. Decidi la rotta, poi affronta le onde.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's07', voce: 'seneca', testo: "L'ira è un breve furore che lascia lunghi rimpianti. Il suo rimedio è il tempo: aspetta.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's08', voce: 'seneca', testo: "Non scegliere un amico per ottenere qualcosa: sceglilo perché accanto a lui vuoi diventare migliore.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's09', voce: 'seneca', testo: "Vivi come se qualcuno ti guardasse: non per timore, ma per fare le cose come vorresti averle fatte.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's10', voce: 'seneca', testo: "Prima di condannare l'errore di un altro, chiediti quante volte l'hai commesso tu.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's11', voce: 'seneca', testo: "La morte non è un evento lontano: ci si avvicina un poco ogni giorno. Perciò vivi ora, con pienezza.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's12', voce: 'seneca', testo: "Smetti di temere ciò che è inevitabile. Prepara ciò che puoi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's13', voce: 'seneca', testo: "La fortuna può toglierti molto, ma non ciò che sei diventato.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's14', voce: 'seneca', testo: "Se una cosa ti pesa, chiediti se pesa per la cosa o per il modo in cui la sollevi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's15', voce: 'seneca', testo: "La cosa più preziosa che possiedi è il tuo tempo: donalo a chi lo merita.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's16', voce: 'seneca', testo: "Sopporta le fatiche: ti rendono più solido, come i venti rendono più salda la quercia.", fonte: { autore: 'Seneca', opera: "Sulla provvidenza" } },
  { id: 's17', voce: 'seneca', testo: "Non basta leggere molto: bisogna tornare spesso ai pochi pensieri che ti aiutano davvero.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's18', voce: 'seneca', testo: "Ritirati un poco in te stesso ogni giorno. Là dentro c'è più pace che in qualunque viaggio.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's19', voce: 'seneca', testo: "Non è il luogo a guarirti: porti te stesso ovunque. Cambia il modo di guardare, non il paesaggio.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's20', voce: 'seneca', testo: "Chi rimanda la vita a domani la perde oggi. Comincia da qualcosa di piccolo, adesso.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's21', voce: 'seneca', testo: "Fai il bene con piacere e senza contare i favori: il bene fatto è già il suo premio.", fonte: { autore: 'Seneca', opera: "Sui benefici" } },
  { id: 's22', voce: 'seneca', testo: "Le tue paure arrivano spesso prima della realtà. Lascia che arrivino dopo, e forse non arriveranno.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's23', voce: 'seneca', testo: "Ogni sera passa in rassegna la giornata, senza paura e senza indulgenza: è così che si impara a vivere.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's24', voce: 'seneca', testo: "Se sbagli, correggiti senza punirti. Il perdono che dai agli altri, concedilo anche a te.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's25', voce: 'seneca', testo: "Cerca di essere amico di te stesso: troverai in casa una buona compagnia.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's26', voce: 'seneca', testo: "Chi segue il proprio destino è accompagnato; chi vi si oppone è trascinato.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's27', voce: 'seneca', testo: "L'invidia è un conto fatto male: guarda ciò che hai prima di guardare ciò che manca.", fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" } },
  { id: 's28', voce: 'seneca', testo: "Una vita non si giudica dalla sua lunghezza, ma da come è stata vissuta.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's29', voce: 'seneca', testo: "Dorme bene chi ha la coscienza in ordine: comincia a ordinarla stasera.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's30', voce: 'seneca', testo: "Ciò che è davvero tuo non può esserti portato via. Custodisci quello.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's31', voce: 'seneca', testo: "Pensare al peggio con calma toglie alla sorpresa il suo potere.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's32', voce: 'seneca', testo: "Ogni fatica sostenuta oggi è una libertà in più domani.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's33', voce: 'seneca', testo: "La misura è amica della serenità: evita l'eccesso nel desiderio come nel timore.", fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" } },
  { id: 's34', voce: 'seneca', testo: "Ascolta chi ti dice la verità, anche quando dispiace: ti risparmierà lunghi errori.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's35', voce: 'seneca', testo: "Chi si lamenta della brevità della vita ne ha sprecata molta. Non è tardi per cominciare a usarla.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's36', voce: 'seneca', testo: "Il saggio non nasconde le emozioni: le riconosce, e poi sceglie che cosa farne.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's37', voce: 'seneca', testo: "Pensa a chi vive con meno di te e con più serenità: che cosa sa, che tu non sai?", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's38', voce: 'seneca', testo: "Ciò che ci appartiene è come ciò che prendiamo a prestito: restituiscilo con garbo, quando sarà il momento.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's39', voce: 'seneca', testo: "Comincia l'anno, il mese, il giorno come se fosse il primo: hai il diritto di ricominciare quando vuoi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's40', voce: 'seneca', testo: "Sii gentile con chi sbaglia: l'errore è la condizione di chi sta imparando.", fonte: { autore: 'Seneca', opera: "Sulla clemenza" } },
  { id: 's41', voce: 'seneca', testo: "Ciò che gli altri hanno di più non ti toglie nulla: guarda a te, e a ciò che puoi coltivare.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's42', voce: 'seneca', testo: "Non tutto ciò che si desidera vale il desiderio: prova a chiederti che cosa ne resterebbe una volta ottenuto.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's43', voce: 'seneca', testo: "Chi si accontenta di ciò che ha non è povero, anche se ha poco.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's44', voce: 'seneca', testo: "Correre da un luogo all'altro non serve a nulla, se porti con te le stesse paure.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's45', voce: 'seneca', testo: "Nessuno vive bene guardando soltanto a se stesso: per vivere per te devi vivere anche per gli altri.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's46', voce: 'seneca', testo: "L'amicizia mette in comune ciò che accade: gioie e dispiaceri pesano meno se condivisi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's47', voce: 'seneca', testo: "«Stai attento la prossima volta; per stavolta passi». Puoi dirtelo anche tu, con la stessa gentilezza.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's48', voce: 'seneca', testo: "Quando l'ira sale, guardati allo specchio: la faccia dell'ira non piace a nessuno.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's49', voce: 'seneca', testo: "Con chi ignora, l'ira serve a poco: correggilo, se puoi, e altrimenti lascialo andare.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's50', voce: 'seneca', testo: "Scegliti amici semplici e miti: accanto a loro l'ira trova meno pretesti.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's51', voce: 'seneca', testo: "Il tempo che ti resta è più che sufficiente, se eviti di disperderlo in cose che contano poco.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's52', voce: 'seneca', testo: "Chi si affanna per molte cose non vive: le rincorre. Scegline poche, e vivile.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's53', voce: 'seneca', testo: "Chi vive ogni giorno come se fosse l'ultimo non aspetta domani per essere grato.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's54', voce: 'seneca', testo: "Ogni giorno dobbiamo prepararci ad andarcene, e poi restare qui con più leggerezza.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's55', voce: 'seneca', testo: "Non serve dolersi due volte: una per la cosa, e una per l'idea che la cosa possa ripetersi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's56', voce: 'seneca', testo: "Non lasciare che l'attesa del male ti tolga la pace di oggi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's57', voce: 'seneca', testo: "Senza una meta nessun vento è favorevole, ma un passo da fare c'è sempre.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's58', voce: 'seneca', testo: "Sii tenero con te come lo saresti con un amico, e severo soltanto quanto serve a correggerti.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's59', voce: 'seneca', testo: "Un'anima tranquilla non ha bisogno di grandi cose: le bastano poche, ben usate.", fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" } },
  { id: 's60', voce: 'seneca', testo: "Evita di sovraccaricarti di impegni: chi si disperde in troppe cose ne porta a termine poche.", fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" } },
  { id: 's61', voce: 'seneca', testo: "Cambia spesso attività, se ti stanca: il riposo è parte del lavoro.", fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" } },
  { id: 's62', voce: 'seneca', testo: "Il dolore condiviso è più leggero: cerca chi ti ascolti, e ascolta a tua volta.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's63', voce: 'seneca', testo: "Ridere della vita è più saggio che piangerla: fa meno male e mostra più coraggio.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's64', voce: 'seneca', testo: "Fai i conti ogni sera con la giornata: chi la conosce da vicino non ha paura di guardarla.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's65', voce: 'seneca', testo: "La solitudine può essere una cura, se la usi per ascoltarti e non per rimuginare.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's66', voce: 'seneca', testo: "Il coraggio si impara a poco a poco: comincia da una piccola cosa che ti spaventa un po'.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's67', voce: 'seneca', testo: "Non aspettare la vecchiaia per essere saggio: ogni età ha il suo compito.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 'm01', voce: 'marco', testo: "Ciò che accade non entra nella mia mente: sono io a lasciarlo entrare, con il mio giudizio.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm02', voce: 'marco', testo: "Ogni mattina ricordo che incontrerò persone difficili: non per rancore, ma per essere preparato.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm03', voce: 'marco', testo: "La mia mente prende il colore dei pensieri che frequenta. Scelgo con cura a che cosa pensare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm04', voce: 'marco', testo: "Posso ritirarmi in me in qualsiasi momento: nessun luogo è più tranquillo della mia anima.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm05', voce: 'marco', testo: "Faccio soltanto ciò che è giusto e dico soltanto ciò che è vero: da qui comincia la mia libertà.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm06', voce: 'marco', testo: "La miglior risposta a chi mi offende è non diventare come lui.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm07', voce: 'marco', testo: "Guardo dall'alto le cose che mi agitano: da lassù sono molto più piccole.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm08', voce: 'marco', testo: "Tutto ciò che vedo cambierà: perché darmi tanta pena per ciò che passa?", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm09', voce: 'marco', testo: "Faccio ora ciò che ho tra le mani, come se fosse l'ultima cosa: con cura, con affetto, con giustizia.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm10', voce: 'marco', testo: "L'ostacolo diventa materia: ciò che si oppone al mio agire mi mostra dove esercitarmi.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm11', voce: 'marco', testo: "Del futuro non mi preoccupo: quando verrà, avrò le stesse armi che ho oggi, la ragione.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm12', voce: 'marco', testo: "Sono parte di un tutto: ciò che accade a me ha un posto nell'ordine delle cose.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm13', voce: 'marco', testo: "Le persone agiscono per ignoranza del bene: capirlo mi aiuta a non odiarle.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm14', voce: 'marco', testo: "Il presente è l'unica cosa che posso possedere o perdere: perciò lo custodisco.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm15', voce: 'marco', testo: "La fama dura poco, e anche chi ci ricorderà sarà presto dimenticato a sua volta.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm16', voce: 'marco', testo: "Sono nato per collaborare, come le mani, i piedi, le palpebre: agire contro gli altri è agire contro di me.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm17', voce: 'marco', testo: "Prima di ogni pensiero mi chiedo: a che cosa mi serve? Se non mi serve, lo lascio andare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm18', voce: 'marco', testo: "Rimango fermo come uno scoglio: le onde si infrangono, e poi l'acqua si calma.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm19', voce: 'marco', testo: "La vita è breve: il frutto migliore è un carattere buono e azioni fatte per il bene di tutti.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm20', voce: 'marco', testo: "Guardo le cose come stanno: quest'acqua è acqua, questo vestito è lana. Togliere il fumo è liberarsi.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm21', voce: 'marco', testo: "Se ciò che mi accade lascia intatto il mio carattere, la ferita è solo apparente.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm22', voce: 'marco', testo: "Adirarmi contro un fatto lo rende più grave. Guardo il fatto: quasi tutto il peso è nel mio pensiero.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm23', voce: 'marco', testo: "Comincio dalle piccole cose: un gesto gentile, una parola calma. La virtù è fatta di questo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm24', voce: 'marco', testo: "Ogni azione, anche la più piccola, la faccio bene: nessuna cosa è piccola per chi la fa con attenzione.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm25', voce: 'marco', testo: "Ciò che mi capita è alla portata della mia natura: se pesa, posso reggerlo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm26', voce: 'marco', testo: "Ogni sera dedico un pensiero a ciò che ho ricevuto di buono. È un modo di riposare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm27', voce: 'marco', testo: "Non aspetto la giornata perfetta: quella di oggi basta per esercitare la virtù.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm28', voce: 'marco', testo: "Ciò che il tempo porta via non è mai stato mio: mio è soltanto il momento.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm29', voce: 'marco', testo: "Ogni cosa è legata alle altre: guardando un albero vedo il sole, l'acqua, i secoli.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm30', voce: 'marco', testo: "La ragione è la mia cittadella: se la custodisco, nessuna tempesta la raggiunge.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm31', voce: 'marco', testo: "Quando mi alzo con fatica, ricordo per che cosa sono nato: per fare ciò che è umano.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm32', voce: 'marco', testo: "Non voglio essere lodato né temuto: voglio essere onesto e utile.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm33', voce: 'marco', testo: "Se qualcuno mi mostra che sbaglio, lo ringrazio: cerco la verità, e la verità aiuta sempre.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm34', voce: 'marco', testo: "Un giorno è già molto: se lo vivo bene, è una vita intera in piccolo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm35', voce: 'marco', testo: "Parlo di meno e ascolto di più: l'ascolto è già una forma di giustizia.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm36', voce: 'marco', testo: "Guardo le cose con gratitudine: ciò che sembra ordinario è ciò che manca di più quando viene a mancare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm37', voce: 'marco', testo: "Non posso scegliere ciò che accade: posso scegliere chi voglio essere mentre accade.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm38', voce: 'marco', testo: "La morte è un processo della natura, come la nascita: non c'è motivo di temerla più del vento.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm39', voce: 'marco', testo: "Ogni piccolo dispiacere si scioglie, se lo guardo con il tempo davanti: tra un anno, che peso avrà?", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm40', voce: 'marco', testo: "Se mi accorgo di essermi perso, torno. Tornare è già ricominciare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm41', voce: 'marco', testo: "Se un pensiero mi agita, lo guardo come si guarda un'onda: arriva, si alza, passa.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm42', voce: 'marco', testo: "Chi sbaglia non mi danneggia: il mio carattere resta quello di prima.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm43', voce: 'marco', testo: "Le cose scorrono come un fiume in piena: aggrapparsi non serve, serve imparare a stare a galla.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm44', voce: 'marco', testo: "Se ogni gesto, ogni parola, ogni pensiero potesse essere l'ultimo, resterebbe solo ciò che conta.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm45', voce: 'marco', testo: "Non discuto più su come dovrebbe essere una persona buona: cerco di esserlo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm46', voce: 'marco', testo: "Il miglior modo di difendersi da chi mi ha fatto un torto è non rassomigliargli.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm47', voce: 'marco', testo: "Siamo tutti cittadini di una stessa città: ciò che serve a uno serve a molti.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm48', voce: 'marco', testo: "Vivo bene dovunque mi trovi: anche a corte si può vivere bene, se si vuole.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm49', voce: 'marco', testo: "Quando la giornata è stata lunga, ricordo che bisogna anche riposarsi: la natura ha dato una misura a tutto.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm50', voce: 'marco', testo: "Se qualcuno mi corregge, accolgo la correzione come una cura, non come un'offesa.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm51', voce: 'marco', testo: "Amare anche chi sbaglia è la cosa più umana che io possa fare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm52', voce: 'marco', testo: "Sarò presto un ricordo, e chi mi ha offeso anche: perché dargli il mio tempo?", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm53', voce: 'marco', testo: "La parte di me che guida i giudizi resta intatta se non la cedo: è la mia sola fortezza.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm54', voce: 'marco', testo: "Il carattere migliore si riconosce da questo: passare la giornata senza agitarsi, senza intorpidirsi, senza recitare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm55', voce: 'marco', testo: "Ciò che lascia intatto il carattere lascia intatta anche la vita.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm56', voce: 'marco', testo: "Ognuno ha qualcosa da insegnarmi: comincio dal nonno, dalla madre, dai maestri.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm57', voce: 'marco', testo: "La retta ragione sa essere felice: è una capacità che allenata cresce.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm58', voce: 'marco', testo: "Le mie giornate sono piccole vite: quale voglio consegnare a stasera?", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm59', voce: 'marco', testo: "Non mi lamento del tempo che ho: mi chiedo che cosa ne faccio.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm60', voce: 'marco', testo: "Il cosmo è come una città: ogni parte ha il suo posto e il suo compito.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm61', voce: 'marco', testo: "Guardo con calma ciò che passa: le cose vengono e vanno, io resto con ciò che scelgo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm62', voce: 'marco', testo: "Non mi vergogno di ricominciare: ogni mattina è un'occasione di essere migliore di ieri.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm63', voce: 'marco', testo: "Se dimentico ciò che ho imparato, lo riprendo dall'inizio: non c'è fretta, c'è direzione.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm64', voce: 'marco', testo: "Il fatto è uno; le storie che gli aggiungo sono mie. Rimango sul fatto.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm65', voce: 'marco', testo: "Chi mi contraddice mi mostra un lato che non vedevo: lo ascolto.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm66', voce: 'marco', testo: "Vivo il tempo che ho come un ospite riconoscente, non come un creditore.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm67', voce: 'marco', testo: "Tra ciò che mi accade e ciò che faccio c'è uno spazio: è lì che sono libero.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
];

export const PENSIERI = [...PENSIERI_BASE, ...PENSIERI_3];
