// Pensieri da portare con te: formulazioni originali di idee stoiche, una per voce. Nessuna citazione dai libri.

export const PENSIERI = [
  { id: 'e01', voce: 'epitteto', testo: "Alcune cose dipendono da te, altre no. Comincia sempre da qui: qual è quale?", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e02', voce: 'epitteto', testo: "Non ti turbano le cose, ma i giudizi che ne dai. Cambia il giudizio, e la cosa peserà meno.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e03', voce: 'epitteto', testo: "Non pretendere che le cose vadano come vuoi. Vuoi che vadano come vanno, e starai sereno.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e04', voce: 'epitteto', testo: "Un'impressione non è un fatto. Prima di crederle, chiedile: sei vera?", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e05', voce: 'epitteto', testo: "Nessuno può ferirti senza il tuo consenso: ciò che ti ferisce è il giudizio che dai all'offesa.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e06', voce: 'epitteto', testo: "Il corpo, la reputazione, i beni: non sono davvero tuoi. Tuo è soltanto il modo in cui li usi.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e07', voce: 'epitteto', testo: "Ciò che perdi non è distrutto: è tornato a chi te l'aveva prestato. Ringrazia per il tempo che l'hai avuto.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e08', voce: 'epitteto', testo: "La vita è un banchetto: prendi con garbo ciò che ti passa davanti, e lascia passare ciò che non è ancora arrivato.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e09', voce: 'epitteto', testo: "Sei un attore in una parte scelta da altri, breve o lunga: recitala bene. Scegliere la parte non spetta a te.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e10', voce: 'epitteto', testo: "Prima di ogni impresa chiediti che cosa comporta. Chi sa a che cosa va incontro, non si lascia sorprendere.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e11', voce: 'epitteto', testo: "Il desiderio ti rende schiavo di ciò che desideri. Desidera poco, e sarai libero.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e12', voce: 'epitteto', testo: "Non sono le persone a offenderti, ma la tua idea di ciò che avrebbero dovuto fare.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e13', voce: 'epitteto', testo: "Fai ciò che è giusto senza contare gli applausi. Il valore sta nell'azione, non nel riconoscimento.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e14', voce: 'epitteto', testo: "Esercitati nelle piccole cose: una parola detta con calma, un desiderio lasciato andare. Si comincia da lì.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e15', voce: 'epitteto', testo: "Il filosofo non parla molto di ciò che sa. Lo mostra con ciò che fa.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e16', voce: 'epitteto', testo: "Se ti criticano, rispondi con calma: chi conoscesse il resto di te avrebbe ben altro da dire. E vai avanti.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e17', voce: 'epitteto', testo: "È libero solo chi è padrone di sé. Comincia dai desideri.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e18', voce: 'epitteto', testo: "Ciò che chiami sfortuna è quasi sempre una prova: chiediti che cosa ti chiede di imparare.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e19', voce: 'epitteto', testo: "Un ostacolo ti misura: mostra che cosa sei disposto a fare.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e20', voce: 'epitteto', testo: "Non lodare ciò che appartiene agli altri come se fosse anche tuo: la ricchezza, la bellezza, il talento sono doni loro.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e21', voce: 'epitteto', testo: "Quando ti manca qualcosa, chiediti a che prezzo l'avresti ottenuta: ogni cosa ha il suo prezzo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e22', voce: 'epitteto', testo: "Se vuoi migliorare, accetta di sembrare inesperto agli occhi degli altri.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e23', voce: 'epitteto', testo: "Non chiedere agli altri di essere diversi. Chiedi a te stesso di rispondere bene a come sono.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e24', voce: 'epitteto', testo: "Il tuo compito è tenere in ordine il giudizio. Il resto lo farà la vita.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e25', voce: 'epitteto', testo: "La calma non è l'assenza di eventi: è il modo in cui ti tieni in mezzo a essi.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e26', voce: 'epitteto', testo: "Chi ha imparato a lasciare andare ha ben poco da temere.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e27', voce: 'epitteto', testo: "La morte e l'esilio non sono terribili in sé: lo è l'opinione che ne abbiamo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e28', voce: 'epitteto', testo: "Prima di rispondere a un'offesa, guarda che cosa ti sta chiedendo: la tua calma o la tua rabbia?", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e29', voce: 'epitteto', testo: "Se ami una tazza, ricordati che è una tazza: quando si romperà, la tua serenità resterà intera.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e30', voce: 'epitteto', testo: "Il tempo che passi a lamentarti è tempo tolto a ciò che potresti fare.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e31', voce: 'epitteto', testo: "Un principio semplice, tenuto a portata di mano, vale più di cento discorsi: distingui ciò che dipende da te.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e32', voce: 'epitteto', testo: "Fai attenzione a ciò che ti occupa: ogni pensiero sprecato per ciò che è degli altri è una forza in meno per ciò che è tuo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e33', voce: 'epitteto', testo: "Non giudicare in fretta. Chi vede solo un pezzo, giudica soltanto un pezzo.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e34', voce: 'epitteto', testo: "Le difficoltà rivelano chi sei: non tremare, sono un allenamento.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e35', voce: 'epitteto', testo: "Sei responsabile della tua parte, non del risultato. Fai bene la prima.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e36', voce: 'epitteto', testo: "Se devi scegliere tra la comodità e il dovere, ricordati che cosa vorrai aver scelto a fine giornata.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e37', voce: 'epitteto', testo: "Cerca dentro ciò che ti serve: la pace dipende da te, e il luogo conta poco.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e38', voce: 'epitteto', testo: "Chi accetta di poter perdere ciò che non è suo, smette di temere gli altri.", fonte: { autore: 'Epitteto', opera: "Manuale" } },
  { id: 'e39', voce: 'epitteto', testo: "Comincia oggi. Il progresso non è un colpo di fortuna: è la somma di piccoli giorni.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 'e40', voce: 'epitteto', testo: "Ogni sera chiediti: che cosa ho fatto, che cosa ho tralasciato? Poi dormi.", fonte: { autore: 'Epitteto', opera: "Diatribe" } },
  { id: 's01', voce: 'seneca', testo: "Non abbiamo poco tempo: ne perdiamo molto. La vita è lunga, se sai come usarla.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's02', voce: 'seneca', testo: "Soffriamo più con l'immaginazione che nella realtà. Guarda ciò che c'è, prima di temere ciò che potrebbe esserci.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's03', voce: 'seneca', testo: "Ogni giorno è una piccola vita: cominciala bene e chiudila in pace.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's04', voce: 'seneca', testo: "Chi è dappertutto è altrove. Scegli un posto dove stare, e stai lì con tutto te stesso.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's05', voce: 'seneca', testo: "La vera povertà è il desiderio che non si ferma. Chi si accontenta è già ricco.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's06', voce: 'seneca', testo: "Il vento giova solo a chi ha scelto la meta. Decidi la rotta, poi affronta le onde.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's07', voce: 'seneca', testo: "L'ira è un breve furore che lascia lunghi rimpianti. Il suo rimedio è il tempo: aspetta.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's08', voce: 'seneca', testo: "Non scegliere un amico per ottenere qualcosa: sceglilo perché accanto a lui vuoi diventare migliore.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's09', voce: 'seneca', testo: "Vivi come se qualcuno ti guardasse: non per timore, ma per fare le cose come vorresti averle fatte.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's10', voce: 'seneca', testo: "Prima di condannare l'errore di un altro, chiediti quante volte l'hai commesso tu.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's11', voce: 'seneca', testo: "La morte non è un evento lontano: ci si avvicina un poco ogni giorno. Perciò vivi ora, con pienezza.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's12', voce: 'seneca', testo: "Smetti di temere ciò che è inevitabile. Prepara ciò che puoi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's13', voce: 'seneca', testo: "La fortuna può toglierti molto, ma non ciò che sei diventato.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's14', voce: 'seneca', testo: "Se una cosa ti pesa, chiediti se pesa per la cosa o per il modo in cui la sollevi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's15', voce: 'seneca', testo: "La cosa più preziosa che possiedi è il tuo tempo: donalo a chi lo merita.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's16', voce: 'seneca', testo: "Sopporta le fatiche: ti rendono più solido, come i venti rendono più salda la quercia.", fonte: { autore: 'Seneca', opera: "Sulla provvidenza" } },
  { id: 's17', voce: 'seneca', testo: "Non basta leggere molto: bisogna tornare spesso ai pochi pensieri che ti aiutano davvero.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's18', voce: 'seneca', testo: "Ritirati un poco in te stesso ogni giorno. Là dentro c'è più pace che in qualunque viaggio.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's19', voce: 'seneca', testo: "Non è il luogo a guarirti: porti te stesso ovunque. Cambia il modo di guardare, non il paesaggio.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's20', voce: 'seneca', testo: "Chi rimanda la vita a domani la perde oggi. Comincia da qualcosa di piccolo, adesso.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's21', voce: 'seneca', testo: "Fai il bene con piacere e senza contare i favori: il bene fatto è già il suo premio.", fonte: { autore: 'Seneca', opera: "Sui benefici" } },
  { id: 's22', voce: 'seneca', testo: "Le tue paure arrivano spesso prima della realtà. Lascia che arrivino dopo, e forse non arriveranno.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's23', voce: 'seneca', testo: "Ogni sera passa in rassegna la giornata, senza paura e senza indulgenza: è così che si impara a vivere.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's24', voce: 'seneca', testo: "Se sbagli, correggiti senza punirti. Il perdono che dai agli altri, concedilo anche a te.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's25', voce: 'seneca', testo: "Cerca di essere amico di te stesso: troverai in casa una buona compagnia.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's26', voce: 'seneca', testo: "Chi segue il proprio destino è accompagnato; chi vi si oppone è trascinato.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's27', voce: 'seneca', testo: "L'invidia è un conto fatto male: guarda ciò che hai prima di guardare ciò che manca.", fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" } },
  { id: 's28', voce: 'seneca', testo: "Una vita non si giudica dalla sua lunghezza, ma da come è stata vissuta.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's29', voce: 'seneca', testo: "Dorme bene chi ha la coscienza in ordine: comincia a ordinarla stasera.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's30', voce: 'seneca', testo: "Ciò che è davvero tuo non può esserti portato via. Custodisci quello.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's31', voce: 'seneca', testo: "Pensare al peggio con calma toglie alla sorpresa il suo potere.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's32', voce: 'seneca', testo: "Ogni fatica sostenuta oggi è una libertà in più domani.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's33', voce: 'seneca', testo: "La misura è amica della serenità: evita l'eccesso nel desiderio come nel timore.", fonte: { autore: 'Seneca', opera: "Sulla tranquillità dell'animo" } },
  { id: 's34', voce: 'seneca', testo: "Ascolta chi ti dice la verità, anche quando dispiace: ti risparmierà lunghi errori.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's35', voce: 'seneca', testo: "Chi si lamenta della brevità della vita ne ha sprecata molta. Non è tardi per cominciare a usarla.", fonte: { autore: 'Seneca', opera: "Sulla brevità della vita" } },
  { id: 's36', voce: 'seneca', testo: "Il saggio non nasconde le emozioni: le riconosce, e poi sceglie che cosa farne.", fonte: { autore: 'Seneca', opera: "Sull'ira" } },
  { id: 's37', voce: 'seneca', testo: "Pensa a chi vive con meno di te e con più serenità: che cosa sa, che tu non sai?", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's38', voce: 'seneca', testo: "Ciò che ci appartiene è come ciò che prendiamo a prestito: restituiscilo con garbo, quando sarà il momento.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's39', voce: 'seneca', testo: "Comincia l'anno, il mese, il giorno come se fosse il primo: hai il diritto di ricominciare quando vuoi.", fonte: { autore: 'Seneca', opera: "Lettere a Lucilio" } },
  { id: 's40', voce: 'seneca', testo: "Sii gentile con chi sbaglia: l'errore è la condizione di chi sta imparando.", fonte: { autore: 'Seneca', opera: "Sulla clemenza" } },
  { id: 'm01', voce: 'marco', testo: "Ciò che accade non entra nella mia mente: sono io a lasciarlo entrare, con il mio giudizio.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm02', voce: 'marco', testo: "Ogni mattina ricordo che incontrerò persone difficili: non per rancore, ma per essere preparato.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm03', voce: 'marco', testo: "La mia mente prende il colore dei pensieri che frequenta. Scelgo con cura a che cosa pensare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm04', voce: 'marco', testo: "Posso ritirarmi in me in qualsiasi momento: nessun luogo è più tranquillo della mia anima.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm05', voce: 'marco', testo: "Faccio soltanto ciò che è giusto e dico soltanto ciò che è vero: da qui comincia la mia libertà.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm06', voce: 'marco', testo: "La miglior risposta a chi mi offende è non diventare come lui.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm07', voce: 'marco', testo: "Guardo dall'alto le cose che mi agitano: da lassù sono molto più piccole.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm08', voce: 'marco', testo: "Tutto ciò che vedo cambierà: perché darmi tanta pena per ciò che passa?", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm09', voce: 'marco', testo: "Faccio ora ciò che ho tra le mani, come se fosse l'ultima cosa: con cura, con affetto, con giustizia.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm10', voce: 'marco', testo: "L'ostacolo diventa materia: ciò che si oppone al mio agire mi mostra dove esercitarmi.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm11', voce: 'marco', testo: "Del futuro non mi preoccupo: quando verrà, avrò le stesse armi che ho oggi, la ragione.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm12', voce: 'marco', testo: "Sono parte di un tutto: ciò che accade a me ha un posto nell'ordine delle cose.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm13', voce: 'marco', testo: "Le persone agiscono per ignoranza del bene: capirlo mi aiuta a non odiarle.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm14', voce: 'marco', testo: "Il presente è l'unica cosa che posso possedere o perdere: perciò lo custodisco.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm15', voce: 'marco', testo: "La fama dura poco, e anche chi ci ricorderà sarà presto dimenticato a sua volta.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm16', voce: 'marco', testo: "Sono nato per collaborare, come le mani, i piedi, le palpebre: agire contro gli altri è agire contro di me.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm17', voce: 'marco', testo: "Prima di ogni pensiero mi chiedo: a che cosa mi serve? Se non mi serve, lo lascio andare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm18', voce: 'marco', testo: "Rimango fermo come uno scoglio: le onde si infrangono, e poi l'acqua si calma.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm19', voce: 'marco', testo: "La vita è breve: il frutto migliore è un carattere buono e azioni fatte per il bene di tutti.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm20', voce: 'marco', testo: "Guardo le cose come stanno: quest'acqua è acqua, questo vestito è lana. Togliere il fumo è liberarsi.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm21', voce: 'marco', testo: "Se ciò che mi accade lascia intatto il mio carattere, la ferita è solo apparente.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm22', voce: 'marco', testo: "Adirarmi contro un fatto lo rende più grave. Guardo il fatto: quasi tutto il peso è nel mio pensiero.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm23', voce: 'marco', testo: "Comincio dalle piccole cose: un gesto gentile, una parola calma. La virtù è fatta di questo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm24', voce: 'marco', testo: "Ogni azione, anche la più piccola, la faccio bene: nessuna cosa è piccola per chi la fa con attenzione.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm25', voce: 'marco', testo: "Ciò che mi capita è alla portata della mia natura: se pesa, posso reggerlo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm26', voce: 'marco', testo: "Ogni sera dedico un pensiero a ciò che ho ricevuto di buono. È un modo di riposare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm27', voce: 'marco', testo: "Non aspetto la giornata perfetta: quella di oggi basta per esercitare la virtù.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm28', voce: 'marco', testo: "Ciò che il tempo porta via non è mai stato mio: mio è soltanto il momento.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm29', voce: 'marco', testo: "Ogni cosa è legata alle altre: guardando un albero vedo il sole, l'acqua, i secoli.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm30', voce: 'marco', testo: "La ragione è la mia cittadella: se la custodisco, nessuna tempesta la raggiunge.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm31', voce: 'marco', testo: "Quando mi alzo con fatica, ricordo per che cosa sono nato: per fare ciò che è umano.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm32', voce: 'marco', testo: "Non voglio essere lodato né temuto: voglio essere onesto e utile.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm33', voce: 'marco', testo: "Se qualcuno mi mostra che sbaglio, lo ringrazio: cerco la verità, e la verità aiuta sempre.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm34', voce: 'marco', testo: "Un giorno è già molto: se lo vivo bene, è una vita intera in piccolo.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm35', voce: 'marco', testo: "Parlo di meno e ascolto di più: l'ascolto è già una forma di giustizia.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm36', voce: 'marco', testo: "Guardo le cose con gratitudine: ciò che sembra ordinario è ciò che manca di più quando viene a mancare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm37', voce: 'marco', testo: "Non posso scegliere ciò che accade: posso scegliere chi voglio essere mentre accade.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm38', voce: 'marco', testo: "La morte è un processo della natura, come la nascita: non c'è motivo di temerla più del vento.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm39', voce: 'marco', testo: "Ogni piccolo dispiacere si scioglie, se lo guardo con il tempo davanti: tra un anno, che peso avrà?", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
  { id: 'm40', voce: 'marco', testo: "Se mi accorgo di essermi perso, torno. Tornare è già ricominciare.", fonte: { autore: 'Marco Aurelio', opera: "A se stesso" } },
];
