// I modelli del quaderno e le loro domande-guida. Le domande riprendono pratiche stoiche:
// la preparazione del mattino (Marco Aurelio, II, 1), l'esame della sera (Seneca, Sull'ira, III, 36),
// il distinguere ciò che dipende da noi (Epitteto). «domande» sono quelle proposte all'inizio, «altre» le alternative.

const modello = (id, titolo, sotto, intro, domande, altre) => ({ id, titolo, sotto, intro, domande, pool: [...domande, ...altre] });

// La distinzione di fondo dello stoicismo (Epitteto, Manuale 1): è presente in ogni pagina e non si cambia.
export const FISSI = {
  titolo: 'Sempre con te: la dicotomia del controllo',
  intro: 'Alcune cose dipendono da noi, altre no. Da questa distinzione comincia tutto lo stoicismo: in ogni pagina puoi tornarci.',
  campi: [
    'Che cosa dipende da me?',
    'Che cosa non dipende da me?',
  ],
};

export const MODELLI = [
  modello(
    'mattina',
    'Mattina',
    'Prepararsi alla giornata',
    'Marco Aurelio cominciava la giornata dicendosi che cosa avrebbe incontrato e come voleva affrontarlo. Tre domande, pochi minuti.',
    [
      'Che cosa potrebbe mettermi alla prova oggi?',
      'Come voglio essere quando succede?',
      'Qual è il mio compito più importante di oggi?',
    ],
    [
      'Che cosa dipende da me, oggi, e che cosa no?',
      'Con quale persona voglio essere più paziente?',
      'Che cosa posso lasciar andare fin da adesso?',
      'Quale piccolo gesto renderà buona questa giornata?',
      'Che cosa temo di affrontare, e qual è il primo passo?',
      'Chi posso aiutare oggi?',
      'Quale qualità voglio esercitare oggi: pazienza, chiarezza, coraggio, gentilezza?',
      'Chi incontrerò oggi che potrebbe mettere alla prova la mia pazienza?',
      'Quale mia abitudine rischia oggi di trascinarmi?',
      'Che cosa vorrei aver fatto, stasera, che valga la pena?',
      'Se oggi potessi fare una cosa sola per il bene di qualcuno, quale sarebbe?',
      'Quale desiderio voglio tenere a bada oggi?',
      'Quale paura voglio guardare in faccia oggi?',
      'Come voglio rispondere se qualcuno mi tratterà male?',
      'Che cosa posso fare meglio di ieri, anche di poco?',
      'Di che cosa voglio prendermi cura per prima cosa?',
      'Quale impressione voglio esaminare prima di crederle?',
      'Che cosa vorrei ricordare, stasera, di questa giornata?',
      'Dove rischio di recitare una parte che non mi somiglia?',
      'Quale compito rimando da troppo, e posso cominciare oggi?',
      'Con chi voglio essere più gentile?',
      'Quale imprevisto posso già immaginare, per non farmi cogliere di sorpresa?',
      'Che cosa mi basta per stare bene oggi?',
      'Che cosa posso lasciare al tempo, senza affannarmi?',
      'In quale momento della giornata voglio fermarmi a respirare?',
      'A chi devo una parola sincera?',
      'Quale piccolo piacere posso godermi con misura?',
      'Che cosa farebbe, oggi, una persona che stimo?',
      'Quale parte del mio lavoro merita più attenzione?',
      'Che cosa posso dare, oggi, senza aspettarmi niente in cambio?',
      'Che cosa temo che gli altri pensino di me, e quanto mi riguarda davvero?',
      'Quale opinione altrui devo smettere di inseguire?',
      'Quale cosa che non dipende da me devo accettare oggi, senza discuterla?',
      'Che cosa posso preparare adesso, per affrontare meglio la giornata?',
      'Quale parola gentile posso dire a qualcuno, appena lo incontro?',
      'Che cosa mi serve per cominciare senza fretta?',
      'Quale scelta di oggi voglio prendere con calma, e non d\'impulso?',
      'Quale piccola fatica accetto volentieri, perché mi fa crescere?',
      'Come voglio trattare me stesso, oggi?',
    ],
  ),
  modello(
    'sera',
    'Sera',
    'Esaminare la giornata',
    'Seneca ogni sera ripercorreva la giornata, senza nascondersi nulla e senza punirsi. Tre domande, con calma.',
    [
      'Che cosa ho fatto bene oggi?',
      'Dove ho sbagliato, o sono stato diverso da come volevo?',
      'Che cosa farò diversamente, se si ripresenta?',
    ],
    [
      'Che cosa mi ha agitato oggi, e dipendeva da me?',
      'Quale impressione ho creduto troppo in fretta?',
      'Con chi sono stato impaziente o ingiusto?',
      'Per che cosa sono grato oggi?',
      'Che cosa ho imparato oggi?',
      'In quale momento sono stato davvero presente?',
      'Che cosa ho rimandato, e qual è il primo passo per domani?',
      'Che cosa mi ha reso inquieto oggi, e che cosa ne ho fatto?',
      'Ho detto qualcosa di cui mi pento? Che cosa direi ora?',
      'Chi ho aiutato oggi, anche in piccolo?',
      'Che cosa ho fatto soltanto per essere approvato?',
      'Quando mi sono lasciato trascinare da un\'impressione?',
      'Dove sono stato onesto, anche quando costava?',
      'Che cosa ho evitato per paura?',
      'Quale desiderio mi ha agitato più del necessario?',
      'Che cosa dipendeva da me, e l\'ho fatto?',
      'Che cosa dipendeva dagli altri, e ho continuato a rincorrerlo?',
      'Quale gesto della giornata rifarei volentieri?',
      'Quale gesto vorrei correggere?',
      'Chi vorrei ringraziare, e ancora non l\'ho fatto?',
      'Che cosa ho lasciato in sospeso, e qual è il primo passo per domani?',
      'In quale momento ho perso la pazienza, e che cosa l\'ha provocata?',
      'Che cosa mi ha dato serenità oggi?',
      'Che cosa lascio andare, prima di dormire?',
      'Con che voce mi sono parlato oggi: severa o amica?',
      'Che cosa ho imparato da una persona difficile?',
      'Ho vissuto qualcosa con attenzione piena? Che cosa?',
      'Quale mia abitudine voglio cambiare, e come comincio?',
      'Se domani fosse uguale a oggi, sarei soddisfatto? Che cosa cambierei?',
      'Che cosa ho fatto per gli altri, oltre che per me?',
      'Quale timore di stamattina si è rivelato più grande della realtà?',
      'Qual è la cosa più semplice, bella o utile che è successa oggi?',
      'Quale scelta di oggi rifarei allo stesso modo?',
      'Che cosa mi ha tolto pace, e che cosa posso fare per riaverla?',
      'In quale momento ho scelto la calma?',
      'Che cosa ho detto o fatto che ha aiutato qualcuno?',
      'Che cosa vorrei dire a me stesso, prima di dormire?',
      'Che cosa ho lasciato che mi disturbasse più del dovuto?',
      'Quale persona mi ha fatto un dono oggi, anche senza saperlo?',
    ],
  ),
  modello(
    'lettera',
    'Lettera',
    'Scrivere a se stessi come a un amico',
    'Le Lettere a Lucilio di Seneca sono lettere a un amico, per aiutarlo a vivere meglio. Prova a scrivere a te stesso con lo stesso tono.',
    ['Scrivi a te stesso come scriveresti a un amico che vive ciò che stai vivendo tu.'],
    [
      'Che cosa diresti a un amico che si sente in colpa per ciò che è successo?',
      'Che cosa ricorderesti a un amico di ciò che dipende da lui?',
      'Che cosa vorresti che ti dicesse, adesso, un amico saggio?',
      'Che cosa consiglieresti a un amico che ha paura di ciò che verrà?',
      'Che cosa diresti a un amico stanco, che pensa di non farcela?',
      'Che cosa diresti a un amico che è stanco di ricominciare?',
      'Che cosa diresti a un amico che ha fatto un errore e non riesce a perdonarsi?',
      'Che cosa diresti a un amico che teme di non essere all\'altezza?',
      'Che cosa diresti a un amico che si sente solo?',
      'Che cosa diresti a un amico che ha perso qualcuno o qualcosa di importante?',
      'Che cosa diresti a un amico che è arrabbiato con un collega?',
      'Che cosa diresti a un amico che ha paura di una decisione?',
      'Che cosa diresti a un amico che si confronta sempre con gli altri?',
      'Che cosa diresti a un amico che non riesce a dormire?',
      'Che cosa diresti a un amico che è sopraffatto dagli impegni?',
      'Che cosa diresti a un amico che ha deluso qualcuno?',
      'Che cosa diresti a un amico che prova invidia?',
      'Che cosa diresti a un amico che rimanda da mesi qualcosa?',
      'Che cosa diresti a un amico che si sente in ritardo rispetto alla vita?',
      'Che cosa diresti a un amico che teme il giudizio degli altri?',
      'Che cosa diresti a un amico che soffre per un torto ricevuto?',
      'Che cosa diresti a un amico che ha perso fiducia in se stesso?',
      'Che cosa diresti a un amico che non sa che cosa vuole?',
      'Che cosa diresti a un amico che si preoccupa per il futuro?',
      'Che cosa diresti a un amico che si sente in colpa per aver riposato?',
      'Che cosa diresti a un amico che ha perso la pazienza con chi ama?',
      'Che cosa diresti a un amico che ha bisogno di ricominciare?',
      'Scrivi a te stesso guardando la tua vita dall\'alto: che cosa vedi, da lassù?',
      'Che cosa vorresti che un amico saggio ti dicesse, guardando ciò che stai vivendo con distacco?',
      'Che cosa diresti a un amico che sta per affrontare una prova?',
      'Che cosa diresti a un amico che non riesce a lasciar andare il passato?',
      'Che cosa diresti a un amico che è troppo severo con se stesso?',
      'Che cosa diresti a un amico che teme di aver perso tempo?',
      'Che cosa diresti a un amico che si sente ingiustamente trattato?',
      'Che cosa diresti a un amico che non vede via d\'uscita?',
      'Che cosa diresti a un amico che ha appena ricominciato da zero?',
    ],
  ),
  modello(
    'libero',
    'Pagina libera',
    'Scrivere quello che vuoi',
    'Uno spazio senza domande, per annotare un pensiero, un ricordo o una frase da tenere.',
    [],
    [],
  ),
];
