// Pagine di studio della Fase 3, lotto 2 (17 in più, per arrivare a 60). Stessi tipi di blocco di studio.js.
// Testi originali: le idee sono degli antichi, le parole sono nostre.

export const PAGINE_STUDIO_3B = [
  {
    id: 'la-premeditazione-dei-mali',
    titolo: 'La premeditazione dei mali',
    sotto: 'Immaginare in anticipo ciò che si teme, per affrontarlo con più calma.',
    blocchi: [
      { t: 'p', x: `Tra gli esercizi più caratteristici degli stoici c'è la **premeditazione dei mali**: immaginare, con calma e con metodo, che cosa potrebbe andare storto. Seneca la raccomanda spesso. Non serve a farsi paura: serve a **togliere alla sorpresa la sua forza**.` },
      { t: 'h', x: 'Perché funziona' },
      { t: 'p', x: `Il male che arriva all'improvviso ci travolge due volte: per quello che è, e perché non ci siamo preparati. Chi lo ha già guardato in anticipo ha un piano, ha misurato la sua forza e sa che ne può uscire. La paura vaga si trasforma in una difficoltà con un nome.` },
      { t: 'h', x: 'I passi' },
      { t: 'passi', x: [
        `**Scegli un timore preciso.** Non «tutto andrà male», ma «il colloquio potrebbe andare male».`,
        `**Immaginalo con calma.** Guarda la scena con pochi dettagli, senza drammatizzare.`,
        `**Chiediti che cosa faresti.** Cerca i primi gesti concreti.`,
        `**Guarda che cosa resta.** Le persone, le capacità, la libertà di rispondere.`,
        `**Dagli una misura.** Quanto sarebbe grave, davvero?`,
      ] },
      { t: 'h', x: 'Un avvertimento' },
      { t: 'p', x: `Se un pensiero ti prende troppo, fermati: l'esercizio non deve diventare rimuginio. Gli stoici lo facevano con serenità e per poco. Quando la paura sale, torna al presente e riprendi un'altra volta.` },
      { t: 'azione', x: 'Esercizio: Prepararsi al peggio', az: 'esercizio', id: 'prepararsi-al-peggio' },
      { t: 'azione', x: 'Meditazione: Guardare il peggio con calma', az: 'meditazione', id: 'guardare-il-peggio' },
    ],
  },
  {
    id: 'il-ricordo-della-fine',
    titolo: 'Il ricordo della fine',
    sotto: 'Perché gli stoici pensavano alla morte, e che cosa ne ricavavano per vivere.',
    blocchi: [
      { t: 'p', x: `Gli stoici pensavano alla morte spesso, e con serenità. Epitteto invita a tenerla davanti agli occhi ogni giorno, e Marco Aurelio se la ricorda di continuo. Non lo fanno per tristezza: la considerano un modo di **mettere le cose nella giusta misura**.` },
      { t: 'h', x: 'Che cosa dà questo pensiero' },
      { t: 'lista', x: [
        `**Le proporzioni.** Ciò che ci sembrava enorme, di fronte alla fine, si riduce.`,
        `**Il presente.** Se il tempo è limitato, non si spreca in rancori e rinvii.`,
        `**La gratitudine.** Ciò che ci è dato non è dovuto: è un dono.`,
        `**Meno paura.** Ciò che si guarda spesso, a poco a poco, spaventa meno.`,
      ] },
      { t: 'h', x: 'Che cosa non è' },
      { t: 'p', x: `Non è pessimismo né desiderio di morire. Gli stoici amavano la vita e la volevano vivere bene. Il pensiero della fine serve a **scegliere meglio come viverla**. Se ti pesa o ti turba, puoi lasciarlo per un altro momento: nessuna pratica va forzata.` },
      { t: 'azione', x: 'Il tempo e la morte', az: 'studio', id: 'il-tempo-la-morte' },
      { t: 'azione', x: 'Esercizio: Come se fosse l’ultimo', az: 'esercizio', id: 'come-se-fosse-l-ultimo' },
      { t: 'azione', x: 'Meditazione: Il tempo che hai', az: 'meditazione', id: 'il-tempo-che-hai' },
    ],
  },
  {
    id: 'accettare-cio-che-accade',
    titolo: 'Accettare ciò che accade',
    sotto: 'Un’accettazione attiva: riconoscere i fatti per poter agire.',
    blocchi: [
      { t: 'p', x: `Gli stoici chiedono di **accogliere ciò che accade**, e questo si presta a fraintendimenti. Non chiedono di essere passivi, di subire ingiustizie o di dire che va tutto bene. Chiedono di riconoscere i fatti per quello che sono, senza lottare contro la realtà, per poi decidere che cosa fare.` },
      { t: 'h', x: 'Due tempi' },
      { t: 'lista', x: [
        `**Prima, accettare il fatto.** È successo, è così, non posso cambiare il passato.`,
        `**Poi, agire nel presente.** Che cosa posso fare, da qui, con ciò che dipende da me?`,
      ] },
      { t: 'h', x: 'Una frase del maestro' },
      { t: 'p', x: `Epitteto invita a non pretendere che le cose vadano come vogliamo, ma a volere che vadano come vanno. Cleante, nel suo inno, si dice pronto a seguire senza esitazione ciò che il destino dispone. Sono due modi di dire la stessa cosa: la pace nasce quando smettiamo di litigare con la realtà.` },
      { t: 'nota', x: `Accettare non vuol dire approvare. Puoi accettare un fatto (una malattia, un lutto, un torto subito) e allo stesso tempo lavorare per cambiare ciò che si può cambiare.` },
      { t: 'azione', x: 'Esercizio: La brocca che si rompe', az: 'esercizio', id: 'la-brocca-che-si-rompe' },
      { t: 'azione', x: 'Esercizio: Il fiume degli eventi', az: 'esercizio', id: 'il-fiume-degli-eventi' },
    ],
  },
  {
    id: 'la-tranquillita-dell-animo',
    titolo: 'La tranquillità dell’animo',
    sotto: 'La meta degli stoici: una serenità che non dipende dagli eventi.',
    blocchi: [
      { t: 'p', x: `Seneca dedicò un intero scritto alla **tranquillità dell'animo**, in risposta a un amico che si sentiva instabile e insoddisfatto. La tranquillità, per lui, non è una vita senza scosse, ma una **stabilità interiore** che permette di attraversarle.` },
      { t: 'h', x: 'Che cosa la disturba' },
      { t: 'lista', x: [
        `**Il continuo cambiare rotta:** cominciare cento cose e non finirne una.`,
        `**Il desiderare troppo:** ogni cosa ottenuta ne fa venire in mente un'altra.`,
        `**Il paragone con gli altri:** guardare chi ha di più.`,
        `**L'occupazione senza senso:** correre senza sapere dove.`,
      ] },
      { t: 'h', x: 'Che cosa la sostiene' },
      { t: 'lista', x: [
        `**Poche scelte, e stabili.** Sapere che cosa si vuole fare della propria vita.`,
        `**Un ritmo.** Alternare attività e riposo, compagnia e solitudine.`,
        `**Amicizie buone.** Persone con cui parlare del vero.`,
        `**Semplicità.** Limitare le cose che ci possiedono.`,
      ] },
      { t: 'p', x: `Seneca non promette una serenità perfetta. Invita a ritrovarla, ogni volta che si perde, con gesti semplici e ripetuti.` },
      { t: 'azione', x: 'Meditazione: La calma della sera', az: 'meditazione', id: 'la-calma-della-sera' },
      { t: 'azione', x: 'Esercizio: Quanto basta', az: 'esercizio', id: 'quanto-basta' },
    ],
  },
  {
    id: 'il-progresso-e-il-sapiente',
    titolo: 'Il progresso e il sapiente',
    sotto: 'Nessuno è perfetto: gli stoici parlano di chi si sta esercitando.',
    blocchi: [
      { t: 'p', x: `Gli stoici descrivevano un ideale, il **sapiente**: una persona che vive sempre secondo virtù, senza passioni che la turbino. Ammettevano però che è una figura rarissima, forse mai esistita. Quasi tutti siamo invece **in cammino**, e a chi si esercita danno un nome: chi fa progressi.` },
      { t: 'h', x: 'Che cosa vuol dire fare progressi' },
      { t: 'lista', x: [
        `**Accorgersi prima.** Vedere che ci si sta arrabbiando mentre accade, e non solo dopo.`,
        `**Recuperare prima.** Tornare al centro in meno tempo.`,
        `**Ripetere meno gli stessi errori,** o ripeterli con meno danni.`,
        `**Essere più gentili** con sé e con gli altri.`,
      ] },
      { t: 'h', x: 'Una misura umana' },
      { t: 'p', x: `I progressi si vedono di rado da un giorno all'altro: si vedono su mesi. Per questo giova un quaderno, dove segnare di tanto in tanto come è andata. Gli stoici stessi tornavano sugli stessi esercizi per tutta la vita, senza vergogna.` },
      { t: 'nota', x: `Se ti senti indietro, ricordati di Seneca: scriveva agli amici di essere ancora un principiante. Nessuno arriva. Si continua.` },
      { t: 'azione', x: 'Il quaderno: modello Sera', az: 'studio', id: 'scrivere-per-pensare' },
      { t: 'azione', x: 'Esercizio: Esame della sera', az: 'esercizio', id: 'esame-della-sera' },
    ],
  },
  {
    id: 'la-parte-guida',
    titolo: 'La parte guida',
    sotto: 'Il centro di comando interiore: dove nascono i giudizi e le scelte.',
    blocchi: [
      { t: 'p', x: `Gli stoici chiamavano **parte guida** (in greco *hegemonikón*) il centro della nostra vita interiore: ciò che riceve le impressioni, le giudica e decide come reagire. È la sede della ragione in noi.` },
      { t: 'h', x: 'Perché è importante' },
      { t: 'p', x: `Tutto ciò che accade fuori passa da qui. Il corpo può ammalarsi, le circostanze cambiare, le persone deluderci: la parte guida resta il luogo in cui decidiamo come stare. Marco Aurelio la immagina come una **cittadella** che nessuno può conquistare se non le apriamo la porta.` },
      { t: 'h', x: 'Come curarla' },
      { t: 'lista', x: [
        `**Vigilare** sui pensieri che ci attraversano.`,
        `**Non lasciarla sola** nei momenti di agitazione: fermarsi e respirare.`,
        `**Nutrirla** di buone letture, buone conversazioni, buoni esempi.`,
        `**Riposarla,** perché anche la ragione si stanca.`,
      ] },
      { t: 'azione', x: 'Esercizio: Il rifugio dentro', az: 'esercizio', id: 'il-rifugio-dentro' },
      { t: 'azione', x: 'Meditazione: Il rifugio interiore', az: 'meditazione', id: 'il-rifugio-interiore' },
    ],
  },
  {
    id: 'i-doveri-e-i-ruoli',
    titolo: 'I doveri e i ruoli',
    sotto: 'Come gli stoici decidevano che cosa fare: guardando le proprie relazioni.',
    blocchi: [
      { t: 'p', x: `Nel decidere che cosa fare, gli stoici non partivano dai desideri, ma dai **ruoli**. Siamo figli, genitori, amici, cittadini, colleghi: ciascuno di questi ruoli comporta dei **doveri**, cioè azioni convenienti. Epitteto insiste: se sai che ruolo hai, sai che cosa ti compete.` },
      { t: 'h', x: 'Un esempio semplice' },
      { t: 'p', x: `Un genitore può non amare sempre il proprio figlio, in una giornata difficile, ma sa che un genitore accudisce. Non dipende dal sentimento: dipende dal ruolo. Così si trova una direzione anche quando le emozioni sono confuse.` },
      { t: 'h', x: 'I ruoli che abbiamo' },
      { t: 'lista', x: [
        `**Quelli ricevuti:** figlio, fratello, cittadino.`,
        `**Quelli scelti:** amico, compagno, collega, volontario.`,
        `**Quello di essere umano:** verso chiunque incontriamo.`,
      ] },
      { t: 'p', x: `Quando i ruoli sembrano in conflitto (il lavoro contro la famiglia), gli stoici invitano a guardare la giustizia: che cosa devo, in questo momento, a chi?` },
      { t: 'azione', x: 'Esercizio: La lista dei doveri', az: 'esercizio', id: 'la-lista-dei-doveri' },
      { t: 'azione', x: 'Esercizio: La parte che recito', az: 'esercizio', id: 'la-parte-che-recito' },
      { t: 'azione', x: 'Panezio e le quattro maschere', az: 'studio', id: 'panezio' },
    ],
  },
  {
    id: 'indifferenti-e-preferibili',
    titolo: 'Indifferenti e preferibili',
    sotto: 'Salute, denaro, fama: si possono desiderare, ma non sono il bene.',
    blocchi: [
      { t: 'p', x: `Una delle idee più fraintese dello stoicismo è quella degli **indifferenti**. Per gli stoici, salute, ricchezza, reputazione, piacere, e i loro contrari, non sono né bene né male in sé: dipende da come li usiamo. Il vero bene è la virtù.` },
      { t: 'h', x: 'Preferibili e da evitare' },
      { t: 'p', x: `Attenzione: indifferente non vuol dire irrilevante. Gli stoici distinguevano gli indifferenti **preferibili** (salute, amici, una casa) da quelli da **evitare** (malattia, povertà, solitudine). È naturale preferire i primi. Solo, non se ne fa dipendere la propria vita buona.` },
      { t: 'h', x: 'Che cosa cambia' },
      { t: 'lista', x: [
        `Puoi cercare la salute, e restare in pace se la perdi.`,
        `Puoi lavorare per un guadagno, senza farne il tuo valore.`,
        `Puoi desiderare la stima degli altri, ma senza vendere la tua onestà.`,
      ] },
      { t: 'nota', x: `Questo è un modo per non diventare schiavi delle cose. Non è un invito a farne a meno.` },
      { t: 'azione', x: 'Le quattro virtù', az: 'studio', id: 'le-quattro-virtu' },
      { t: 'azione', x: 'Esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'l-esame-di-coscienza',
    titolo: 'L’esame di coscienza serale',
    sotto: 'Come rivedere la giornata come faceva Seneca, senza sensi di colpa.',
    blocchi: [
      { t: 'p', x: `Seneca racconta di rivedere ogni sera la giornata, in silenzio, quando la lampada era spenta e la moglie taceva. Guardava ogni cosa senza sconti e senza punizioni: riconosceva gli errori, decideva come evitarli e si perdonava. È uno degli esercizi più antichi e più semplici.` },
      { t: 'h', x: 'Tre domande' },
      { t: 'passi', x: [
        `**Che cosa ho fatto bene?** Anche una piccola cosa.`,
        `**Dove ho sbagliato, o potevo fare meglio?** Senza giudicarti.`,
        `**Che cosa farò diversamente domani?** Una cosa sola.`,
      ] },
      { t: 'h', x: 'La differenza dal senso di colpa' },
      { t: 'p', x: `Il senso di colpa guarda indietro e punisce. L'esame guarda avanti e corregge. Seneca chiude con una frase gentile: ti perdono, ma stai attento la prossima volta. Il perdono a se stessi rende possibile il cambiamento.` },
      { t: 'azione', x: 'Esercizio: La sera in un minuto', az: 'esercizio', id: 'la-sera-in-un-minuto' },
      { t: 'azione', x: 'Meditazione: Esame della sera', az: 'meditazione', id: 'esame-della-sera-guidato' },
    ],
  },
  {
    id: 'il-perdono-e-la-clemenza',
    titolo: 'Il perdono e la clemenza',
    sotto: 'Come trattare chi sbaglia: con fermezza e con benevolenza.',
    blocchi: [
      { t: 'p', x: `Seneca scrisse un trattato sulla **clemenza**, dedicato al giovane Nerone: un invito a governare senza crudeltà. Ne vengono idee utili anche per la vita di tutti i giorni: la clemenza è la capacità di **non essere più duri del necessario** con chi ha sbagliato.` },
      { t: 'h', x: 'Clemenza non è debolezza' },
      { t: 'p', x: `Gli stoici distinguono il perdono dalla condiscendenza. La clemenza non cancella l'errore né la conseguenza: sceglie una misura giusta, senza rabbia. Chi è clemente resta fermo sui principi ma ha pietà della persona.` },
      { t: 'h', x: 'Perché conviene' },
      { t: 'lista', x: [
        `Chi sbaglia spesso è ignorante o ferito: la durezza peggiora le cose.`,
        `Chi è duro è a sua volta prigioniero della rabbia.`,
        `Un giorno saremo noi ad aver bisogno di clemenza.`,
      ] },
      { t: 'p', x: `Vale anche per se stessi: essere clementi con i propri errori è il primo passo per correggerli.` },
      { t: 'azione', x: "L'ira secondo Seneca", az: 'studio', id: 'l-ira-secondo-seneca' },
      { t: 'azione', x: 'Esercizio: Per ora ti perdono', az: 'esercizio', id: 'ti-perdono-per-ora' },
    ],
  },
  {
    id: 'il-corpo-e-la-malattia',
    titolo: 'Il corpo e la malattia',
    sotto: 'Come gli stoici guardavano la salute, la fatica e la sofferenza fisica.',
    blocchi: [
      { t: 'p', x: `Gli stoici sapevano che il corpo può ammalarsi, e non lo negavano. Epitteto, che secondo la tradizione era zoppo, ricorda che il corpo può essere impedito senza che la nostra scelta lo sia. Seneca, che soffrì a lungo di disturbi respiratori, scrive di malattia con esperienza diretta.` },
      { t: 'h', x: 'Due cose distinte' },
      { t: 'lista', x: [
        `**Il fatto fisico:** la malattia, il dolore, la stanchezza. Vanno curati, con i mezzi della medicina.`,
        `**Il giudizio su di esso:** «è una punizione», «non ce la faccio», «sono finito». Quello si può esaminare.`,
      ] },
      { t: 'h', x: 'Che cosa aiuta' },
      { t: 'p', x: `Gli stoici non promettono di eliminare il dolore. Suggeriscono di **non aggiungere sofferenza alla sofferenza**: evitare il catastrofismo, restare nel presente, chiedere aiuto, farsi curare. Il pensiero filosofico è un compagno della cura, mai un suo sostituto.` },
      { t: 'nota', x: `Questa pagina è una riflessione, non un consiglio medico. Per qualsiasi problema di salute, fisico o psicologico, rivolgiti a un medico o a un professionista.` },
      { t: 'azione', x: 'Il dolore e la perdita', az: 'studio', id: 'il-dolore-e-la-perdita' },
      { t: 'azione', x: 'Esercizio: Il peggio, misurato', az: 'esercizio', id: 'il-peggio-misurato' },
    ],
  },
  {
    id: 'il-denaro-e-la-ricchezza',
    titolo: 'Il denaro e la ricchezza',
    sotto: 'Un rapporto sereno con ciò che si possiede.',
    blocchi: [
      { t: 'p', x: `Seneca era ricco, e i suoi critici glielo rimproveravano. Lui rispondeva che il denaro non è un male: lo è l'attaccamento. Il saggio, diceva, tiene la ricchezza in casa e non nel cuore.` },
      { t: 'h', x: 'Le idee di base' },
      { t: 'lista', x: [
        `**Il denaro è un indifferente preferibile:** utile, ma non decide il valore di una vita.`,
        `**Si è poveri per il desiderio, non per il conto in banca.** Chi vuole sempre di più è povero anche con molto.`,
        `**Una misura.** Ciò che basta a stare bene è meno di quanto pensiamo.`,
        `**Un uso.** Il denaro serve a fare del bene, per sé e per gli altri.`,
      ] },
      { t: 'h', x: 'Un esercizio antico' },
      { t: 'p', x: `Seneca suggeriva di provare, ogni tanto, alcuni giorni di vita semplice: pasti poveri, vestiti modesti. Serve a scoprire che si può stare con poco, e a perdere la paura di perdere. Fallo con serenità e per poco.` },
      { t: 'azione', x: 'Esercizio: Quanto basta', az: 'esercizio', id: 'quanto-basta' },
      { t: 'azione', x: 'Esercizio: Il rimedio dell’abitudine', az: 'esercizio', id: 'il-rimedio-dell-abitudine' },
    ],
  },
  {
    id: 'la-fama-e-il-giudizio-degli-altri',
    titolo: 'La fama e il giudizio degli altri',
    sotto: 'Che cosa fare quando il parere altrui pesa troppo.',
    blocchi: [
      { t: 'p', x: `Uno dei pesi più comuni è il **giudizio degli altri**: che cosa penseranno, che cosa dicono di me. Marco Aurelio, imperatore e quindi sotto gli occhi di tutti, riflette spesso su quanto la fama sia fragile e la memoria breve.` },
      { t: 'h', x: 'Tre osservazioni' },
      { t: 'lista', x: [
        `**Il giudizio altrui non dipende da noi.** Possiamo agire bene, e ricevere critiche lo stesso.`,
        `**Chi giudica spesso non sa.** Parla con le sue idee e i suoi timori.`,
        `**La fama passa.** Chi ci loda oggi domani ci dimentica, e viceversa.`,
      ] },
      { t: 'h', x: 'Che cosa fare' },
      { t: 'p', x: `Non serve disinteressarsi degli altri: serve **scegliere chi ascoltare**. Se una critica è vera, è un aiuto. Se è falsa, puoi lasciarla. Il criterio è sempre lo stesso: mi aiuta a essere migliore?` },
      { t: 'azione', x: 'Esercizio: Lodi e biasimi', az: 'esercizio', id: 'lodi-e-biasimi' },
      { t: 'azione', x: 'Esercizio: Accogli la correzione', az: 'esercizio', id: 'accogli-la-correzione' },
    ],
  },
  {
    id: 'la-solitudine-e-la-compagnia',
    titolo: 'La solitudine e la compagnia',
    sotto: 'Stare bene da soli e stare bene con gli altri: due arti che si aiutano.',
    blocchi: [
      { t: 'p', x: `Seneca consiglia due cose che sembrano opposte: frequentare buoni amici e sapersi ritirare in se stessi. Sono in realtà due lati dello stesso equilibrio. Chi non sa stare solo cerca gli altri per riempire un vuoto. Chi non sa stare con gli altri si chiude per difendersi.` },
      { t: 'h', x: 'La solitudine che fa bene' },
      { t: 'lista', x: [
        `**Scelta,** e non subita.`,
        `**Breve** e con uno scopo: pensare, leggere, riposare.`,
        `**Con un ritorno:** si torna dagli altri più ricchi.`,
      ] },
      { t: 'h', x: 'La compagnia che fa bene' },
      { t: 'p', x: `Scegli persone con cui parlare del vero. Seneca scriveva che la frequentazione di chi è migliore di noi ci migliora. E ricordava di essere anche noi quella persona per qualcuno.` },
      { t: 'nota', x: `Se la solitudine ti pesa da tempo, parlane con qualcuno di fiducia. Nessuna filosofia sostituisce le relazioni.` },
      { t: 'azione', x: 'Amicizia e comunità', az: 'studio', id: 'amicizia-e-comunita' },
      { t: 'azione', x: 'Esercizio: Le due mani', az: 'esercizio', id: 'le-due-mani' },
    ],
  },
  {
    id: 'la-gratitudine',
    titolo: 'La gratitudine',
    sotto: 'Un modo stoico di guardare ciò che si è ricevuto.',
    blocchi: [
      { t: 'p', x: `Il primo libro dell'opera di Marco Aurelio è un lungo elenco di **ringraziamenti**: al nonno, ai genitori, ai maestri, agli amici, per ciò che ciascuno gli ha dato. È un esercizio che si può ripetere: guardare la propria vita come il risultato di molti doni.` },
      { t: 'h', x: 'Perché aiuta' },
      { t: 'lista', x: [
        `**Sposta l'attenzione** da ciò che manca a ciò che c'è.`,
        `**Riduce il rancore:** è difficile serbarlo mentre si ringrazia.`,
        `**Rende generosi:** chi ha ricevuto è più incline a dare.`,
        `**Aiuta con la perdita:** ciò che si è ricevuto resta, anche quando finisce.`,
      ] },
      { t: 'h', x: 'Seneca e i benefici' },
      { t: 'p', x: `Seneca dedicò un trattato al ricevere e al dare i benefici. Vi sostiene che chi riceve un bene deve ricordarlo con gratitudine, e chi lo dà deve dimenticarlo. Questa asimmetria è il segreto della generosità.` },
      { t: 'azione', x: 'Esercizio: Ciò che ho ricevuto', az: 'esercizio', id: 'cio-che-ho-ricevuto' },
      { t: 'azione', x: 'Esercizio: Un favore in silenzio', az: 'esercizio', id: 'un-favore-in-silenzio' },
    ],
  },
  {
    id: 'errori-di-chi-comincia',
    titolo: 'Gli errori di chi comincia',
    sotto: 'Come non fraintendere lo stoicismo, e che cosa fare se succede.',
    blocchi: [
      { t: 'p', x: `Chi comincia con lo stoicismo può inciampare in alcuni equivoci. Conoscerli aiuta a usarlo bene.` },
      { t: 'h', x: 'I più comuni' },
      { t: 'lista', x: [
        `**Reprimere le emozioni.** Gli stoici volevano capirle, e curarle, e non cancellarle.`,
        `**Usare la filosofia come scudo.** Dirsi «non dipende da me» per evitare di fare ciò che invece dipende da noi.`,
        `**Diventare freddi.** L'idea era il contrario: più giustizia e più benevolenza verso gli altri.`,
        `**Aspettarsi la perfezione.** Nessuno la raggiunge: si migliora e basta.`,
        `**Farne una gara.** Lo stoicismo non è un modo di sentirsi superiori.`,
      ] },
      { t: 'h', x: 'Che cosa fare' },
      { t: 'p', x: `Torna spesso alle basi: ciò che dipende da te, i giudizi, le virtù. Scegli pochi esercizi e ripetili. E se una pratica ti fa stare peggio, mettila da parte: gli stoici volevano una vita migliore, non una prova di resistenza.` },
      { t: 'azione', x: 'Falsi miti sullo stoicismo', az: 'studio', id: 'falsi-miti' },
      { t: 'azione', x: 'Come usare questa app', az: 'studio', id: 'come-usare' },
    ],
  },
  {
    id: 'un-mese-di-pratica',
    titolo: 'Un mese di pratica',
    sotto: 'Un piano semplice per costruire l’abitudine, settimana per settimana.',
    blocchi: [
      { t: 'p', x: `Gli stoici insistevano: la filosofia si impara **con l'esercizio**. Ecco un piano leggero, per un mese. Puoi cambiarlo come vuoi: le pratiche servono più dei piani.` },
      { t: 'h', x: 'Prima settimana: guardare' },
      { t: 'p', x: `Ogni giorno, una volta, ferma il pensiero e chiediti: è un fatto o un giudizio? Bastano due minuti. Puoi usare l'esercizio **Fermati, impressione**.` },
      { t: 'h', x: 'Seconda settimana: distinguere' },
      { t: 'p', x: `Ogni giorno scrivi due colonne: ciò che dipende da te e ciò che non dipende da te. Servono pochi minuti, e cambiano il modo di affrontare la giornata.` },
      { t: 'h', x: 'Terza settimana: agire' },
      { t: 'p', x: `Ogni mattina scegli un compito piccolo e lo fai con attenzione. La sera, guardi come è andata.` },
      { t: 'h', x: 'Quarta settimana: esaminare' },
      { t: 'p', x: `Ogni sera fai l'esame della giornata, in tre domande. Nel fine settimana rileggi le pagine del quaderno e nota che cosa è cambiato.` },
      { t: 'nota', x: `Se salti un giorno, riprendi dal successivo. Nessuno ti valuta: l'abitudine si costruisce con la ripresa, non con la perfezione.` },
      { t: 'azione', x: 'Esercizio: Fermati, impressione', az: 'esercizio', id: 'fermati-impressione' },
    ],
  },
];
