// Pagine di studio sullo stoicismo. Testi originali: le idee sono degli autori antichi, le parole sono nostre.
// Tipi di blocco: h (titolo), p (testo), lista, passi, nota, azione. Nel testo, **così** diventa grassetto.
// Un blocco «azione» apre un esercizio (az: 'esercizio'), una pagina di studio (az: 'studio') o una meditazione (az: 'meditazione').

export const PAGINE_STUDIO = [
  {
    id: 'cose-lo-stoicismo',
    titolo: "Che cos'è lo stoicismo",
    sotto: 'Una filosofia che è anche un modo di vivere, nata ad Atene più di duemila anni fa.',
    blocchi: [
      { t: 'p', x: `Lo stoicismo è una scuola filosofica nata ad Atene attorno al 300 a.C. Il nome viene dalla **Stoà Poikile**, il «portico dipinto» dove il suo fondatore, **Zenone di Cizio**, teneva le lezioni. Portico in greco si dice *stoà*: gli stoici sono, alla lettera, «quelli del portico».` },
      { t: 'p', x: `Per gli stoici la filosofia non era soltanto una teoria da studiare: era un'**arte di vivere**. Serviva a essere più liberi, più sereni e più giusti. Molti testi antichi sono esercizi che l'autore pratica e fa praticare al lettore, non trattati da leggere e basta.` },
      { t: 'h', x: 'Tre parti, un solo scopo' },
      { t: 'p', x: `Gli stoici dividevano la filosofia in tre parti: la **logica** (come si ragiona e si giudica), la **fisica** (come è fatto il mondo e qual è il nostro posto in esso) e l'**etica** (come si vive e si agisce). Non erano tre materie separate: erano tre modi di allenare la stessa cosa, la capacità di vivere bene.` },
      { t: 'h', x: 'Tre epoche' },
      { t: 'lista', x: [
        `**Lo stoicismo antico** (dal 300 a.C.): Zenone, Cleante e Crisippo. Ci restano quasi solo frammenti, raccolti dagli studiosi.`,
        `**Lo stoicismo di mezzo:** filosofi come Panezio e Posidonio portano lo stoicismo a Roma.`,
        `**Lo stoicismo romano** (dal I secolo d.C.): Seneca, Musonio Rufo, Epitteto e Marco Aurelio. Sono loro che ci hanno lasciato i testi più letti.`,
      ] },
      { t: 'h', x: 'Quattro idee da cui partire' },
      { t: 'lista', x: [
        `**Ciò che dipende da noi.** Alcune cose sono in nostro potere (i nostri giudizi, le nostre scelte), altre no (gli eventi, le altre persone, il passato).`,
        `**La ragione.** L'essere umano ha la capacità di esaminare ciò che pensa prima di crederci.`,
        `**La virtù.** Per gli stoici il vero bene è vivere con saggezza, giustizia, coraggio e misura. Il resto (salute, ricchezze, fama) è preferibile ma non decide la nostra vita.`,
        `**La comunità.** Siamo parte di una comunità umana: agire con giustizia verso gli altri è parte del vivere bene.`,
      ] },
      { t: 'h', x: 'Che cosa promette e che cosa no' },
      { t: 'p', x: `Lo stoicismo promette una **libertà interiore**: un modo di stare nelle cose che dipende meno da ciò che accade. Non promette una vita senza dolore né un carattere di ferro. Promette un lavoro, da fare a poco a poco, con esercizi semplici.` },
      { t: 'azione', x: 'Prova un primo esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'falsi-miti',
    titolo: 'Falsi miti',
    sotto: 'Che cosa lo stoicismo non è, contro il modo comune di dire «stoico».',
    blocchi: [
      { t: 'p', x: `Nel parlare comune «stoico» vuol dire chi sopporta in silenzio, senza emozioni. È un equivoco, e vale la pena chiarirlo, perché cambia il modo di usare questa filosofia.` },
      { t: 'h', x: 'Falso: lo stoico non prova emozioni' },
      { t: 'p', x: `Gli stoici distinguevano le **passioni** (paura, desiderio smodato, dolore, piacere sfrenato), cioè le emozioni che nascono da un giudizio sbagliato, da alcune **emozioni buone**, come una gioia serena, una prudenza ragionevole e una volontà giusta. Chiedevano di capire ciò che si sente, non di smettere di sentire. Anche le reazioni immediate del corpo, come un sussulto, un rossore, un brivido, sono per Seneca del tutto naturali: la passione comincia dopo, quando ci crediamo.` },
      { t: 'h', x: 'Falso: bisogna sopportare tutto senza reagire' },
      { t: 'p', x: `La distinzione fondamentale separa le cose in nostro potere da quelle che non lo sono. Ciò che è in nostro potere, per esempio agire con giustizia, va fatto con impegno. Gli stoici furono spesso attivi nella vita pubblica, e Marco Aurelio governò un impero. Accettare ciò che è fuori dal nostro potere è diverso dal rinunciare a cambiare ciò che possiamo cambiare.` },
      { t: 'h', x: 'Falso: è una filosofia fredda e individualista' },
      { t: 'p', x: `Gli stoici si sentivano cittadini del mondo. Per loro tutti gli esseri umani appartengono a un'unica comunità, e la giustizia verso gli altri fa parte del vivere bene. Marco Aurelio ricorda a se stesso di essere nato per collaborare, come le mani di un solo corpo.` },
      { t: 'h', x: 'Falso: è pensiero positivo' },
      { t: 'p', x: `Gli stoici guardavano la realtà com'è, anche nei suoi aspetti duri. Praticavano perfino l'esercizio di immaginare in anticipo le difficoltà, per affrontarle con più calma. Non si tratta di ripetersi che andrà tutto bene, ma di prepararsi a vivere anche quando non andrà tutto bene.` },
      { t: 'h', x: 'Falso: è per persone forti o perfette' },
      { t: 'p', x: `Gli stoici si consideravano dei «progredienti»: persone in cammino. Seneca ed Epitteto parlano continuamente delle proprie difficoltà e di quelle dei loro allievi. Il punto non è essere perfetti, ma esercitarsi.` },
      { t: 'h', x: 'Falso: è una filosofia da citazioni' },
      { t: 'p', x: `Le frasi celebri, isolate, fanno poco. Il cuore dello stoicismo sono gli **esercizi**: pratiche precise, da ripetere, che cambiano poco a poco il modo di vedere. Per questo Un momento propone esercizi e non soltanto frasi.` },
      { t: 'h', x: 'Falso: è fatalismo' },
      { t: 'p', x: `Gli stoici non dicevano «tanto è tutto scritto». Dicevano: impegnati con tutte le forze in ciò che dipende da te, e accetta con calma l'esito. Uno dei loro esercizi consiste proprio nell'agire con una riserva: «lo farò, se nulla lo impedisce».` },
      { t: 'azione', x: 'Leggi che cosa sono le tre discipline', az: 'studio', id: 'tre-discipline' },
    ],
  },
  {
    id: 'cosa-dice-la-ricerca',
    titolo: 'Che cosa dice la ricerca',
    sotto: 'Che cosa sappiamo oggi sull\'efficacia degli esercizi stoici, e che cosa ancora no.',
    blocchi: [
      { t: 'p', x: `Lo stoicismo è una pratica antica, ma da qualche anno è anche oggetto di studio scientifico. Qui trovi che cosa è stato verificato e che cosa è ancora aperto. Le prove sono poche e giovani: le presentiamo con prudenza.` },
      { t: 'h', x: 'Da lì viene la psicoterapia cognitiva' },
      { t: 'p', x: `**Albert Ellis** e **Aaron Beck**, i fondatori delle terapie cognitive e comportamentali (oggi tra le più studiate), hanno dichiarato di essersi ispirati agli stoici. L'idea comune è che le emozioni dipendano anche dal modo in cui interpretiamo ciò che accade. Ellis citava spesso Epitteto: non sono le cose a turbarci, ma i giudizi che ne diamo.` },
      { t: 'p', x: `Anche la mindfulness ha un antenato in un esercizio stoico, l'**attenzione** al momento presente. Questo collegamento è descritto in un articolo pubblicato nel 2023 sulla rivista *Neurological Sciences* (Cavanna e altri).` },
      { t: 'h', x: 'Una prova controllata' },
      { t: 'p', x: `Nel 2025 una ricerca dell'Università Royal Holloway di Londra ha assegnato a sorte 119 persone a due gruppi: uno ha fatto per due settimane esercizi stoici quotidiani online, l'altro è rimasto in attesa. Il primo gruppo ha avuto **meno sintomi di depressione** e ha evitato meno i propri stati interiori. L'ansia è migliorata soltanto a un mese di distanza.` },
      { t: 'h', x: 'Stoic Week' },
      { t: 'p', x: `Ogni anno, dal 2013, migliaia di persone seguono per una settimana pratiche stoiche e misurano il proprio benessere prima e dopo. Dai rapporti risultano miglioramenti nella soddisfazione di vita e nella resilienza. Sono dati utili ma limitati: chi partecipa si sceglie da solo e manca un gruppo di confronto.` },
      { t: 'h', x: 'Che cosa ancora non sappiamo' },
      { t: 'lista', x: [
        `Se i benefici durano a lungo, oltre pochi mesi.`,
        `Quali esercizi funzionano meglio, e per quali persone.`,
        `Se lo stoicismo funziona meglio o peggio delle altre pratiche, come la mindfulness o la terapia cognitiva.`,
      ] },
      { t: 'nota', x: `Gli esercizi stoici sono un aiuto per il pensiero e l'attenzione. Possono affiancare, ma non sostituire, il parere del medico o un percorso di cura.` },
      { t: 'azione', x: 'Prova un esercizio', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'tre-discipline',
    titolo: 'Le tre discipline',
    sotto: 'La chiave con cui Epitteto, e dopo di lui Marco Aurelio, ordinano gli esercizi.',
    blocchi: [
      { t: 'p', x: `Epitteto dice che chi vuole diventare un uomo migliore deve esercitarsi in tre ambiti. Questa tripartizione è la chiave di lettura anche dei pensieri di Marco Aurelio. Sono le **tre discipline**, e in Un momento sono la bussola con cui ti chiediamo: dove ti sei perso?` },
      { t: 'passi', x: [
        { titolo: 'La disciplina del desiderio e della paura.', testo: `Riguarda ciò che vogliamo e ciò che temiamo. Insegna a desiderare e a evitare solo ciò che dipende da noi, e ad accogliere con calma il resto. Corrisponde, nella filosofia stoica, alla **fisica**: vedere gli eventi nel loro posto nell'ordine più grande delle cose.` },
        { titolo: "La disciplina dell'azione.", testo: `Riguarda ciò che facciamo e i nostri doveri: agire con giustizia, con misura, pensando agli altri. Corrisponde all'**etica**.` },
        { titolo: 'La disciplina del giudizio.', testo: `Riguarda ciò che pensiamo: non credere alle prime impressioni, distinguere ciò che è vero da ciò che è solo apparente. Corrisponde alla **logica**.` },
      ] },
      { t: 'h', x: 'Da dove cominciare' },
      { t: 'p', x: `Epitteto consiglia di cominciare dalla prima, il desiderio e la paura, perché è la più urgente: è lì che nasce gran parte dell'infelicità. La disciplina del giudizio è la più fine e la più difficile, e la lasciava agli allievi più avanti.` },
      { t: 'h', x: 'Come le usa la app' },
      { t: 'lista', x: [
        `**Giudizio:** «Ciò che mi turba è il fatto, o quello che ne ho concluso?»`,
        `**Desiderio e paura:** «Sto cercando di controllare ciò che non dipende da me?»`,
        `**Azione:** «Che cosa devo fare, adesso, davvero?»`,
      ] },
      { t: 'p', x: `Le tre discipline si tengono insieme: quando cambia il giudizio, cambia anche il desiderio, e cambia l'azione. Puoi partire da qualunque punto.` },
      { t: 'azione', x: 'Esercizio del giudizio: Fermati, impressione', az: 'esercizio', id: 'fermati-impressione' },
      { t: 'azione', x: "Esercizio dell'azione: Il primo gesto piccolo", az: 'esercizio', id: 'il-primo-gesto-piccolo' },
    ],
  },
  {
    id: 'cio-che-dipende-da-noi',
    titolo: 'Ciò che dipende da noi',
    sotto: 'La distinzione da cui parte il Manuale di Epitteto.',
    blocchi: [
      { t: 'p', x: `Il *Manuale* di Epitteto comincia con una regola semplice: alcune cose dipendono da noi, altre no. Da qui discende quasi tutto il resto. Imparare a distinguere le due cose, ogni volta, è già metà del lavoro.` },
      { t: 'h', x: 'Dipende da noi' },
      { t: 'lista', x: [
        `Ciò che **pensiamo** e **giudichiamo**.`,
        `Ciò che **vogliamo** e ciò che **rifiutiamo**.`,
        `Il modo in cui **scegliamo di agire**.`,
      ] },
      { t: 'h', x: 'Non dipende da noi' },
      { t: 'lista', x: [
        `Il **corpo** e la sua salute.`,
        `Le **ricchezze**, la posizione, i ruoli.`,
        `La **reputazione**: che cosa gli altri pensano di noi.`,
        `Ciò che **decidono gli altri**, e l'esito finale delle cose.`,
        `Il **passato**.`,
      ] },
      { t: 'h', x: 'Che cosa succede quando le confondiamo' },
      { t: 'p', x: `Se trattiamo come nostro ciò che appartiene ad altri o al caso, rischiamo l'ansia (perché non possiamo garantirlo) e la delusione (perché può sfuggirci). Se trattiamo come non nostro ciò che lo è, rischiamo l'impotenza: ci sentiamo in balia di tutto, anche di ciò che potremmo cambiare.` },
      { t: 'h', x: 'Un errore comune' },
      { t: 'p', x: `Non significa disinteressarsi delle cose: significa mettere il proprio impegno dove serve. Tieni alla salute, al lavoro, alle persone: fai tutto ciò che è in tuo potere. Poi accetta con calma che l'esito non sia nelle tue mani. Gli stoici lo dicevano con la formula «se nulla lo impedisce».` },
      { t: 'h', x: 'Le zone grigie' },
      { t: 'p', x: `Molte situazioni sono miste: la salute dipende in parte da come ti curi, il lavoro in parte da come lo fai. In quei casi fai la tua parte con impegno e lascia il resto. La domanda utile è sempre la stessa: che cosa, qui, è davvero in mano mia?` },
      { t: 'azione', x: 'Fai l\'esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
      { t: 'azione', x: 'Fai l\'esercizio: Se nulla lo impedisce', az: 'esercizio', id: 'se-nulla-lo-impedisce' },
    ],
  },
  {
    id: 'impressioni-giudizio',
    titolo: 'Le impressioni e il giudizio',
    sotto: 'Tra ciò che accade e ciò che proviamo c\'è uno spazio: il giudizio.',
    blocchi: [
      { t: 'p', x: `Per gli stoici tutto ciò che percepiamo ci arriva sotto forma di **impressione**: il modo in cui una situazione ci appare. Le impressioni arrivano da sole, non le scegliamo. Ma c'è un passaggio successivo che è nostro: **dare o negare il proprio assenso**, cioè credere a quell'impressione oppure esaminarla.` },
      { t: 'passi', x: [
        { titolo: 'Arriva un\'impressione.', testo: `Per esempio: «Mi ha risposto male, non mi rispetta». È rapida e sembra evidente.` },
        { titolo: 'Puoi esaminarla.', testo: `Che cosa è accaduto davvero? Che cosa ci ho aggiunto? Potrebbe essere diversa?` },
        { titolo: 'Decidi se credere.', testo: `Solo dopo, se regge, dai il tuo assenso. Le emozioni che seguono dipendono da quello.` },
      ] },
      { t: 'h', x: 'Il giudizio pesa più dei fatti' },
      { t: 'p', x: `Epitteto sostiene che ciò che ci turba non sono le cose, ma i giudizi che ne diamo. I fatti contano, ma gran parte del peso viene da ciò che ci abbiamo aggiunto: un'intenzione, una condanna, un pronostico.` },
      { t: 'h', x: 'Descrivere senza aggiungere' },
      { t: 'p', x: `Marco Aurelio propone un esercizio di esattezza: descrivere ogni cosa nuda, per ciò che è, senza le aggiunte dell'opinione. Un pranzo pregiato diventa «un pesce morto e un po' d'uva»: non per disgusto, ma per togliere il fumo che ci mette la vanità.` },
      { t: 'h', x: 'I primi movimenti' },
      { t: 'p', x: `Seneca ricorda che le prime reazioni del corpo (un sussulto, un rossore, un brivido) sfuggono al nostro controllo e non sono ancora passioni. La passione comincia quando ci diamo ragione: «è giusto che io mi arrabbi». Lì possiamo fermarci.` },
      { t: 'azione', x: 'Esercizio: Fermati, impressione', az: 'esercizio', id: 'fermati-impressione' },
      { t: 'azione', x: 'Esercizio: Descrivi senza aggiungere', az: 'esercizio', id: 'descrivi-senza-aggiungere' },
      { t: 'azione', x: 'Esercizio: Il fatto e il giudizio', az: 'esercizio', id: 'fatto-e-giudizio' },
    ],
  },
  {
    id: 'paura-desiderio',
    titolo: 'La paura e il desiderio',
    sotto: 'Le passioni secondo gli stoici, e come si curano.',
    blocchi: [
      { t: 'p', x: `Per gli stoici le emozioni che ci turbano di più nascono da un **giudizio**: crediamo che una certa cosa sia un bene o un male, e che dobbiamo averla o evitarla. Da qui le quattro passioni principali, che dipendono dal tempo e dal tipo di cosa.` },
      { t: 'lista', x: [
        `**Il desiderio:** giudichiamo che un bene futuro sia da ottenere a ogni costo.`,
        `**La paura:** giudichiamo che un male futuro stia per colpirci.`,
        `**Il piacere sfrenato:** giudichiamo che un bene presente sia da afferrare senza misura.`,
        `**Il dolore:** giudichiamo che un male presente sia una sventura.`,
      ] },
      { t: 'h', x: 'Le emozioni buone' },
      { t: 'p', x: `Il saggio stoico non è privo di emozioni. Prova tre buone disposizioni: la **gioia** serena, la **prudenza** (che ci fa evitare con giudizio ciò che è davvero dannoso) e una **volontà** ragionevole. Sono le forme sane di ciò che, in eccesso, diventa passione.` },
      { t: 'h', x: 'Come si cura la paura' },
      { t: 'p', x: `Il metodo stoico agisce sul giudizio e sull'abitudine. Si esamina ciò che si teme (è davvero un male? dipende da me?), si misura la sua probabilità, si immagina con calma il caso peggiore per preparare una risposta, e si ricorda che tutto ciò che possediamo può finire. Sono gli esercizi della premeditazione dei mali e del ricordo della fragilità delle cose.` },
      { t: 'h', x: 'Come si cura il desiderio' },
      { t: 'p', x: `Si desidera con misura ciò che dipende da noi, e si accoglie il resto senza pretendere. Epitteto propone di cominciare dalle piccole cose: rinunciare a un desiderio da poco, per allenarsi a quelli più grandi.` },
      { t: 'azione', x: 'Esercizio: Il peggio, misurato', az: 'esercizio', id: 'il-peggio-misurato' },
      { t: 'azione', x: 'Esercizio: Prepararsi al peggio', az: 'esercizio', id: 'prepararsi-al-peggio' },
      { t: 'azione', x: 'Esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'esercizi-spirituali',
    titolo: 'Gli esercizi spirituali',
    sotto: 'Il catalogo delle pratiche stoiche.',
    blocchi: [
      { t: 'p', x: `Le scuole filosofiche greche e romane proponevano ai propri allievi **pratiche concrete** per trasformare il modo di vedere e di vivere. «Spirituale» qui indica ciò che riguarda l'intera persona, e non solo il pensiero.` },
      { t: 'p', x: `Non ci è rimasto un manuale che elenchi questi esercizi, perché erano un insegnamento orale e tradizionale. Ma ne troviamo le tracce ovunque, e alcuni elenchi antichi permettono di ricostruirne i gruppi principali.` },
      { t: 'h', x: 'Quattro gruppi' },
      { t: 'lista', x: [
        `**L'attenzione** (in greco *prosoché*): la vigilanza continua su di sé e sul momento presente, in modo che la regola di vita sia sempre «a portata di mano».`,
        `**Le meditazioni e i ricordi:** prepararsi ai mali possibili, ricordare la fragilità delle cose e la morte, guardare il mondo dall'alto, ricordare ciò che è bene.`,
        `**Gli esercizi di pensiero:** leggere, ascoltare, ricercare, esaminare a fondo.`,
        `**Gli esercizi attivi:** il dominio di sé, il compimento dei propri doveri, l'indifferenza verso ciò che non dipende da noi.`,
      ] },
      { t: 'h', x: 'A che cosa servono' },
      { t: 'p', x: `Lo scopo è una vera **conversione dello sguardo**: passare da una vita agitata, dominata da desideri e timori, a una vita più libera e più lucida. Non basta capire un'idea: bisogna ripeterla, provarla, farla propria, come si allena un muscolo.` },
      { t: 'h', x: 'Come compaiono in Un momento' },
      { t: 'p', x: `Ogni esercizio della app indica la sua famiglia e la sua fonte. «Qui e ora con i cinque sensi» e «Respiro e attenzione» sono esercizi di attenzione. «Prepararsi al peggio» e «La brocca che si può rompere» sono meditazioni. «Fermati, impressione» e «Il fatto e il giudizio» sono esercizi di pensiero. «Il primo gesto piccolo» e «Chi voglio essere qui» sono esercizi attivi.` },
      { t: 'azione', x: 'Esercizio di attenzione: Qui e ora, con i cinque sensi', az: 'esercizio', id: 'qui-e-ora-cinque-sensi' },
      { t: 'azione', x: "Meditazione: L'attenzione a se stessi", az: 'meditazione', id: 'attenzione-presente' },
    ],
  },
  {
    id: 'tre-maestri',
    titolo: 'I tre maestri',
    sotto: 'Epitteto, Seneca e Marco Aurelio: chi erano e come parlano.',
    blocchi: [
      { t: 'p', x: `Le tre voci della app sono tre autori stoici romani. Sono molto diversi per vita e per tono, e proprio per questo si completano.` },
      { t: 'h', x: 'Epitteto (circa 50 – circa 135 d.C.)' },
      { t: 'p', x: `Nacque schiavo, in Frigia. Divenne libero e insegnò filosofia prima a Roma e poi a Nicopoli, in Grecia. Non scrisse nulla: le sue lezioni furono messe per iscritto dal suo allievo **Arriano**, che ne ricavò gli *Discorsi* (o *Diatribe*) e il breve *Manuale*. Il suo tono è **secco e diretto**: parla come un maestro che non gira intorno alle cose. Per lui la filosofia è un'officina, una «sala operatoria» dell'anima.` },
      { t: 'h', x: 'Seneca (circa 4 a.C. – 65 d.C.)' },
      { t: 'p', x: `Nato in Spagna, visse a Roma: fu scrittore, uomo di Stato e per anni consigliere dell'imperatore Nerone, che nel 65 d.C. gli ordinò di togliersi la vita. Scrisse trattati (*Sull'ira*, *Sulla brevità della vita*, *Sulla tranquillità dell'animo*) e le *Lettere a Lucilio*, un amico più giovane a cui parla da amico esperto. Il suo tono è **caldo e vicino**, come una lettera: spiega, consola, si mette in gioco.` },
      { t: 'h', x: 'Marco Aurelio (121–180 d.C.)' },
      { t: 'p', x: `Fu imperatore romano dal 161 al 180. Nei momenti liberi, spesso durante le campagne militari, scrisse in greco appunti per se stesso, che noi conosciamo con il titolo *A se stesso* (o *Ricordi*). Non erano destinati a nessuno: sono un quaderno di esercizi personali. Il suo tono è **interiore e riservato**, di chi parla a se stesso.` },
      { t: 'h', x: 'Come usare le voci' },
      { t: 'p', x: `Nella app puoi cambiare voce quando vuoi. Se hai bisogno di essere scosso, prova Epitteto. Se hai bisogno di essere accompagnato, prova Seneca. Se cerchi un silenzio in cui riflettere, prova Marco Aurelio. Gli esercizi restano gli stessi: cambia il modo di dirli.` },
      { t: 'azione', x: 'Leggi come leggerli', az: 'studio', id: 'come-leggere' },
    ],
  },
  {
    id: 'come-usare',
    titolo: 'Come usare Un momento',
    sotto: 'Un modo semplice di usare la app, senza obblighi.',
    blocchi: [
      { t: 'p', x: `Un momento non ti chiede di praticare ogni giorno, di accumulare giorni di fila o di rispondere a notifiche. Lo apri quando ti serve, e lo lasci quando ti basta.` },
      { t: 'h', x: 'Quando stai male' },
      { t: 'passi', x: [
        { titolo: 'Tocca «Ho bisogno di un momento».', testo: `Scegli che cosa senti e dove ti sei perso.` },
        { titolo: 'Scegli quanto tempo hai.', testo: `Un minuto basta per cominciare. Se hai più tempo, un esercizio più lungo va più a fondo.` },
        { titolo: 'Fai l\'esercizio un passo alla volta.', testo: `Non devi crederci per forza: provalo. Puoi tornare indietro o fermarti quando vuoi.` },
      ] },
      { t: 'h', x: 'Quando vuoi un momento di calma' },
      { t: 'p', x: `Nella sezione Esercizi trovi le meditazioni a tempo, per esempio quella sull'attenzione a se stessi o l'esame della sera. Puoi farle anche senza un motivo preciso.` },
      { t: 'h', x: 'Quando vuoi capire' },
      { t: 'p', x: `In Studio trovi le pagine che spiegano lo stoicismo e le fonti da cui vengono gli esercizi. Ogni esercizio ha un collegamento alla pagina che lo approfondisce.` },
      { t: 'h', x: 'Alcuni consigli' },
      { t: 'lista', x: [
        `**Comincia dai brevi.** Un esercizio da uno o tre minuti, fatto davvero, vale più di uno lungo lasciato a metà.`,
        `**Ripeti quelli che funzionano.** Gli esercizi stoici sono fatti per essere ripetuti: la seconda volta è più facile.`,
        `**Cambia voce se un tono non ti aiuta.** Ognuno risponde a modo suo.`,
        `**Non contare i giorni.** L'unico giorno che conta è quello in cui ti serve.`,
      ] },
      { t: 'nota', x: `Un momento nasce dalla sapienza degli stoici antichi e propone esercizi di pensiero e di attenzione. Non sostituisce il parere del medico né un percorso di cura o di sostegno psicologico: se il malessere è forte o dura da tempo, parlane con il tuo medico o con un professionista.` },
    ],
  },
  {
    id: 'come-leggere',
    titolo: 'Come leggere gli stoici',
    sotto: 'Da dove cominciare, e come leggerli senza perdersi.',
    blocchi: [
      { t: 'p', x: `Leggere gli stoici è più semplice di quanto si pensi, se si sceglie l'ordine giusto e si legge poco alla volta. Ecco un percorso.` },
      { t: 'passi', x: [
        { titolo: 'Epitteto, *Manuale*.', testo: `Poche pagine, tutte utili. È il testo più diretto: un piccolo libro di regole di vita da tenere a portata di mano.` },
        { titolo: 'Marco Aurelio, *A se stesso*.', testo: `Appunti brevi, che si aprono a caso. Ottimo per leggere una pagina la sera.` },
        { titolo: 'Seneca, *Lettere a Lucilio*.', testo: `Lettere brevi e ricche, dove Seneca ragiona su una sola idea alla volta. Si leggono una per volta.` },
        { titolo: 'Pierre Hadot, *Esercizi spirituali e filosofia antica*.', testo: `Per capire che cosa erano davvero gli esercizi. Meno immediato, ma prezioso.` },
        { titolo: 'Gli stoici antichi.', testo: `I frammenti di Zenone, Cleante e Crisippo, raccolti negli *Stoici antichi*: per chi vuole andare alla fonte, con calma.` },
      ] },
      { t: 'h', x: 'Come leggere' },
      { t: 'lista', x: [
        `**Poco alla volta.** Dieci minuti, una pagina, un'idea.`,
        `**Con un quaderno.** Scrivi una frase con parole tue e chiediti dove puoi usarla oggi.`,
        `**Anche più edizioni.** Le traduzioni cambiano molto: confrontarne due aiuta a capire.`,
        `**Non serve finire.** Questi testi sono fatti per essere ripresi a pezzi.`,
      ] },
      { t: 'nota', x: `Le edizioni consigliate stanno nella pagina Fonti, nelle Info.` },
    ],
  },
  {
    id: 'il-tempo-la-morte',
    titolo: 'Il tempo e la morte',
    sotto: 'Perché gli stoici ricordavano ogni giorno che la vita è breve.',
    blocchi: [
      { t: 'p', x: `Gli stoici ricordavano spesso che il tempo è limitato e che la vita finisce. Non lo facevano per rattristarsi, ma per vivere meglio: chi ricorda che il tempo è poco, lo usa con più cura.` },
      { t: 'h', x: 'Il tempo è il nostro bene più prezioso' },
      { t: 'p', x: `Seneca, nella *Brevità della vita*, sostiene che non abbiamo poco tempo, ma ne sprechiamo molto. La vita è abbastanza lunga se la si impiega bene. Per questo consiglia di custodire il proprio tempo come si custodisce il denaro, e di donarlo a chi lo merita.` },
      { t: 'h', x: 'Solo il presente è nostro' },
      { t: 'p', x: `Marco Aurelio osserva che il passato e il futuro sfuggono al nostro potere: il passato è chiuso, il futuro è ignoto. Ci resta il presente, ed è tutto ciò che possiamo perdere o possedere. Vale la pena viverlo con attenzione.` },
      { t: 'h', x: 'Imparare a morire' },
      { t: 'p', x: `«Filosofare è imparare a morire» è una formula antica, ed era un vero esercizio: pensare alla propria fine con calma, per liberarsi dalla paura che ci tiene prigionieri. Chi ha guardato la morte in faccia con serenità, vive con più libertà.` },
      { t: 'h', x: 'Ciò che ami è fragile' },
      { t: 'p', x: `Gli stoici invitavano a ricordare anche la fragilità delle cose e delle persone care. Non per amarle di meno, ma per amarle con più attenzione, con le mani aperte, senza pretendere che durino.` },
      { t: 'nota', x: `Sono temi delicati. Se un esercizio su questo ti pesa, fermati e passa ad altro: è una pratica da fare quando ti senti pronto.` },
      { t: 'azione', x: 'Esercizio: La brocca che si può rompere', az: 'esercizio', id: 'la-brocca-che-si-rompe' },
      { t: 'azione', x: 'Esercizio: Esame della sera', az: 'esercizio', id: 'esame-della-sera' },
    ],
  },
  {
    id: 'vista-dall-alto',
    titolo: "La vista dall'alto",
    sotto: 'Guardare le cose da lontano, per ritrovare la giusta misura.',
    blocchi: [
      { t: 'p', x: `Tra gli esercizi più suggestivi degli stoici c'è la **vista dall'alto**: immaginare di guardare la propria vita, la propria città, il mondo intero da molto in alto, come se ci si allontanasse da terra. Marco Aurelio la pratica più volte nei suoi appunti.` },
      { t: 'h', x: 'A che cosa serve' },
      { t: 'p', x: `Quando siamo dentro un problema, ci sembra grandissimo. Guardato da lontano, ritrova la sua misura: le nostre preoccupazioni sono una piccola parte di una storia molto più vasta, fatta di persone, luoghi e secoli. È una forma di **fisica vissuta**: non una teoria sul cosmo, ma un modo di guardare che cambia lo stato d'animo.` },
      { t: 'h', x: 'Come si fa' },
      { t: 'passi', x: [
        { titolo: 'Parti da dove sei.', testo: `La stanza, il tuo corpo, il tuo problema.` },
        { titolo: 'Sali un poco.', testo: `Il palazzo, la strada, il quartiere, la città con le sue luci.` },
        { titolo: 'Sali ancora.', testo: `La regione, il mare, la Terra vista dallo spazio, tanti esseri umani che vivono, lavorano, soffrono e sperano.` },
        { titolo: 'Guarda anche il tempo.', testo: `Le epoche passate, i secoli che verranno. Quanto pesava, tra mille anni, ciò che ti agita oggi?` },
        { titolo: 'Torna giù.', testo: `Riporta questo sguardo nel tuo problema: è ancora tuo, ma è meno grande di prima.` },
      ] },
      { t: 'azione', x: "Meditazione guidata: Vista dall'alto", az: 'meditazione', id: 'vista-dall-alto-guidata' },
    ],
  },
];
