// Pagine di studio della versione 1.3: la storia della scuola, le sue parti e la vita di Seneca.
// Fonti per le date e i fatti: Pohlenz (La Stoa), Reale (Seneca), Diogene Laerzio nell'edizione dei frammenti.
// Testi originali: le idee sono degli antichi, le parole sono nostre. Stessi tipi di blocco di studio.js.

export const PAGINE_STUDIO_4 = [
  {
    id: 'le-tre-eta-della-stoa',
    titolo: 'La scuola in tre età',
    sotto: "Dall'Atene di Zenone alla Roma degli imperatori: come cambia lo stoicismo in cinque secoli.",
    blocchi: [
      { t: 'p', x: `La scuola stoica dura circa cinque secoli. In questo tempo cambia città, lingua e carattere. Gli studiosi la dividono in tre età: **antica**, **di mezzo** e **romana**. È uno schema moderno, comodo per orientarsi: gli antichi stessi non parlavano di una «Stoà di mezzo».` },
      { t: 'h', x: 'La Stoà antica (circa 300–200 a.C.)' },
      { t: 'p', x: `Zenone di Cizio comincia a insegnare ad Atene attorno al 300 a.C., nel portico dipinto da cui la scuola prende il nome. In città era arrivato da poco Epicuro, che indicava nel piacere il fine della vita. Zenone risponde mettendo al centro la ragione e la virtù. Dopo di lui guidano la scuola Cleante e poi Crisippo, che dà al sistema la sua forma completa.` },
      { t: 'p', x: `È l'età in cui si costruisce l'impianto: una logica, una fisica e un'etica legate tra loro. Due allievi di Zenone, Aristone ed Erillo, seguirono strade proprie, ma le loro scuole si spensero presto.` },
      { t: 'h', x: 'La Stoà di mezzo (circa 130–50 a.C.)' },
      { t: 'p', x: `Con **Panezio** e **Posidonio** la scuola esce da Atene e si apre al mondo: a Rodi, a Roma, ai viaggi, alla storia e alle scienze. Diventa meno rigida. Si interessa all'uomo com'è, con il suo carattere e la sua vita pubblica, e discute con più libertà alcune tesi di Crisippo.` },
      { t: 'h', x: 'La Stoà romana (I e II secolo d.C.)' },
      { t: 'p', x: `Con Seneca, Musonio Rufo, Epitteto e Marco Aurelio lo stoicismo diventa soprattutto una guida per vivere. Sono gli autori arrivati fino a noi in opere intere, e sono quelli da cui vengono gli esercizi di questa app. Parlano meno di sistema e più di pratica: come reggere l'ira, la perdita, la paura, il tempo che passa.` },
      { t: 'lista', x: [
        `**Età antica:** costruire il sistema (Zenone, Cleante, Crisippo).`,
        `**Età di mezzo:** aprire la scuola al mondo (Panezio, Posidonio).`,
        `**Età romana:** praticare nella vita di ogni giorno (Seneca, Musonio, Epitteto, Marco Aurelio).`,
      ] },
      { t: 'nota', x: `Il filo che lega le tre età è lo stesso: la ragione come guida e la virtù come unico vero bene. Cambiano il tono e la distanza dalla vita quotidiana, non la direzione.` },
      { t: 'azione', x: 'Panezio', az: 'studio', id: 'panezio' },
      { t: 'azione', x: 'Posidonio', az: 'studio', id: 'posidonio' },
      { t: 'azione', x: 'Come lo stoicismo arriva a Roma', az: 'studio', id: 'lo-stoicismo-a-roma' },
    ],
  },
  {
    id: 'come-conosciamo-i-primi-stoici',
    titolo: 'Come conosciamo i primi stoici',
    sotto: 'Opere perdute, citazioni e raccolte: la strada dei frammenti fino a noi.',
    blocchi: [
      { t: 'p', x: `Di Zenone, Cleante e Crisippo non è arrivato quasi nessun libro intero. Lo sappiamo da altri autori che li leggevano quando le loro opere esistevano ancora e li hanno riassunti, discussi o criticati. Per questo ogni notizia sui primi stoici va letta sapendo **chi la riferisce**.` },
      { t: 'h', x: 'Le fonti antiche' },
      { t: 'lista', x: [
        `**Diogene Laerzio:** un biografo vissuto secoli dopo. Nel settimo libro delle sue *Vite dei filosofi* racconta la vita e le dottrine degli stoici. Sono sue molte delle storie note su Zenone e Cleante.`,
        `**Cicerone e Seneca:** espongono, in latino, idee stoiche, e a volte le discutono.`,
        `**Plutarco:** scrive contro gli stoici, e proprio per questo ci lascia citazioni di Crisippo.`,
        `**Gli autori romani della scuola:** Epitteto e Marco Aurelio nominano spesso i maestri antichi.`,
      ] },
      { t: 'h', x: 'La raccolta moderna' },
      { t: 'p', x: `All'inizio del Novecento lo studioso tedesco Hans von Arnim ha riunito tutti i frammenti in quattro volumi, usciti tra il 1903 e il 1924. Il primo è dedicato a Zenone, Cleante e agli altri allievi, il secondo e il terzo a Crisippo. In Italia questa raccolta è stata tradotta e curata da Roberto Radice, con il titolo *Stoici antichi. Tutti i frammenti*.` },
      { t: 'h', x: 'Che cosa cambia per chi legge' },
      { t: 'lista', x: [
        `Le **date** dei primi stoici sono spesso calcolate e vanno prese come approssimazioni: per questo nelle pagine si trova «attorno al» o «secondo la tradizione».`,
        `Gli **aneddoti** (il naufragio di Zenone, il lavoro notturno di Cleante) sono storie raccontate secoli dopo: illuminano il carattere, non sono cronaca sicura.`,
        `Le **dottrine** si ricostruiscono mettendo insieme più testimonianze, e a volte gli antichi si contraddicono.`,
      ] },
      { t: 'p', x: `Per praticare non serve nulla di tutto questo: Epitteto, Seneca e Marco Aurelio bastano. Ma sapere come è fatta la strada aiuta a fidarsi di ciò che si legge, e a distinguere ciò che è certo da ciò che è tradizione.` },
      { t: 'azione', x: 'Gli stoici antichi', az: 'studio', id: 'stoici-antichi' },
      { t: 'azione', x: 'Come leggere gli stoici', az: 'studio', id: 'come-leggere' },
    ],
  },
  {
    id: 'panezio',
    titolo: 'Panezio',
    sotto: 'Lo stoico che parlava ai romani: meno rigore, più vita vera.',
    blocchi: [
      { t: 'p', x: `Panezio nacque a Lindo, nell'isola di Rodi, attorno al 185 a.C., in una famiglia ricca e nobile. Da giovane si legò a Scipione Emiliano, il generale che guidava la politica estera di Roma, e lo accompagnò in un lungo viaggio in Oriente, tra il 140 e il 139. Tornato ad Atene, nel 129 prese la guida della scuola stoica. Visse fino ai primi anni del secolo successivo.` },
      { t: 'h', x: 'Che cosa cambiò' },
      { t: 'p', x: `Per Panezio la filosofia valeva per come si vive, più che per i dogmi da difendere. Evitò le sottigliezze di logica e le liti tra scuole, e cercò uno stoicismo che reggesse alla prova dei fatti.` },
      { t: 'lista', x: [
        `**Il saggio perfetto:** lo guardava con un po' di ironia. Gli interessava l'uomo reale, con i suoi limiti, più di una figura ideale.`,
        `**Il dolore:** è una prova da attraversare, irrobustendo corpo e animo, così che non impedisca di fare ciò che si deve.`,
        `**Le passioni:** a Crisippo, che le riduceva tutte a giudizi, rispose che nell'anima c'è anche una parte fatta di impulsi, da educare e non solo da correggere con il ragionamento.`,
        `**La serenità:** parlò di una gioia di vivere che nasce da una vita coerente con la propria natura, senza puntare a un'insensibilità totale.`,
      ] },
      { t: 'h', x: 'Le quattro maschere' },
      { t: 'p', x: `La sua idea più originale riguarda il **dovere**. Un attore porta una maschera, noi ne portiamo quattro. La prima è la natura che ci accomuna: siamo tutti esseri dotati di ragione. La seconda è la nostra indole personale, con i suoi talenti e i suoi limiti. La terza viene dalle circostanze in cui la vita ci mette, e la quarta dalle scelte che facciamo, per esempio il mestiere.` },
      { t: 'p', x: `Ne segue che il dovere non è identico per tutti: dipende anche da chi sei e dalla situazione in cui ti trovi. Panezio precisa però un limite. La ragione comune resta la regola, e l'indole personale non diventa una scusa per fare ciò che si vuole.` },
      { t: 'h', x: 'I doveri e la grandezza d\'animo' },
      { t: 'p', x: `Il suo libro *Sul dovere* uscì poco dopo il 129 ed era pensato per i romani impegnati nella vita pubblica. Tra le virtù mise in primo piano la **grandezza d'animo**: guardare le cose esterne dall'alto, senza farsene dominare. Ma avvertì che ha valore solo quando serve la comunità e non l'ambizione personale. Cicerone si ispirò a questo libro per scrivere i suoi *Doveri*.` },
      { t: 'h', x: 'Perché ci interessa' },
      { t: 'p', x: `In questa app le pagine sui doveri e sui ruoli continuano la sua idea: prima di decidere, chiediti quali parti stai recitando e che cosa chiedono. E ricorda che uno stoico può essere sereno senza essere di ferro.` },
      { t: 'azione', x: 'I doveri e i ruoli', az: 'studio', id: 'i-doveri-e-i-ruoli' },
      { t: 'azione', x: 'Posidonio', az: 'studio', id: 'posidonio' },
    ],
  },
  {
    id: 'posidonio',
    titolo: 'Posidonio',
    sotto: 'Il filosofo-scienziato: viaggiare, misurare, capire come tutto si tiene insieme.',
    blocchi: [
      { t: 'p', x: `Posidonio nacque ad Apamea, in Siria, poco dopo il 135 a.C. Studiò ad Atene con Panezio, poi viaggiò a lungo e aprì la sua scuola a Rodi. Molti giovani romani andavano ad ascoltarlo: tra loro Cicerone, che studiò a Rodi nel 78 a.C. Nel 51 tornò a Roma e morì poco dopo, a ottantacinque anni.` },
      { t: 'h', x: 'Un filosofo che viaggia' },
      { t: 'p', x: `Nel primo decennio del I secolo a.C. Posidonio esplorò l'Occidente: la Spagna, la Gallia, la Liguria, l'Etruria. Osservava le coste e le maree, le miniere, i popoli e i loro costumi. Scrisse un'opera *Dell'oceano e delle terre adiacenti*, studiò i vulcani e i terremoti nell'area dell'Etna e di Napoli, e continuò la storia di Roma scritta da Polibio, a partire dal 144 a.C.` },
      { t: 'p', x: `Per uno stoico è una novità. Nella scuola antica il mondo si studiava soprattutto con il ragionamento. Lui ci aggiunse l'osservazione diretta.` },
      { t: 'h', x: 'Tutto è connesso' },
      { t: 'p', x: `Il cosmo stoico è come un unico corpo vivo, in cui ogni parte agisce sulle altre: è la **simpatia** (*sympátheia*). Nella scuola antica l'idea serviva soprattutto a difendere la fede nel destino e nella divinazione. Posidonio la mise al centro della sua spiegazione della natura: il clima, il paesaggio, le maree, il carattere dei popoli dipendono da una catena di cause che risale fino al sole e agli astri.` },
      { t: 'h', x: 'Le passioni' },
      { t: 'p', x: `Su un punto si allontanò da Crisippo. Per Crisippo le passioni sono errori di giudizio. Per Posidonio, come per Zenone secondo la sua lettura, nascono dallo scontro tra la ragione e una parte irrazionale dell'anima, con impulsi propri. Ne veniva che la ragione da sola non basta: servono anche un'educazione del carattere e la cura del corpo.` },
      { t: 'h', x: 'Il fine della vita' },
      { t: 'p', x: `Secondo le testimonianze antiche, Posidonio indicava come scopo della vita osservare la verità del mondo e il suo ordine, e cooperare a metterlo in atto per quanto si può. Una vita di studio, insomma, ma per il bene comune.` },
      { t: 'p', x: `Le sue opere sono perdute. Sappiamo di lui da altri, e l'influenza arriva a Seneca: un allievo di Posidonio, Asclepiodoto, si occupò dell'origine dei terremoti, e i suoi materiali servirono a Seneca per le *Questioni naturali*.` },
      { t: 'azione', x: 'La natura e il cosmo', az: 'studio', id: 'la-natura-e-il-cosmo' },
      { t: 'azione', x: 'Le quattro passioni', az: 'studio', id: 'le-quattro-passioni' },
    ],
  },
  {
    id: 'lo-stoicismo-a-roma',
    titolo: 'Come lo stoicismo arriva a Roma',
    sotto: 'Una scuola greca che diventa la filosofia dei romani.',
    blocchi: [
      { t: 'p', x: `I romani non avevano una tradizione filosofica. La filosofia greca li raggiunge quando Roma, conquistata la Grecia, diventa una potenza e si accorge di dover dare un senso al proprio potere. Lo stoicismo trova un terreno adatto: parla di dovere, di servizio alla comunità, di fermezza. Sono valori che i romani già stimavano.` },
      { t: 'h', x: 'Il circolo di Scipione' },
      { t: 'p', x: `Nel II secolo a.C. Panezio e lo storico Polibio frequentano Scipione Emiliano e i suoi amici. Panezio scrive pensando ai romani: un'etica che riguarda la vita pubblica, con i doveri e la grandezza d'animo al servizio dello Stato.` },
      { t: 'h', x: 'I filosofi in casa' },
      { t: 'p', x: `Nelle case dei grandi romani vivevano filosofi greci, come consiglieri e maestri. Cicerone tenne con sé lo stoico Diodoto e lo mantenne fino alla morte, nel 59 a.C., anche quando era diventato cieco. Catone ebbe accanto Antipatro di Tiro e Atenodoro di Tarso. Nel 78 a.C. Cicerone andò a Rodi a sentire Posidonio.` },
      { t: 'h', x: 'Cicerone, il traduttore' },
      { t: 'p', x: `Cicerone non era uno stoico di scuola, ma scrisse in latino i libri che fecero conoscere la filosofia greca a Roma. Nei *Doveri* riprese le idee di Panezio, e nei suoi dialoghi espose e discusse le dottrine stoiche. Con lui il latino diventa una lingua filosofica.` },
      { t: 'h', x: 'Catone, l\'esempio' },
      { t: 'p', x: `Catone il Giovane, che morì a Utica nel 46 a.C., divenne per gli stoici romani la figura esemplare di chi resta coerente con le proprie idee quando costa. Molto tempo dopo, il senatore Trasea Peto scrisse una sua biografia. Anche Seneca lo citerà spesso come modello.` },
      { t: 'h', x: 'Che cosa cambia' },
      { t: 'lista', x: [
        `Lo stoicismo greco era una scuola con un sistema. A Roma diventa una **guida per la vita pubblica e privata**.`,
        `Cresce il peso della giustizia e del dovere verso gli altri: ne parlano le pagine sulle virtù.`,
        `Con Seneca, Musonio ed Epitteto l'attenzione passa dallo Stato all'anima di ciascuno.`,
      ] },
      { t: 'azione', x: 'La giustizia', az: 'studio', id: 'virtu-giustizia' },
      { t: 'azione', x: 'Gli stoici sotto gli imperatori', az: 'studio', id: 'gli-stoici-e-il-potere' },
      { t: 'azione', x: 'La scuola in tre età', az: 'studio', id: 'le-tre-eta-della-stoa' },
    ],
  },
  {
    id: 'gli-stoici-e-il-potere',
    titolo: 'Gli stoici sotto gli imperatori',
    sotto: 'Quando la filosofia costa cara: coraggio, esilio e opposizione nel I secolo.',
    blocchi: [
      { t: 'p', x: `Nel I secolo d.C. lo stoicismo conta tra i suoi seguaci senatori e uomini di governo. Alcuni si trovano in contrasto con imperatori violenti, perché la scuola si considera custode della morale pubblica. Le storie che seguono mostrano che cosa voleva dire, per loro, essere coerenti.` },
      { t: 'h', x: 'Sotto Nerone' },
      { t: 'lista', x: [
        `**Seneca:** consigliere dell'imperatore, si ritira dalla vita pubblica nel 62. Nel 65 riceve l'ordine di togliersi la vita, dopo la congiura di Pisone. La scuola in quanto scuola non c'entrava con la congiura.`,
        `**Musonio Rufo:** nel 65 è mandato in esilio a Giaro, un'isola piccola e ostile del mar Egeo. Molti vanno fin là ad ascoltarlo.`,
        `**Trasea Peto:** senatore mite e leale, ammiratore di Catone. Non si presta alle adulazioni al potere e smette di frequentare il senato, dedicandosi ad attività utili ai concittadini. Nel 66 viene condannato a morte insieme a Barea Sorano.`,
      ] },
      { t: 'p', x: `Trasea non era un rivoluzionario. Aveva fatto la carriera pubblica ed era rimasto leale. Rifiutò soltanto di partecipare a ciò che riteneva vergognoso, e fu abbastanza per essere considerato un pericolo.` },
      { t: 'h', x: 'Sotto i Flavi' },
      { t: 'p', x: `Elvidio Prisco si era avvicinato allo stoicismo per temprare il carattere alle lotte della politica. Nel 71 l'imperatore Vespasiano bandì da Roma i filosofi, stoici e cinici in particolare. Musonio fu prima risparmiato, poi esiliato anche lui; Tito lo richiamò e gli assegnò un posto di fiducia.` },
      { t: 'h', x: 'Sotto Domiziano' },
      { t: 'p', x: `Domiziano prese provvedimenti contro i filosofi nell'89 e li inasprì nel 93 o nel 95. Giunio Aruleno Rustico fu condannato a morte, nel 93, per aver scritto la verità sulla morte di Trasea. Epitteto, bandito dall'Italia come gli altri filosofi, si trasferì a Nicopoli, in Grecia, dove aprì la sua scuola.` },
      { t: 'h', x: 'Che cosa insegna' },
      { t: 'lista', x: [
        `Il loro coraggio non è aggressivo. Scelgono ciò che dipende da loro: evitare l'adulazione, il tradimento e le ingiustizie.`,
        `Non tutti scelgono lo stesso modo. Seneca, dopo il ritiro, condannava ancora i tentativi di rovesciare l'imperatore, e Marco Aurelio governò l'impero per quasi vent'anni.`,
        `Il filo comune è la virtù messa prima del vantaggio: per questo li si ricorda.`,
      ] },
      { t: 'nota', x: `Sono storie di persone che hanno pagato molto. Sono raccontate per capire da dove viene la parola «coerenza» nello stoicismo, non per chiederti gesti eroici.` },
      { t: 'azione', x: 'Il coraggio', az: 'studio', id: 'virtu-coraggio' },
      { t: 'azione', x: 'La giustizia', az: 'studio', id: 'virtu-giustizia' },
      { t: 'azione', x: 'Musonio Rufo', az: 'studio', id: 'autore-musonio' },
    ],
  },
  {
    id: 'logica-fisica-etica',
    titolo: 'Logica, fisica, etica',
    sotto: 'Le tre parti della filosofia stoica e l\'immagine del frutteto.',
    blocchi: [
      { t: 'p', x: `Per gli stoici la filosofia ha tre parti che stanno insieme: la **logica**, la **fisica** e l'**etica**. Le hanno spesso illustrate con l'immagine di un frutteto.` },
      { t: 'passi', x: [
        { titolo: 'La logica è il muro.', testo: `Serve a difendere il frutteto dagli assalti esterni. È l'arte di ragionare bene: distinguere il vero dal falso, non farsi ingannare dalle apparenze.` },
        { titolo: 'La fisica è l\'albero.', testo: `È lo studio della natura e del mondo. Per gli stoici l'universo è ordinato dalla ragione: da questo ordine nascono le idee di «vivere secondo natura» e di accettare ciò che accade.` },
        { titolo: 'L\'etica è il frutto.', testo: `È lo scopo di tutto: come vivere bene. I frutti crescono sull'albero, e l'albero ha bisogno del muro.` },
      ] },
      { t: 'h', x: 'Perché stanno insieme' },
      { t: 'p', x: `Un'etica senza radici resta un'opinione. La fisica le dà le radici, perché mostra il posto dell'uomo nel mondo, e la logica la difende dai discorsi capziosi. Nell'insegnamento antico si partiva dalla logica, si passava all'etica e si arrivava alla fisica, che culminava nella riflessione sul divino.` },
      { t: 'h', x: 'Il legame con le tre discipline' },
      { t: 'p', x: `Epitteto riprende questa struttura e la volge alla pratica. Le sue tre discipline corrispondono alle tre parti: il **desiderio** alla fisica (accettare l'ordine delle cose), l'**azione** all'etica (fare ciò che è giusto) e il **giudizio** alla logica (esaminare le impressioni). Sono lo stesso frutteto, visto da chi lo abita ogni giorno.` },
      { t: 'h', x: 'In pratica' },
      { t: 'lista', x: [
        `Quando qualcosa ti turba, la **logica** è la domanda: «Che cosa è davvero accaduto, e che cosa ci ho aggiunto io?»`,
        `La **fisica** è lo sguardo largo: «Questo fa parte dell'ordine delle cose. Che cosa dipende da me?»`,
        `L'**etica** è la scelta: «Che cosa è giusto fare adesso, dato il mio ruolo?»`,
      ] },
      { t: 'nota', x: `Non serve conoscere la logica tecnica degli antichi per esercitarsi. Basta ricordare che i tre passi vanno insieme: capire, accettare, agire.` },
      { t: 'azione', x: 'Le tre discipline', az: 'studio', id: 'tre-discipline' },
      { t: 'azione', x: 'Le impressioni e il giudizio', az: 'studio', id: 'impressioni-giudizio' },
    ],
  },
  {
    id: 'la-cura-dell-anima',
    titolo: 'La filosofia come cura dell\'anima',
    sotto: 'Da Socrate a Seneca: perché gli antichi volevano guarire e non solo spiegare.',
    blocchi: [
      { t: 'p', x: `Per gli antichi la filosofia non era un sapere da accumulare: era una **cura**. L'idea ha un nome, la «cura dell'anima», e ha una storia lunga. È la ragione per cui questo corso racconta anche come gli stoici mettevano in pratica le loro idee.` },
      { t: 'h', x: 'Socrate' },
      { t: 'p', x: `Socrate girava per Atene a ripetere a tutti la stessa cosa: prima del corpo, della ricchezza e della fama, prenditi cura della tua anima, che diventi il più buona possibile. Per lui conoscere se stessi voleva dire esaminare che cosa si è capaci di fare e di essere.` },
      { t: 'h', x: 'Platone: l\'erba e la formula' },
      { t: 'p', x: `Nel dialogo *Carmide* Socrate propone un rimedio per il mal di testa: un'erba, accompagnata da una formula da pronunciare. L'erba è la medicina del corpo. La formula, spiega, sono i bei discorsi con cui si forma nell'anima la misura, cioè la temperanza. Il messaggio: non si cura una parte senza curare l'intero, e il corpo dipende anche dall'anima.` },
      { t: 'h', x: 'L\'età ellenistica' },
      { t: 'p', x: `Dopo Aristotele tutte le scuole concordano su uno scopo: rendere l'uomo felice, liberandolo dai turbamenti. Epicuro lo dice con un'immagine: una filosofia che lascia intatte le passioni dell'anima è inutile, come una medicina che lascia le malattie nel corpo.` },
      { t: 'p', x: `Gli stoici chiamano il traguardo **apatia**, cioè libertà dalle passioni. Ma per «passione» intendono un'emozione eccessiva, che nasce da un giudizio sbagliato. Le emozioni buone, come la gioia e la benevolenza, restano.` },
      { t: 'h', x: 'Seneca, il medico' },
      { t: 'p', x: `Seneca porta l'idea alle conseguenze estreme. I grandi mali, dice, stanno meno nelle cose che nel valore che diamo loro. Quindi non serve cambiare le cose: serve cambiare il modo di valutarle. Come un medico, scrive lettere e trattati per curare ciò che chiama i mali dell'anima: l'ira, la paura, il lutto, la fretta, il tempo sprecato.` },
      { t: 'h', x: 'Che cosa significa per te' },
      { t: 'lista', x: [
        `Le **pratiche** degli stoici sono le medicine: la preparazione del mattino, l'esame della sera, la riserva, lo sguardo dall'alto.`,
        `Le **pagine della Biblioteca** sono la diagnosi: aiutano a capire che cosa si sta curando.`,
        `Il **quaderno** è il diario della cura: serve a vedere i giudizi che ripetiamo.`,
      ] },
      { t: 'nota', x: `Ricordati il confine: è una cura dell'anima nel senso degli antichi, cioè un lavoro su come pensi e su come vivi. Non sostituisce il parere di un medico né una terapia.` },
      { t: 'azione', x: 'Gli esercizi spirituali', az: 'studio', id: 'esercizi-spirituali' },
      { t: 'azione', x: 'La vita di Seneca', az: 'studio', id: 'la-vita-di-seneca' },
      { t: 'azione', x: 'Le impressioni e il giudizio', az: 'studio', id: 'impressioni-giudizio' },
    ],
  },
  {
    id: 'la-vita-di-seneca',
    titolo: 'La vita di Seneca',
    sotto: 'Un filosofo tra il potere e l\'esilio: le tappe di una vita non semplice.',
    blocchi: [
      { t: 'p', x: `Per leggere Seneca conviene conoscere la sua vita. Non è la biografia di un saggio in disparte: è quella di un uomo di potere, con anni di malattia, di esilio e di errori. Le tappe che seguono servono a capire da dove parlano le sue lettere.` },
      { t: 'passi', x: [
        { titolo: 'Gli inizi (circa 4 a.C.).', testo: `Nasce a Cordova, in Spagna, da Seneca il Vecchio, maestro di retorica, e da Elvia. Ancora bambino è portato a Roma, dove studia retorica e comincia ad appassionarsi alla filosofia. I suoi maestri sono stoici e neopitagorici; con uno di loro pratica per un periodo una vita molto rigida, senza carne.` },
        { titolo: 'La salute e l\'Egitto.', testo: `Di costituzione fragile, forse asmatico, vive a lungo in Egitto presso una zia. Torna a Roma nel 31, fa l'avvocato con successo ed entra nella carriera pubblica: nel 33 è questore.` },
        { titolo: 'L\'esilio in Corsica (41–49).', testo: `Sotto l'imperatore Claudio, accusato in una vicenda di corte, è mandato in Corsica. Sono otto anni di vita solitaria. In questo periodo scrive *L'ira* e alcune consolazioni, tra cui quelle per la madre Elvia e per Polibio.` },
        { titolo: 'Il maestro di Nerone (dal 49).', testo: `Richiamato a Roma da Agrippina, diventa maestro del figlio di lei, Domizio, il futuro Nerone. Sperava di farne un buon sovrano: a questo periodo appartiene *La clemenza*.` },
        { titolo: 'Gli anni difficili (58–62).', testo: `Nel 58 è accusato di essersi arricchito e di vivere nel lusso. Nel 59 si trova coinvolto nell'uccisione di Agrippina, ordinata da Nerone. È il periodo più incerto della sua vita.` },
        { titolo: 'Il ritiro (62–65).', testo: `Nel 62 si allontana dalla vita politica e si dedica allo studio e alla scrittura. Nascono le *Lettere a Lucilio*, la sua opera più importante, concluse nel 65, e le *Questioni naturali*.` },
        { titolo: 'La fine (65).', testo: `Coinvolto nella congiura di Pisone, riceve da Nerone l'ordine di togliersi la vita.` },
      ] },
      { t: 'h', x: 'Che cosa ne ricaviamo' },
      { t: 'lista', x: [
        `Seneca parla di **tempo, di paura, di lutto e di ira** perché li ha conosciuti da vicino.`,
        `Le lettere nascono dal ritiro: sono il frutto di una vita che ha cambiato direzione.`,
        `Le accuse di lusso e di compromessi ci ricordano che non si chiede a un maestro di essere perfetto. Lui stesso diceva di scrivere per chi sta ancora cercando.`,
      ] },
      { t: 'azione', x: 'Seneca', az: 'studio', id: 'autore-seneca' },
      { t: 'azione', x: 'La filosofia come cura dell\'anima', az: 'studio', id: 'la-cura-dell-anima' },
      { t: 'azione', x: 'L\'ira secondo Seneca', az: 'studio', id: 'l-ira-secondo-seneca' },
    ],
  },
];
