// Pagine di studio della Fase 3, lotto 1: la mappa delle passioni, le virtù una per una, il glossario esteso e i sette autori.
// Stessi tipi di blocco di studio.js. Testi originali: le idee sono degli antichi, le parole sono nostre.

export const PAGINE_STUDIO_3A = [
  {
    id: 'mappa-delle-passioni',
    titolo: 'La mappa delle passioni',
    sotto: 'Venticinque emozioni che turbano, ordinate come facevano gli stoici.',
    blocchi: [
      { t: 'p', x: `Gli stoici non si limitavano a dire «le emozioni sbagliate sono quattro». Le antiche fonti ci hanno lasciato un elenco più fine, in cui ogni famiglia di passioni ha le sue sottospecie. Serve a dare un **nome preciso** a ciò che si sente, e dare un nome è già un primo passo per esaminarlo.` },
      { t: 'nota', x: `L'elenco viene dalla tradizione antica e le traduzioni italiane dei termini greci variano molto. Qui i nomi sono scelti per essere chiari, non per seguire una sola edizione.` },
      { t: 'h', x: 'Le sottospecie del desiderio (verso un bene che manca)' },
      { t: 'lista', x: [
        `**Bisogno:** vogliamo qualcosa e ci sentiamo incompleti senza.`,
        `**Ostilità:** un desiderio di male verso qualcuno, che cresce e si ripete.`,
        `**Rivalsa:** vogliamo far pagare un torto.`,
        `**Ira:** il desiderio di reagire subito a ciò che ci sembra un'offesa.`,
        `**Rancore:** l'ira che resta, si conserva e si rimastica.`,
        `**Passione amorosa:** il desiderio che ci prende e ci fa dipendere da una persona.`,
      ] },
      { t: 'h', x: 'Le sottospecie della paura (verso un male che potrebbe arrivare)' },
      { t: 'lista', x: [
        `**Esitazione:** la paura di agire che ci blocca.`,
        `**Vergogna:** la paura del giudizio degli altri.`,
        `**Spavento:** una paura improvvisa che toglie la voce.`,
        `**Sgomento:** una paura di fronte a qualcosa di insolito.`,
        `**Turbamento:** una paura confusa che agita il pensiero.`,
        `**Angoscia:** la paura senza un oggetto chiaro, che stringe.`,
      ] },
      { t: 'h', x: 'Le sottospecie del piacere (per un bene presente)' },
      { t: 'lista', x: [
        `**Compiacimento del male altrui:** gioire di una disgrazia che tocca qualcuno.`,
        `**Incanto:** il piacere che ci ammalia e ci distrae.`,
        `**Vanto:** il piacere di sentirsi superiori.`,
        `**Dissipazione:** il piacere che si scioglie in eccessi.`,
      ] },
      { t: 'h', x: 'Le sottospecie del dolore (per un male presente)' },
      { t: 'lista', x: [
        `**Compassione:** soffrire per il male che colpisce un altro, in modo che ci paralizza.`,
        `**Invidia:** soffrire per il bene di un altro.`,
        `**Gelosia:** soffrire perché un altro ha ciò che vorremmo solo per noi.`,
        `**Rivalità:** soffrire perché un altro ottiene ciò che anche noi vogliamo.`,
        `**Peso:** un dolore che opprime.`,
        `**Tormento:** un dolore che ci consuma dentro.`,
        `**Sconforto:** un dolore che ci fa arrendere.`,
        `**Smarrimento:** un dolore che confonde e toglie il filo dei pensieri.`,
        `**Pena:** il dolore di chi si abbandona.`,
      ] },
      { t: 'h', x: 'Come usarla' },
      { t: 'p', x: `Quando stai male, prova a cercare la voce che ti somiglia di più. Poi chiediti: quale giudizio c'è sotto? Per esempio, dietro il **bisogno** c'è spesso «senza questo non sto bene», e dietro la **vergogna** c'è «il parere degli altri decide il mio valore». Sono giudizi che si possono esaminare.` },
      { t: 'azione', x: 'Le quattro passioni', az: 'studio', id: 'le-quattro-passioni' },
      { t: 'azione', x: 'Esercizio: Fermati, impressione', az: 'esercizio', id: 'fermati-impressione' },
    ],
  },
  {
    id: 'virtu-saggezza',
    titolo: 'La saggezza',
    sotto: 'La virtù che vede le cose come sono e sceglie bene.',
    blocchi: [
      { t: 'p', x: `La saggezza è la prima delle quattro virtù. Per gli stoici è la capacità di **distinguere** ciò che è bene, ciò che è male e ciò che è indifferente. Da lei dipendono le altre: senza vedere chiaro, il coraggio diventa avventatezza e la giustizia diventa zelo cieco.` },
      { t: 'h', x: 'Che cosa la compone' },
      { t: 'lista', x: [
        `**Esame delle impressioni:** ogni cosa ci appare in un certo modo, e la saggezza controlla se è vero.`,
        `**Senso della misura del valore:** sapere che cosa pesa davvero e che cosa pesa poco.`,
        `**Prudenza:** guardare le conseguenze prima di agire.`,
        `**Memoria di ciò che dipende da noi:** ricordarlo nel momento in cui serve.`,
      ] },
      { t: 'h', x: 'Come si allena' },
      { t: 'p', x: `La saggezza si allena con piccoli esami quotidiani: fermarsi prima di rispondere, chiedersi da dove viene un'idea, controllare le parole con cui ci raccontiamo un fatto. Non è un sapere da libro: è un'abitudine di attenzione.` },
      { t: 'h', x: 'Un errore comune' },
      { t: 'p', x: `Saggezza non vuol dire sapere tutto né avere sempre ragione. Gli stoici stessi dicevano che il saggio perfetto è raro, forse mai esistito. Conta il **progresso**: essere oggi un po' più chiari di ieri.` },
      { t: 'azione', x: 'Le quattro virtù', az: 'studio', id: 'le-quattro-virtu' },
      { t: 'azione', x: 'Esercizio: Descrivi senza aggiungere', az: 'esercizio', id: 'descrivi-senza-aggiungere' },
    ],
  },
  {
    id: 'virtu-giustizia',
    titolo: 'La giustizia',
    sotto: 'La virtù che guarda agli altri: dare a ciascuno ciò che gli spetta.',
    blocchi: [
      { t: 'p', x: `Per gli stoici gli esseri umani sono fatti per stare insieme. La giustizia è la virtù che regola questo stare insieme: rispettare ciò che è dovuto agli altri e contribuire al bene comune. Marco Aurelio la ricorda spesso a se stesso: siamo nati per collaborare, come le due mani o i due occhi.` },
      { t: 'h', x: 'Che cosa la compone' },
      { t: 'lista', x: [
        `**Onestà:** dire il vero e mantenere ciò che si promette.`,
        `**Equità:** trattare le persone senza favoritismi.`,
        `**Benevolenza:** volere il bene di chi ci sta accanto, anche di chi è difficile.`,
        `**Senso del dovere sociale:** fare la propria parte, per piccola che sia.`,
      ] },
      { t: 'h', x: 'Nella vita di tutti i giorni' },
      { t: 'p', x: `La giustizia comincia nei gesti piccoli: rispondere a un messaggio, restituire ciò che si è preso, ascoltare fino in fondo, riconoscere il merito altrui. Epitteto insisteva sui **ruoli**: figlio, genitore, amico, cittadino, collega. Ogni ruolo ha i suoi doveri, e viverli bene è un modo di essere giusti.` },
      { t: 'h', x: 'Con chi ci fa torto' },
      { t: 'p', x: `Gli stoici pensavano che chi sbaglia sbagli per ignoranza: crede di fare il proprio bene e si inganna. Questo non giustifica l'errore, ma cambia lo sguardo: puoi difenderti senza odiare.` },
      { t: 'azione', x: 'Esercizio: Chi voglio essere qui', az: 'esercizio', id: 'chi-voglio-essere-qui' },
      { t: 'azione', x: 'Esercizio: Chi sbaglia non sa', az: 'esercizio', id: 'chi-sbaglia-non-sa' },
    ],
  },
  {
    id: 'virtu-coraggio',
    titolo: 'Il coraggio',
    sotto: 'La virtù di chi fa ciò che è giusto anche quando costa fatica.',
    blocchi: [
      { t: 'p', x: `Il coraggio stoico non è audacia né assenza di paura. È la capacità di **restare fedeli al giudizio giusto** anche quando qualcosa ci spaventa o ci costa. Chi è coraggioso sente la paura, ma non la lascia decidere.` },
      { t: 'h', x: 'Che cosa lo compone' },
      { t: 'lista', x: [
        `**Costanza:** continuare, senza cambiare rotta a ogni difficoltà.`,
        `**Pazienza:** sopportare ciò che non si può cambiare, senza lamento inutile.`,
        `**Fiducia nella propria scelta:** sapere che, se hai agito con onestà, hai fatto la tua parte.`,
        `**Capacità di resistere alla fatica:** quella del corpo e quella della mente.`,
      ] },
      { t: 'h', x: 'Due forme' },
      { t: 'p', x: `C'è il coraggio di **agire**: dire una cosa scomoda, cominciare un compito temuto, chiedere scusa. E c'è il coraggio di **sopportare**: reggere una perdita, una malattia, un'attesa. Gli stoici lo allenavano con piccole prove volontarie e con la premeditazione dei mali.` },
      { t: 'h', x: 'Come si allena' },
      { t: 'p', x: `Scegli ogni tanto una piccola scomodità da affrontare, senza necessità e senza esagerare. Serve a ricordare che si può stare anche senza ciò a cui ci si è abituati. La paura si ridimensiona quando la si conosce.` },
      { t: 'azione', x: 'Esercizio: Prepararsi al peggio', az: 'esercizio', id: 'prepararsi-al-peggio' },
      { t: 'azione', x: 'Esercizio: Il primo gesto piccolo', az: 'esercizio', id: 'il-primo-gesto-piccolo' },
    ],
  },
  {
    id: 'virtu-temperanza',
    titolo: 'La temperanza',
    sotto: 'La virtù della misura: desiderare quanto basta.',
    blocchi: [
      { t: 'p', x: `La temperanza è la virtù che dà **misura** ai desideri e ai piaceri. Gli stoici la distinguevano dall'astinenza: il piacere si può godere, purché non diventi un bisogno. Chi è temperante può godere di una buona cena e, il giorno dopo, mangiare poco senza lamentarsi.` },
      { t: 'h', x: 'Che cosa la compone' },
      { t: 'lista', x: [
        `**Ordine:** fare le cose al momento giusto, nel modo giusto.`,
        `**Pudore:** un rispetto di sé che evita ciò che sminuisce.`,
        `**Sobrietà:** usare le cose senza farsene usare.`,
        `**Autocontrollo:** fermarsi prima che il desiderio decida per noi.`,
      ] },
      { t: 'h', x: 'Nella vita di tutti i giorni' },
      { t: 'p', x: `Oggi la temperanza tocca il cibo, il telefono, gli acquisti, il lavoro, i confronti con gli altri. Il segnale è semplice: se una cosa ti trascina e poi ti lascia peggio di prima, è il momento di rimettere una misura.` },
      { t: 'h', x: 'Un esercizio antico' },
      { t: 'p', x: `Seneca consigliava di scegliere ogni tanto qualche giorno di vita più semplice: cibo modesto, vestiti poveri, letto duro. Poi ci si domanda: è questo che temevo? Spesso la risposta è no, e la paura di perdere le comodità si scioglie.` },
      { t: 'azione', x: 'Esercizio: Quanto basta', az: 'esercizio', id: 'quanto-basta' },
      { t: 'azione', x: 'Esercizio: Il riposo ha la sua misura', az: 'esercizio', id: 'il-riposo-ha-la-sua-misura' },
    ],
  },
  {
    id: 'glossario-2',
    titolo: 'Glossario: altri termini',
    sotto: 'Ventisei parole in più, per leggere gli stoici con più sicurezza.',
    blocchi: [
      { t: 'p', x: `Questa pagina continua il glossario essenziale. I termini sono in ordine alfabetico, con il greco tra parentesi dove serve.` },
      { t: 'lista', x: [
        `**Accettazione:** il modo stoico di stare davanti a ciò che non dipende da noi: si riconosce com'è, senza lottare contro il fatto.`,
        `**Amor fati:** espressione moderna, non degli antichi, che riassume l'invito a volere ciò che accade.`,
        `**Apatia** (*apátheia*): per gli stoici non è indifferenza, ma libertà dalle passioni.`,
        `**Buona emozione** (*eupátheia*): le emozioni che nascono da un giudizio giusto, come la gioia e la benevolenza.`,
        `**Cosmopoli:** la città comune di tutti gli esseri umani, al di là dei confini.`,
        `**Dicotomia del controllo:** il modo moderno di chiamare la distinzione tra ciò che è in nostro potere e il resto.`,
        `**Equanimità:** la calma di chi resta uguale a sé nella buona e nella cattiva sorte.`,
        `**Eudaimonia:** una vita fiorita, riuscita. Per gli stoici coincide con la virtù.`,
        `**Esame di coscienza:** la revisione serale della giornata, come la faceva Seneca.`,
        `**Esercizi spirituali:** pratiche di pensiero e di attenzione con cui ci si trasforma.`,
        `**Fato:** l'ordine delle cause con cui il mondo procede. Per gli stoici nulla è casuale.`,
        `**Gioia:** l'emozione buona che nasce da ciò che è davvero bene.`,
        `**Impassibilità:** un modo sbagliato di capire lo stoicismo: gli stoici chiedevano di curare le emozioni, senza cancellarle.`,
        `**Ira:** la passione contro cui Seneca scrisse tre libri.`,
        `**Ordine della natura:** la razionalità che gli stoici vedevano in tutto il mondo.`,
        `**Ostacolo:** ciò che si frappone e che diventa materia per esercitare la virtù.`,
        `**Premeditazione dei mali:** immaginare in anticipo un male possibile, per prepararsi.`,
        `**Preferibile:** ciò che è da preferire (salute, amici) senza che sia essenziale alla virtù.`,
        `**Presente:** l'unico tempo su cui abbiamo presa. Il passato è chiuso e il futuro deve ancora venire.`,
        `**Provvidenza:** la fiducia che il mondo sia ordinato. Non tutti gli stoici la vedevano allo stesso modo.`,
        `**Ragione:** la capacità di esaminare ciò che pensiamo. Ci accomuna tutti.`,
        `**Ruolo:** la parte che ci è data (figlio, genitore, cittadino). Ha dei doveri.`,
        `**Sguardo dall'alto:** l'esercizio di immaginare la propria vita dall'alto, per ridimensionarla.`,
        `**Sobrietà:** il vivere con poco senza sentirsi poveri.`,
        `**Tempo:** il bene più prezioso e meno custodito, secondo Seneca.`,
        `**Uso delle impressioni:** il modo in cui si maneggia ciò che appare alla mente.`,
      ] },
      { t: 'azione', x: 'Glossario essenziale', az: 'studio', id: 'glossario' },
    ],
  },
  {
    id: 'autore-epitteto',
    titolo: 'Epitteto',
    sotto: 'Uno schiavo diventato maestro: la filosofia come esercizio quotidiano.',
    blocchi: [
      { t: 'p', x: `Epitteto nacque a Ierapoli, in Frigia, tra il 50 e il 60 d.C., e da giovane fu schiavo a Roma. Ottenuta la libertà, insegnò filosofia. Quando l'imperatore Domiziano cacciò i filosofi dall'Italia, si stabilì a Nicopoli, in Grecia, dove ebbe una scuola frequentata da molti giovani. Morì in tarda età, verso il 138, negli stessi anni dell'imperatore Adriano.` },
      { t: 'h', x: 'Le opere' },
      { t: 'p', x: `Epitteto non scrisse nulla. Le sue lezioni ci sono arrivate grazie a un allievo, **Arriano**, che le trascrisse nei *Discorsi* (di cui restano quattro libri) e ne trasse un piccolo compendio, il *Manuale* (*Encheiridion*).` },
      { t: 'h', x: 'Le idee centrali' },
      { t: 'lista', x: [
        `**Il confine del controllo.** Il punto di partenza di tutto.`,
        `**Le tre discipline:** desiderio, azione e giudizio, tre campi in cui esercitarsi.`,
        `**I ruoli:** ognuno ha una parte da recitare bene, senza scegliere quale.`,
        `**Il maestro come medico:** la scuola è un ambulatorio dove si curano i giudizi.`,
      ] },
      { t: 'h', x: 'Il suo stile' },
      { t: 'p', x: `Diretto, spesso duro, pieno di esempi quotidiani. Epitteto sa che le idee non bastano: vanno esercitate ogni giorno. Non a caso il suo insegnamento è diventato la base degli esercizi di questa app.` },
      { t: 'azione', x: 'Il Manuale di Epitteto', az: 'studio', id: 'il-manuale-di-epitteto' },
      { t: 'azione', x: 'Esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'autore-seneca',
    titolo: 'Seneca',
    sotto: 'Il filosofo che scrive lettere: caldo, pratico, pieno di vita.',
    blocchi: [
      { t: 'p', x: `Lucio Anneo Seneca nacque a Cordova, in Spagna, attorno al 4 a.C., e crebbe a Roma. Fu scrittore, avvocato, uomo politico. Sotto Claudio fu mandato in esilio in Corsica per otto anni. Tornato a Roma, divenne maestro e consigliere del giovane Nerone. Nel 65 d.C., accusato di aver partecipato a una congiura, fu costretto a togliersi la vita.` },
      { t: 'h', x: 'Le opere' },
      { t: 'lista', x: [
        `**Lettere a Lucilio:** centoventiquattro lettere a un amico, su come vivere.`,
        `**La brevità della vita, La tranquillità dell'animo, La vita felice:** trattati sul tempo e sulla serenità.`,
        `**L'ira:** tre libri sulla passione che più lo preoccupava.`,
        `**Consolazioni:** lettere a chi è in lutto.`,
        `**Tragedie:** drammi di ambientazione mitica, in un genere diverso dalle opere morali.`,
      ] },
      { t: 'h', x: 'Le idee centrali' },
      { t: 'lista', x: [
        `**Il tempo:** la sola vera ricchezza, e la più sprecata.`,
        `**La premeditazione dei mali:** guardarli in faccia per non esserne travolti.`,
        `**L'esame della sera:** rivedere la giornata con benevolenza e onestà.`,
        `**L'ira:** capirla, rimandarla, correggerne le cause.`,
      ] },
      { t: 'h', x: 'Un maestro imperfetto' },
      { t: 'p', x: `Seneca visse nella ricchezza e nel potere, e già i contemporanei glielo rimproveravano. Lui lo ammetteva: diceva di scrivere per chi cerca di migliorare, senza salire su un piedistallo. Questa onestà rende le sue pagine più credibili, non meno.` },
      { t: 'azione', x: "L'ira secondo Seneca", az: 'studio', id: 'l-ira-secondo-seneca' },
      { t: 'azione', x: 'Esercizio: Esame della sera', az: 'esercizio', id: 'esame-della-sera' },
      { t: 'azione', x: 'La vita di Seneca', az: 'studio', id: 'la-vita-di-seneca' },
    ],
  },
  {
    id: 'autore-marco-aurelio',
    titolo: 'Marco Aurelio',
    sotto: "L'imperatore che scrive a se stesso per restare fedele ai suoi principi.",
    blocchi: [
      { t: 'p', x: `Marco Aurelio nacque a Roma nel 121 d.C. e fu imperatore dal 161 alla morte, nel 180. Regnò negli anni di guerre di confine, di una grave epidemia e di crisi economiche. Passò molti anni all'accampamento, sulle frontiere del Danubio.` },
      { t: 'h', x: "L'opera" },
      { t: 'p', x: `Scrisse in greco un quaderno di riflessioni personali, oggi chiamato in italiano *A se stesso* o *Pensieri*. Non era destinato alla pubblicazione: sono appunti per ricordarsi ogni giorno di ciò in cui credeva. Il primo libro è un elenco di gratitudini verso chi lo ha formato.` },
      { t: 'h', x: 'Le idee centrali' },
      { t: 'lista', x: [
        `**Vedere le cose come sono:** togliere alle impressioni ciò che vi aggiungiamo.`,
        `**La brevità del tempo:** ricordarsi che tutto passa, per dare il giusto peso alle cose.`,
        `**La collaborazione:** siamo nati per aiutarci, come parti di un unico corpo.`,
        `**Il rifugio interiore:** un luogo di calma che possiamo trovare dentro di noi.`,
      ] },
      { t: 'h', x: 'Come leggerlo' },
      { t: 'p', x: `Non è un trattato: va letto a piccole dosi, una o due pagine alla volta. Le frasi tornano, cambiano forma, si correggono. È il diario di un uomo che si esercita, non di uno che ha già trovato tutte le risposte.` },
      { t: 'azione', x: 'Meditazione: La mattina', az: 'meditazione', id: 'la-mattina' },
      { t: 'azione', x: 'Esercizio: Il rifugio dentro', az: 'esercizio', id: 'il-rifugio-dentro' },
    ],
  },
  {
    id: 'autore-musonio',
    titolo: 'Musonio Rufo',
    sotto: 'Il maestro di Epitteto: una filosofia da praticare ogni giorno.',
    blocchi: [
      { t: 'p', x: `Gaio Musonio Rufo nacque in Etruria attorno al 30 d.C. e fu cavaliere romano. Insegnò filosofia a Roma e fu esiliato più volte, sotto Nerone e sotto Vespasiano, per le sue idee libere. Fu maestro di Epitteto. Richiamato a Roma dall'imperatore Tito, vi insegnò ancora per molti anni.` },
      { t: 'h', x: 'Le opere' },
      { t: 'p', x: `Come Epitteto, non scrisse libri. Un allievo, **Lucio**, raccolse appunti delle sue lezioni: ci restano una ventina di brevi discorsi e alcuni frammenti.` },
      { t: 'h', x: 'Le idee centrali' },
      { t: 'lista', x: [
        `**La filosofia si pratica:** un ragionamento senza pratica è come un medico che non cura.`,
        `**L'esercizio del corpo e della mente:** insieme, con semplicità e senza eccessi.`,
        `**Una vita sobria:** cibo, vestiti e casa essenziali, non per punirsi ma per essere liberi.`,
        `**Gli stessi doveri per tutti:** Musonio sosteneva che anche le donne dovessero studiare filosofia, un'idea insolita nel suo tempo.`,
      ] },
      { t: 'h', x: 'Perché leggerlo' },
      { t: 'p', x: `Musonio dà l'impressione di un uomo che parla in una stanza, ai suoi allievi, con parole semplici. È utile per capire da dove viene la sobrietà pratica di Epitteto.` },
      { t: 'azione', x: 'Come leggere gli stoici', az: 'studio', id: 'come-leggere' },
      { t: 'azione', x: 'Esercizio: Quanto basta', az: 'esercizio', id: 'quanto-basta' },
      { t: 'azione', x: 'Gli stoici sotto gli imperatori', az: 'studio', id: 'gli-stoici-e-il-potere' },
    ],
  },
  {
    id: 'autore-zenone',
    titolo: 'Zenone di Cizio',
    sotto: 'Il fondatore: un naufrago che aprì una scuola sotto un portico.',
    blocchi: [
      { t: 'p', x: `Zenone nacque a Cizio, nell'isola di Cipro, attorno al 334 a.C. Era un mercante. Secondo la tradizione, una nave con il suo carico fece naufragio vicino ad Atene e lui, arrivato in città, si accostò alla filosofia. Frequentò varie scuole e infine cominciò a insegnare sotto un portico dipinto, la **Stoà Poikile**, da cui la sua scuola prese il nome.` },
      { t: 'h', x: 'Le opere' },
      { t: 'p', x: `Le sue opere sono perdute. Ne restano titoli e citazioni in autori successivi, come Diogene Laerzio, raccolti nell'edizione dei frammenti di von Arnim.` },
      { t: 'h', x: 'Le idee centrali' },
      { t: 'lista', x: [
        `**Vivere in accordo con la natura:** la formula con cui riassumeva il fine della vita.`,
        `**La filosofia in tre parti:** logica, fisica ed etica, legate tra loro.`,
        `**Una città ideale universale:** una comunità in cui tutti sono cittadini, senza confini.`,
        `**Il valore della semplicità:** una vita frugale, coerente con ciò che si pensa.`,
      ] },
      { t: 'azione', x: 'Gli stoici antichi', az: 'studio', id: 'stoici-antichi' },
      { t: 'azione', x: 'La scuola in tre età', az: 'studio', id: 'le-tre-eta-della-stoa' },
    ],
  },
  {
    id: 'autore-cleante',
    titolo: 'Cleante',
    sotto: 'Il pugile che diventò filosofo: un lavoratore instancabile.',
    blocchi: [
      { t: 'p', x: `Cleante nacque ad Asso, nella Troade, nel 331 a.C. secondo la tradizione antica, ma forse più tardi. Fu pugile, dice la tradizione, e, arrivato ad Atene, faceva il portatore d'acqua di notte per pagarsi le lezioni di Zenone. Gli succedette alla guida della scuola e la tenne per circa trent'anni.` },
      { t: 'h', x: "L'opera" },
      { t: 'p', x: `Di Cleante ci resta soprattutto l'**Inno a Zeus**, una preghiera in versi. Vi esprime la fiducia in un ordine razionale del mondo e chiede di accettarlo senza lamento. Fu un testo caro agli stoici, che Epitteto ricorda volentieri.` },
      { t: 'h', x: 'Le idee centrali' },
      { t: 'lista', x: [
        `**L'accettazione:** seguire volentieri ciò che accade, e non trascinati.`,
        `**La costanza:** un impegno lento e paziente, più che geniale.`,
        `**Il valore del lavoro:** la filosofia si sostiene con la fatica quotidiana.`,
      ] },
      { t: 'h', x: 'Perché ricordarlo' },
      { t: 'p', x: `Cleante mostra che lo stoicismo non nasce in una torre d'avorio: viene da una vita di lavoro, di sacrificio e di perseveranza. Il suo passo è una buona compagnia quando la strada sembra lunga.` },
      { t: 'azione', x: 'Gli stoici antichi', az: 'studio', id: 'stoici-antichi' },
    ],
  },
  {
    id: 'autore-crisippo',
    titolo: 'Crisippo',
    sotto: "Il sistematore: colui che diede allo stoicismo la sua forma completa.",
    blocchi: [
      { t: 'p', x: `Crisippo nacque a Soli, in Cilicia, attorno al 280 a.C. Giunto ad Atene, studiò con Cleante e ne prese la guida. Fu un autore prolifico: la tradizione gli attribuisce centinaia di opere. Morì attorno al 206 a.C.` },
      { t: 'h', x: 'Il ruolo' },
      { t: 'p', x: `Gli antichi lo consideravano il secondo fondatore della scuola: si diceva che, senza di lui, lo stoicismo non sarebbe esistito. Sistemò la logica, ampliò la fisica, precisò l'etica e difese la dottrina dalle obiezioni.` },
      { t: 'h', x: 'Le opere' },
      { t: 'p', x: `Anche di Crisippo restano soprattutto frammenti, raccolti nei volumi di von Arnim. Una parte riguarda le passioni: le considerava **giudizi sbagliati** e non impulsi estranei alla ragione, una tesi che ha segnato tutto lo stoicismo successivo.` },
      { t: 'h', x: 'Le idee centrali' },
      { t: 'lista', x: [
        `**Le passioni come giudizi:** l'emozione nasce dal modo in cui interpretiamo.`,
        `**La logica come strumento:** ragionare bene serve a vivere bene.`,
        `**Il destino e la libertà:** un tentativo di conciliare un mondo ordinato e la nostra responsabilità.`,
      ] },
      { t: 'azione', x: 'Le quattro passioni', az: 'studio', id: 'le-quattro-passioni' },
    ],
  },
];
