// Pagine di studio sullo stoicismo. Testi originali: le idee sono degli autori antichi, le parole sono nostre.
// Tipi di blocco: h (titolo), p (testo), lista, passi, nota, azione. Nel testo, **così** diventa grassetto.
// Un blocco «azione» apre un esercizio (az: 'esercizio'), una pagina di studio (az: 'studio') o una meditazione (az: 'meditazione').

import { PAGINE_STUDIO_3A } from './studio3.js';
import { PAGINE_STUDIO_3B } from './studio4.js';
import { PAGINE_STUDIO_4 } from './studio5.js';

const PAGINE_BASE = [
  {
    id: 'cose-lo-stoicismo',
    titolo: "Che cos'è lo stoicismo",
    sotto: 'Una filosofia che è anche un modo di vivere, nata ad Atene più di duemila anni fa.',
    blocchi: [
      { t: 'p', x: `Lo stoicismo è una scuola filosofica nata ad Atene attorno al 300 a.C. Il nome viene dalla **Stoà Poikile**, il «portico dipinto» dove il suo fondatore, **Zenone di Cizio**, teneva le lezioni. Portico in greco si dice *stoà*: gli stoici sono, alla lettera, «quelli del portico».` },
      { t: 'p', x: `Per gli stoici la filosofia non era soltanto una teoria da studiare: era un'**arte di vivere**. Serviva a essere più liberi, più sereni e più giusti. Molti testi antichi sono esercizi che l'autore pratica e fa praticare al lettore, non trattati da leggere e basta.` },
      { t: 'h', x: 'Tre parti, un solo scopo' },
      { t: 'p', x: `Gli stoici dividevano la filosofia in tre parti: la **logica** (come si ragiona e si giudica), la **fisica** (come è fatto il mondo e qual è il nostro posto in esso) e l'**etica** (come si vive e si agisce). Non erano tre materie separate: erano tre modi di allenare la stessa cosa, la capacità di vivere bene.` },
      { t: 'h', x: 'Tre epoche' },
      { t: 'lista', x: [
        `**Lo stoicismo antico** (dal 300 a.C.): Zenone, Cleante e Crisippo. Ci restano quasi solo frammenti, raccolti dagli studiosi.`,
        `**Lo stoicismo di mezzo:** filosofi come Panezio e Posidonio portano lo stoicismo a Roma.`,
        `**Lo stoicismo romano** (dal I secolo d.C.): Seneca, Musonio Rufo, Epitteto e Marco Aurelio. Sono loro che ci hanno lasciato i testi più letti.`,
      ] },
      { t: 'h', x: 'Quattro idee da cui partire' },
      { t: 'lista', x: [
        `**Ciò che dipende da noi.** Alcune cose sono in nostro potere (i nostri giudizi, le nostre scelte), altre no (gli eventi, le altre persone, il passato).`,
        `**La ragione.** L'essere umano ha la capacità di esaminare ciò che pensa prima di crederci.`,
        `**La virtù.** Per gli stoici il vero bene è vivere con saggezza, giustizia, coraggio e misura. Il resto (salute, ricchezze, fama) è preferibile ma non decide la nostra vita.`,
        `**La comunità.** Siamo parte di una comunità umana: agire con giustizia verso gli altri è parte del vivere bene.`,
      ] },
      { t: 'h', x: 'Che cosa promette e che cosa no' },
      { t: 'p', x: `Lo stoicismo promette una **libertà interiore**: un modo di stare nelle cose che dipende meno da ciò che accade. Non promette una vita senza dolore né un carattere di ferro. Promette un lavoro, da fare a poco a poco, con esercizi semplici.` },
      { t: 'azione', x: 'Prova un primo esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'falsi-miti',
    titolo: 'Falsi miti',
    sotto: 'Che cosa lo stoicismo non è, contro il modo comune di dire «stoico».',
    blocchi: [
      { t: 'p', x: `Nel parlare comune «stoico» vuol dire chi sopporta in silenzio, senza emozioni. È un equivoco, e vale la pena chiarirlo, perché cambia il modo di usare questa filosofia.` },
      { t: 'h', x: 'Falso: lo stoico non prova emozioni' },
      { t: 'p', x: `Gli stoici distinguevano le **passioni** (paura, desiderio smodato, dolore, piacere sfrenato), cioè le emozioni che nascono da un giudizio sbagliato, da alcune **emozioni buone**, come una gioia serena, una prudenza ragionevole e una volontà giusta. Chiedevano di capire ciò che si sente, non di smettere di sentire. Anche le reazioni immediate del corpo, come un sussulto, un rossore, un brivido, sono per Seneca del tutto naturali: la passione comincia dopo, quando ci crediamo.` },
      { t: 'h', x: 'Falso: bisogna sopportare tutto senza reagire' },
      { t: 'p', x: `La distinzione fondamentale separa le cose in nostro potere da quelle che non lo sono. Ciò che è in nostro potere, per esempio agire con giustizia, va fatto con impegno. Gli stoici furono spesso attivi nella vita pubblica, e Marco Aurelio governò un impero. Accettare ciò che è fuori dal nostro potere è diverso dal rinunciare a cambiare ciò che possiamo cambiare.` },
      { t: 'h', x: 'Falso: è una filosofia fredda e individualista' },
      { t: 'p', x: `Gli stoici si sentivano cittadini del mondo. Per loro tutti gli esseri umani appartengono a un'unica comunità, e la giustizia verso gli altri fa parte del vivere bene. Marco Aurelio ricorda a se stesso di essere nato per collaborare, come le mani di un solo corpo.` },
      { t: 'h', x: 'Falso: è pensiero positivo' },
      { t: 'p', x: `Gli stoici guardavano la realtà com'è, anche nei suoi aspetti duri. Praticavano perfino l'esercizio di immaginare in anticipo le difficoltà, per affrontarle con più calma. Non si tratta di ripetersi che andrà tutto bene, ma di prepararsi a vivere anche quando non andrà tutto bene.` },
      { t: 'h', x: 'Falso: è per persone forti o perfette' },
      { t: 'p', x: `Gli stoici si consideravano dei «progredienti»: persone in cammino. Seneca ed Epitteto parlano continuamente delle proprie difficoltà e di quelle dei loro allievi. Il punto non è essere perfetti, ma esercitarsi.` },
      { t: 'h', x: 'Falso: è una filosofia da citazioni' },
      { t: 'p', x: `Le frasi celebri, isolate, fanno poco. Il cuore dello stoicismo sono gli **esercizi**: pratiche precise, da ripetere, che cambiano poco a poco il modo di vedere. Per questo Stoicismo quotidiano propone esercizi e non soltanto frasi.` },
      { t: 'h', x: 'Falso: è fatalismo' },
      { t: 'p', x: `Gli stoici non dicevano «tanto è tutto scritto». Dicevano: impegnati con tutte le forze in ciò che dipende da te, e accetta con calma l'esito. Uno dei loro esercizi consiste proprio nell'agire con una riserva: «lo farò, se nulla lo impedisce».` },
      { t: 'azione', x: 'Leggi che cosa sono le tre discipline', az: 'studio', id: 'tre-discipline' },
    ],
  },
  {
    id: 'cosa-dice-la-ricerca',
    titolo: 'Che cosa dice la ricerca',
    sotto: 'Che cosa sappiamo oggi sull\'efficacia degli esercizi stoici, e che cosa ancora no.',
    blocchi: [
      { t: 'p', x: `Lo stoicismo è una pratica antica, ma da qualche anno è anche oggetto di studio scientifico. Qui trovi che cosa è stato verificato e che cosa è ancora aperto. Le prove sono poche e giovani: le presentiamo con prudenza.` },
      { t: 'h', x: 'Da lì viene la psicoterapia cognitiva' },
      { t: 'p', x: `**Albert Ellis** e **Aaron Beck**, i fondatori delle terapie cognitive e comportamentali (oggi tra le più studiate), hanno dichiarato di essersi ispirati agli stoici. L'idea comune è che le emozioni dipendano anche dal modo in cui interpretiamo ciò che accade. Ellis citava spesso Epitteto: non sono le cose a turbarci, ma i giudizi che ne diamo.` },
      { t: 'p', x: `Anche la mindfulness ha un antenato in un esercizio stoico, l'**attenzione** al momento presente. Questo collegamento è descritto in un articolo pubblicato nel 2023 sulla rivista *Neurological Sciences* (Cavanna e altri).` },
      { t: 'h', x: 'Una prova controllata' },
      { t: 'p', x: `Nel 2025 una ricerca dell'Università Royal Holloway di Londra ha assegnato a sorte 119 persone a due gruppi: uno ha fatto per due settimane esercizi stoici quotidiani online, l'altro è rimasto in attesa. Il primo gruppo ha avuto **meno sintomi di depressione** e ha evitato meno i propri stati interiori. L'ansia è migliorata soltanto a un mese di distanza.` },
      { t: 'h', x: 'Stoic Week' },
      { t: 'p', x: `Ogni anno, dal 2013, migliaia di persone seguono per una settimana pratiche stoiche e misurano il proprio benessere prima e dopo. Dai rapporti risultano miglioramenti nella soddisfazione di vita e nella resilienza. Sono dati utili ma limitati: chi partecipa si sceglie da solo e manca un gruppo di confronto.` },
      { t: 'h', x: 'Che cosa ancora non sappiamo' },
      { t: 'lista', x: [
        `Se i benefici durano a lungo, oltre pochi mesi.`,
        `Quali esercizi funzionano meglio, e per quali persone.`,
        `Se lo stoicismo funziona meglio o peggio delle altre pratiche, come la mindfulness o la terapia cognitiva.`,
      ] },
      { t: 'nota', x: `Gli esercizi stoici sono un aiuto per il pensiero e l'attenzione. Possono affiancare, ma non sostituire, il parere del medico o un percorso di cura.` },
      { t: 'azione', x: 'Prova un esercizio', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'tre-discipline',
    titolo: 'Le tre discipline',
    sotto: 'La chiave con cui Epitteto, e dopo di lui Marco Aurelio, ordinano gli esercizi.',
    blocchi: [
      { t: 'p', x: `Epitteto dice che chi vuole diventare un uomo migliore deve esercitarsi in tre ambiti. Questa tripartizione è la chiave di lettura anche dei pensieri di Marco Aurelio. Sono le **tre discipline**, e in Stoicismo quotidiano sono la bussola con cui ti chiediamo: dove ti sei perso?` },
      { t: 'passi', x: [
        { titolo: 'La disciplina del desiderio e della paura.', testo: `Riguarda ciò che vogliamo e ciò che temiamo. Insegna a desiderare e a evitare solo ciò che dipende da noi, e ad accogliere con calma il resto. Corrisponde, nella filosofia stoica, alla **fisica**: vedere gli eventi nel loro posto nell'ordine più grande delle cose.` },
        { titolo: "La disciplina dell'azione.", testo: `Riguarda ciò che facciamo e i nostri doveri: agire con giustizia, con misura, pensando agli altri. Corrisponde all'**etica**.` },
        { titolo: 'La disciplina del giudizio.', testo: `Riguarda ciò che pensiamo: non credere alle prime impressioni, distinguere ciò che è vero da ciò che è solo apparente. Corrisponde alla **logica**.` },
      ] },
      { t: 'h', x: 'Da dove cominciare' },
      { t: 'p', x: `Epitteto consiglia di cominciare dalla prima, il desiderio e la paura, perché è la più urgente: è lì che nasce gran parte dell'infelicità. La disciplina del giudizio è la più fine e la più difficile, e la lasciava agli allievi più avanti.` },
      { t: 'h', x: 'Come le usa la app' },
      { t: 'lista', x: [
        `**Giudizio:** «Ciò che mi turba è il fatto, o quello che ne ho concluso?»`,
        `**Desiderio e paura:** «Sto cercando di controllare ciò che non dipende da me?»`,
        `**Azione:** «Che cosa devo fare, adesso, davvero?»`,
      ] },
      { t: 'p', x: `Le tre discipline si tengono insieme: quando cambia il giudizio, cambia anche il desiderio, e cambia l'azione. Puoi partire da qualunque punto.` },
      { t: 'azione', x: 'Esercizio del giudizio: Fermati, impressione', az: 'esercizio', id: 'fermati-impressione' },
      { t: 'azione', x: "Esercizio dell'azione: Il primo gesto piccolo", az: 'esercizio', id: 'il-primo-gesto-piccolo' },
      { t: 'azione', x: 'Logica, fisica, etica', az: 'studio', id: 'logica-fisica-etica' },
    ],
  },
  {
    id: 'cio-che-dipende-da-noi',
    titolo: 'Ciò che dipende da noi',
    sotto: 'La distinzione da cui parte il Manuale di Epitteto.',
    blocchi: [
      { t: 'p', x: `Il *Manuale* di Epitteto comincia con una regola semplice: alcune cose dipendono da noi, altre no. Da qui discende quasi tutto il resto. Imparare a distinguere le due cose, ogni volta, è già metà del lavoro.` },
      { t: 'h', x: 'Dipende da noi' },
      { t: 'lista', x: [
        `Ciò che **pensiamo** e **giudichiamo**.`,
        `Ciò che **vogliamo** e ciò che **rifiutiamo**.`,
        `Il modo in cui **scegliamo di agire**.`,
      ] },
      { t: 'h', x: 'Non dipende da noi' },
      { t: 'lista', x: [
        `Il **corpo** e la sua salute.`,
        `Le **ricchezze**, la posizione, i ruoli.`,
        `La **reputazione**: che cosa gli altri pensano di noi.`,
        `Ciò che **decidono gli altri**, e l'esito finale delle cose.`,
        `Il **passato**.`,
      ] },
      { t: 'h', x: 'Che cosa succede quando le confondiamo' },
      { t: 'p', x: `Se trattiamo come nostro ciò che appartiene ad altri o al caso, rischiamo l'ansia (perché non possiamo garantirlo) e la delusione (perché può sfuggirci). Se trattiamo come non nostro ciò che lo è, rischiamo l'impotenza: ci sentiamo in balia di tutto, anche di ciò che potremmo cambiare.` },
      { t: 'h', x: 'Un errore comune' },
      { t: 'p', x: `Non significa disinteressarsi delle cose: significa mettere il proprio impegno dove serve. Tieni alla salute, al lavoro, alle persone: fai tutto ciò che è in tuo potere. Poi accetta con calma che l'esito non sia nelle tue mani. Gli stoici lo dicevano con la formula «se nulla lo impedisce».` },
      { t: 'h', x: 'Le zone grigie' },
      { t: 'p', x: `Molte situazioni sono miste: la salute dipende in parte da come ti curi, il lavoro in parte da come lo fai. In quei casi fai la tua parte con impegno e lascia il resto. La domanda utile è sempre la stessa: che cosa, qui, è davvero in mano mia?` },
      { t: 'azione', x: 'Fai l\'esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
      { t: 'azione', x: 'Fai l\'esercizio: Se nulla lo impedisce', az: 'esercizio', id: 'se-nulla-lo-impedisce' },
    ],
  },
  {
    id: 'impressioni-giudizio',
    titolo: 'Le impressioni e il giudizio',
    sotto: 'Tra ciò che accade e ciò che proviamo c\'è uno spazio: il giudizio.',
    blocchi: [
      { t: 'p', x: `Per gli stoici tutto ciò che percepiamo ci arriva sotto forma di **impressione**: il modo in cui una situazione ci appare. Le impressioni arrivano da sole, non le scegliamo. Ma c'è un passaggio successivo che è nostro: **dare o negare il proprio assenso**, cioè credere a quell'impressione oppure esaminarla.` },
      { t: 'passi', x: [
        { titolo: 'Arriva un\'impressione.', testo: `Per esempio: «Mi ha risposto male, non mi rispetta». È rapida e sembra evidente.` },
        { titolo: 'Puoi esaminarla.', testo: `Che cosa è accaduto davvero? Che cosa ci ho aggiunto? Potrebbe essere diversa?` },
        { titolo: 'Decidi se credere.', testo: `Solo dopo, se regge, dai il tuo assenso. Le emozioni che seguono dipendono da quello.` },
      ] },
      { t: 'h', x: 'Il giudizio pesa più dei fatti' },
      { t: 'p', x: `Epitteto sostiene che ciò che ci turba non sono le cose, ma i giudizi che ne diamo. I fatti contano, ma gran parte del peso viene da ciò che ci abbiamo aggiunto: un'intenzione, una condanna, un pronostico.` },
      { t: 'h', x: 'Descrivere senza aggiungere' },
      { t: 'p', x: `Marco Aurelio propone un esercizio di esattezza: descrivere ogni cosa nuda, per ciò che è, senza le aggiunte dell'opinione. Un pranzo pregiato diventa «un pesce morto e un po' d'uva»: non per disgusto, ma per togliere il fumo che ci mette la vanità.` },
      { t: 'h', x: 'I primi movimenti' },
      { t: 'p', x: `Seneca ricorda che le prime reazioni del corpo (un sussulto, un rossore, un brivido) sfuggono al nostro controllo e non sono ancora passioni. La passione comincia quando ci diamo ragione: «è giusto che io mi arrabbi». Lì possiamo fermarci.` },
      { t: 'azione', x: 'Esercizio: Fermati, impressione', az: 'esercizio', id: 'fermati-impressione' },
      { t: 'azione', x: 'Esercizio: Descrivi senza aggiungere', az: 'esercizio', id: 'descrivi-senza-aggiungere' },
      { t: 'azione', x: 'Esercizio: Il fatto e il giudizio', az: 'esercizio', id: 'fatto-e-giudizio' },
    ],
  },
  {
    id: 'paura-desiderio',
    titolo: 'La paura e il desiderio',
    sotto: 'Le passioni secondo gli stoici, e come si curano.',
    blocchi: [
      { t: 'p', x: `Per gli stoici le emozioni che ci turbano di più nascono da un **giudizio**: crediamo che una certa cosa sia un bene o un male, e che dobbiamo averla o evitarla. Da qui le quattro passioni principali, che dipendono dal tempo e dal tipo di cosa.` },
      { t: 'lista', x: [
        `**Il desiderio:** giudichiamo che un bene futuro sia da ottenere a ogni costo.`,
        `**La paura:** giudichiamo che un male futuro stia per colpirci.`,
        `**Il piacere sfrenato:** giudichiamo che un bene presente sia da afferrare senza misura.`,
        `**Il dolore:** giudichiamo che un male presente sia una sventura.`,
      ] },
      { t: 'h', x: 'Le emozioni buone' },
      { t: 'p', x: `Il saggio stoico non è privo di emozioni. Prova tre buone disposizioni: la **gioia** serena, la **prudenza** (che ci fa evitare con giudizio ciò che è davvero dannoso) e una **volontà** ragionevole. Sono le forme sane di ciò che, in eccesso, diventa passione.` },
      { t: 'h', x: 'Come si cura la paura' },
      { t: 'p', x: `Il metodo stoico agisce sul giudizio e sull'abitudine. Si esamina ciò che si teme (è davvero un male? dipende da me?), si misura la sua probabilità, si immagina con calma il caso peggiore per preparare una risposta, e si ricorda che tutto ciò che possediamo può finire. Sono gli esercizi della premeditazione dei mali e del ricordo della fragilità delle cose.` },
      { t: 'h', x: 'Come si cura il desiderio' },
      { t: 'p', x: `Si desidera con misura ciò che dipende da noi, e si accoglie il resto senza pretendere. Epitteto propone di cominciare dalle piccole cose: rinunciare a un desiderio da poco, per allenarsi a quelli più grandi.` },
      { t: 'azione', x: 'Esercizio: Il peggio, misurato', az: 'esercizio', id: 'il-peggio-misurato' },
      { t: 'azione', x: 'Esercizio: Prepararsi al peggio', az: 'esercizio', id: 'prepararsi-al-peggio' },
      { t: 'azione', x: 'Esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
      { t: 'azione', x: 'Esercizio: La speranza e il timore', az: 'esercizio', id: 'speranza-e-timore' },
    ],
  },
  {
    id: 'esercizi-spirituali',
    titolo: 'Gli esercizi spirituali',
    sotto: 'Il catalogo delle pratiche stoiche.',
    blocchi: [
      { t: 'p', x: `Le scuole filosofiche greche e romane proponevano ai propri allievi **pratiche concrete** per trasformare il modo di vedere e di vivere. «Spirituale» qui indica ciò che riguarda l'intera persona, e non solo il pensiero.` },
      { t: 'p', x: `Non ci è rimasto un manuale che elenchi questi esercizi, perché erano un insegnamento orale e tradizionale. Ma ne troviamo le tracce ovunque, e alcuni elenchi antichi permettono di ricostruirne i gruppi principali.` },
      { t: 'h', x: 'Quattro gruppi' },
      { t: 'lista', x: [
        `**L'attenzione** (in greco *prosoché*): la vigilanza continua su di sé e sul momento presente, in modo che la regola di vita sia sempre «a portata di mano».`,
        `**Le meditazioni e i ricordi:** prepararsi ai mali possibili, ricordare la fragilità delle cose e la morte, guardare il mondo dall'alto, ricordare ciò che è bene.`,
        `**Gli esercizi di pensiero:** leggere, ascoltare, ricercare, esaminare a fondo.`,
        `**Gli esercizi attivi:** il dominio di sé, il compimento dei propri doveri, l'indifferenza verso ciò che non dipende da noi.`,
      ] },
      { t: 'h', x: 'A che cosa servono' },
      { t: 'p', x: `Lo scopo è una vera **conversione dello sguardo**: passare da una vita agitata, dominata da desideri e timori, a una vita più libera e più lucida. Non basta capire un'idea: bisogna ripeterla, provarla, farla propria, come si allena un muscolo.` },
      { t: 'h', x: 'Come compaiono in Stoicismo quotidiano' },
      { t: 'p', x: `Ogni esercizio della app indica la sua famiglia e la sua fonte. «Qui e ora con i cinque sensi» e «Respiro e attenzione» sono esercizi di attenzione. «Prepararsi al peggio» e «La brocca che si può rompere» sono meditazioni. «Fermati, impressione» e «Il fatto e il giudizio» sono esercizi di pensiero. «Il primo gesto piccolo» e «Chi voglio essere qui» sono esercizi attivi.` },
      { t: 'azione', x: 'Esercizio di attenzione: Qui e ora, con i cinque sensi', az: 'esercizio', id: 'qui-e-ora-cinque-sensi' },
      { t: 'azione', x: "Meditazione: L'attenzione a se stessi", az: 'meditazione', id: 'attenzione-presente' },
      { t: 'azione', x: "La filosofia come cura dell'anima", az: 'studio', id: 'la-cura-dell-anima' },
      { t: 'azione', x: 'Perché respiri, pause e scrittura', az: 'info', id: 'perche-respiri-pause-scrittura' },
    ],
  },
  {
    id: 'tre-maestri',
    titolo: 'I tre maestri',
    sotto: 'Epitteto, Seneca e Marco Aurelio: chi erano e come parlano.',
    blocchi: [
      { t: 'p', x: `Le tre voci della app sono tre autori stoici romani. Sono molto diversi per vita e per tono, e proprio per questo si completano.` },
      { t: 'h', x: 'Epitteto (nato tra il 50 e il 60, morto verso il 138 d.C.)' },
      { t: 'p', x: `Nacque schiavo, in Frigia. Divenne libero e insegnò filosofia prima a Roma e poi a Nicopoli, in Grecia. Non scrisse nulla: le sue lezioni furono messe per iscritto dal suo allievo **Arriano**, che ne ricavò gli *Discorsi* (o *Diatribe*) e il breve *Manuale*. Il suo tono è **secco e diretto**: parla come un maestro che non gira intorno alle cose. Per lui la filosofia è un'officina, una «sala operatoria» dell'anima.` },
      { t: 'h', x: 'Seneca (circa 4 a.C. – 65 d.C.)' },
      { t: 'p', x: `Nato in Spagna, visse a Roma: fu scrittore, uomo di Stato e per anni consigliere dell'imperatore Nerone, che nel 65 d.C. gli ordinò di togliersi la vita. Scrisse trattati (*Sull'ira*, *Sulla brevità della vita*, *Sulla tranquillità dell'animo*) e le *Lettere a Lucilio*, un amico a cui parla da amico esperto. Il suo tono è **caldo e vicino**, come una lettera: spiega, consola, si mette in gioco.` },
      { t: 'h', x: 'Marco Aurelio (121–180 d.C.)' },
      { t: 'p', x: `Fu imperatore romano dal 161 al 180. Nei momenti liberi, spesso durante le campagne militari, scrisse in greco appunti per se stesso, che noi conosciamo con il titolo *A se stesso* (o *Ricordi*). Non erano destinati a nessuno: sono un quaderno di esercizi personali. Il suo tono è **interiore e riservato**, di chi parla a se stesso.` },
      { t: 'h', x: 'Come usare le voci' },
      { t: 'p', x: `Nella app puoi cambiare voce quando vuoi. Se hai bisogno di essere scosso, prova Epitteto. Se hai bisogno di essere accompagnato, prova Seneca. Se cerchi un silenzio in cui riflettere, prova Marco Aurelio. Gli esercizi restano gli stessi: cambia il modo di dirli.` },
      { t: 'azione', x: 'Leggi come leggerli', az: 'studio', id: 'come-leggere' },
      { t: 'azione', x: 'La vita di Seneca', az: 'studio', id: 'la-vita-di-seneca' },
      { t: 'azione', x: 'Gli stoici sotto gli imperatori', az: 'studio', id: 'gli-stoici-e-il-potere' },
    ],
  },
  {
    id: 'come-usare',
    titolo: 'Come usare Stoicismo quotidiano',
    sotto: 'Un modo semplice di usare la app, senza obblighi.',
    blocchi: [
      { t: 'p', x: `Stoicismo quotidiano non ti chiede di praticare ogni giorno, di accumulare giorni di fila o di rispondere a notifiche. Lo apri quando ti serve, e lo lasci quando ti basta.` },
      { t: 'h', x: 'Quando stai male' },
      { t: 'passi', x: [
        { titolo: 'Tocca «Ho bisogno di un momento».', testo: `Scegli che cosa senti e dove ti sei perso.` },
        { titolo: 'Scegli quanto tempo hai.', testo: `Un minuto basta per cominciare. Se hai più tempo, un esercizio più lungo va più a fondo.` },
        { titolo: 'Fai l\'esercizio un passo alla volta.', testo: `Non devi crederci per forza: provalo. Puoi tornare indietro o fermarti quando vuoi.` },
      ] },
      { t: 'h', x: 'Quando vuoi un momento di calma' },
      { t: 'p', x: `Nella sezione Esercizi trovi le meditazioni a tempo, per esempio quella sull'attenzione a se stessi o l'esame della sera. Puoi farle anche senza un motivo preciso.` },
      { t: 'h', x: 'Quando vuoi capire' },
      { t: 'p', x: `In Studio trovi le pagine che spiegano lo stoicismo e le fonti da cui vengono gli esercizi. Ogni esercizio ha un collegamento alla pagina che lo approfondisce.` },
      { t: 'h', x: 'Alcuni consigli' },
      { t: 'lista', x: [
        `**Comincia dai brevi.** Un esercizio da uno o tre minuti, fatto davvero, vale più di uno lungo lasciato a metà.`,
        `**Ripeti quelli che funzionano.** Gli esercizi stoici sono fatti per essere ripetuti: la seconda volta è più facile.`,
        `**Cambia voce se un tono non ti aiuta.** Ognuno risponde a modo suo.`,
        `**Non contare i giorni.** L'unico giorno che conta è quello in cui ti serve.`,
      ] },
      { t: 'nota', x: `Stoicismo quotidiano nasce dalla sapienza degli stoici antichi e propone esercizi di pensiero e di attenzione. Non sostituisce il parere del medico né un percorso di cura o di sostegno psicologico: se il malessere è forte o dura da tempo, parlane con il tuo medico o con un professionista.` },
    ],
  },
  {
    id: 'scrivere-per-pensare',
    titolo: 'Scrivere per pensare',
    sotto: 'Il quaderno degli stoici: appunti per sé, esami della sera, lettere a un amico.',
    blocchi: [
      { t: 'p', x: `Gli stoici scrivevano molto, e non soltanto per gli altri. Scrivere era un modo di tenere le idee **sottomano**, di guardare i propri pensieri da fuori e di correggersi. Per questo Stoicismo quotidiano ha un Quaderno.` },
      { t: 'h', x: 'Marco Aurelio: appunti a se stesso' },
      { t: 'p', x: `Il libro che leggiamo con il titolo *A se stesso* (o *Ricordi*) è il quaderno privato di un imperatore. Non era scritto per essere pubblicato: sono promemoria, esercizi, frasi per ricordarsi ciò che conta. Cominciare la giornata con una **preparazione del mattino** (II, 1) e ricordarsi il proprio compito (V, 1) sono pratiche che lì trovi scritte.` },
      { t: 'h', x: 'Seneca: l\'esame della sera e le lettere' },
      { t: 'p', x: `Seneca racconta che ogni sera ripercorreva la giornata, senza nascondersi nulla e senza punirsi (*Sull'ira*, III, 36). Le sue *Lettere a Lucilio* sono lettere a un amico, per aiutarlo a vivere meglio: consigli scritti con calore, come si parla a chi si vuole bene.` },
      { t: 'h', x: 'I quattro modelli del Quaderno' },
      { t: 'lista', x: [
        `**Mattina:** prepararsi alla giornata. Che cosa potrebbe mettermi alla prova? Come voglio essere? Qual è il mio compito?`,
        `**Sera:** esaminare la giornata. Che cosa ho fatto bene? Dove ho sbagliato? Che cosa farò diversamente?`,
        `**Lettera:** scrivere a te stesso come scriveresti a un amico che vive ciò che vivi tu.`,
        `**Pagina libera:** un pensiero, un ricordo, una frase da tenere.`,
      ] },
      { t: 'h', x: 'Alcuni consigli' },
      { t: 'lista', x: [
        `**Scrivi con parole semplici.** Non serve scrivere bene: serve scrivere vero.`,
        `**Descrivi prima i fatti,** poi ciò che ci hai aggiunto tu.`,
        `**Sii gentile con te stesso.** Seneca si correggeva senza punirsi.`,
        `**Poche righe bastano.** Meglio tre righe oneste che una pagina di buone intenzioni.`,
      ] },
      { t: 'azione', x: 'Esercizio: Prepara la giornata', az: 'esercizio', id: 'prepara-la-giornata' },
      { t: 'azione', x: 'Meditazione: La mattina', az: 'meditazione', id: 'la-mattina' },
    ],
  },
  {
    id: 'come-leggere',
    titolo: 'Come leggere gli stoici',
    sotto: 'Da dove cominciare, e come leggerli senza perdersi.',
    blocchi: [
      { t: 'p', x: `Leggere gli stoici è più semplice di quanto si pensi, se si sceglie l'ordine giusto e si legge poco alla volta. Ecco un percorso.` },
      { t: 'passi', x: [
        { titolo: 'Epitteto, *Manuale*.', testo: `Poche pagine, tutte utili. È il testo più diretto: un piccolo libro di regole di vita da tenere a portata di mano.` },
        { titolo: 'Marco Aurelio, *A se stesso*.', testo: `Appunti brevi, che si aprono a caso. Ottimo per leggere una pagina la sera.` },
        { titolo: 'Seneca, *Lettere a Lucilio*.', testo: `Lettere brevi e ricche, dove Seneca ragiona su una sola idea alla volta. Si leggono una per volta.` },
        { titolo: 'Pierre Hadot, *Esercizi spirituali e filosofia antica*.', testo: `Per capire che cosa erano davvero gli esercizi. Meno immediato, ma prezioso.` },
        { titolo: 'Gli stoici antichi.', testo: `I frammenti di Zenone, Cleante e Crisippo, raccolti negli *Stoici antichi*: per chi vuole andare alla fonte, con calma.` },
      ] },
      { t: 'h', x: 'Come leggere' },
      { t: 'lista', x: [
        `**Poco alla volta.** Dieci minuti, una pagina, un'idea.`,
        `**Con un quaderno.** Scrivi una frase con parole tue e chiediti dove puoi usarla oggi.`,
        `**Anche più edizioni.** Le traduzioni cambiano molto: confrontarne due aiuta a capire.`,
        `**Non serve finire.** Questi testi sono fatti per essere ripresi a pezzi.`,
      ] },
      { t: 'nota', x: `Le edizioni consigliate stanno nella pagina Fonti, nelle Info.` },
    ],
  },
  {
    id: 'il-tempo-la-morte',
    titolo: 'Il tempo e la morte',
    sotto: 'Perché gli stoici ricordavano ogni giorno che la vita è breve.',
    blocchi: [
      { t: 'p', x: `Gli stoici ricordavano spesso che il tempo è limitato e che la vita finisce. Non lo facevano per rattristarsi, ma per vivere meglio: chi ricorda che il tempo è poco, lo usa con più cura.` },
      { t: 'h', x: 'Il tempo è il nostro bene più prezioso' },
      { t: 'p', x: `Seneca, nella *Brevità della vita*, sostiene che non abbiamo poco tempo, ma ne sprechiamo molto. La vita è abbastanza lunga se la si impiega bene. Per questo consiglia di custodire il proprio tempo come si custodisce il denaro, e di donarlo a chi lo merita.` },
      { t: 'h', x: 'Solo il presente è nostro' },
      { t: 'p', x: `Marco Aurelio osserva che il passato e il futuro sfuggono al nostro potere: il passato è chiuso, il futuro è ignoto. Ci resta il presente, ed è tutto ciò che possiamo perdere o possedere. Vale la pena viverlo con attenzione.` },
      { t: 'h', x: 'Imparare a morire' },
      { t: 'p', x: `«Filosofare è imparare a morire» è una formula antica, ed era un vero esercizio: pensare alla propria fine con calma, per liberarsi dalla paura che ci tiene prigionieri. Chi ha guardato la morte in faccia con serenità, vive con più libertà.` },
      { t: 'h', x: 'Ciò che ami è fragile' },
      { t: 'p', x: `Gli stoici invitavano a ricordare anche la fragilità delle cose e delle persone care. Non per amarle di meno, ma per amarle con più attenzione, con le mani aperte, senza pretendere che durino.` },
      { t: 'nota', x: `Sono temi delicati. Se un esercizio su questo ti pesa, fermati e passa ad altro: è una pratica da fare quando ti senti pronto.` },
      { t: 'azione', x: 'Esercizio: La brocca che si può rompere', az: 'esercizio', id: 'la-brocca-che-si-rompe' },
      { t: 'azione', x: 'Esercizio: Esame della sera', az: 'esercizio', id: 'esame-della-sera' },
    ],
  },
  {
    id: 'vista-dall-alto',
    titolo: "La vista dall'alto",
    sotto: 'Guardare le cose da lontano, per ritrovare la giusta misura.',
    blocchi: [
      { t: 'p', x: `Tra gli esercizi più suggestivi degli stoici c'è la **vista dall'alto**: immaginare di guardare la propria vita, la propria città, il mondo intero da molto in alto, come se ci si allontanasse da terra. Marco Aurelio la pratica più volte nei suoi appunti.` },
      { t: 'h', x: 'A che cosa serve' },
      { t: 'p', x: `Quando siamo dentro un problema, ci sembra grandissimo. Guardato da lontano, ritrova la sua misura: le nostre preoccupazioni sono una piccola parte di una storia molto più vasta, fatta di persone, luoghi e secoli. È una forma di **fisica vissuta**: non una teoria sul cosmo, ma un modo di guardare che cambia lo stato d'animo.` },
      { t: 'h', x: 'Come si fa' },
      { t: 'passi', x: [
        { titolo: 'Parti da dove sei.', testo: `La stanza, il tuo corpo, il tuo problema.` },
        { titolo: 'Sali un poco.', testo: `Il palazzo, la strada, il quartiere, la città con le sue luci.` },
        { titolo: 'Sali ancora.', testo: `La regione, il mare, la Terra vista dallo spazio, tanti esseri umani che vivono, lavorano, soffrono e sperano.` },
        { titolo: 'Guarda anche il tempo.', testo: `Le epoche passate, i secoli che verranno. Quanto pesava, tra mille anni, ciò che ti agita oggi?` },
        { titolo: 'Torna giù.', testo: `Riporta questo sguardo nel tuo problema: è ancora tuo, ma è meno grande di prima.` },
      ] },
      { t: 'azione', x: "Meditazione guidata: Vista dall'alto", az: 'meditazione', id: 'vista-dall-alto-guidata' },
    ],
  },
  {
    id: 'dicotomia-in-pratica',
    titolo: 'La dicotomia del controllo, in pratica',
    sotto: 'Come usare ogni giorno la distinzione tra le cose in nostro potere e le altre.',
    blocchi: [
      { t: 'p', x: `Il *Manuale* di Epitteto comincia con una frase sola: alcune cose dipendono da noi, altre no. Da questa distinzione, che gli studiosi chiamano **dicotomia del controllo**, nasce quasi tutto il resto dello stoicismo.` },
      { t: 'h', x: 'Che cosa dipende da noi' },
      { t: 'lista', x: [
        `I nostri **giudizi** su ciò che accade.`,
        `I nostri **desideri** e le nostre avversioni, cioè ciò che cerchiamo e ciò che evitiamo.`,
        `Le nostre **scelte** e le nostre azioni.`,
      ] },
      { t: 'h', x: 'Che cosa non dipende da noi' },
      { t: 'lista', x: [
        `Il **corpo**, la salute, la vita.`,
        `La **reputazione** e ciò che gli altri pensano di noi.`,
        `Le **ricchezze**, i ruoli, gli eventi.`,
        `Il **passato**, e come andrà il futuro.`,
        `Le scelte delle altre persone.`,
      ] },
      { t: 'h', x: 'Come si usa' },
      { t: 'passi', x: [
        { titolo: 'Fermati.', testo: `Quando qualcosa ti agita, chiediti che cosa ti agita.` },
        { titolo: 'Dividi.', testo: `In una colonna scrivi ciò che dipende da te, nell'altra ciò che non dipende da te.` },
        { titolo: 'Agisci sulla prima.', testo: `Nella prima colonna c'è ciò su cui puoi fare qualcosa: comincia da lì, con un gesto piccolo.` },
        { titolo: 'Accetta la seconda.', testo: `Su ciò che sfugge al tuo controllo non puoi agire. Puoi scegliere come stare, senza pretendere che vada altrimenti.` },
      ] },
      { t: 'nota', x: `Nel Quaderno questa distinzione è sempre con te: ogni pagina si chiude con le due domande «Che cosa dipende da me?» e «Che cosa non dipende da me?».` },
      { t: 'azione', x: 'Esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
    ],
  },
  {
    id: 'l-ira-secondo-seneca',
    titolo: 'L\'ira secondo Seneca',
    sotto: 'Che cos\'è la rabbia, come nasce e che cosa fare quando sale.',
    blocchi: [
      { t: 'p', x: `Seneca dedica alla rabbia un intero trattato, *Sull'ira*. Per lui è la più violenta e la più rovinosa delle passioni: un breve furore che lascia lunghi rimpianti. Ne parla con precisione quasi clinica, perché la conosceva bene.` },
      { t: 'h', x: 'Come nasce' },
      { t: 'p', x: `L'ira non arriva dal nulla: comincia da un'impressione (un torto subìto, uno sgarbo, una promessa mancata) a cui diamo il nostro assenso. Solo dopo il giudizio arriva la rabbia. Il primo scatto del corpo, come il colore del viso, non è ancora ira: lo diventa quando ci acconsentiamo.` },
      { t: 'h', x: 'I rimedi' },
      { t: 'lista', x: [
        `**Il ritardo.** Il miglior rimedio è aspettare: lasciare che il tempo abbassi la temperatura prima di rispondere.`,
        `**Evitare le occasioni.** Chi si accorge di irritarsi facilmente con certe persone o situazioni può cominciare da lì.`,
        `**Scegliere compagni miti.** Attorno a persone semplici e tranquille, l'ira trova meno pretesti.`,
        `**Guardarsi allo specchio.** Vedere il proprio volto sfigurato dalla rabbia è, per Seneca, un ottimo freno.`,
        `**L'esame della sera.** Ripassare la giornata, senza indulgenza e senza severità, per capire che cosa ci ha fatto arrabbiare.`,
      ] },
      { t: 'nota', x: `Seneca chiede di lasciarsi guidare dalla ragione, e non dall'emozione. Prima si respira, poi si sceglie che cosa fare.` },
      { t: 'azione', x: 'Esercizio: Aspetta prima di rispondere', az: 'esercizio', id: 'aspetta-prima-di-rispondere' },
      { t: 'azione', x: 'Esercizio: Non somigliargli', az: 'esercizio', id: 'non-somigliargli' },
    ],
  },
  {
    id: 'la-paura-del-futuro',
    titolo: 'La paura del futuro',
    sotto: 'Perché immaginare il peggio fa male, e come gli stoici lo usavano a proprio favore.',
    blocchi: [
      { t: 'p', x: `Spesso soffriamo più per ciò che immaginiamo che per ciò che accade. Seneca lo scrive più volte a Lucilio: le paure arrivano prima della realtà, e a volte la realtà non arriva affatto.` },
      { t: 'h', x: 'Due modi di guardare il futuro' },
      { t: 'lista', x: [
        `**Preoccuparsi:** girare e rigirare gli scenari peggiori, senza sapere che farne. Toglie energie e non porta soluzioni.`,
        `**Prepararsi:** guardare il peggio con calma, misurarlo, chiedersi che cosa si potrebbe fare. Toglie potere alla sorpresa.`,
      ] },
      { t: 'p', x: `Gli stoici praticavano la seconda strada con un esercizio che in latino si chiama *praemeditatio malorum*, la premeditazione dei mali. La preparazione del mattino di Marco Aurelio, in cui si ricorda che si incontreranno persone difficili, ne è un esempio.` },
      { t: 'h', x: 'Tre domande per la paura' },
      { t: 'passi', x: [
        { titolo: 'È ancora successo?', testo: `Se è ancora da venire, hai davanti un'impressione, e nessun fatto.` },
        { titolo: 'Dipende da me?', testo: `Se dipende da te, prepara ciò che puoi. Se non dipende da te, lascia andare il controllo.` },
        { titolo: 'Che cosa farei, se accadesse?', testo: `Spesso la risposta esiste, e rassicura più dell'ansia.` },
      ] },
      { t: 'azione', x: 'Esercizio: Il peggio misurato', az: 'esercizio', id: 'il-peggio-misurato' },
      { t: 'azione', x: 'Esercizio: Un momento alla volta', az: 'esercizio', id: 'un-momento-alla-volta' },
    ],
  },
  {
    id: 'il-dolore-e-la-perdita',
    titolo: 'Il dolore e la perdita',
    sotto: 'Che cosa dicono gli stoici quando qualcosa o qualcuno se ne va.',
    blocchi: [
      { t: 'p', x: `Gli stoici non erano insensibili alla perdita. Seneca, scrivendo agli amici in lutto, ammette le lacrime: sono naturali. Invita però a evitare di restare prigionieri del lamento: il dolore prolungato lascia intatta la perdita e consuma ciò che ci resta.` },
      { t: 'h', x: 'Restituire, non perdere' },
      { t: 'p', x: `Epitteto propone di cambiare le parole: non dire «l'ho perduto», ma «l'ho restituito». Ciò che abbiamo ci è stato prestato per un tempo, e ringraziare per quel tempo è un modo di guardare la perdita senza esserne schiacciati.` },
      { t: 'h', x: 'Ciò che resta' },
      { t: 'lista', x: [
        `Ciò che abbiamo ricevuto da chi non c'è più (un modo di essere, una parola, un ricordo) resta con noi.`,
        `Ricordare con gratitudine non toglie il dolore, ma lo cambia di natura.`,
        `Il lutto ha i suoi tempi: nessuno chiede di finirlo in fretta.`,
      ] },
      { t: 'nota', x: `Se il dolore è troppo grande, o dura da tempo, parlane con il tuo medico o con una persona di fiducia: non sostituiamo un sostegno vero.` },
      { t: 'azione', x: 'Esercizio: Ciò che ho ricevuto', az: 'esercizio', id: 'cio-che-ho-ricevuto' },
      { t: 'azione', x: 'Esercizio: La brocca che si rompe', az: 'esercizio', id: 'la-brocca-che-si-rompe' },
    ],
  },
  {
    id: 'le-quattro-virtu',
    titolo: 'Le quattro virtù',
    sotto: 'Saggezza, giustizia, coraggio e temperanza: il centro dell\'etica stoica.',
    blocchi: [
      { t: 'p', x: `Per gli stoici l'unico vero bene è la **virtù**, cioè il buon uso della ragione nella vita. Salute, ricchezza e fama sono preferibili, ma non decidono se una vita è buona. La virtù, poi, si divide in quattro parti, che tornano spesso negli autori.` },
      { t: 'lista', x: [
        `**Saggezza:** sapere che cosa è bene e che cosa è male, e giudicare con chiarezza. È l'attenzione ai giudizi.`,
        `**Giustizia:** dare a ciascuno ciò che gli spetta, e agire per il bene comune. Marco Aurelio insiste sul nostro essere nati per collaborare.`,
        `**Coraggio:** affrontare ciò che è difficile senza farsi guidare dalla paura, e restare in piedi in ciò che non possiamo cambiare.`,
        `**Temperanza:** la giusta misura nei desideri e nei piaceri, senza eccessi né rinunce inutili.`,
      ] },
      { t: 'h', x: 'Un uso pratico' },
      { t: 'p', x: `Ogni situazione difficile chiama una virtù. Davanti a un torto, la giustizia e la temperanza. Davanti a una paura, il coraggio. Davanti a una scelta complessa, la saggezza. Chiedersi «quale virtù serve qui?» è un modo semplice di orientarsi.` },
      { t: 'azione', x: 'Esercizio: Sii ciò che cerchi', az: 'esercizio', id: 'sii-l-uomo-buono' },
      { t: 'azione', x: 'Esercizio: Un testimone esemplare', az: 'esercizio', id: 'un-testimone-esemplare' },
    ],
  },
  {
    id: 'le-quattro-passioni',
    titolo: 'Le quattro passioni',
    sotto: 'La mappa stoica delle emozioni che ci turbano, e di quelle buone.',
    blocchi: [
      { t: 'p', x: `Gli stoici chiamavano **passioni** le emozioni che nascono da un giudizio sbagliato e ci portano fuori strada. Le raggruppavano in quattro famiglie, secondo due criteri: riguardano un bene o un male, e riguardano il presente o il futuro.` },
      { t: 'lista', x: [
        `**Desiderio:** vogliamo con ansia un bene che non abbiamo ancora.`,
        `**Paura:** temiamo un male che potrebbe arrivare.`,
        `**Piacere:** ci esaltiamo per un bene presente, dandogli troppo peso.`,
        `**Dolore:** ci abbattiamo per un male presente, dandogli troppo peso.`,
      ] },
      { t: 'h', x: 'Le emozioni buone' },
      { t: 'p', x: `Gli stoici non sognavano un essere umano senza emozioni. Parlavano anche di emozioni buone, che nascono da un giudizio giusto: la **gioia** (per ciò che è davvero bene), la **volontà** ragionevole (che desidera ciò che è giusto) e la **cautela** (che si difende dal male vero, cioè dal fare il male, e non dal disagio).` },
      { t: 'h', x: 'A che cosa serve la mappa' },
      { t: 'p', x: `Riconoscere in quale famiglia cade ciò che sentiamo è già un passo: se è desiderio o paura, lavoriamo sul futuro e su ciò che non dipende da noi. Se è dolore, guardiamo il giudizio sul presente. È la ragione per cui, in Stoicismo quotidiano, cominci scegliendo che cosa senti.` },
      { t: 'azione', x: 'Esercizio: Fermati, impressione', az: 'esercizio', id: 'fermati-impressione' },
    ],
  },
  {
    id: 'il-tempo-secondo-seneca',
    titolo: 'Il tempo secondo Seneca',
    sotto: 'Non abbiamo poco tempo: ne perdiamo molto.',
    blocchi: [
      { t: 'p', x: `Nel trattato *Sulla brevità della vita*, Seneca risponde a chi si lamenta che la vita sia troppo corta. La sua tesi è diretta: non è breve la vita che abbiamo, ma è breve il tempo che sappiamo usare. Lo sprechiamo in impegni inutili, preoccupazioni, rinvii.` },
      { t: 'h', x: 'Tre modi di perdere tempo' },
      { t: 'lista', x: [
        `**Rimandare:** aspettare il momento giusto, che non arriva mai, per cominciare a vivere.`,
        `**Disperdersi:** riempirsi di impegni che non contano, per paura del vuoto.`,
        `**Rimuginare:** vivere nel passato e nel futuro, senza abitare il presente.`,
      ] },
      { t: 'h', x: 'Che cosa suggerisce' },
      { t: 'p', x: `Seneca non invita ad affannarsi di più: invita a scegliere. Il tempo è l'unica cosa che ci è davvero affidata, e conviene dedicarlo a ciò che vale. Ognuno può cominciare da un gesto: ridurre una cosa inutile e proteggere una cosa che conta.` },
      { t: 'azione', x: 'Meditazione: Il tempo che hai', az: 'meditazione', id: 'il-tempo-che-hai' },
      { t: 'azione', x: 'Esercizio: Il tempo che perdi', az: 'esercizio', id: 'il-tempo-che-perdi' },
    ],
  },
  {
    id: 'amicizia-e-comunita',
    titolo: 'Amicizia e comunità',
    sotto: 'Gli stoici e gli altri: non si vive bene da soli.',
    blocchi: [
      { t: 'p', x: `Nonostante l'immagine dello stoico solitario, i testi insistono sul contrario. Seneca scrive che nessuno vive bene guardando soltanto a se stesso: per vivere per sé, occorre vivere anche per gli altri. Le sue lettere sono lettere a un amico.` },
      { t: 'h', x: 'La città comune' },
      { t: 'p', x: `Marco Aurelio sostiene che, se la ragione è comune a tutti, siamo tutti cittadini di una stessa città, il cosmo. Siamo nati per collaborare, come le mani e i piedi. Agire gli uni contro gli altri va contro la nostra natura.` },
      { t: 'h', x: 'L\'amicizia' },
      { t: 'lista', x: [
        `Scegli amici semplici e miti: accanto a loro cresci, senza dover difenderti.`,
        `L'amicizia mette in comune ciò che accade, le gioie e le pene.`,
        `Un amico è chi ti dice la verità con affetto, e chi accetta la tua.`,
      ] },
      { t: 'azione', x: 'Esercizio: Vivere anche per gli altri', az: 'esercizio', id: 'vivere-anche-per-gli-altri' },
      { t: 'azione', x: 'Meditazione: La città comune', az: 'meditazione', id: 'la-citta-comune' },
    ],
  },
  {
    id: 'stoicismo-e-lavoro',
    titolo: 'Stoicismo e lavoro',
    sotto: 'Fare bene la propria parte, senza lasciarsi divorare dal risultato.',
    blocchi: [
      { t: 'p', x: `Il lavoro è uno dei luoghi in cui la distinzione tra cose in nostro potere e cose fuori dal nostro potere si mette più alla prova: scadenze, colleghi, valutazioni, incertezza. Gli stoici offrono alcune indicazioni semplici.` },
      { t: 'lista', x: [
        `**Sei responsabile della tua parte, non del risultato.** Fai bene ciò che spetta a te (Epitteto).`,
        `**Ogni compito ha la sua misura.** Marco Aurelio, che alla mattina fatica ad alzarsi, si ricorda che ognuno ha un lavoro suo e che quello dà senso alla giornata.`,
        `**Non sovraccaricarti.** Seneca, nella *Tranquillità dell'animo*, consiglia di non disperdersi in troppe imprese e di concedere riposo alla mente.`,
        `**Il giudizio degli altri non è tuo.** Lodi e critiche passano: ciò che resta è il modo in cui hai lavorato.`,
      ] },
      { t: 'h', x: 'Quando il lavoro ti travolge' },
      { t: 'p', x: `Scegli una cosa sola, la più vicina, e falla con attenzione. Poi la successiva. Se il peso è cronico e ti consuma, non è un problema di filosofia: parlane con il tuo medico o con chi può aiutarti.` },
      { t: 'azione', x: 'Esercizio: Un compito per oggi', az: 'esercizio', id: 'un-compito-per-oggi' },
      { t: 'azione', x: 'Esercizio: Il riposo ha la sua misura', az: 'esercizio', id: 'il-riposo-ha-la-sua-misura' },
    ],
  },
  {
    id: 'stoicismo-e-relazioni',
    titolo: 'Stoicismo e relazioni',
    sotto: 'Come stare con chi ci ferisce, ci delude o ci sta accanto.',
    blocchi: [
      { t: 'p', x: `Le relazioni sono il luogo dove più facilmente ci feriamo, e dove gli esercizi stoici servono di più. Il punto di partenza è sempre lo stesso: non possiamo controllare gli altri, possiamo scegliere come rispondere.` },
      { t: 'h', x: 'Quando qualcuno ti ferisce' },
      { t: 'lista', x: [
        `**Sbaglia per ignoranza,** non perché sia un mostro (Marco Aurelio).`,
        `**È una persona come te,** con i suoi limiti e le sue paure.`,
        `**Nessun danno:** il suo errore lascia il tuo carattere com'era.`,
        `**Non somigliargli:** il modo migliore di difenderti da chi ti fa un torto è restare te stesso.`,
      ] },
      { t: 'h', x: 'Quando sei tu a sbagliare' },
      { t: 'p', x: `Riconoscilo senza nasconderti, correggiti e lasciati andare. Seneca si diceva: «Stai attento la prossima volta; per ora ti perdono». Chiedere scusa è un atto di giustizia, non di debolezza.` },
      { t: 'azione', x: 'Esercizio: Quattro ragioni per non odiare', az: 'esercizio', id: 'quattro-ragioni' },
      { t: 'azione', x: 'Esercizio: Accogli la correzione', az: 'esercizio', id: 'accogli-la-correzione' },
    ],
  },
  {
    id: 'la-natura-e-il-cosmo',
    titolo: 'La natura e il cosmo',
    sotto: 'Vivere secondo natura, e sentirsi parte di un tutto.',
    blocchi: [
      { t: 'p', x: `«Vivere secondo natura» è la formula più celebre dello stoicismo. Non vuol dire tornare alla vita selvatica: vuol dire vivere secondo la propria natura di esseri razionali e sociali, e in armonia con l'ordine più grande di cui siamo parte.` },
      { t: 'h', x: 'Tre idee' },
      { t: 'lista', x: [
        `**Siamo parte di un tutto.** Ciò che ci accade ha un posto nell'ordine delle cose: è un'idea che consola e che ridimensiona.`,
        `**Ciò che avviene è naturale.** Marco Aurelio ricorda che tutto ciò che accade è sempre accaduto e accadrà ancora, ovunque: non è una condanna personale.`,
        `**La ragione ci accomuna.** Da qui la fraternità tra gli esseri umani: il cosmo come una grande città.`,
      ] },
      { t: 'p', x: `Nella pratica: quando ti pesa un avvenimento, ricordarti che fa parte di un ordine più ampio aiuta ad accoglierlo senza sentirti perseguitato.` },
      { t: 'azione', x: 'Meditazione: Vista dall\'alto', az: 'meditazione', id: 'vista-dall-alto-guidata' },
      { t: 'azione', x: 'Esercizio: Il fiume degli eventi', az: 'esercizio', id: 'il-fiume-degli-eventi' },
      { t: 'azione', x: 'Posidonio', az: 'studio', id: 'posidonio' },
    ],
  },
  {
    id: 'stoici-antichi',
    titolo: 'Gli stoici antichi',
    sotto: 'Zenone, Cleante, Crisippo: gli inizi della scuola e i frammenti che ne restano.',
    blocchi: [
      { t: 'p', x: `Gli autori più letti (Seneca, Epitteto, Marco Aurelio) vengono tre secoli dopo la nascita dello stoicismo. La scuola comincia ad Atene, attorno al 300 a.C., con **Zenone di Cizio**, che insegnava sotto un portico, la *Stoà*: da lì il nome.` },
      { t: 'lista', x: [
        `**Zenone di Cizio** fonda la scuola e ne stabilisce le idee di base: la vita secondo ragione e secondo natura.`,
        `**Cleante** gli succede. Di lui resta un celebre *Inno a Zeus*, che esprime la fiducia in un ordine razionale del mondo.`,
        `**Crisippo** è considerato il vero sistematore: scrisse centinaia di opere, con cui la dottrina prese la sua forma definitiva. Si diceva che, senza di lui, non ci sarebbe stata la Stoà.`,
      ] },
      { t: 'h', x: 'Perché ne restano solo frammenti' },
      { t: 'p', x: `Le opere degli stoici antichi sono andate quasi tutte perdute. Ne restano citazioni e riassunti in altri autori, che gli studiosi hanno raccolto: la raccolta classica è quella di Hans von Arnim, *Stoici antichi. Tutti i frammenti*. Per questo, per conoscere lo stoicismo, si comincia dai testi romani, che ci sono arrivati interi.` },
      { t: 'azione', x: 'Come leggere gli stoici', az: 'studio', id: 'come-leggere' },
      { t: 'azione', x: 'Come conosciamo i primi stoici', az: 'studio', id: 'come-conosciamo-i-primi-stoici' },
      { t: 'azione', x: 'La scuola in tre età', az: 'studio', id: 'le-tre-eta-della-stoa' },
    ],
  },
  {
    id: 'glossario',
    titolo: 'Glossario essenziale',
    sotto: 'Le parole dello stoicismo, spiegate in modo semplice.',
    blocchi: [
      { t: 'p', x: `Gli stoici usano alcuni termini greci, e qualche parola italiana con un senso particolare. Eccoli in ordine alfabetico, senza tecnicismi.` },
      { t: 'lista', x: [
        `**Assenso** (*sýnkatathesis*): il «sì» che diamo a un'impressione, quando la riteniamo vera. È il punto in cui possiamo scegliere.`,
        `**Attenzione** (*prosoché*): la vigilanza su di sé, sui propri pensieri e sulle proprie azioni. L'esercizio di base.`,
        `**Dovere** (*kathêkon*): ciò che è conveniente fare in una certa situazione, secondo il proprio ruolo e la propria natura.`,
        `**Impressione** (*phantasía*): il modo in cui una cosa ci appare. Non è ancora un fatto: va esaminata.`,
        `**Indifferenti** (*adiáphora*): le cose che in sé sono neutre, né buone né cattive, come salute, ricchezza, fama. Se ne può preferire qualcuna, ma non decidono la bontà della vita.`,
        `**Libertà interiore:** la capacità di scegliere come rispondere, qualunque cosa accada.`,
        `**Logos:** la ragione, insieme in noi e nel mondo. Ciò che rende ordinato il cosmo e ci permette di capirlo.`,
        `**Parte guida** (*hegemonikón*): la sede della ragione in noi, cioè ciò che giudica e decide.`,
        `**Passione** (*páthos*): un'emozione che nasce da un giudizio sbagliato e ci porta fuori strada.`,
        `**Progresso** (*prokopé*): il cammino di chi si esercita. Nessuno diventa saggio in un giorno: si migliora.`,
        `**Scelta** (*prohaíresis*): la facoltà di scegliere e di giudicare. In Epitteto è ciò che davvero ci appartiene.`,
        `**Sapiente:** la persona ideale che vive sempre secondo virtù. Un modello a cui tendere, più che una persona reale.`,
        `**Tranquillità** (*euthymía*, *ataraxía*): la serenità di chi non si lascia turbare. È la meta delle pratiche.`,
        `**Virtù** (*aretê*): l'eccellenza del carattere: saggezza, giustizia, coraggio, temperanza.`,
      ] },
      { t: 'azione', x: 'Le quattro virtù', az: 'studio', id: 'le-quattro-virtu' },
    ],
  },
  {
    id: 'domande-sullo-stoicismo',
    titolo: 'Domande frequenti sullo stoicismo',
    sotto: 'Risposte brevi a dubbi comuni.',
    blocchi: [
      { t: 'p', x: `Alcuni dubbi tornano spesso, a chi si avvicina allo stoicismo. Ecco qualche risposta breve.` },
      { t: 'lista', x: [
        `**Lo stoicismo è una religione?** No. È una filosofia pratica. Gli stoici parlavano di un ordine razionale del mondo (a volte lo chiamavano Dio), ma gli esercizi si possono fare a prescindere da ciò in cui si crede.`,
        `**Vuol dire non provare emozioni?** No. Vuol dire non farsi guidare da emozioni che nascono da giudizi sbagliati, e coltivare quelle buone: gioia, cautela, volontà ragionevole.`,
        `**Vuol dire accettare tutto?** No. Accettiamo ciò che non dipende da noi. Su ciò che dipende da noi, agire con giustizia è un dovere.`,
        `**Serve per il successo?** Non è il suo scopo. Serve per vivere con più libertà e più serenità, qualunque cosa accada.`,
        `**Funziona anche in un momento di crisi?** Alcuni esercizi sì, soprattutto quelli brevi. Se stai molto male, però, parlane con il tuo medico o con una persona di fiducia.`,
        `**Devo leggere i classici?** Non è obbligatorio. Chi vuole, può cominciare dal *Manuale* di Epitteto, che è breve.`,
        `**Gli stoici erano perfetti?** No. Seneca era ricchissimo e criticato per le contraddizioni, Marco Aurelio era un imperatore in guerra. Proprio per questo i loro esercizi sono nati dalla vita vera.`,
      ] },
      { t: 'azione', x: 'Che cos\'è lo stoicismo', az: 'studio', id: 'cose-lo-stoicismo' },
    ],
  },
  {
    id: 'il-manuale-di-epitteto',
    titolo: 'Il Manuale di Epitteto',
    sotto: 'Un piccolo libro di 53 brevi capitoli, da cui cominciare.',
    blocchi: [
      { t: 'p', x: `Epitteto, ex schiavo e maestro di filosofia, non scrisse nulla: le sue lezioni furono raccolte dal suo allievo Arriano nei *Discorsi* e in un riassunto pratico, il *Manuale* (in greco *Encheirídion*, «ciò che si tiene a portata di mano»). È il libro più breve e più usato per cominciare.` },
      { t: 'h', x: 'Alcuni capitoli da conoscere' },
      { t: 'lista', x: [
        `**Capitolo 1:** alcune cose dipendono da noi, altre no. Il punto di partenza di tutto.`,
        `**Capitolo 5:** non sono le cose a turbare gli esseri umani, ma i giudizi che ne danno.`,
        `**Capitolo 8:** non pretendere che gli eventi accadano come vuoi: vuoi che accadano come accadono, e vivrai sereno.`,
        `**Capitolo 11:** non dire «ho perduto», ma «ho restituito».`,
        `**Capitolo 17:** siamo attori in una parte scelta da un altro: il nostro compito è recitarla bene.`,
        `**Capitolo 20:** ricordati che a offenderti non è chi ti insulta, ma il giudizio che ne dai.`,
        `**Capitolo 26:** guarda ciò che ti capita con gli occhi con cui guardi ciò che capita agli altri.`,
        `**Capitolo 33:** scegli un carattere e mantienilo, sia da solo sia in compagnia.`,
      ] },
      { t: 'h', x: 'Come leggerlo' },
      { t: 'p', x: `Non di seguito, come un romanzo. Un capitolo al giorno, magari la mattina, e poi un pensiero da portare con sé. Molti dei nostri esercizi nascono da questi capitoli.` },
      { t: 'azione', x: 'Esercizio: Ciò che dipende da me', az: 'esercizio', id: 'cio-che-dipende-da-me' },
      { t: 'azione', x: 'Come leggere gli stoici', az: 'studio', id: 'come-leggere' },
    ],
  },
  {
    id: 'un-giorno-stoico',
    titolo: 'Un giorno stoico',
    sotto: 'Mattina, giornata e sera: come si può organizzare una giornata con le pratiche degli stoici.',
    blocchi: [
      { t: 'p', x: `Gli stoici non praticavano soltanto nei momenti di crisi. Le loro pratiche accompagnavano l'intera giornata, in tre momenti semplici. Non serve farle tutte: si può cominciare da una.` },
      { t: 'h', x: 'La mattina: prepararsi' },
      { t: 'p', x: `Marco Aurelio comincia la giornata ricordandosi che incontrerà persone difficili e che ognuno ha un compito suo. Pochi minuti per chiedersi: che cosa potrebbe mettermi alla prova? Come voglio essere?` },
      { t: 'lista', x: [
        `Nel Quaderno: la pagina **Mattina**.`,
        `Un esercizio breve: **Prepara la giornata**.`,
        `Una meditazione di cinque minuti: **La mattina**.`,
      ] },
      { t: 'h', x: 'Durante il giorno: fermarsi e guardare' },
      { t: 'p', x: `Quando qualcosa ti agita, tra un impegno e l'altro, fermati un momento. Chiediti: che cosa sto pensando? dipende da me? che cosa posso fare adesso? Sono le tre domande sottomano. Bastano un minuto e un respiro.` },
      { t: 'h', x: 'La sera: esaminare' },
      { t: 'p', x: `Seneca ogni sera ripassava la giornata, senza nascondersi nulla e senza punirsi. Tre domande: che cosa ho fatto bene? dove ho sbagliato? che cosa farò diversamente? Poi si dorme, e si comincia da capo.` },
      { t: 'lista', x: [
        `Nel Quaderno: la pagina **Sera**.`,
        `Una meditazione di dieci minuti: **Esame della sera**.`,
        `Un esercizio breve: **Per ora ti perdono**.`,
      ] },
      { t: 'azione', x: 'Meditazione: La mattina', az: 'meditazione', id: 'la-mattina' },
      { t: 'azione', x: 'Meditazione: Esame della sera', az: 'meditazione', id: 'esame-della-sera-guidato' },
    ],
  },
];

export const PAGINE_STUDIO = [...PAGINE_BASE, ...PAGINE_STUDIO_3A, ...PAGINE_STUDIO_3B, ...PAGINE_STUDIO_4];

// Come si presenta l'elenco dello Studio: gruppi tematici, in ordine di lettura. Ogni pagina sta in un solo gruppo.
export const GRUPPI_STUDIO = [
  { nome: 'Per cominciare', ids: ['cose-lo-stoicismo', 'falsi-miti', 'come-usare', 'come-leggere', 'domande-sullo-stoicismo', 'errori-di-chi-comincia', 'un-giorno-stoico', 'un-mese-di-pratica', 'cosa-dice-la-ricerca'] },
  { nome: 'Le idee di fondo', ids: ['tre-discipline', 'logica-fisica-etica', 'cio-che-dipende-da-noi', 'dicotomia-in-pratica', 'impressioni-giudizio', 'la-parte-guida', 'la-natura-e-il-cosmo', 'indifferenti-e-preferibili', 'i-doveri-e-i-ruoli', 'il-progresso-e-il-sapiente', 'la-cura-dell-anima', 'esercizi-spirituali'] },
  { nome: 'Le passioni e le virtù', ids: ['paura-desiderio', 'mappa-delle-passioni', 'le-quattro-passioni', 'le-quattro-virtu', 'virtu-saggezza', 'virtu-giustizia', 'virtu-coraggio', 'virtu-temperanza'] },
  { nome: 'Quando qualcosa pesa', ids: ['l-ira-secondo-seneca', 'la-paura-del-futuro', 'il-dolore-e-la-perdita', 'il-perdono-e-la-clemenza', 'accettare-cio-che-accade', 'la-tranquillita-dell-animo', 'la-premeditazione-dei-mali', 'il-ricordo-della-fine', 'il-tempo-la-morte'] },
  { nome: 'Le pratiche di ogni giorno', ids: ['l-esame-di-coscienza', 'scrivere-per-pensare', 'vista-dall-alto', 'la-gratitudine', 'il-tempo-secondo-seneca'] },
  { nome: 'Nelle situazioni della vita', ids: ['il-denaro-e-la-ricchezza', 'la-fama-e-il-giudizio-degli-altri', 'il-corpo-e-la-malattia', 'la-solitudine-e-la-compagnia', 'amicizia-e-comunita', 'stoicismo-e-lavoro', 'stoicismo-e-relazioni'] },
  { nome: 'Gli autori', ids: ['tre-maestri', 'autore-epitteto', 'il-manuale-di-epitteto', 'autore-seneca', 'la-vita-di-seneca', 'autore-marco-aurelio', 'autore-musonio', 'autore-zenone', 'autore-cleante', 'autore-crisippo'] },
  { nome: 'La storia della scuola', ids: ['le-tre-eta-della-stoa', 'stoici-antichi', 'come-conosciamo-i-primi-stoici', 'panezio', 'posidonio', 'lo-stoicismo-a-roma', 'gli-stoici-e-il-potere'] },
  { nome: 'Glossario', ids: ['glossario', 'glossario-2'] },
];
